### ISSUE TITLE
Standardizing the EIP/ERC Process

### ISSUE THREAD

**Issue by GriffGreen** [ethereum/EIPs#1002]
I know a lot of people are working on this and I am not even sure that this is really an EIP, but there is clearly a movement to revise EIP1. The Fellowship of Ethereum Magicians is working on this process and I think it needs an issue to maintain updates on the process for transparency... and this is a very auspicious number for such a magical EIP :-D

Some relevant issues already proposed with very nice informative comments are: 
https://github.com/ethereum/EIPs/issues/797
https://github.com/ethereum/EIPs/issues/898 
https://github.com/ethereum/EIPs/issues/736
https://github.com/ethereum/EIPs/issues/988

A lot of this will be discussed in Toronto and will likely be live streamed so more people can participate in the discussion.

**Comment by Arachnid** [comment]
> I know a lot of people are working on this and I am not even sure that this is really an EIP, but there is clearly a movement to revise EIP1.

It's not an EIP, but it makes sense as an issue. Not every PR or issue in this repo has to be an EIP. :)
