### ISSUE TITLE
ERC1003 Token Standard (ERC20 Extension)

### ISSUE THREAD

**Issue by k06a** [ethereum/EIPs#1003]
```
EIP: 1003
Title: ERC1003 Token Standard (ERC20 Extension)
Author: Anton Bukov <k06aaa@gmail.com>
Type: Token Standard
Category: ERC
Created: 2018-04-15
Updated: 2018-08-09
```

## Simple Summary

An extension of the standard interface ERC20 for tokens with method that allows **safely** pass and handle tokens into smart contracts.

## Abstract

I propose to move tokens from **spender** to **destination contract** over fake `caller`, which will be `msg.sender`.

Also this standard protects from ERC20 stealing, example:
```
function depositTokenCanBeStolen(address _spender, uint taskId, uint _value) public {
    require(token.transferFrom(_spender, this, _value));
    tasksBalance[_spender] += _value;
}
```

In case of separate calls for ERC20: `approve` and `depositTokenCanBeStolen` tokens of the stranger can be used for the task he doesn't wanna support. Someone `approves` tokens, and another person can spend it, that's why usually developers use `tx.origin` – but this prevents tx chain length scaling.

## [ERC827](https://github.com/ethereum/EIPs/issues/827) comparison

- In ERC827 `msg.sender` tells that `_spender` pays, you can check it only using `tx.origin`.
- In ERC1003 `msg.sender` pays himself for `_beneficiary`, nothing to worry about.

### ERC20 Methods

All usual ERC20 methods.

### ERC1003 Methods

**transferToContract - ERC1003**

Implementation example:

```
import "openzeppelin-solidity/contracts/ownership/Ownable.sol";
import "openzeppelin-solidity/contracts/token/ERC20/ERC20.sol";

contract ERC1003Caller is Ownable {
    function makeCall(address _target, bytes _data) external payable onlyOwner returns (bool) {
        return _target.call.value(msg.value)(_data);
    }
}

contract ERC1003Token is ERC20 {
    ERC1003Caller public caller_ = new ERC1003Caller();
    address[] internal sendersStack_;

    function transferToContract(address _to, uint256 _value, bytes _data) public payable returns (bool) {
        sendersStack_.push(msg.sender);
        approve(_to, _value);
        require(caller_.makeCall.value(msg.value)(_to, _data));
        sendersStack_.length -= 1;
        return true;
    }

    function transferFrom(address _from, address _to, uint256 _value) public returns (bool) {
        address from = (_from != address(caller_)) ? _from : sendersStack_[sendersStack_.length - 1];
        return super.transferFrom(from, _to, _value);
    }
}
```

Example of smart contract, compatible with both ERC20 and ERC1003 :

```
function depositToken(address _beneficiary, uint _value) public {
    require(token.transferFrom(msg.sender, this, _value));
    balanceOfAccount[_beneficiary] += _value;
}
```

Also can deposit all `allowed` tokens:
```
function depositToken(address _beneficiary) public {
    uint256 amount = token.allowed(msg.sender, this);
    require(token.transferFrom(msg.sender, this, amount));
    balanceOfAccount[_beneficiary] += amount;
}
```

The only **mandatory** argument is `_beneficiary`.

**Comment by mad2sm0key** [comment]
You are transferring tokens to the tokens contract. I'm not sure that's a great idea. Also, if you want the receiver contract to get the tokens from the token contract you need to approve the amount first (before the .call(_data)). The receiving functions need to be payable as well if you intend to transfer value (eth). 
Everyone that uses your transfer will pass the tokens through the token contract. I don't feel this approach is a good idea

**Comment by k06a** [comment]
@mad2sm0key thanks! Forgot to add this code, this was code from my mind.

**Comment by k06a** [comment]
@mad2sm0key think of it as of everyone is spending only it’s own tokens. And you will see, this idea will solve ERC827 `to.origin` issues.

**Comment by mad2sm0key** [comment]
@k06a The updated code makes more sense now. However, your example depositToken can be used to deposit tokens for any account. There is no authentication. Maybe one is not needed in your particular case. That's pretty much the same as in ERC827. You can't really know who the actual sender is.

**Comment by k06a** [comment]
@mad2sm0key the `msg.sender` pays with tokens for any `_account` it wants. This code is fully compatible with both ERC20 (2 tx) and ERC1003 (1 tx).

**Comment by k06a** [comment]
Hey @spalladino @Shrugs @facuspagnuolo what do you think?

**Comment by mad2sm0key** [comment]
@k06a How much gas does this use ? Oh, and the _surrender_ is a nice idea.

**Comment by k06a** [comment]
## ERC827 and ERC1003 gas comparison

### ERC827


Field | Value
--- | ---
status | 0x1 Transaction mined and execution succeed
from | 0xca35b7d915458ef540ade6068dfe2f44e8fa733c
to | MyToken.approve(address,uint256,bytes) 0x692a70d2e424a56d2c6c27aa97d1a86395877b3a
gas | 3000000 gas
transaction cost | 62256 gas
execution cost | 52016 gas
hash | 0x12833914473d7d06ec75b9e25dd084220f86d642e7b971521854f1d6a80d331a
input | 0x5c17f9f4<br>000000000000000000000000bbf289d846208c16edc8474705c748aff07732db<br>0000000000000000000000000000000000000000000000000000000000000064<br>0000000000000000000000000000000000000000000000000000000000000060<br>0000000000000000000000000000000000000000000000000000000000000044<br>0bb92e1a<br>000000000000000000000000ca35b7d915458ef540ade6068dfe2f44e8fa733c<br>0000000000000000000000000000000000000000000000000000000000000064<br>00000000000000000000000000000000000000000000000000000000
decoded input | {<br>&nbsp;&nbsp;&nbsp;&nbsp;"address _spender": "0xbbf289d846208c16edc8474705c748aff07732db",<br>&nbsp;&nbsp;&nbsp;&nbsp;"uint256 _value": "100"<br>}
decoded output | {<br>&nbsp;&nbsp;&nbsp;&nbsp;"0": "bool: true"<br>}
logs | [<br>&nbsp;&nbsp;&nbsp;&nbsp;{<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"topic": "8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925",<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"event": "Approval",<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"args": [<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"ca35b7d915458ef540ade6068dfe2f44e8fa733c",<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"bbf289d846208c16edc8474705c748aff07732db",<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"100"<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;]<br>&nbsp;&nbsp;&nbsp;&nbsp;},<br>&nbsp;&nbsp;&nbsp;&nbsp;{<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"topic": "ddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef",<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"event": "Transfer",<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"args": [<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"ca35b7d915458ef540ade6068dfe2f44e8fa733c",<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"bbf289d846208c16edc8474705c748aff07732db",<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"100"<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;]<br>&nbsp;&nbsp;&nbsp;&nbsp;}<br>]
value | 0 wei

## ERC1003 without surrender

Field | Value
-- | --
status | 0x1 Transaction mined and execution succeed
from | 0xca35b7d915458ef540ade6068dfe2f44e8fa733c
to | MyToken.transferToContract(address,uint256,bytes) 0x692a70d2e424a56d2c6c27aa97d1a86395877b3a
gas | 3000000 gas
transaction cost | 108161 gas
execution cost | 112921 gas
hash | 0x37fa283222a1d39d648331ca8420bb0860aa9b90bd6025cb47021b166624e877
input | 0x3f35d033<br>000000000000000000000000bbf289d846208c16edc8474705c748aff07732db<br>0000000000000000000000000000000000000000000000000000000000000064<br>0000000000000000000000000000000000000000000000000000000000000060<br>0000000000000000000000000000000000000000000000000000000000000044<br>badccf2d<br>000000000000000000000000ca35b7d915458ef540ade6068dfe2f44e8fa733c<br>0000000000000000000000000000000000000000000000000000000000000064<br>00000000000000000000000000000000000000000000000000000000<br>
decoded input | {<br>&nbsp;&nbsp;&nbsp;&nbsp;"address _to": "0xbbf289d846208c16edc8474705c748aff07732db",<br>&nbsp;&nbsp;&nbsp;&nbsp;"uint256 _value": "100",<br>&nbsp;&nbsp;&nbsp;&nbsp;"bytes _data": "0xbadccf2d000000000000000000000000ca35b7d915458ef540ade6068dfe2f44e8fa733c0000000000000000000000000000000000000000000000000000000000000064"<br>}
decoded output | {<br>&nbsp;&nbsp;&nbsp;&nbsp;"0": "bool: true"<br>}
logs | [<br>&nbsp;&nbsp;&nbsp;&nbsp;{<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"topic": "ddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef",<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"event": "Transfer",<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"args": [<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"ca35b7d915458ef540ade6068dfe2f44e8fa733c",<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"692a70d2e424a56d2c6c27aa97d1a86395877b3a",<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"100"<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;]<br>&nbsp;&nbsp;&nbsp;&nbsp;},<br>&nbsp;&nbsp;&nbsp;&nbsp;{<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"topic": "8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925",<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"event": "Approval",<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"args": [<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"692a70d2e424a56d2c6c27aa97d1a86395877b3a",<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"bbf289d846208c16edc8474705c748aff07732db",<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"100"<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;]<br>&nbsp;&nbsp;&nbsp;&nbsp;},<br>&nbsp;&nbsp;&nbsp;&nbsp;{<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"topic": "ddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef",<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"event": "Transfer",<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"args": [<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"692a70d2e424a56d2c6c27aa97d1a86395877b3a",<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"bbf289d846208c16edc8474705c748aff07732db",<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"100"<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;]<br>&nbsp;&nbsp;&nbsp;&nbsp;}<br>]
value | 0 wei

## ERC1003 with surrender

Field | Value
-- | --
status | 0x1 Transaction mined and execution succeed
from | 0xca35b7d915458ef540ade6068dfe2f44e8fa733c
to | MyToken.transferToContract(address,uint256,bytes) 0x692a70d2e424a56d2c6c27aa97d1a86395877b3a
gas | 3000000 gas
transaction cost | 103299 gas
execution cost | 108059 gas
hash | 0x36a9544f551d94dd3890668dfc45c355602a9bb939da550b4e9d114b620f4f6e
input | 0x3f35d033<br>000000000000000000000000bbf289d846208c16edc8474705c748aff07732db<br>0000000000000000000000000000000000000000000000000000000000000064<br>0000000000000000000000000000000000000000000000000000000000000060<br>0000000000000000000000000000000000000000000000000000000000000044<br>badccf2d<br>000000000000000000000000ca35b7d915458ef540ade6068dfe2f44e8fa733c<br>0000000000000000000000000000000000000000000000000000000000000032<br>00000000000000000000000000000000000000000000000000000000
decoded input | {<br>&nbsp;&nbsp;&nbsp;&nbsp;"address _to": "0xbbf289d846208c16edc8474705c748aff07732db",<br>&nbsp;&nbsp;&nbsp;&nbsp;"uint256 _value": "100",<br>&nbsp;&nbsp;&nbsp;&nbsp;"bytes _data": "0xbadccf2d000000000000000000000000ca35b7d915458ef540ade6068dfe2f44e8fa733c0000000000000000000000000000000000000000000000000000000000000032"<br>}
decoded output | {<br>&nbsp;&nbsp;&nbsp;&nbsp;"0": "bool: true"<br>}
logs | [<br>&nbsp;&nbsp;&nbsp;&nbsp;{<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"topic": "ddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef",<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"event": "Transfer",<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"args": [<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"ca35b7d915458ef540ade6068dfe2f44e8fa733c",<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"692a70d2e424a56d2c6c27aa97d1a86395877b3a",<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"100"<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;]<br>&nbsp;&nbsp;&nbsp;&nbsp;},<br>&nbsp;&nbsp;&nbsp;&nbsp;{<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"topic": "8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925",<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"event": "Approval",<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"args": [<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"692a70d2e424a56d2c6c27aa97d1a86395877b3a",<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"bbf289d846208c16edc8474705c748aff07732db",<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"100"<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;]<br>&nbsp;&nbsp;&nbsp;&nbsp;},<br>&nbsp;&nbsp;&nbsp;&nbsp;{<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"topic": "ddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef",<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"event": "Transfer",<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"args": [<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"692a70d2e424a56d2c6c27aa97d1a86395877b3a",<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"bbf289d846208c16edc8474705c748aff07732db",<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"50"<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;]<br>&nbsp;&nbsp;&nbsp;&nbsp;},<br>&nbsp;&nbsp;&nbsp;&nbsp;{<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"topic": "ddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef",<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"event": "Transfer",<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"args": [<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"692a70d2e424a56d2c6c27aa97d1a86395877b3a",<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"ca35b7d915458ef540ade6068dfe2f44e8fa733c",<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"50"<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;]<br>&nbsp;&nbsp;&nbsp;&nbsp;},<br>&nbsp;&nbsp;&nbsp;&nbsp;{<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"topic": "8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925",<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"event": "Approval",<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"args": [<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"692a70d2e424a56d2c6c27aa97d1a86395877b3a",<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"bbf289d846208c16edc8474705c748aff07732db",<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"0"<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;]<br>&nbsp;&nbsp;&nbsp;&nbsp;}<br>]
value | 0 wei

**Comment by mg6maciej** [comment]
While this might solve some issues with #827, it's vulnerable the same way #827 is, so I'd suggest putting a big warning "**This standard is still a draft and is proven to be unsafe to be used**" (copied from #827) at the top of this issue and closing it.
If you want to learn more, please read discussion on #827 and here: https://gitter.im/ERC827/Lobby

**Comment by k06a** [comment]
@mg6maciej ok, but why to close this issue?

**Comment by mg6maciej** [comment]
Unless you want to actively work on making it secure (maybe together with @AugustoL, author of #827), it's better if less eyes see it. Open issues are just a bit easier to browse though. Closed issue is also a warning sign. See #821, which was an alternative to #721 before they joined forces. Maybe @AnthonyAkentiev from Thetta/Thetta-DAO-Framework would not reference this and #827 if they were both closed before.

**Comment by k06a** [comment]
One more try:

```
contract ERC827Caller {
    function makeCall(address _target, bytes _data) external payable returns (bool) {
        // solium-disable-next-line security/no-call-value
        return _target.call.value(msg.value)(_data);
    }
}

contract ERC827Caller {

ERC827Caller public caller_;
mapping(address => mapping(address => uint256)) public allowedOverCaller_;

constructor() public {
    caller_ = new ERC827Caller();
}

function transferFrom(address _from, address _to, uint256 _value) public returns (bool) {
    address caller = caller_;
    if (_from != caller) {
        return super.transferFrom(_from, _to, _value);
    }

    require(_to != address(0));
    require(_value <= balances[caller]);
    require(_value <= allowedOverCaller_[_from][msg.sender]);

    balances[_from] = balances[_from].sub(_value);
    balances[_to] = balances[_to].add(_value);
    allowedOverCaller_[_from][msg.sender] = allowedOverCaller_[_from][msg.sender].sub(_value);
    emit Transfer(_from, _to, _value);
    return true;
}

function transferToContract(address _to, uint256 _value, bytes _data) public payable returns (bool) {
    allowanceOverCaller_[msg.sender][_to] = _value;
    require(caller_.makeCall.value(msg.value)(_to, _data));
    allowanceOverCaller_[msg.sender][_to] = 0;
    return true;
}

}
```

**Comment by k06a** [comment]
Or even more shorter version of `transferFrom` overriding:
```
function transferFrom(address _from, address _to, uint256 _value) public returns (bool) {
    return super.transferFrom(_from != caller_ ? _from : sendersStack_[sendersStack_.length - 1], _to, _value);
}
```

**Comment by k06a** [comment]
Updated theme message

**Comment by k06a** [comment]
It seems ERC1003 will work for ERC721
