### ISSUE TITLE
SAR, SHR, SHL bitshifting operations as opcodes

### ISSUE THREAD

**Issue by VoR0220** [ethereum/EIPs#104]
Working in Solidity has given me a previously unfounded appreciation for the art of bit shifting. I think that these should be added to the EVM as opcodes and should have low gas costs as normal processors usually benefit from bitshifting...while we can replicate that using a combination of MUL and MOD...I think it would be good for these to have their own opcodes for the purposes of low intensive resource constraints. These would be the traditional Arithmetic shift, shift right, and shift left.

**Comment by VoR0220** [comment]
closing as it has been explained to me the reasoning behind this design decision.

**Comment by Denton-L** [comment]
Out of curiosity, what's the rationale behind this?

**Comment by VoR0220** [comment]
JITs can implement the opcodes to rely on bit shifting.
