### ISSUE TITLE
Storage Gas Refund

### ISSUE THREAD

**Issue by enriquejr99** [ethereum/EIPs#1048]
Currently, the EVM refunds gas to those who delete data from storage or call the contract suicide function. This is done to incentivize users to free storage if they no longer need it.

[Detailed gas costs spreadsheet](https://docs.google.com/spreadsheets/d/1m89CVujrQe5LAFJ8-YAUCcNK950dUzMQPMJBxRtGCqs)

The problem is that gas is refunded after the code execution has finished instead of on the go. This means operations such as clearing long arrays may end up running out of gas although they shouldn't.

This is an example of a function with an execution cost higher than its transaction cost:

```
pragma solidity ^0.4.23;

contract Array {
    uint256 a;
    
    function Test() external {
        a = 1;
        delete a;
        a = 1;
        delete a;
        a = 1;
        delete a;
        a = 1;
        delete a;
        a = 1;
        delete a;
        a = 1;
        delete a;
        a = 1;
        delete a;
        a = 1;
        delete a;
    }
}
```

According to Remix, this function has a transaction cost of 110795 gas. However, you will need to send at least 221590 gas (twice as much) to prevent your transaction from running out of gas; even though you will only be charged 110795 gas.

Refunding gas on the go requires more computations and is therefore refunded afterwards, in bulk. However, I would suggest something such as: 

Once a user runs out of gas, use the yet to be refunded gas. Once the refundable gas == 0, throw out of gas. This allows users to send the appropriate gas amount, without having the computational impact of refunding multiple times on the go.

**Comment by spalladino** [comment]
I'm worried that this could enable reentrancy attacks. Today, if a contract uses Solidity's `transfer` for sending ETH, the amount of gas associated is limited, so that no reentrancies can be executed. With this new semantics, an attacker could call from a malicious contract that deletes several storage slots in order to _gain_ gas, and then use it to execute a reentrancy.

**Comment by enriquejr99** [comment]
Just add an exeption. Something like, while executing the `transfer` function, do not allow usage of the yet to be refunded gas. Therefore the gas associated is limited just as how it is today.

**Comment by spalladino** [comment]
Transfer and send are Solidity constructs, they just wrap EVM `CALL` with a certain value, so it is not possible to know if transfer or send were used (instead of an actual function call) from the EVM.

**Comment by enriquejr99** [comment]
True. Then, we could modify the `.gas()` behaviour.

I believe we can solve this issue because we currently limit one integer, `gas_left`, to not decrease by more than 2300. Therefore, we should also be able to limit the total of two integers, `gas_left + refundable_gas`, because the total is also a single integer; just like `gas_left`.
