### ISSUE TITLE
A proposal to move the content in ethereum/wiki to a Wikipedia-style wiki site

### ISSUE THREAD

**Issue by jamesray1** [ethereum/EIPs#1053]
> Github wikis have the limitation that anyone can edit them while it is difficult to moderate them (it is not possible to watch a page to get updates for changes), which is a double-edged sword, in that it is great for non-censorship which is in the spirit of the [Ethereum philosophy](https://github.com/ethereum/wiki/wiki/White-Paper#philosophy), however it is also prone to graffiti, bias, etc. Because of this limitation of lack of ease for moderation, we should consider moving the content in this wiki to a wiki site, e.g. one that is hosted by [Media Wiki](https://www.mediawiki.org/wiki/MediaWiki), adding a deprecation notice to this wiki and refer to the proposed new Media Wiki hosted site. This would have the benefits of anyone still being able to edit the wiki (they do not even need to create an account, although there are advantages to doing so), as well as being able to more easily moderate content.
— https://github.com/ethereum/wiki/wiki#a-proposal-to-move-the-content-in-this-wiki-to-a-wikipedia-style-wiki-site

Also posted in https://ethereum-magicians.org/t/a-proposal-to-move-the-content-in-ethereum-wiki-to-a-wikipedia-style-wiki-site/265.

**Comment by Arachnid** [comment]
This doesn't really belong in the EIPs repository.

**Comment by virgil** [comment]
This is currently being worked on by myself.  I already have the domain Ethereum.wiki

**Comment by jamesray1** [comment]
@virgil, cool, yeah I saw that at https://github.com/ethereum/wiki/wiki/FAQs#where-can-i-learn-more-about-ethereum. Feel free to keep me in the loop; I'll be interested to see how it pans out.
