### ISSUE TITLE
EIP-ProgPoW: a programmatic Proof-of-Work algorithm

### ISSUE THREAD

**Issue by ifdefelse** [ethereum/EIPs#1058]
A programmatic POW algorithm that can maximally utilize functions on commodity (widely distributed and readily available) GPUs limits optimization potential for a specialize mining ASIC.  An implementation of this idea is presented here:  https://github.com/ethereum/EIPs/pull/1057

This PR describes a fully implemented algorithm based on ethminer code.  It attempts to be permanently "ASIC-resistant" without the need for future small forks. The goal is to extend the runaway and allow for a gentle transition to Casper, minimizing network turbulence and maximizing time for Casper validation.  

Thanks in advance for any thoughts and comments.

**Comment by csulmone** [comment]
Is there a performance penalty for proof of work verification?

**Comment by fuzzyTew** [comment]
Hey, this looks cool.  I'm surprised there's not more discussion.

I wanted to suggest that `prog_seed` I think it's called, be based on a block hash rather than a block number.  This would make it more difficult to predict future inner loops.
