### ISSUE TITLE
Suggestion: Add Logarithm Opcode

### ISSUE THREAD

**Issue by fubuloubu** [ethereum/EIPs#1065]
Was curious what issues there would be with adding a integer logarithm opcode?

I understand that logarithm opcodes for other processors are typically floating point instructions, but there has got to be a decent fixed-point operation that can be implemented in our 256-bit processor, that also minimizes information loss from the operation (especially when using change of bases to compute arbitrary logarithms), and is bounded by a constant time for a reasonable input.

I have a preliminary idea for such an algorithm [here](https://github.com/fubuloubu/evm-logarithm), but I am sure there are holes in such an approach that can be improved upon. My preliminary approach uses 256 loops at most, at costs about 160k gas. Hopefully that can be substantially reduced with an opcode.

A good minimal implementation would be able to implement at least a base 2 logarithm instruction that compiler writers could leverage via `log_a(b) = (DIV (B2LOG b 2) (B2LOG a 2))` either internally or through a psuedo opcode that implements that macro.

**Comment by Arachnid** [comment]
FWIW, you can get the base 2 log of an integer fairly efficiently in a few different ways: https://graphics.stanford.edu/~seander/bithacks.html#IntegerLogLookup

**Comment by fubuloubu** [comment]
Cool!

Would be interesting to see if a general solution exists for computing integer logarithms, perhaps using a double word in memory.

Does the lookup table approach work for a VM implementation?
