### ISSUE TITLE
Support anchor tags on eips.ethereum.org (direct links to sections)

### ISSUE THREAD

**Issue by jamesray1** [ethereum/EIPs#1106]

**Comment by Arachnid** [comment]
What is a "URL heading"?

**Comment by jamesray1** [comment]
Like this: https://github.com/ethereum/wiki/wiki/Design-Rationale#principles. In any markdown document on GitHub, when you click or tap on a heading, a link will display, which you can then get the URL for, which is in the format page_url#heading.

**Comment by Arachnid** [comment]
Oh, you mean anchors?

I don't think it's possible to modify Jekyll's markdown processing to automatically add these.

**Comment by ryanio** [comment]
+1

I would find html anchor tags on the website really useful.

Googling around I found this repository which looks like it could be a pretty great solution? https://github.com/allejo/jekyll-anchor-headings

There is also a ToC one that could be really cool as well: https://github.com/allejo/jekyll-toc
