### ISSUE TITLE
ERC-1123 – Revised Ethereum Smart Contract Packaging Standard

### ISSUE THREAD

**Issue by gnidan** [ethereum/EIPs#1123]
# Revised Ethereum Smart Contract Packaging Standard

**Read**: [EIP Draft](https://eips.ethereum.org/EIPS/eip-1123)

## Summary

A data format to describe a single package for distribution with the Ethereum Package Management system (EthPM). This supersedes [EIP-190](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-190.md).

## Notes

Alternate formatting for the EIP submission in corresponding draft PR (#1131) is available hosted on GitHub Pages at http://ethpm.github.io/ethpm-spec/contrib/ethpm/eip-1123.

**Comment by pipermerriam** [comment]
An explicit 👍 from some of the various teams and projects which have either been involved in the creation of this spec, or who have worked specifically on software that is likely to leverage this spec would be a good signal.  Here is a non-exhaustive list.

- Embark maintainers
- Remix maintainers
- Andy or someone from Maker/Dappsys
- Truffle folks
- Populus (me, nick, or @davesque)

Please add names/projects/teams that I've missed here.  I don't think we have a good "enterprise" representative to speak for the private/consortium chain use case in this list and I'd like to have their view represented.

**Comment by njgheorghita** [comment]
This ERC has been superseded by [ERC 2678](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-2678.md) (EthPM v3).

**Comment by MicahZoltu** [comment]
@njgheorghita I recommend marking this EIP as abandoned if you have a new one that you plan to push through to final and not this one.

Alternatively, if this is meant to represent a previous version and you don't plan on working further on it, then consider marking this as Last Call and then final so it is no longer a DRAFT and people can start relying on its stability.
