### ISSUE TITLE
Split ERC-20 contract into token, token registry, ICO and ICO registry 

### ISSUE THREAD

**Issue by rumkin** [ethereum/EIPs#1127]
```
Title: ERC-1127
Status: Active
Type: ERC
Author: Rumkin <dev@rumk.in>
Created: 2018-05-01
```

I have several theses: 
1. ICO is one time action. When it ends there is no need to let it to stay into blockchain as active entry and it could be killed.
2. ERC-20 interface itself have very predictable and strict behav and there is no need in special custom code to make it work. Any custom behavior should me moved out of that contract.
3. There should be registry like ENS to register token names instead of hosting name in contract.
4. There should be registry like ENS to register ICO contracts to make it easy to track new ICOs.
5. Any tokens or digital asset could be owned by contract or address. But there is no standard like erc20 to describe ownerOf and ownedBy behavior.

Well I have no complete code. Just a several ideas which I want to discuss before writing something.

## Workflow

As I already mentioned ICO is temporary contract which have short term lifetime. So It could be removed after ICO ends. As I think the workflow should looks like this:

1. Subject (contract or address) publishes token contract which now belongs to that contract or.
2. Subject publishes ICO contract.
3. Subject transfer some token amount to ICO contract.
4. Subject register ICO contract into ICO Registry.
4. Someone buys tokens from ICO contract.
5. ICO contract transfer tokens to that party.
6. After ICO ends.
7. ICO Registry mark ICO as completed and allow to register its token into token registry.
8. Token is published into token registry.

**Comment by shrugs** [comment]
Most crowdsales are already abstracted from the token (see: OpenZeppelin). You can optionally extend the [FinalizableCrowdsale](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/contracts/crowdsale/distribution/FinalizableCrowdsale.sol) with an option to destroy itself once it's been finalized.

Registering token names is probably not the job of a standard, and very much gets into the weeds of how that process is governed. see: https://github.com/ethereum/EIPs/issues/740

likewise for ICO registrars. There are a multitude of other, off-chain services which perform this task as well.

Tokens can be owned by an account, which may or may not be a contract. I'm not sure what you're asking, though; `MyNFT.ownerOf(_address)` works regardless of whether or not the address has code at that location or not.

**Comment by SUZWIL** [comment]
I have a erc20 token stuck.
I am the token holder but is stuck in smart contract.
