### ISSUE TITLE
Add mission statement

### ISSUE THREAD

**Issue by fulldecent** [ethereum/EIPs#1128]
Presently the ethereum/EIPs project does not have a mission statement.

---

<strike>Recently something changed and now the majority of EIPs here have no path to become "final" standards. Pull request #1100 addresses that issue.</strike>

However, one of the EIP editors (the people with commit access here) mentioned that #1100 is not urgent. There are no remaining complaints on #1100, it has EIP editor endorsements, but it is not merged.

I reviewed the project README.md and was hoping to find something like "our goal is to discuss and pass high-quality standards reflecting established best practices in the community." So I could tell this person that #1100 is urgent (because presently, standards are prevented from passing). Alas no such line exists, in fact, there is nothing in the README.md that explains why we are contributing here.

**It is much easier to set expectations for each other in this project if we have a clearly defined goal. And we should state that goal in the README.md.**

**Comment by fulldecent** [comment]
Also, to be clear: EIP is ///NOT/// a governance process. It is ///NOT/// a referendum process. It is a documentation project.

**Comment by Arachnid** [comment]
> Recently something changed and now the majority of EIPs here have no path to become "final" standards. Pull request #1100 addresses that issue.

Uh? What changed?

**Comment by fulldecent** [comment]
Core Devs removed themselves from ERCs. But of course that issue is resolved now.

**Comment by fulldecent** [comment]
First draft mission statement:

> The goal of the EIP project is to document best practices across the Ethereum community and to document them in a high quality and implementable way.

**Comment by MicahZoltu** [comment]
I'm not a fan of that mission statement.  I have argued many times in the past that EIPs are not the place to document your best practices.  Use a blog, write a book, tweet about it, etc.  EIPs are for standardization, when standardization is necessary.  Just because you have a good idea or a good design pattern doesn't mean you need a standard.

**Comment by fulldecent** [comment]
New proposed mission statement:

> The goal of the EIP project is to document standardized protocols for Ethereum clients and applications and to document them in a high quality and implementable way.
