### ISSUE TITLE
EIP20 Optional functions

### ISSUE THREAD

**Issue by adirmola** [ethereum/EIPs#1139]
As far a I understand it is consider an EIP20-compliance to add custom functions that isn't listed in the EIP20 interface?

The [EIP20 page](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-20.md) listing some optional functions - so it's looks like we're restricted only to those optional functions above the six mandatory functions but not any other (otherwise why to write it down as optional - any other function is optional)?

So my suggestion is to:
1. delete those optional function or to change the term to "nice to have" or something else.
2. may be also add some clarification that the functions is the minimum required and it's possible to add custom functions.

**Comment by DanielRX** [comment]
You might want to take a look at [https://tools.ietf.org/html/rfc2119](RFC 2119) which explains the use of  optional.

**Comment by adirmola** [comment]
Great reference.
Thanks.
But if we'll get into nuances so it is still not smooth.
In one Hand the EIP20 use the term "OPTIONAL" but in the other hand it says that "interfaces and other contracts MUST NOT expect these values to be present" - so it's moving out all the meaning of "OPTIONAL" according to the definition in the reference that said that we should expect to it.

Maybe the term SHOULD\RECOMMENDED it more accurate.

**Comment by DanielRX** [comment]
No, MUST NOT and OPTIONAL fit:

"You **must not** assume the functions are there, as they are **optional**"

Another wording would be "You **must** check the functions are there, as they are **optional**"
