### ISSUE TITLE
Display the review end period for last calls on eips.ethereum.org

### ISSUE THREAD

**Issue by fulldecent** [ethereum/EIPs#1147]
- [ ] For Last Call, include the discussion end date

![screen shot 2018-06-09 at 6 15 47 pm](https://user-images.githubusercontent.com/382183/41196574-40c06866-6c11-11e8-8397-34f9b88a3ec4.png)

- [ ] On the EIP page, link to the standard and the discussion

* https://eips.ethereum.org/EIPS/eip-721

**Comment by axic** [comment]
This comment goes back [this commit](https://github.com/ethereum/EIPs/commit/c9a9320e9dcb42accad38036228ca48f7cb00788#diff-a87271f8186c59c075e229cd7421f205):

```
 status: Last Call
 review-period-end: 2018-06-18
```

And as far as I understand the goal is to display the period end field on the rendered version.

**Comment by fulldecent** [comment]
Yes please @axic
