### ISSUE TITLE
Official ERC20 document declares named return parameters that cause compiler warnings

### ISSUE THREAD

**Issue by o0ragman0o** [ethereum/EIPs#1149]
The official ERC20 document and perhaps others, declare named return parameters of the same name as the function for `name`, `symbol`, `decimals` and `totalSupply`. This raises shadow declaration warnings in the compiler which a standard really should not do.

Additionally it breaks the opportunity for recursive calling. As unlikely as that might be for a getter, it breaks logic to have a parameter declaration prevent a declared function from being called and by this could be considered a bug. 

While ERC20 has long been standardised, I think the parameter naming convention needs revision.  My own styling uses prefixed and suffixed underscores for passed and return parameter names.

e.g. `function foo(uint _in) returns (uint out_);`   

[https://github.com/ethereum/EIPs/blob/master/EIPS/eip-20.md](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-20.md)

**Comment by DanielRX** [comment]
AFAIK the parameter naming has no actual value in the standard, as the function sig produced will be based only on the function name and input/output types

Would  `public string name = "nameOfToken";` not produce the correct hash with the implicit getter?

**Comment by o0ragman0o** [comment]
This issue isn't about function signatures. It's about standards documentation leading to compiler warnings and type clashes.

**Comment by DanielRX** [comment]
The documentation states what must be there, parameter names are not in that section

I assume you also want the function `transfer` or similarly the event `Transfer` to be renamed? 
This is a compiler warning that has been accepted as part of ERC20 due to the circumstances around the creation of the standard.

**Comment by o0ragman0o** [comment]
Where are you looking? I provided the link to the standard in the original
post. The document has parameter names.
Can you provide a reference for where there's been an acceptance of the
warning for this standard? If that's the case then I can note it in future
audits.

`transfer` and `Transfer` are distinct identifiers so is not the issue here.

**Comment by DanielRX** [comment]
My mistake, not a compiler warning, just a linting warning. It was so long ago that I had forgotten the context.

The documentation is not meant to be an implementation, those are left to 3rd parties:
[OpenZepplin](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/contracts/token/ERC20/DetailedERC20.sol) have, as I described, used implicit getters to make this valid. 

For all intents and purposes, 
`function x() returns(bool y) { y = true; }`
is the same as
`function x() returns(bool) { return true; }`.

Also `function x(bool z);` and `function x(bool notZ);` will compile to the same thing

In the description for all the functions, named parameters are used purely as descriptions for the developers. Parameter naming is purely for working with the values. As can be seen throughout the community, people have adopted their own names, as they should. For example, in my own code I use `gameName` as the return param name.
