### ISSUE TITLE
Please specify full inherited context parts for CALLCODE and DELEGATECALL

### ISSUE THREAD

**Issue by ytrezq** [ethereum/EIPs#1169]
There things which are counter intuitive (which is in inherited or not).
For example, the fact that using CODESIZE returns the code size of caller and not the code size of temporary replacement code from target address.

**Comment by axic** [comment]
@nicksavers @pirapira is this described in the Yellowpaper correctly?

Should this be described in https://eips.ethereum.org/EIPS/eip-7 ?

**Comment by axic** [comment]
@ytrezq I suggest to open an issue on https://github.com/ethereum/yellowpaper, link it here, and close this one.
