### ISSUE TITLE
Non-fungible royalty token

### ISSUE THREAD

**Issue by aalimk** [ethereum/EIPs#1190]
eip:
title: Non-fungible royalty token standard
author: Aalim Khan (aalim.khan@gmail.com) and Shaan Ray (twitter.com/shaanray)
status: Draft
type: Standards Track
category: ERC
created: 2018-06-24

### Simple Summary

A standard interface for non-fungible tokens that pay royalties for a digital asset to the original creator(s) and/or owner(s).

### Abstract

This standard will allow for the implementation of a standard API for non-fungible tokens that represent virtual collectibles or physical property within smart contracts.
Examples include:

    Virtual collectibles: in game assets, digital art, music, stock images
    Physical property: unique artwork, limited edition vehicles, real estate, physical collectibles or memorabilia

There will be 3 types of relationships that can exist with the digital asset:

    The "creator" who holds the creative license
    The "owner" who holds the ownership license
    The "renter" who rents the digital asset

The creative license holder of a token will always get paid an agreed upon portion of a digital asset's value every time the digital asset is the subject of a transaction.
A transaction in this context is one of the following 3 cases:

    The digital asset's ownership license is sold to a new owner
    The digital asset is rented out by the ownership license holder to another user
    The creative license holder sells the creative license (the license seller is entitled to 100% of the revenue from this transaction)

### Motivation

Existing standards for non-fungible tokens fall short of addressing the issue of ensuring that the creator(s) of an asset are entitled to the revenue or value generated by an asset over the course of its existence.

### Specification

Methods

// Function to initialize token and set the owner(s) and the royalty rates. Returns the unique token ID for the digital asset.
`function approve(address[] owners, uint royaltyForOwnershipTransfer, uint royaltyForRental) returns uint256;`

// Function to transfer creative license of token
`function transferCreativeLicense(address[] creativeLicenseHolders, address[] newOwners, uint256 tokenId);`

// Function to transfer ownership license of token
`function transferOwnershipLicense(address[] creativeLicenseHolders, address[] ownershipLicenseHolders, address newOwners[], uint256 tokenId);`

// Function to rent asset
`function rentAsset(address[] creativeLicenseHolders, address[] ownershipLicenseHolders, address[] renters, uint256 tokenId);`

Events

```
event Approval(address[] indexed _owner, address[] indexed _approved, uint256 indexed _tokenId);

event CreativeLicenseTransferred(address[] indexed creativeLicenseHolders, address[] indexed newOwners, uint256 indexed tokenId);

event OwnershipLicenseTransferred(address[] indexed creativeLicenseHolders, address[] indexed ownershipLicenseHolders, address[] indexed newOwners, uint256 indexed tokenId);

event AssetRented(address[] indexed creativeLicenseHolders, address[] indexed ownershipLicenseHolders, address[] indexed renters, uint256 indexed tokenId);
```

### Rationale

This ERC standard would empower creators of unique digital and real world assets to participate in the financial upside of their creations. This standard will reward creators beyond the point of initial sale of their product. It will encourage individuals to unleash their creative potential and be confident that their creations will provide them recurring income as the asset's price rises in value or achieves commercial success. It will allow for multiple parties to co-create and sell assets. Guaranteeing creative owners a means to reliable recurring revenue will foster the growth of various creative industries for the benefit of all.

For example, in the art industry, the artist does not receive any royalty from their work after the initial sale. If artists can be guaranteed that their creative efforts can provide them with a means of recurring revenue, this will inspire more people to consider commercializing their creativity which will be beneficial to not only the art industry, but to the wider art community as a whole.

Another example can be found in the gaming industry. E-sports is a huge phenomenon where many people tune in to watch. When well known players of a gaming community take part in global tournaments, viewership of the game's live streams rise and so do game's popularity. Digital assets of popular players from previous tournaments can be rented out to other players which will serve to drive up the hype of the digital asset, the people involved, and the game as a whole.

### Copyright

Copyright and related rights waived via CC0.

**Comment by aalimk** [comment]
Implementation TBD

**Comment by MicahZoltu** [comment]
@aalimk Do you plan on pursuing this as an EIP?  Right now this is just an idea, and ideas should be discussed over at https://ethereum-magicians.org/ rather than here (this is a fairly recent process change).

**Comment by MicahZoltu** [comment]
Closing this issue for housekeeping purposes. People are welcome to continue discussing in this thread, but for additional visibility an EIP should be created or the conversation should be migrated to https://ethereum-magicians.org/
