### ISSUE TITLE
A standard contracts to have for Self Contained HTML

### ISSUE THREAD

**Issue by quantumproducer** [ethereum/EIPs#1198]
The biggest obstacles to true standalone "decentralized" applications is hosting.

For applications that do not depend on data kept offchain, all that is  needed to
run the dapp is an html page. This proposal is thus: Smart Contracts include an `html` function that returns a string which is valid HTML for viewing and accessing the page.

It might make sense to reference packages like JQuery or eth-lawyer (my own tool for getting callbacks to account changes) in comments in the html. If the comment includes an address and abi of the package, a user could copy and paste code from the blockchain and assemble their own website.

Please note,, I am not suggesting a package manager built into Ethereum, although that a standard could emerge letting a third party tool scrape a smart contract and assemble a webpage without further input from the user. Writers who don't follow the standard could still deploy their own webpages using the html function.

No changes necessary to the EVM. This is a suggestion to smart contract developers to start standardizing on the `html` function to use for website rendering instructions.

**Comment by Arachnid** [comment]
This seems like a bad idea to me - there's absolutely no need to store this data onchain.

**Comment by quantumproducer** [comment]
@Arachnid  How can fully decentralized applications be realized then? The hosting will be dependent on a third party -- github is centralized.

**Comment by Arachnid** [comment]
Using Swarm, IPFS, Tor, or any number of other offchain solutions.

**Comment by quantumproducer** [comment]
IFPS requires a node to stay online, Tor also requires centralized hosting. Swarm, AFAIK, is just a reference to a storage but not a storage medium itself?

**Comment by MicahZoltu** [comment]
Decentralized storage is certainly hard, but I agree with @Arachnid that using Ethereum as a storage system is generally a poor solution due to how crazy expensive it is.

In many/most cases, there _is_ some central entity that has incentive to keep the data available.  That entity may operate in the dark (anonymously, hiding from state censors, etc.), but that doesn't matter.  If such an entity doesn't naturally exist, you can create an incentivization system to cause them to exist.  e.g., allow users to buy content from other users, thus encouraging users to store data indefinitely so they can sell it back to people when requested.

**Comment by jpitts** [comment]
@quantumproducer you might consider a thorough listing of what needs you are addressing, and options for going about fulfilling the needs. 

A method of referencing the default DApp for different screen sizes might be helpful to someone who finds a contract directly or in a blockchain explorer, but go as far as to put those assets in a smart contract is wasteful. 

A more important driver here may be ensuring that the user of the smart contract loads the best possible DApp for interacting with it. This could involve conveying, in a standard way, the appropriate version and addresses/hashes on Swarm, IPFS, etc from which the DApp's assets may be retrieved.

**Comment by quantumproducer** [comment]
@jpitts  

```
storage_type: swarm | IPFS | ...
storage_identifier: ABC123..
```

Something like this?

**Comment by xinbenlv** [comment]
I like the idea, maybe  create a standard to having a smart contract being readable with certain redirected storage?
Like 

```
uri: http://some_uri
```

and uri could be IPFS uri too, so you have full backward compatibility to HTTP, while also supporting new decentralized storage

oh by the way you can add things like hash code to ensure the statistic conent being served has not been tampered
