### ISSUE TITLE
ERC-1211 Common Ownership Self-Assessed Tax (COST) Interface [Draft]

### ISSUE THREAD

**Issue by sindarknave** [ethereum/EIPs#1211]
---
eip: 1211
title: Common Ownership Self-Assessed Tax (COST) Interface
author: Brian Ng (ngwingkui@gmail.com)
discussions-to: ngwingkui@gmail.com
status: Draft
type: Standards Track (Core, Networking, Interface, ERC)
category: ERC
created: 2018-07-10
requires (*optional): ERC-20, ERC-721, EIP-1155
replaces (*optional): 
---

## Simple Summary
A standard interface for the decentralized market ownership of a non-fungible asset ([EIP-721](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-721.md)) or multi-class item ([EIP-1155](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1155.md)). 

## Abstract
Ownership of an asset incentivizes me to invest in it and make it better. But it also prevents me from allocating it to someone who values it more. A common ownership scheme (COST scheme) allows me to own the asset but also requires me to announce my valuation of the asset each arbitrary time period, a percentage of which is taxed. If someone can beat my valuation, they can buy the asset at that price. This maintains both allocative and investment efficiency for public resources.

Same as the ERC-20 token allows for liquidity on a DEX, unifying a standard interface for COST schemes on blockchain non-fungible assets allows for licenses to be liquidly discovered and traded, maintaining necessary market volume for a COST scheme to function.

For discussion around COST schemes and its history in the Ethereum community, refer to 
- [Vitalik Buterin: On Radical Markets](https://vitalik.ca/general/2018/04/20/radical_markets.html)
- [Glen Weyl: Radical Markets Uprooting Capitalism and Democracy for a Just Society](https://www.youtube.com/watch?v=KSfLFIJYp6A)
- [Paul Milgrom, Glen Weyl, Anthony Lee Zhang: Redesigning Spectrum Licenses to Encourage Innovation and Investment](https://anthonyleezhang.github.io/pdfs/depreciatinglicenses.pdf)
- [Brian Ng: The Future of Blockchain Needs Economics](https://hackernoon.com/wanted-market-designers-for-the-blockchain-draft-d7d4ea4dc979)

## Motivation

While previous work most directly addresses the efficient allocation of public resources by governments, for instance auctions for fisheries and radio spectra, an unexplored use-case is for COST schemes to distribute virtual or privately owned assets among owners. 

First of all, the trustless nature of blockchain smart contracts reduce the financial and operational risk on governing bodies. If a startup were to use a COST scheme to distribute ownership of ridesharing cars, for instance, deploying it on a public blockchain rather than a centralized database would minimize the counterparty risk of owning a car license. If the governing corporation goes out of business, the license owner need not to rely on it in order to resell the object to other parties. The general public would still be able to verify that ownership is decentralized, and determine the current license owner. 

Second of all, it is cheaper to automate scheduled auctions on a public blockchain as they are naturally publicized, which brings governing bodies more flexibility and transparency. If a uniform standard is implemented for COST schemes, decentralized exchanges will be able to provide a standard user experience for asset discovery, valuation updates, auctions, tax payments, and so on. The turnover period could also be shortened from one year to increase allocative efficiency. 

Virtual on-chain assets, for instance ERC-721 non-fungible tokens, and rights over the ENS, are the best first use-case for blockchain COST schemes. For one, they can be liquidly transferred among without the need for centralized oracles, and secondly no fixed social norms exist for how they should be distributed. Standards in development for non-fungible assets (e.g. EIP 1155) on Ethereum already encourage multi-class, fractional ownership schemes by design. 

Third of all, having a blockchain COST scheme encourages other ways of distributing the revenue from COST auctions. For instance, instead of being paid to the governing body, the self-assessed tax could be burnt or redistributed equally to all token holders. For instance, one may imagine a variation of dPoS governance where the rights to a set of 20 block producers are determined with a COST scheme. While allowing block producers to bribe voters by sending them a share of profits, the scheme would automate a license fee to be distributed to all the people who did not vote for them, mimicking a VCG mechanism.

## Specification

The procedure for a COST scheme is as follows: A governing body wishes to distribute an asset which it owns. The government initially sells a depreciating license for a given resource to bidders in an auction. The depreciating license has indefinite length, but is characterized by some periodic depreciation rate τ. At the end of each period, a share τ of the license reverts to the government; the license holder must announce a price at which she repurchases the share τ of the license from the government. If someone else can beat that price, they can purchase the asset from the license holder. ([Weyl and Zhang 2016](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2744810))

We can alternatively think of the repurchase as a self-assessed license fee, and the depreciation rate τ designed to be the sale probability at equilibrium. License owners’ price announcements are kept in a publically available register, and any interested party can purchase any license from its current owner at her current value announcement.

WIP

## Rationale
WIP

## Backwards Compatibility

None in mind. 

## Test Cases
WIP

## Implementation
WIP

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by jessebmiller** [comment]
@sindarknave I'd be interested in working on this proposal with you if you.

**Comment by blakewest** [comment]
Has there been any other work on this? I'm interested in using something like this for a side project...
