### ISSUE TITLE
Idea: Making some functions self executable

### ISSUE THREAD

**Issue by seliestel** [ethereum/EIPs#1230]
We (@aribo and @seliestel) have been discussing an idea to make some functions self executable. This would allow the deployment of contracts that execute in the future without an explicit call/send by an external agent. The objective is to create the potential for autonomous code running on the EVM. Of course, this would need to come with a cost and some limitations, in order to protect the network from potential complications and abuses.

The proposal is to create a new opcode 'SELFCALL' with four arguments:

- **p** (position to mem where the bytecode to be executed is located), 
- **initial block** (set when the contract is created), 
- **interval** (number of blocks between executions, set in the contract code), and
- **gas price** (price of gas to be paid at execution, set in contract code). 

The EVM would need to calculate the difference between the current block number and the **initial block**. If this difference modulo **interval** is 0, the SELF bytecode located in **p** would be executed.

This opcode could be translated as a specific type of function modifier in Solidity, e.g. `self`. This modifier could be added to any function we want to self execute in the future.

SELF functions will be executed by the EVM every time a new block is mined, only if they have enough ether available. SELF functions would need to pay a set amount of gas every time they are called regardless of the computations they perform - basically the cost of the opcode. Moreover, the EVM would execute the SELF function as long as there is enough ether to pay the gas spent by its execution. 

Some SELF functions would never be called because they have run out of allocated ether. Others might be called and pay the set amount of gas, but then result in no computation or change of state (for example, an alarm clock that begins with a require statement and only runs when a certain time has been reached). Finally, some SELF functions would incur an additional cost in ether as they are executed by the EVM when called.

An example of a SELF function in solidity:

```
function wakeUp self(uint 5, uint 10000) {
  require (now == wakeUpTime);
  doSomething(); 
}
```

The SELF function wakeUp would be called by the EVM every 5 blocks since the contract was first constructed. It would pay 10,000 wei per gas for its execution. The cost in gas of calling the SELF function would be standarized. If the time now is less or more than wakeUpTime the function would do nothing and it would only have to pay in ether the set amount for being called. If wakeUpTime has been reached, it would need to pay in addition the cost in gas of running the function doSomething().

@seliestel 
@aribo

**Comment by adibas03** [comment]
From your description,
All contracts with the `SELFCALL` opcode would have to be watched till the execution time, or eternity by the present model. I do not think this would be a good implementation as this could easily lead to DDOSing the network.
On the implementation, a needed argument to prevent watching such contracts for eternity is `maxCalls`
The **maxCalls** arg would tell the EVM the maximum number of times, the call has to be made.
so, the contract would have to maintain a state `totalCalls` which the EVM uses to compare and would be one of the check to keep watching such said contract.

**Comment by DennisBPeterson** [comment]
One way to do this would be to have a (sparse) list of future blocks, each with a list of selfcall executions. The miner for each new block checks its list for scheduled selfcalls, and optionally executes some of them. Every time a selfcall executes, it optionally adds itself to the list on some future block.

Fluctuating gas prices would make this pretty uncertain though...you'd still have to monitor the chain in case your selfcall fails. As long as you're doing that, you might as well just issue the transactions.

**Comment by seliestel** [comment]
Thanks, @DennisBPeterson, @Arachnid and @adibas03 for the comments and suggestions. We are opening a thread on Ethereum Magicians, as Nick suggested. Maybe that will reignite the question of deferred (and recursive) execution and perhaps allow the community to find workable solutions to make it less problematic. At this stage of EVM development, it seems like a desirable step forward.

**Comment by fraymond** [comment]
It's not easy to schedule a function call by time on Ethereum. Maybe can we schedule it by block numbers, say, execute something every 50 blocks.
