### ISSUE TITLE
Cap new contracts at 100,000 eth

### ISSUE THREAD

**Issue by aakilfernandes** [ethereum/EIPs#124]
For blocks where `block.number >= DAO_TOKEN_REFUND`, make the following changes:

No transaction may increase the eth balance of a contract deployed after `DAO_TOKEN_REFUND` above 100,000. Any such transaction should fail and send all gas to the miner.

**Comment by PeterBorah** [comment]
In general, making contracts fail for reasons outside of their control seems dangerous to me. For example, I can imagine attacks that involved sending a contract enough Eth to put it near the limit, in order to prevent it from taking an action that would coincidentally also give it some Eth.

**Comment by aakilfernandes** [comment]
@PeterBorah this would only apply to newly deployed contracts. It seems like a relatively simple issue to take into account, especially when the alternative is hard forks to issue refunds.

I agree this is not a good solution, however i also believe forking for refunds is a worse solution. And I'll take the least bad solution.

**Comment by PeterBorah** [comment]
In practice, I suspect a common solution will be to have multiple contracts, each controlling part of the Eth. If that's true, then it won't actually provide much extra security, since they can likely all be attacked at once.

**Comment by aakilfernandes** [comment]
@PeterBorah we can look at the code and see evidence of devs who do that. Then we can all agree not to fork to refund them since they violated the "social contract".

**Comment by aakilfernandes** [comment]
If the concern is the introduction of new bugs, we could allow contracts with some sort of flag. Either an opcode or call to an different contract that indicates "DO NOT RESCUE".

So the instantiation code could have something like `DNR.register()`. Contracts that register with the DNR couild exceed the 1,000,000 limit

**Comment by subtly** [comment]
Crippling every contract in the system (some exchanges already use contracts which high balances) is a no-go. Would also create the same DoS issue with current SF.

**Comment by aakilfernandes** [comment]
Yes this is looking more and more problematic. I'm going to close.
