### ISSUE TITLE
ERC ? : Token Migration

### ISSUE THREAD

**Issue by chiro-hiro** [ethereum/EIPs#1246]
```
title: Token Migration
author: Chiro Hiro (@chiro-hiro)
status: Draft
discussions-to: <chiro@fkguru.com>
category: ERC
created: 2018-07-23
```
# Token Migration

## Simple Summary

This document provides a standard to migrating the old token standard to the new one.

## Abstract

Each particular token is holding ledger of transactions then It isn't a good idea to make a massive copy, meanwhile new standard of the token is feature rich and secure, so a migration is needed to keep all tokens are up-to-date and reduce the fragment. The Token Migration defines a set of methods to migrate token's ledger for reasonable cost and security.

## Motivation

There are many standards of Ethereum token such as `ERC-20`, `ERC-223`, `ERC-821`. We need a standard to stay away from the fragment or at least a method to migrate old token standard like `ERC-20` to the new one.

# Specification

## Rationale

The old token will be burned in an invalid address which will keep increasing over time (e.g `0x0000000000000000000000000000000000000001`) meanwhile a new token will be issued with the same amount.

The burning process makes the old token impossible to recover or redeem once again.

The cost of migration will be distributed among tokenholders and It cost around `77470 gas` for each `migrate()` call.

The redeemed token and the non-redeemed token will be *transferred* normally.

## Implementation

ERC20 Token interface:
```
contract ERC20Interface {
    function totalSupply() public constant returns (uint);
    function balanceOf(address tokenOwner) public constant returns (uint balance);
    function allowance(address tokenOwner, address spender) public constant returns (uint remaining);
    function transfer(address to, uint256 tokens) public returns (bool success);
    function approve(address spender, uint tokens) public returns (bool success);
    function transferFrom(address from, address to, uint tokens) public returns (bool success);

    event Transfer(address indexed from, address indexed to, uint tokens);
    event Approval(address indexed tokenOwner, address indexed spender, uint tokens);
}
```
New token with migration code:
```
contract NewToken{
    
    mapping (address => uint256) public balances;
    
    uint256 currentProcess = 1;
    
    ERC20Interface oldToken;
    
    constructor(address _oldAddress) public {
        oldToken = ERC20Interface(_oldAddress);
    }

    /* Token code here */
    
    function migrate() public returns(bool){
        uint256 oldBalance = oldToken.balanceOf(msg.sender);
        
        require(oldBalance > 0);
        
        //Burn old token
        require(address(oldToken).delegatecall(bytes4(keccak256("transfer(address,uint256)")), address(currentProcess), oldBalance));
        
        //Issue new token
        balances[msg.sender] = oldBalance;
        
        currentProcess++;
        
        return true;
    }
    
}
```

**Comment by flygoing** [comment]
I don't think this will work as expected. This `address(oldToken).delegatecall(bytes4(keccak256("transfer(address,uint256)")), address(currentProcess), oldBalance)` wont transfer the tokens on the old token to `currentProcess`, since delegatecall will make it act on the current contracts Storage. This will essentially call the `transfer` function of `oldToken`, but act on the storage of the `newToken` contract. Which doesn't make much sense.

Also, why even have `currentProcess`? Just send to 0x0...0 or 0x0...dead. The `currentProcess` variable isn't even public so you aren't getting anything by including it aside from the added gas costs.

**Comment by chiro-hiro** [comment]
@flygoing 
>I don't think this will work as expected. This address(oldToken).delegatecall(bytes4(keccak256("transfer(address,uint256)")), address(currentProcess), oldBalance) wont transfer the tokens on the old token to currentProcess.

The fist one, I need to burn the old token by send it to invalid address. 

> since delegatecall will make it act on the current contracts Storage. This will essentially call the transfer function of oldToken, but act on the storage of the newToken contract. Which doesn't make much sense.

Could you teach me about this section. I have just expected `delegatecall()` will keep `msg.sender` of current actor.

>Also, why have currentProcess? Just send to 0x0...0 or 0x0...0dead. The currentProcess variable isn't even public so you aren't getting anything by including it aside from the added gas costs.

Some token contract won't allow me to burn token since:
```
modifier onlyValidAddress(address _to){
    require(_to != address(0x00));
}
```
I'd like to keep migration is able to track.
> For this to work you'd have to approve the newToken contract to move the oldToken, and do a transferFrom within the newToken's migrate function.

It's mean, I have to paying  for gas of two transactions.

**Comment by flygoing** [comment]
> Could you teach me about this section?. I have just expected delegatecall() will keep msg.sender of the original actor who calls migrate() and trigger oldToken.transfer(address, uint256);.

the DELEGATECALL opcode calls the _code_ of the given address, in this case `oldToken`'s code, *but* it calls it with the calling contracts storage. It's _delegating_ it's execution code to another contract. Yes, DELEGATECALL preserves msg.sender and msg.value, but it also acts on the calling contracts storage.

> Some token contract won't allow me to burn token since:

Then send them all to 0x1.

> I'd like to keep migration is able to track. It's possible to rebuild a table of redeemed holders. e.g.

Does it need to be rebuilt on-chain? If not, you could simply use events to log the migration, e.g. an event in solidity like `Migration(address migrator, address oldToken, uint256 amount)` or something similar.

> It's mean, I have to paying for gas of two transactions.

That's just how ERC20 tokens work. A contract can't move another addresses tokens for them outside of the approve/transferFrom workflow.

**Comment by chiro-hiro** [comment]
@flygoing Thank you very much, I will keep thinking for a reasonable on-chain migration.

**Comment by flygoing** [comment]
>This migration need three steps to be done, I thought.

>1. The token-holder registers his address
>2. The token-holder approve newToken to use his token.
>3. The token-holder triggers newToken's migrate() then finish the migration.

They don't need to register their address for anything. `approve` allows a third party address to move tokens upto the amount I specify from my address to anywhere else. So I `approve` the newToken contract to move my oldTokens. Then I call `migrate` on newToken, which checks the balance of oldToken, moves them to either itself or to a burn address, and then creates the same amount in itself for the person migrating.

> I think, we can use burn and redeem mechanism.
>
>The token-holder transfer all tokens to address(keccak256(ms.sender)).
>Trigger newToken's redeem().

With this, I could redeem all my tokens on one address, then move them to another address, and redeem them again. Rinse and repeat.

**Comment by chiro-hiro** [comment]
@flygoing I get it, I will close this issue.
