### ISSUE TITLE
Transaction Receipts – Gas Details

### ISSUE THREAD

**Issue by subtly** [ethereum/EIPs#126]
<pre>
  EIP: 126
  Title: Transaction Receipts – Gas Details
  Author: Alex Leverington
  Status: Active
  Type: Standards Track
  Created: 2016-06-30
</pre>

==Abstract==
Add additional information to transaction receipts for gas accounting and analysis.

==Specification==
Add "gas refunded" and "gas cost" to transaction receipts and modify gas "used" to be based on accumulation of intrinsic cost and executed opcodes, excluding refunds.

==Rationale==
Improve metrics for analysis and accounting.

**Comment by janx** [comment]
What if we keep `gas_used` unchanged but add a accumulated `gas_refunded`? We can still deduce the same metrics but dApp depends on `gas_used` can keep unchanged.
