### ISSUE TITLE
ERC - Extendable Atomic Swaps

### ISSUE THREAD

**Issue by James-Sangalli** [ethereum/EIPs#1327]
Hi All,

**Preface**
Since writing ERC875 and being able to successfully and securely pull of atomic swaps through our standard via our wallet ([AlphaWallet](https://github.com/alpha-wallet)), I propose this standard as an idea for extending the functionality of existing standards to include basic atomic swaps.

**Motivation**
I personally believe that atomic swaps (the solution to the delivery vs payment problem) is one of the biggest advantages blockchain technology has to offer as it allows capabilities to securely trade on asset for currency. 

Since we have proven the ability to pull of atomic swaps in our standard, it is trivial to extend the functionality to other standards such as ERC20 and ERC721.

**Draft**
```
interface ERC20AtomicSwapExtension
{
    function trade(uint256 expiry, uint256 tokens, uint8 v, bytes32 r, bytes32 s) public payable;
}

interface ERC721AtomicSwapExtension
{
    function trade(uint256 expiry, uint256 tokenId, uint8 v, bytes32 r, bytes32 s) public payable;
}
```

Click [here](https://github.com/alpha-wallet/ERC-extendable-atomic-swaps) to see a contract implementation

**Comment by mudgen** [comment]
I am trying to understand this.  Can you lay out the steps of how this actually works?

Here is something from one of your articles:

> In ERC875 you can make an order by cryptographically signing a message containing the price, an expiry date for the deal and the signature itself. This process is done off chain and is only broadcasted at the time of settlement. This means you can update your order without ever paying gas. When a buyer is interested, all she has to do is receive the order and broadcast the transaction with the order details and the appropriate amount of ether to fulfil the deal.

Here are my questions:
1. How is the cryptographically signed message broadcasted?
2. How does the buyer receive the order?
3. What transaction does the buyer broadcast?

By "broadcast" do you mean execute a transaction on the ethereum network?

When does `trade` get called?

Can you lay out a sequence of steps that show the full use of the `trade` function?

I looked at ERC875 but how `trade` is used is still unclear to me. I want to understand this so please help clear it up for me.

**Comment by James-Sangalli** [comment]
Hi @mudgen 

1. it is inputed as data into the trade function call which can then do the ecrecover logic and balance manipulation as seen in ERC875 implementation [here](https://github.com/alpha-wallet/ERC875/blob/master/ERCTokenImplementation.sol#L70)

2. This logic is handled in seperate implementations, a service provider might have a market queue for example

3. The buyer produces the trade function call. No other party is needed and gas is only paid by the buyer meaning that the seller doesn't even need ether to sell a token. 

Note: trade function is defined in a sample way in this [repo](https://github.com/alpha-wallet/ERC875)

**Comment by mudgen** [comment]
I understand now. This is great, thank you.

**Comment by James-Sangalli** [comment]
Since this is included in EIP875, gonna close it.
