### ISSUE TITLE
Idea: Interacting with contracts without spending gas 

### ISSUE THREAD

**Issue by filips123** [ethereum/EIPs#1354]
## Summary

A way to interact with smart contracts (read and write) without spending gas.

## Abstract

Currently, only read functions of smart contracts are free, but they can not change data. Gas is needed for other (write) interaction with smart contracts. This could be the problem, because users of đApps must have enough Ethereum for their usage. This is not good for new users of đApps because they must buy Ethereum even for simple contract operations.

In order to make Ethereum and smart contracts more useful and user-friendly, there should be a way to interact with them without gas.

## Possible solutions

One solution is to make another blockchain network, which will be just for smart contracts and it will be free. Like test networks but more stable. This has a problem, because users would have to download both blockchains for usage of đApps.

Another solution is to make faucet for gas on mainnet. This could also has a problem, because it could lead to abuse of faucet.

**Comment by filips123** [comment]
Yes, but there should be some "official" solution or recommendation. There could also be some way to interact with both blockchains at same time.

**Comment by OFRBG** [comment]
Gas is vital to avoid spam attacks and keep the economic mechanism running. There are other proposals to do what you are suggesting via delegated gas spending i.e. the DApp owner or a third-party pays for the transaction. See #1228 for example.

**Comment by lsaether** [comment]
@filips123 

#1228 or #1077 is likely what you're looking for. 

These standards do not try to make smart contract interaction "free" but rather provide a way for a third party to pay the gas costs on behalf of the users. Depending on how DApps integrate this into their UX, it would seamlessly feel to the user that interacting with smart contracts are free. The way it works is that users sign messages signalling execution requests, and relay these messages to third party executioners. The executioners deploy the transaction to the chain and cover the gas fees. They can then be reimbursed in a token or in some other way (such as gaining a new user).

**Comment by UP822718** [comment]
Hay was proof of work originally meant for anti spam for email. Why don't you have the user do a small bit of work for the ethereum network to do a biger bit of work?
