### ISSUE TITLE
ERC 1361 - ETHPay : Standardized AppLinks for signing ETH transactions using an installed wallet on mobiles

### ISSUE THREAD

**Issue by madhavanmalolan** [ethereum/EIPs#1361]
```
---
eip: <to be assigned>
title: Standardized AppLink for signing ETH Transactions using an installed wallet on mobile
author: Madhavan Malolan (@madhavanmalolan)
status: Draft
type: Interface
created: 2018-08-29
---
```
## Simple Summary
Proposing standardizing the `ethpay://` URI (AppLink) so that native app developers can invoke user's wallets to sign transactions.

## Abstract
Proposing a simple mechanism that will allow developers to build DApps as native apps without having to maintain the users' wallets/private keys. DApps today are built primarily on the web because of the access to Web3 injections, but the user experience is lacking. Native apps provide a much richer experience. A MetaMask equivalent for native apps will help the developer community a long way.

## Motivation
App developers today need to maintain the private keys and keep pace with the changes happening on the Web3 libraries. A large majority of people have some ethereum Wallet installed on their phone which already maintains their keys and accounts. Why should every app developer have to re-invent the wheel by building the entire wallet stack into their app? By having a standardised AppLink app developers can leverage the existance of other ethereum wallets on the user's phone to sign and send transactions.

## Specification
The AppLink will be an URI of scheme `ethpay://`

### Possible actions
- `sign` : The wallet signs the data sent to it and redirects to a URI also specified in the request with the signature as a query parameter
- `sendSignedTransaction` : The wallet signs a transaction and sends it to an Ethereum Node

### Allowed parameters
- `action` : may be one of `sign` or `sendSignedTransaction`
- `to` : An Ethereum Address to which the transaction is to be sent. Required if action is `sendSignedTransaction`
- `value` : Integral value of number of Wei to include in the transaction. Optional.
- `data` : Data that needs to be signed. If action is `sendSignedTransaction` this should be hex encoded. Required if type is `sign`
- `gas` : Amount of gas to be used in the transaction. Required if action is `sendSignedTransaction`
- `gasPrice` : Gas price for the transaction. Optional. If not provided for action `sendSignedTransaction`, current gas price will be used.
- `redirectUri` : The URI to which the wallet should redirect with signature after signing. Used only for action `sign`.

## Rationale
The URI based AppLinks will allow app developers to request signing of transactions without needing to use any external library.
The users will not have to trust the app developer with their private keys, since it is maintained by a separate wallet app they already use.

## Implementation
A rough implementation of this protocol has been done using [Web3 1.0.0-beta](https://github.com/ethereum/web3.js) on a [React Native](https://facebook.github.io/react-native/) app. It uses [Infura](https://infura.io) as an Ethereum node.

The implementation handles App Links and a basic implementation of an ETH wallet.

You can find the [app's implementation here](https://github.com/madhavanmalolan/ethpay)

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by shrugs** [comment]
for `sendSignedTransaction` (maybe, `signAndSendTransaction`?), Would we not want the wallet app to redirect back to the original app after sending? I expect the original app would want information like a transaction hash.

**Comment by Dobrokhvalov** [comment]
I like the idea. However, there is an issue when multiple apps support the same URI scheme on iOS - https://stackoverflow.com/questions/13130442/multiple-apps-with-the-same-url-scheme-ios#13130479

One possible workaround can be using a dedicated website where user can choose his wallet. Something like this - https://www.youtube.com/watch?v=GMXEOdlR9L8&feature=youtu.be

We also have similar discussion on the WalletConnect's discourse - https://discuss.walletconnect.org/t/asymmetric-key-for-mobile-to-mobile/39/4?u=dobrokhvalov

cc @pedrouid

**Comment by madhavanmalolan** [comment]
@shrugs I think that's a fair point. I imagined the apps to send tracking information in `data`. But there's nothing stopping us from having a callback

**Comment by pedrouid** [comment]
This is super cool and something we have been thinking a lot on WalletConnect as @Dobrokhvalov has pointed out. I would perhaps extend ERC-681 to include the `redirectUri` parameter. Currently wallets already listen for `ethereum:` scheme and we have actually used this as a base for WalletConnect Standard URI Format following the ERC-831 URI Format. It would be great to use this proposal to specifically improve ERC-681 to work better with AppLinks

**Comment by ChrisCates** [comment]
@madhavanmalolan, it would be nice to have Swift and Java implementations.

There are web3 libraries for Swift and Android. But do we really need those?
