### ISSUE TITLE
EIP new opcode "codehash"

### ISSUE THREAD

**Issue by wanderer** [ethereum/EIPs#139]
# Overview
Adds a new opcode `CODEHASH`. This opcode returns the codeHash of an account given its address.

# Specification
The proposed value for this opcode is  `0xa5`.

This opcode pushes the hash of an account  to the stack, given the account's address. The account's address is pop from the stack. If the account doesn't exist then it push `0` to the stack  pops a single item from the stack.

# Rationale

This helps complete the set of getter operation for accounts. The other getter operations are
`EXTCODECOPY`, `EXTCODESIZE`, `BALANCE`.

The usecase for this opcode is for typechecking on the contract level. For example if you wanted to build a subcurrency that didn't have a central register account. The contract would need to know that it was sending units to an contract of a valid type.

Consider the following pseudocode.  This contract has to function `spend` and `receive`. The `spend` function need to check that it is "talking" to a contract of the same type. 
```
const validType = "0xsomehash"

function spend (to, amount) {
    if(CODEHASH(to) === validType) {
         storage['balance'] -= amount
         to.receive(amount)
    }
} 

function receive (amount) {
    if(CODEHASH(from) === validType) {
      storage['balance'] += amount
    }
} 
```

This should enable us to build shard proof subcurrencies since it would allow contracts that interact with a limited subtree of the state independently of the global knowledge of the contract. This would be useful in light client's applications as well as.

**Comment by axic** [comment]
I was writing a similar contract snippet to calculate code hash with `EXTCODECOPY` + `SHA3` as part of a pre-call verification the recipient.

Since there's no streaming `SHA3` in that case the memory equalling to `EXTCODESIZE` needs to be allocated.

**Comment by chriseth** [comment]
It would be great if we could also get information about the contract init code, that would actually allow proper reasoning or type checking of contracts, because we often do not only need the functionality of a contract but also its current or at least initial state. Luckily, with metropolis, we might be able to achieve that: The address of a contracts is the hash of its init code. Still, we are not 100% there, because the init code also contains the constructor parameters and we might want to allow some variability there.

**Comment by Arachnid** [comment]
While I've got no particular objection to the opcode being added, I don't see the use-case as compelling. Requiring a specific code hash severely restricts interoperability, while not proving anything about the contract's state, so in many cases it's still insufficient. In cases where you absolutely must trust the code you're calling, proof-of-ancestry seems more useful.

**Comment by wanderer** [comment]
@Arachnid 

> while not proving anything about the contract's state

yep. There is a difference between the contract's code and the state of a contract. And I think they should be different opcodes. Also getting stateroots is harder to do from an implementation perspective.

>  I don't see the use-case as compelling. 

What prompted this EIP was thinking about sub-currencies that shard proof. Which I would argue is a good use case. If you build naive subcurrency contract  you would create a single contract that simply creates a ledge in its Storage.  If this was on shard `A` but you lived on shard `B` then you wouldn't want to talk to shard `A` every time you moved around  the subcurrency.  

Another way at looking at this is thinking about it in terms of UTXOs.  This would allow you to build contracts, where every individual instance of the contract was like an UTXO.  

There are several ways of solving these problem. But I think this is an elegant way of doing it and minimally invasive to implementations since implementation would be exactly the same as `BALANCE` except we are now getting the 4th item from RLP account array, instead of the first.

> Requiring a specific code hash severely restricts interoperability

you could check multiple hashes. valid hash types could be set by the parent contract. There are multiple ways to make this reactive.

**Comment by Arachnid** [comment]
> What prompted this EIP was thinking about sub-currencies that shard proof. Which I would argue is a good use case. If you build naive subcurrency contract you would create a single contract that simply creates a ledge in its Storage. If this was on shard A but you lived on shard B then you wouldn't want to talk to shard A every time you moved around the subcurrency.

I think you're going to have to elaborate a bit on how being able to determine the code hash helps with that - I don't follow at all.

> you could check multiple hashes. valid hash types could be set by the parent contract. There are multiple ways to make this reactive.

Only interacting with certain code makes for an extremely inflexible system, though; much of the value of Ethereum, and the Internet as a whole, comes from permissionless innovation, which this completely shuts down.

If your security model absolutely requires you to trust the code you're interacting with, there are alternatives that don't require any EVM modifications; the simplest is proof-of-ancestry. Given a factory contract that creates instances of the contract you care about, you can trivially verify that a contract is descended from it by hashing the factory's address with the creation nonce of the child contract, and verifying it matches the contract's address. Unlike checking the code hash, this also lets you make assertions about the entire state of the target contract.

**Comment by wanderer** [comment]
> Given a factory contract 

If there are shards, then there would be a different  factory contract on each contract. Furthermore let's say a new instance of the contract is created everytime its used in which case generating the address from the factory's address could be 10,000 of hashes. But for simplicity just assume there are no factory contracts

> alternatives that don't require any EVM modifications;

Now lets say we have subcurrency contract like the initial example. It has a simple `send`, `receive`. How does instance `A` send some units to instance  `B` without breaking the integrity of the overall contract?

**Comment by Arachnid** [comment]
> If there are shards, then there would be a different factory contract on each contract.

Yes, but as you already pointed out, it's no problem to check several addresses.

> Furthermore let's say a new instance of the contract is created everytime its used in which case generating the address from the factory's address could be 10,000 of hashes.

You only need one hash, if the factory contract keeps track of how many contracts it's created, and provides the nonce to the created contract for use in proofs.

> Now lets say we have subcurrency contract like the initial example. It has a simple send, receive. How does instance A send some units to instance B without breaking the integrity of the overall contract?

I don't know, how? That's exactly what I was asking for an explanation of.

**Comment by wanderer** [comment]
> You only need one hash, if the factory contract keeps track of how many contracts it's created, and provides the nonce to the created contract for use in proofs.


ok contract `A` creates `B`, `B` creates `C`, `D` creates `F` and so on, and to `Z` How does `Z`. how does `A` generate `Z`s address?

> I don't know, how? That's exactly what I was asking for an explanation of.

well one way  is if you had `codeHash`. `A` would check if `B` is running the correct code. 
 ```
function spend (to, amount) {
    if(CODEHASH(to) === validType) {
         storage['balance'] -= amount
         to.receive(amount)
    }
} 
```
This would prevent units being added or subtracted to contract (which is compose of many instances) by any third party contract.

**Comment by Arachnid** [comment]
> ok contract A creates B, B creates C, D creates F and so on, and to Z How does Z. how does A generate Zs address?

It doesn't - A generates all the contracts, and B through Z call it for new instances.

> This would prevent units being added or subtracted to contract (which is compose of many instances) by any third party contract.

If you're checking only the codehash, then the contract needs to be written so that no set of stored data can "sway it from its appointed course" - for instance, I could create a contract that gives me a massive preloaded balance, then use it to call contracts on other shards to hand over their tokens. From this perspective, checking code hash is simultaneously too restrictive, since it prohibits innovation, and too lax.

**Comment by wanderer** [comment]
> If you're checking only the codehash, then the contract needs to be written so that no set of stored data can "sway it from its appointed course" - for instance, I could create a contract that gives me a massive preloaded balance, then use it to call contracts on other shards to hand over their tokens

yep as @chriseth pointed out.  One way around is to have the contract check its parent's codeHash. There maybe some other hacky ways around this But it would be nice to get more guarantees about the starting state.  

> checking code hash is simultaneously too restrictive, since it prohibits innovation, and too lax.

Provide a counter proposal then

**Comment by Arachnid** [comment]
> Provide a counter proposal then

I just did exactly that - factory contracts, and the ability to prove a contract was generated by a factory. But I think the real solution is, wherever possible, authoring contracts so that they don't have to rely on knowing what code another contract is running - as I stated earlier, all the best innovation is permissionless.

**Comment by wanderer** [comment]
> factory contracts, 

Right, the whole point is that we are trying NOT use single factory contracts. 

> all the best innovation is permissionless.

ok. I'll just take your word on that. Is checking signatures to spend funds permissionless? If that is permissionless then why would checking signatures and checking a codeHash to spend funds not be permissionless?

**Comment by Arachnid** [comment]
> Right, the whole point is that we are trying NOT to use single factory contracts.

Why not?

> ok. I'll just take your word on that. Is checking signatures to spend funds permissionless? If that is permissionless then why would checking signatures and checking a codeHash to spend funds not be permissionless?

By "permissionless" I mean "permissionless innovation" - you don't need to ask someone else in order to build on top of their stack. Open APIs such as HTTP, OAUTH, and the standardized token contract are examples of that. Requiring someone to add the code hash for your contract to a whitelist is an example of the opposite.

If you need to seek permission before doing something new, it becomes enormously harder to do new and interesting things.

**Comment by wanderer** [comment]
> Why not?

1) Shards. Since contracts don't have to phone home to parent contract. 
2) ephemeral contracts that emulate UTXO  

>  permissionless innovation

Im defining the "contract" as a Set of contracts that are all running the same code. Each instance stands for one account. To transfer funds between accounts you need to check codeHash. But to trigger a unit transfer or to interact with a contract in other ways could be done via an permissionless API or an interface the contract provides. Only internal operations need to check. Let me  update the example so that it has an external permissionless API as well as the the internal interface

Also I made a mistake in the original example that might be causing confusion

```
const validType = "0xsomehash"

function spend (to, amount) {
     if(msg.caller == storage['owner'] &&  storage['balance'] > amount){
        storage['balance'] -= amount
        this.internal_spend(to, amount)
     }
} 

function internal_spend(to, amount) {
    if(CODEHASH(to) === validType) {
         storage['balance'] -= amount
         to.internal_receive(amount)
    }
} 

function internal_receive (amount) {
    if(CODEHASH(from) === validType) {
      storage['balance'] += amount
    }
} 
```

**Comment by Arachnid** [comment]
> 1) Shards. Since contracts don't have to phone home to the factory contract. 

With proof-of-ancestry with hashing, that's not necessary even with sharding. It might require having one factory address per shard, though it seems likely that whatever mechanism is used to generate addresses on different shards will be deterministic, and thus still permit the same approach with a single parent hash.

> 2) ephemeral contracts that emulate UTXO

This seems entirely practical with a factory contract too, although it's not clear to me why you'd need to prove the code of such a contract, rather than its ancestry.

> Im defining the "contract" as a Set of contracts that are all running the same code. Each instance stands for one account. 

Okay; fair enough.

> To transfer funds between accounts you need to check codeHash. 

Proving ancestry still seems like a better option to me, since it lets you make assertions about the contract's state as well as its code.

**Comment by chfast** [comment]
+me

**Comment by nmushegian** [comment]
CODEHASH would let you do "short-circuits" in the "what is the type of this address" proof for some cases, which is interesting, but I agree that it's not really enough on its own and people shouldn't use it as a shortcut for having a whole type-factory model

**Comment by axic** [comment]
While this might have limited applications, it can be still very useful in certain cases and given it is already available to the state, it would make sense making it available to EVM.

Proof of ancestry might become more complicated when contract address calculation changes (Serenity?) because multiple ways (the current and the new) of calculating an address must be checked.

**Comment by Arachnid** [comment]
> While this might have limited applications, it can be still very useful in certain cases and given it is already available to the state, it would make sense making it available to EVM.

While I still haven't heard a truly compelling use-case, I agree that it's probably worth adding because it's easily available in the state, and may prove useful.

> Proof of ancestry might become more complicated when contract address calculation changes (Serenity?) because multiple ways (the current and the new) of calculating an address must be checked.

If you get to handwave away checking initial state, I get to handwave away address calculations maybe changing. ;)

**Comment by chfast** [comment]
`CODEHASH` will also allow to check if an account exits. Gas cost of `CALL` depends on it.

**Comment by axic** [comment]
> CODEHASH will also allow to check if an account exits. Gas cost of CALL depends on it.

`EXTCODESIZE` could already be used for that.

**Comment by chfast** [comment]
@axic Actually not, because an account can be in any of 5 states:
- not exists, no executable code, code size 0
- exists, no executable code, code size 0
- exists, executable code, size > 0
- not exists, executable code, code size 0
- exists, executable code, code size 0.
As you can "see code" size property does not match "exists" property.

**Comment by Arachnid** [comment]
But all accounts with code size 0 will have the same hash, so how is `CODEHASH` an improvement?

**Comment by chfast** [comment]
As I understand this `CODEHASH` of an existing account with empty code is Keccak("") and `CODEHASH` of non-existing account is 0. Right?

**Comment by axic** [comment]
> As I understand this CODEHASH of an existing account with empty code is Keccak("") and CODEHASH of non-existing account is 0. Right?

Yes, it should be `c5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470` for empty and `0` for non-existent.

So it is definitely an improvement.

**Comment by chfast** [comment]
The mess is always around precompiled contracts (last 2 states) as we allowed them to be non-existing but still usable.

**Comment by axic** [comment]
Aren't they existing just with codesize 0? Otherwise the empty account call fee would be charged every time.

**Comment by chfast** [comment]
Empty account call fee is charged the first time called (globally). Unless you create them in the genesis block.

**Comment by axic** [comment]
Yes, but that is an edge case as part of the network creation users are instructed to do this. In ethereumjs-vm it is done every time so for example browser-solidity  gas costs won't be confusing.

**Comment by chfast** [comment]
It is edge case, but VM implementations have to handle edge cases.

**Comment by axic** [comment]
> It is edge case, but VM implementations have to handle edge cases.

I don't think it affects the VM, only contracts. Before precompiles are included in the state, `codehash` will return `0`, otherwise `c5d246...`. It is only a problem to contracts, but they already face that with the higher fee they might not be expecting.

**Comment by axic** [comment]
@wanderer I think this should be named `EXTCODEHASH` because it gets an external account's code hash and not the current contract's. This is in line with `EXTCODESIZE`/`EXTCODECOPY`.

`BALANCE` actually should be two opcodes: `BALANCE` and `EXTBALANCE` (currently we have `EXTBALANCE` named `BALANCE`).

**Comment by wanderer** [comment]
closed b/c this functionality can be replicated with  CODESIZE, CODECOPY
