### ISSUE TITLE
Storing the token metadata as a simple string

### ISSUE THREAD

**Issue by arisAlexis** [ethereum/EIPs#1392]
Currently the EIP proposes to have a tokenURI that points to a JSON file somewhere. This needs a lot of extra programming to get it on the IPFS and then code that reads it from there. It will also leave a lot of chancing JSON useless files on IPFS and finally you need to be running an IPFS node to make sure that they are always accessible and not regarded obsolete and removed.  Other option is to keep the URL centralized (which kind of defeats the purpose). 

What I am proposing is to have the option to keep a stringified JSON object directly on the state variable. The pros are:

- Totally decentralized

- No extra programming required (simplicity/ease of use, you can even read the data from explorers)

- Not much more storage. We are already keeping a string, in this case the string is a bit bigger yes depending on the description.

**Comment by axic** [comment]
Which EIP/ERC are you referring to? Perhaps it would make sense to discuss this on the discussion URL of the reference EIP/ERC?
