### ISSUE TITLE
Batch cancellation of transactions

### ISSUE THREAD

**Issue by danfinlay** [ethereum/EIPs#1403]
Sometimes a user has a series of transactions pending that they want to invalidate urgently and atomically.

Currently the best solution is to submit a replacement "zero value" tx for each of the pending txs, with an increase of gas, and hope that miners mine the cancellation transactions first.

This creates a lot of on-chain traffic just for batch cancellation, and can result in inconsistent results, where some dependent transactions are processed when earlier ones were successfully "cancelled".

One way this could be alleviated would be if transactions could have "nonce spans" that included a range of nonces from the current valid nonce to a future nonce, incrementing the account nonce by a user-specified amount, and invalidating any transactions with a nonce below the resulting nonce.

Thoughts? Other approaches?

**Comment by bragadino** [comment]
Approaching the issue in a very naive way. Can we enable the sender to submit a "cancellation" tx, where when broadcasted nodes would drop the previous transaction(s) when their first or last transaction bytes match.

**Comment by kevinsimper** [comment]
This issue resembles this issue a bit in that you want to have a way to easier cancel transactions https://github.com/ethereum/EIPs/pull/599
