### ISSUE TITLE
Proposed ERC20 change: Total Supply should subtract tokens in the 0 address

### ISSUE THREAD

**Issue by matt-lough** [ethereum/EIPs#1419]
- Tokens sent to `address(0)` can not be transferred anymore, they are effectively out of the supply
- Transferring tokens to `address(0)` is a very common implementation of a `burn` function in popular ERC20 frameworks
- The current definition is not defined explicitly and is open to interpretation, recommend a more explicit definition

e.g

Change
> Returns the total token supply.

to
> Returns the sum of all account balances excluding `address(0)`

A simple example implementation:

    function totalSupply() public view returns (uint) {
        return _totalSupply - balances[address(0)];
    }

**Comment by MicahZoltu** [comment]
ERC20 as a standard is final and thus cannot be changed.  There are already tokens out there that don't account for balances in `address(0)` and they are ERC20.  This change would make it so those tokens are suddenly not ERC20 tokens.

I recommend either creating a new ERC that extends ERC20, or providing your feedback to some of the new token standards that are being worked on.  FWIW, I believe ERC-721 already does the right thing in this regard.

**Comment by OFRBG** [comment]
Adding to what @MicahZoltu said, many ERC20 tokens greatly expand on top of the standard. A very popular custom extension was used by SNT, `approveAndCall()`. It was then replaced by #744. ERC20 is pretty solid, and implementation isn't standard. You put anything inside the template as long as it complies with the standard.

On https://github.com/ethereum/EIPs/blob/master/EIPS/eip-20.md, `totalSupply` is defined as

> totalSupply
> Returns the total token supply.

So you have room for interpretation.
