### ISSUE TITLE
EVM: SSTORE/SLOAD gas costs split into processing and storage costs

### ISSUE THREAD

**Issue by axic** [ethereum/EIPs#142]
# Overview

Split the specified gas cost of `SSTORE` and `SLOAD` to processing and storage cost elements.
# Specification

`SSTORE` to have the following gas costs:
- processing: 50 gas
- storage charges:
  - set to non-zero from zero: 19950
  - any other case: 4950
- storage refunds:
  - set to zero from non-zero (ie. deletion): 15000

i.e. setting to non-zero from zero is a total of 20000, while setting to zero is a refund of 10000. (No change here to current behaviour)
# Rationale

Based on the [Merkle Patricia Tree Specification](https://github.com/ethereum/wiki/blob/78990aca283f67ceb26ed70c8eb82008424aaf64/pages/patricia-tree/[english]-patricia-tree.md), inserts and lookups should be the same complexity.

As `SLOAD` currently takes 50 gas to load (lookup), we can assume that is the processing cost for traversing the trie. `SSTORE` should have the same cost for processing.

Making this split now will be beneficial when blockchain rent needs to define the rent figures as opposed to the processing costs.

**Comment by axic** [comment]
The figures above are given as a starting point for discussion.  The specification on tire complexity might be entirely off and that invalidates the above.

Based on the Yellow Paper, the processing fee is 5000 gas for SSTORE, because:
> `Gset` -  20000 -  Paid for an SSTORE operation when the storage value is set to non-zero from zero.
> `Gsreset` -  5000 -  Paid for an SSTORE operation when the storage value’s zeroness remains unchanged or is set to zero.
> `Rsclear` -  15000 -  Refund given (added into refund counter) when the storage value is set to zero from non-zero.

**Comment by chfast** [comment]
-1500 = -1550 + 50

**Comment by axic** [comment]
@chfast thanks, updated!

**Comment by vbuterin** [comment]
The 5000 cost for a value-changing SSTORE is meant to represent the cost to history growth and the Merkle tree recalculations. So it should definitely be much larger than an SLOAD.

**Comment by axic** [comment]
@chfast @vbuterin updated description to map the YP 1:1.

Is there a sensible way to split up the 5000 to processing and storage costs?

- processing: 2000 gas (10x as much as SLOAD in EIP150.1)
- storage charges:
  - set to non-zero from zero: 18000
  - any other case: 3000
- storage refunds:
  - set to zero from non-zero (ie. deletion): 15000
