### ISSUE TITLE
Creator Contract abstraction

### ISSUE THREAD

**Issue by axic** [ethereum/EIPs#143]
This is a follow up to https://github.com/ethereum/EIPs/issues/86 with the intent of moving more logic to contract abstractions.
### Motivation

Replace the special `CREATE` opcode and the special case of external transactions, which cause a contract to be deployed, with a contract.
### Abstract

The creator contract (at address `TBD`) takes bytecode to be deployed as the input and returns 20 bytes output consisting of the 160-bit contract address. 

The EVM opcode `CREATE` is mapped to be a `CALL` to the creator contract.
### Implementation

Initially, this contract could only be implemented as a _precompile_, which has special access to the state. Later, with eWASM, it would be possible to have a privileged set of imported methods to _system contracts_ and the creator contract could be implemented natively in eWASM.

For the current address algorithm it also needs to have access to the sender's nonce (`sha3(rlp([sender, sender_nonce]))`), but with the proposed new Metropolis algorithm (`sha3(sender + bytecode)`) that is not necessary.

Furthermore, the creator contract in eWASM could include the feature set of the [Sentinel Contract](https://github.com/ethereum/evm2.0-design/blob/system-contracts/system_contracts.md#sentinel-contract) to support deploying both EVM1 and eWASM, including validation and metering injection.

**Comment by wanderer** [comment]
would it handle running the initialization code for new contracts also?

**Comment by axic** [comment]
> would it handle running the initialization code for new contracts also?

It has to because it returns the deployed contract address.
