### ISSUE TITLE
EVM opcode: CALLGAS

### ISSUE THREAD

**Issue by axic** [ethereum/EIPs#146]
This is split out of #28.
### Motivation

To allow contracts calculate the gas used effectively.
### Specification

A new opcode, ~~`TXGAS`~~ `CALLGAS` is introduced at `0x3d`. It returns the initial gas allocation for the call. It can be used together with `GAS` (`0x5a`) to calculate the gas used.

Note: this is different to #28 where the opcode `0x5c` was suggested.

**Comment by chfast** [comment]
If this is about current call, I'd name it `MSGGAS`.

How is it better than storing the gas to the memory at the very beginning?

**Comment by axic** [comment]
True! I think `CALLGAS` might be better fitting as we have `CALLVALUE` as well.

**Comment by lastperson** [comment]
This will only solve part of the issue. We also need CALLREFUND counter that will tell how much gas is gathered for refund (storage cleaning) at this point of time.
