### ISSUE TITLE
Solidity Standard Library: function overloading for modifiers

### ISSUE THREAD

**Issue by ChrisCates** [ethereum/EIPs#1465]
Function overloading for the Solidity Standard Library would help improve development processes.
In this context, we could allow both modifiers and arguments to be overloaded...

For example:

function example() public pure returns(bool) {
  return true;
}
// Could be overloaded in such a way like this:
bool hello = false;
function example() public view returns(bool) {
  return hello;
}

Or in the context of arguments for a function:

// One argument
function example(uint arg1) internal {
  //Do stuff
}
// Two arguments
function example(uint arg1, address arg2) internal {
  //Do stuff
}

Overloaded functions make a lot of sense considering the nature of the language and the contexts it is used inlanguage, and how it has evolved in regards to syntax and functionality... This also includes the contexts the language is used in, for example, libraries such as OZ... If there are any concerns in regards to an implementation into the standard library... Would be interested in learning about it.

**Comment by Aniket-Engg** [comment]
```
pragma solidity ^0.4.24;

contract A {
    function f(uint _in) public pure returns (uint out) {
        return _in;
    }

    function f(uint _in, uint _in2) public view returns (uint out) {
     out = _in + _in2;
    }
}
```

This works fine in Remix.

**Comment by ChrisCates** [comment]
@Aniket-Engg, closing... Since I clearly just made a really redundant proposal...
