### ISSUE TITLE
Role of editors in EIP process

### ISSUE THREAD

**Issue by effortEfficiency** [ethereum/EIPs#1467]
I have just read over the EIP readme, and am curious about the role of editors in the whole process. They seem to be gatekeepers at two critical points in the process - assigning a number, and moving the final EIP to "Final" or "Accepted". In the first case, what are the criteria for a new EIP being granted a number, and moving forward in the process? In the second case, what are the criteria for a draft EIP while being reviewed by an editor, and how does an editor decide that there is "rough consensus"?

**Comment by dip239** [comment]
This question should be a part of a bigger discussion.

Please check out a draft of [Decentralizing EIP workflow](https://ethereum-magicians.org/t/decentralizing-eip-workflow/1525/3).
