### ISSUE TITLE
ERC: $ETHEREUM_SOCKET

### ISSUE THREAD

**Issue by fjl** [ethereum/EIPs#147]
Geth and other implementations offer the JSON-RPC over various transports, including Unix Domain Sockets and Windows Named Pipes. Clients of the RPC API need to find the socket in order to connect to the API. 

I propose that API clients (Mist, web3.js when using node.js, ...) should use the value of the `ETHEREUM_SOCKET` environment variable as the default endpoint to connect to. Doing so creates a convention that makes it easier to interact with Ethereum regardless of the node implementation chosen by the user.

Environment variables are a common way to communicate API endpoints. For precedent, consider that ssh agent implementations communicate the location of their socket using the `SSH_AUTH_SOCK` variable. Similarly, dbus-daemon uses `DBUS_SESSION_BUS_ADDRESS` to communicate its endpoint and software that needs access to dbus fails to launch if this variable is not set. 

Setting the variable is left to the user or system administrator. The default can be set through software packaging infrastructure (e.g. using a file in /etc/profile.d on Linux). Advanced init systems like systemd and Apple's launchd also allow setting environment variables in service definitions.

I propose that the value of `ETHEREUM_SOCKET` should be interpreted as follows:
- If set to a URL string starting with http://, https://, ws:// or wss://, the endpoint should be treated as a URL of the given type.
- On UNIX-like platforms, values without such prefix should be interpreted as the file system location of a unix domain socket.
- On Microsoft Windows, values without such prefix should be interpreted as a named `pipe` path.

**Comment by chfast** [comment]
I would give it a bit more precise name, like `ETHEREUM_RPC_ADDRESS` or `ETHEREUM_RPC_SERVER_ADDRESS`...

**Comment by chriseth** [comment]
Are there any hidden security risks in doing this? An attacker might set the environment variable to a proxy and manipulate messages. On the other hand, if the attacker can set an environment variable, they can probably do much more.

**Comment by fjl** [comment]
Let's look at the risks:

One security risk is that some software (looking at you, Mist) still uses the keystore built into the node  to manage accounts. An attacker with the privilege to set environment variables could capture account passwords this way. But such an attacker could also bind the default socket location (e.g. ~/.ethereum/geth.ipc on Linux). Mist could defend against this by not checking the default location and setting --ipcpath to a random location for each launch. We want to remove account management and associated APIs from geth in the long run.

Even if the API only serves public data, a proxy can serve arbitrary state to the app to influence decisions based on blockchain data (e.g. opening door locks, granting access to in-game content...).
This risk also exists now and there is no good defense other than running the Ethereum client in the same process.

**Comment by frozeman** [comment]
I agree +1

**Comment by axic** [comment]
I'm using `ETHEREUM_RPC_URL` in my tools locally. (Contains `http(s)://<ip>:<port>`, but could also include `ipc:///path/to/file`.)

**Comment by karalabe** [comment]
What would be a meaningful default if the env var is not set? Asking because in Go-land the default workspace is defined by GOPATH, and this already causes problems to newcomers even though they are qualified programmers. Requiring the env var to be set by average Joe won't fly imho.

I'd also like to be able to run mutliple instances of Mist and or any other program. How could we do that meaningfully?

**Comment by fjl** [comment]
The idea is to use the variable as a default only. Users can still override the location in some other way (through command line flags, etc.). Environment variables can also be set on a per-session basis.

**Comment by bitpshr** [comment]
What's the status of this ERC? Do we have an ETA of when we can get an editor to review?

**Comment by fjl** [comment]
I think the status of this ERC is: nobody cared about it so it was not implemented. 

We implemented it in the geth installer for Windows: ETHEREUM_SOCKET is set to `\\.\pipe\geth.ipc`. Our package installers for Linux don't set it though.
