### ISSUE TITLE
Ability For Developers or Security Auditors To Cryptographically Sign Contracts

### ISSUE THREAD

**Issue by taoteh1221** [ethereum/EIPs#149]
Wouldn't it be feasible to make it as easy as possible, to digitally sign AND confirm digital signatures of a developer or security auditor on any given deployed contract? Such as requesting a "signature verification" from the contract itself via CLI or Mist? Maybe a specific storage instance per contract, reserved for digital signatures? 

Auditing of smart contracts will surely become the norm within the next few years, since storage of value often occurs within a contract, as well as any reliance on general data integrity (for public chains especially). The easier it is to verify a CERTAIN TRUSTED PARTY's private key signed a specific contract, along with the usual bytecode verification, the more businesses and organizations may be willing trust the Ethereum platform if / when it makes it's way into a mainstream environment in the future.

**Comment by flyswatter** [comment]
This is indeed very easy to do on Ethereum.

Since every transaction is itself signed by a public key, all you actually need is a simple registry contract where anyone can approve an address, along with any other meta-data you think is relevant, maybe a final security rating, for example.

All that remains after a simple registry contract like that is the user experience, for how to represent a contract that may have been reviewed by dozens if not hundreds or thousands of peers?

Maybe incorporating bonding into the review process?  Lots of fun possibilities.

**Comment by axic** [comment]
Solidity itself will have a verification system, where the compilation will also output metadata (in JSON format), which includes all details needed to recreate the contract, etc as well as hashes of the output contracts. That metadata should be available via Swarm/IPFS and it could be signed (in other Swarm objects).

**Comment by taoteh1221** [comment]
@flyswatter Interesting insights. If Ethereum contracts could be signed securely like application binaries on a PC, and display a warning dialog if not trusted or signed (via CLI or Mist GUI) before executing them, I think end-user trust levels may be more in line with mainstream use. 

Additionally, a "Trust this source" feature could be added to the various implementations, which would remove the issue of repeated approval of a trusted source, whether the same contract or a separate one. 

Going this route, there may be less disasters regarding malicious contracts / large ETH losses, as the default  in implementations could be to warn if a signature is non-existent, or not yet marked as a trusted source before execution.

**Comment by taoteh1221** [comment]
@axic Nice to here it's possible with the current upcoming Solidity features. I figured I'd throw this proposal up here for Ethdev's EIP notes, if it tickles their fancy. :smile:

**Comment by simonjanin** [comment]
I coded up a "pre-prototype" of this EIP for fun.
[](https://github.com/simonjanin/EIP149-implementation)

Comments welcome.
