### ISSUE TITLE
Token forwarding (ERC20 extension)

### ISSUE THREAD

**Issue by stasptr** [ethereum/EIPs#1505]
### Preamble

EIP: <to be assigned>
Title: Token standard
Author: Stanislav Petrovskiy @stasptr
Type: Informational
Category: ERC
Status: Draft
Created: 2018-10-17
Requires: EIP20

### Simple Summary

Ability for address owner to set up token forwarding without paying for gas

### Abstract

Proposed erc20 extension has option to set token forwarding from an address to target address by delegate. Tokens transferred to such address are automatically forwarded to target address. Transfer events are emitted as if tokens come to address with forwarding and then to target address.

### Motivation

When application uses erc20 utility token and application users can input tokens, the most user-friendly solution is to assign to users application controlled input addresses. But tokens sent to such addresses are hard to move further because token owner have to have ETH in his account to pay for gas.
Crypto exchanges usually create a contract for each user and use it as input address - universal, but expensive solution.
Another solution is to implement #965 (send by signature token extension)
Proposed solution below is more specific and has some benefits against #965

#### Solution
Token contract has option to set permanent token forwarding from one address to another.
This operation may be performed by owner of address or by delegate using signature.
Tokens transferred to address with forwarding are automatically transferred to the forwarding target address. Transfer events are emitted for whole forwarding path.

Forwarding chain is allowed.
Motivation: simple forwarding is enough if all input address forwarding set to cold wallet. But what if cold wallet is compromised? With forwarding chains we just set forwarding from the compromised wallet to new one.

After forwarding is set, change forwarding can only owner of address - the address receiving tokens from 
this address after forwarding chain. Setting forwarding is similar to transfer address ownership.

When token forwarding is set from some address to some target, the current address balance is transferred to target. So balance of address with forwarding is always 0.
Motivation: application may setup forwarding for user's input address only after user transfers some tokens to it. Further token inputs for this user are forwarding to cold wallet automatically, so application needs to pay for gas only once per user.

#### function ownerOf(address _address) view public returns (address)
Returns real owner of address
if no forwarding for given address is set - returns given address
if forwarding for given address is set to target - returns ownerOf(target)
Chain forwarding is possible, loops is impossible

#### function setupForward(address _address, address _receiver) public
Non delegate setupForward must be called by ownerOf(_address)
Sets forwarding from _address to _receiver
Emits event SetupForward(_address, caller, _receiver)
Transfers current balance of _address to _receiver, with forwarding and transfer events

#### delegateSetupForward(address _address, address _receiver, uint8 _v, bytes32 _r, bytes32 _s) public
delegateSetupForward must check that signature (_v, _r, _s) of message {"setup forward", _tokenAddress, _address, _receiver} belongs to current ownerOf(_address)
Sets forwarding from _address to _receiver
Emits event SetupForward(_address, caller, _receiver)
Transfers current balance of _address to _receiver, with forwarding and transfer events

Motivation: message doesn't start with Ethereum Signed Message prefix, so attack "please sign this message" is impossible. Message doesn't contain delegate, so it may be used by anybody. It is option to discuss adding delegate address to signature. Current message format allows generating pack of signatures using cold hd wallet, and not to regenerate them if application delegate wallet is changed. Application wallet has more chances to be compromised then cold wallet.

#### Interface
```solidity
pragma solidity ^0.4.24;

interface ForwardableToken {
  event SetupForward(address address_, address oldOwner_, address newOwner_);

  function ownerOf(address _address) view public returns (address);
  function setupForward(address _address, address _receiver) public;
  function delegateSetupForward(address _address, address _receiver, uint8 _v, bytes32 _r, bytes32 _s) public;
}
```
#### Implementation
AutoForwardableToken (has some differencies in method names) ](https://github.com/ElylandLLC/ico/blob/master/contracts/AutoForwardableToken.sol)

**Comment by djosey** [comment]
Wonder if anyone ever pursued anything comparable to this standard?
