### ISSUE TITLE
Callbacks for network change and account change

### ISSUE THREAD

**Issue by chevdor** [ethereum/EIPs#151]
I propose the addition of callbacks for the following cases:
1. network changed
2. address/account changed

That would allow DAPP to avoid polling for such critical information

**Comment by Smithgift** [comment]
This is most likely already available.

By network change, do you mean whenever there is a new block (or a new unconfirmed transaction?) In web3.js, you can use one form of [web3.eth.filter](https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethfilter) to fire a callback.

Monitoring a specific address or contract is more difficult. If it's a contract, you can write it to log when something specific happened (i.e. a deposit is made) and then listen in web3.js with [events in the contract object](https://github.com/ethereum/wiki/wiki/JavaScript-API#contract-events).

**Comment by chevdor** [comment]
Indeed, it was not clear :)

By network change, I meant the fact that the user is changing the network. For instance, going from mainnet to testnet or to a custom rpc.

As far as I know, the current network and the current account are the only 2 contextual information that are relevant. As you mentioned, the rest can be figured out using web3 itself.

**Comment by Smithgift** [comment]
I'm not sure how web3 would, theoretically speaking, even know about a change in nodes _without_ manually polling. AFAIK, the JSON-RPC is usually just a fancy HTTP POST to the node. There's not a connection _per se_, only that a given web3 object is set to interact with a given node.

There's work on pub/sub in various places, which would allow for this. (If nothing else, because all the subscriptions stop working!)

**Comment by taoteh1221** [comment]
@chevdor  You may want to have a look here, regarding subscriptions (instead of polling): https://github.com/ethereum/go-ethereum/wiki/RPC-PUB-SUB

**Comment by chevdor** [comment]
@Smithgift @taoteh1221 I am sorry I took some of your time. I realise that I got the wrong link when I submitted this proposal that was originally intended for the metamask repo. This is out-of-topic here. My apologise again for the post in the wrong place.

**Comment by taoteh1221** [comment]
@chevdor No worries here, best wishes building feasible dapps on the platform. 😃
