### ISSUE TITLE
Governance Taxation for Abstainees

### ISSUE THREAD

**Issue by OFRBG** [ethereum/EIPs#1522]
Several community members are very vocal about a lack of involvement in governance decisions. While this is accentuated by [stuff like this](https://github.com/paritytech/parity-ethereum/issues/6995), where people are dismissed if they are not part of the flag of EF, Parity or a sponsored group.

A major problem with governance in Ethereum that I've noticed is that the "commoners" are not only ignored, but often unfairly criticised. It is not wonder that many users are unwilling to take an active part when they're mostly ignored. Hence, this proposal presents the abstainee tax.

If Ethereum wishes to reach a certain participation level, the abstainee tax could improve the indifference of the userbase. In order to hit a specific turnout level, for each decision that a wallet ignores and abstains from voting, it should be taxed a rate of x%, and the raised funds equally distributed among non-abstainess. For each subsequent vote that doesn't reach the objective turnout percentage, the tax rate should be hiked.

Pros:

- People start caring or are pushed to care.
- Decentralise governance.

Cons:

- Exchanges will have to implement voting interfaces or face taxation. Or vote themselves. 
- Uninformed users will lose funds and could lead to investors exiting the currency. 
- Ethereum could be classified as a security.

---

As mentioned in other blog posts, contributors will be unmovable either for or against taxation, possibly under the following underlying arguments:

1. No, it will cause people to exit the market.
2. No, it will cause voter centralisation.
3. No, it will be useless.
4. Yes, we care about making people participate.
5. Yes, it's better to have voter centralisation over hitchhikers.
6. Yes, but the implementation is wrong.
7. I don't care (lol)

(Alternatively, be more inclusive and less hostile to participation.)

**Comment by Grunzwanzling** [comment]
Compulsory voting is a really bad idea.
Forcing people that are not-well informed to vote leads to a large number of so called "donkey-votes" of persons that simply vote at random or for non-serious candidates.
In case of Ethereum, it is also almost technically impossible, because not all wallets are controlled by humans. How would wallets vote that are controlled by smart contracts?
