### ISSUE TITLE
RSS needs to include last-call date

### ISSUE THREAD

**Issue by fulldecent** [ethereum/EIPs#1535]
EIP 820 entered last call and then left and then reentered. This should trigger a new story on the RSS feed but it did not. 

Broken code: https://github.com/ethereum/EIPs/blob/master/last-call.xml#L14-L18

Add the last call review end date into the description or title.

**Comment by bmann** [comment]
I'm taking this on and will be filing some PR to create a number of feeds.

**Comment by bmann** [comment]
Let's discuss this specific issue here, moving from #1687 

From @fulldecent 

> The last call review end date is only relevant when in last call status. And this is already documented in EIP-1. If people are not using it then that’s their error.

Looking at [EIP-1], I see ```review-period-end``` is the suggested metadata. Searching the repo, this looks like it's only been used [3 times](https://github.com/ethereum/EIPs/search?q=review-period-end&type=Commits) .... uh, and then only to document it?

> As a test case can you please ensure that an EIP will show up in your RSS last feed AS A NEW FEED ITEM if the last call date is changed?

The new feed item is a tricky one, as the RSS spec is notoriously tricky, and then it depends on which client you are using if it gets marked as new.

I added the ```lastBuildDate``` so at least the file will get pinged every time that something gets merged --> https://github.com/ethereum/EIPs/blob/23114e86e800284a17d5878986fa4c90805073d2/last-call.xml

If you could comment / +1 that PR it would get us moving.

Note: there are currently _no_ EIPs in Last Call status, so the feed will be empty! If you want to build Jekyll locally and change status for an EIP to test, that's the way to look.

>The current issue is that something can enter last call, then exit and then go through the entire last call process again without anybody noticing.

Yes, hence my proposal for a bunch of new feeds.
