### ISSUE TITLE
Simple replay attack protection

### ISSUE THREAD

**Issue by vbuterin** [ethereum/EIPs#155]
EDITOR UPDATE (2017-08-15): This EIP is now located at https://github.com/ethereum/EIPs/blob/master/EIPS/eip-155.md. Please go there for the correct specification. The text below may be incorrect or outdated, and is not maintained.
-----

### Parameters
- `FORK_BLKNUM`: TBA
- `CHAIN_ID`: 1
### Specification

If `block.number >= FORK_BLKNUM` and `v = CHAIN_ID * 2 + 35` or `v = CHAIN_ID * 2 + 36`, then when computing the hash of a transaction for purposes of signing or recovering, instead of hashing only the first six elements (ie. nonce, gasprice, startgas, to, value, data), hash nine elements, with `v` replaced by `CHAIN_ID`, `r = 0` and `s = 0`. The currently existing signature scheme using `v = 27` and `v = 28` remains valid and continues to operate under the same rules as it does now.
### Example

Consider a transaction with `nonce = 9`, `gasprice = 20 * 10**9`, `startgas = 21000`, `to = 0x3535353535353535353535353535353535353535`, `value = 10**18`, `data=''` (empty).

The "signing data" becomes:

```
0xec098504a817c800825208943535353535353535353535353535353535353535880de0b6b3a764000080018080
```

The "signing hash" becomes:

```
0x2691916f9e6e5b304f135496c08f632040f02d78e36ae5bbbb38f919730c8fa0
```

If the transaction is signed with the private key `0x4646464646464646464646464646464646464646464646464646464646464646`, then the v,r,s values become:

```
(37, 11298168949998536842419725113857172427648002808790045841403298480749678639159, 26113561835810707062310182368620287328545641189938585203131842552044123671646)
```

Notice the use of 37 instead of 27. The signed tx would become:

```
0xf86c098504a817c800825208943535353535353535353535353535353535353535880de0b6b3a76400008025a028ef61340bd939bc2195fe537567866003e1a15d3c71ff63e1590620aa636276a067cbe9d8997f761aecb703304b3800ccf555c9f3dc64214b297fb1966a3b6d83
```
### Rationale

This would provide a way to send transactions that work on ethereum without working on ETC or the Morden testnet. ETC is encouraged to adopt this EIP but replacing `CHAIN_ID` with a different value, and all future testnets, consortium chains and alt-etherea are encouraged to adopt this EIP replacing `CHAIN_ID` with a unique value.

**Comment by janx** [comment]
Our of curious: why make `v=27|28` instead of `v=0|1` at first place?

**Comment by vbuterin** [comment]
It was a carry-over from Bitcoin's Electrum wallet.

**Comment by avtarsehra** [comment]
This looks very similar to our proposal here: https://github.com/avtarsehra/ECIPs/blob/master/ECIPs/ECIP1011.md

**Comment by avtarsehra** [comment]
It's great, that as long as it goes in it will help both etc and eth.

**Comment by avtarsehra** [comment]
Great that etc and eth are coordinating important, mutually beneficial changes. 

https://github.com/avtarsehra/ECIPs/blob/master/ECIPs/ECIP1011.md

**Comment by Smithgift** [comment]
[Relevant Classic ECIP discussion on this subject](https://github.com/ethereumproject/ECIPs/issues/7). [Even more here](https://github.com/ethereumproject/ECIPs/pull/10). As far as I understand it, they're considering adding the blockhash of the nearest fork to the signing process. 

I'm not competent to speak on the cryptographic parts of this idea, but I'll note a philosophical difference between this and ECIP-1011. Here, picking CHAIN_ID requires human intervention to choose which community it belongs in, whereas a machine can compute the right blockhash to stick in if it detects even a minor fork. 

In any case, the existence of two incompatible replay protection systems will hardly fail in their intended function. It's just a kind of balkanization of code that, IMHO, would be harmful for a future cross-chain metaetheral world. I'm not saying that doing our own system would be wrong, but that there's a non-zero cost to having different systems.

**Comment by holiman** [comment]
> because v = 27 and v = 28 will continue to be usable to send transactions on all chains and so that would create a protocol ambiguity as there would be two different valid ways to calculate the sender of a transaction

To clarify, does "continue to be usable to send transactions on all chains" mean that we would retain the old transaction signing scheme as valid, in _addition_ to the new signing scheme?  If so, the specification-paragraph should be updated to reflect that.

**Comment by vbuterin** [comment]
Yes, the old scheme is still valid in addition to the new one.

**Comment by rebroad** [comment]
@vbuterin The mention of ETC confuses me as I thought this issue was being raised to address up-coming forks to ensure replay attacks cannot happen again should the current chain survive in some form. Is that what this issue is created to address?

**Comment by Smithgift** [comment]
@rebroad: This will work just as well for ETH/ETC replay attack prevention. As it is, that's the bigger need.

**Comment by Arachnid** [comment]
Instead of using a 'chain ID' that has a limited namespace of 8 bits, and has to be changed on each fork, I'd like to propose two alternatives:

 1. Before hashing, replace one of V, R, or S with a 'fork ID'. A fork ID is 0 for the initial Ethereum chain. Each time there is a hard fork, the forked side sets a 1 bit in the next available slot, starting with the least significant bit. So, Ethereum post frontier has fork id 1, as does Ethereum Classic. Ethereum after the DAO fork had fork ID 11b = 3, and after the recent gas reprice fork had fork ID 111b = 7. After this fork, Ethereum will have fork ID 1111b = 15. After the forthcoming ETC fork it will have fork ID 101b = 5.
 2. Before hashing, replace one of V, R, or S with the block hash of the block at which the most recent fork occurred.

**Comment by sebs** [comment]
Is this only a protection against simple replay attacks or all attacks in a simple way? Please clarify for the non whitepaper safe fellows.

**Comment by holiman** [comment]
The latter; "all attacks in a simple way".

**Comment by gavofyork** [comment]
following on @Arachnid 's idea, we could augment this with a rule that field 8 in the hash preimage RLP ('r') should be populated by the

**Comment by gavofyork** [comment]
i quite like both of @Arachnid 's suggestions, though think they are as well working in tandem with this proposal; this would allow for alt-etherea, private/consortium chains and testnets to avoid clashing rather than just non-forks.

**Comment by konradkonrad** [comment]
Not sure, if the provided serialization for the signed transaction is correct (or I am misunderstanding this proposal?):
```python
import rlp
from ethereum.utils import decode_hex
# the 'signed tx' from above
eip155_signed = "f86e098504a817c800825208943535353535353535353535353535353535353535880de0b6b3a7640000801ca1a019ae791bb8378a38bb83f5b930fe78a0320cec27d86e5e258c69f0fa9541eb8da1a02bd8e0c5bde4c0800238ce5a59d2f3ce723f1e84a62cab53d961fe3b019d19fc"
list(map(rlp.utils.big_endian_to_int, rlp.decode(decode_hex(eip155_signed))[-3:]))
# [28,
# 18538350366433071197493567112980778422885435717274618683086050914661715717254029,
# 18546566920747953154222317575156555315715115874101297527539304425414456214624764]
```

**Comment by chfast** [comment]
If `v` is one byte, we should also specify the set of possible `CHAIN_ID` values. Is it `{0 - 127} - {13}`, assuming that for 127 `v = 255` or `v = 0`.

We have also Ethereum network id number. Can we use the same value?

**Comment by vbuterin** [comment]
@konradkonrad yep you're right, that tx got serialized incorrectly. I updated it.

**Comment by Nashatyrev** [comment]
Guys, could you please adjust the formula in this issue?

**Comment by mohsenghajar** [comment]
To people who never split their coins (e.g. all original ETH), are any of these updates any danger?  Excuse my ignorance pls.  Thanks.

**Comment by Smithgift** [comment]
@mohsenghajar: If all goes to plan, this will make things _safer,_ as transactions will be limited to one chain. It will be easier to split afterwards, hopefully.

**Comment by kvhnuke** [comment]
It seems like this example has been modified in implementation, please correct me if im wrong.

> then when computing the hash of a transaction for purposes of signing or recovering, instead of hashing only the first six elements (ie. nonce, gasprice, startgas, to, value, data), hash nine elements, with v replaced by **_1 (this is the main CHAIN_ID not the 18)_**, r = 0 and s = 0.


Consider a transaction with nonce = 9, gasprice = 20 * 10^9, startgas = 21000, to = 0x3535353535353535353535353535353535353535, value = 10^18, data='' (empty).

The "signing data" becomes:
`0xec098504a817c800825208943535353535353535353535353535353535353535880de0b6b3a7640000801c8080`

The "signing hash" becomes:
`0xdaf5a779ae972f972197303d7b574746c7ef83eadac0f2791ad23db92e4c8e53`

After signing make sure v is either 37 (18*2+1) or 38(18*2+2) based on 0 or 1
If the transaction is signed with the private key 0x4646464646464646464646464646464646464646464646464646464646464646, 

then v,r,s becomes: 
`37, 0x28ef61340bd939bc2195fe537567866003e1a15d3c71ff63e1590620aa636276, 0x67cbe9d8997f761aecb703304b3800ccf555c9f3dc64214b297fb1966a3b6d83`

then the signed tx becomes:
`0xf86c098504a817c800825208943535353535353535353535353535353535353535880de0b6b3a76400008025a028ef61340bd939bc2195fe537567866003e1a15d3c71ff63e1590620aa636276a067cbe9d8997f761aecb703304b3800ccf555c9f3dc64214b297fb1966a3b6d83`

**Comment by vbuterin** [comment]
Updated, sorry about that!

**Comment by ashchan** [comment]
Does anyone have problem test signed tx against https://github.com/ethereum/tests/blob/develop/TransactionTests/EIP155/ttTransactionTestEip155VitaliksTests.json? 

For me, my temp implementation cannot pass test 1 ~ 11 (Vitalik_11) for simple RLP hash (not sign, but just assume the transaction is already signed and encode the 9 values, with v, r, s read from the JSON file).

Vitalik_12, Vitalik_13 and Vitalik_14 pass. They have normal-looking r and s values. For 1 ~ 11, each test has identical or slightly different r/s values.

**Comment by kvhnuke** [comment]
@ashchan they tested and worked for me, I would look at the pr i did for ethereumjs-tx https://github.com/ethereumjs/ethereumjs-tx/pull/41

**Comment by ashchan** [comment]
@kvhnuke Thank you, will look at that!

**Comment by ashchan** [comment]
@kvhnuke  Excuse me for asking a silly question. In the example on top of this issue page, we have this signing data:

`0xec098504a817c800825208943535353535353535353535353535353535353535880de0b6b3a764000080318080`

Note the last three is `318080`. Given CHAIN_ID is 1, shouldn't [1, 0, 0] be encoded to `018080`?

**Comment by kvhnuke** [comment]
@ashchan yes you are right it should be `018080`, atleast thats what im getting too. I had it as `1c8080` in my above example and i fixed it to `018080`

**Comment by ashchan** [comment]
@kvhnuke Thanks, this is very helpful. 👍

**Comment by etherai** [comment]
Can this EIP be closed?

**Comment by kumavis** [comment]
happy this has been accepted - please close this EIP

**Comment by Arachnid** [comment]
Since issues are currently de-facto EIPs, closing the issue would just make it hard to find.

**Comment by runn1ng** [comment]
Is there any document that describes which chains have which chainId?

I can find that ETH has 1, ETC has 61 for mainnet and 62 for testnet (?). What other options are there?

**Comment by flyswatter** [comment]
I know at least Rootstock and affinity are creating Ethereum-compatible VMs and RPCs, and would make good candidates for chain IDs. It might be a good time to consider good numbering conventions. ETC jumping up 60 sets a precedent, so maybe incrementing 60 each time a chain publicly requests one. Maybe a job for ENS ;)

**Comment by flyswatter** [comment]
Affinity = Dfinity, excuse my auto correct.

**Comment by Nashatyrev** [comment]
From the EIP it is not clear if the `v` value should be bounded to a single byte. 
From Geth and Parity implementation it seems the encoded `v` value is not limited to 8bit and thus the `CHAIN_ID` is not limited as well. 
E.g. this private network perfectly runs with `CHAIN_ID = 16123`: https://blockone.thomsonreuters.com/docs/Norsborg.html
Here is the sample tx encoded `f8ae82477b8504a817c80083015f9094977ddf44438d540892d1b8618fea65395399971680b844eceb6e3e57696e6454757262696e655f30310000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000007__827e19__a025f55532f5cebec362f3f750a3b9c47ab76322622eb3a26ad24c80f9c388c15ba02dcc7ebcfb6ad6ae09f56a29d710cc4115e960a83b98405cf98f7177c14d8a51`
`v` is encoded as `827e19`
Could please anyone confirm if this is the valid EIP interpretation?

**Comment by jhoenicke** [comment]
I would also like a clarification on the size of the value `v`.  Our Trezor implementation currently only supports `CHAIN_ID <= 109` to keep `v` to one byte. 

There should be some limit, either `v` is P_8, P_32, or P_256.  I don't care how high you want to go, although P_8 and P_32 would be easiest to support. The yellow paper requires P_5, which is already violated.

**Comment by chrisfranko** [comment]
EXP is using 2

**Comment by kumavis** [comment]
@chrisfranko what is EXP? btw `2` was used by morden

**Comment by chrisfranko** [comment]
im not really concerned about replaying exp transactions on morden or vice
versa, we already merged the pr on parity and in gexp.

**Comment by kumavis** [comment]
@chrisfranko what is EXP?

**Comment by chrisfranko** [comment]
Expanse? We forked eth like 2 years ago to make an alternative public
ethereum network.

**Comment by maurycyp** [comment]
Echoing @runn1ng , is anyone tracking which network is using which chain ID? I need to select one for INFURAnet, but want to avoid clashes while keeping it small (Trezor, ethereumjs).

If no one objects, I'll go with *** 83 *** .

**Comment by chrisfranko** [comment]
im not even sure, thats why I posted it here.

**Comment by runn1ng** [comment]
Why not make an EIP about it? :)

**Comment by Arachnid** [comment]
Probably this EIP should simply be updated to provide an index of network IDs.

**Comment by aeidelman** [comment]
We are using 30 (Mainnet) and 31 (Testnet) in RSK

**Comment by jyap808** [comment]
Ubiq is using ChainID 88 for Mainnet.

http://coinmarketcap.com/currencies/ubiq/

Thanks

**Comment by warren-bank** [comment]
hi @kvhnuke ..

quick question regarding your [output](#issuecomment-262413098)..

I get the same values, but only if `r` and `s` are assigned to empty (unallocated, zero-length) Buffers.. rather than 1-byte Buffers containing the value `0x00`. Is this correct?

Rather than including a lot of inline code, here are links:
* [test code](https://github.com/warren-bank/ethereumjs-tx-sign/blob/master/tests/05_EIP_155/js/compare_output.js)
* [output](https://github.com/warren-bank/ethereumjs-tx-sign/blob/master/tests/05_EIP_155/run.log)

PS) the example at the top of this EIP seems to be inconsistent.. the final value for its "raw transaction" was copied from the value in your comment.. but none of the data values that show the intermediate steps leading to this final value match the rest of the values in your comment (which also match the values that I see when running the above test code). If you happen to know @vbuterin , you may want to mention this.

**Comment by realcodywburns** [comment]
For context: ETC uses`61` because it is the same as the bip-44 deterministic path. `62` is pesobit and will not cause collision on p2pdev nodes https://github.com/satoshilabs/slips/blob/master/slip-0044.md

**Comment by cdetrio** [comment]
## This EIP is now located at https://github.com/ethereum/EIPs/blob/master/EIPS/eip-155.md. Please go there for the correct specification. The text in this issue may be incorrect or outdated, and is not maintained.

**Comment by nt11** [comment]
Perhaps I'm missing something. EP-155 states:

"If block.number >= FORK_BLKNUM and v = CHAIN_ID * 2 + 35 or v = CHAIN_ID * 2 + 36, then when computing the hash of a transaction for purposes of signing or recovering, instead of hashing only the first six elements (ie. nonce, gasprice, startgas, to, value, data), hash nine elements, with v "

These are instructions for the hashing party, but not the the original signing party. Therefore, the question arises: when signing a transaction, should one use the first equation (with 35) or second equation (with 36). Practically speaking, sometimes the former works and sometimes the latter without any clear rationale. 

Thanks

Nir


The

**Comment by jhoenicke** [comment]
@nt11: 35/36 encodes the low bit of R.y, which is needed to recover the
public key.  Note that you need to flip that bit when doing low s
normalisation.

**Comment by talbp** [comment]
@jhoenicke could you please elaborate a bit on the meaning of "R.y" and "low s normalization"? I wasn't able to find either terms.
A reference to a place which defines them, could also be great.

Thanks in advance!
Tal

**Comment by haydenhab57** [comment]
https://github.com/ethereum/yellowpaper/pull/412

**Comment by jhoenicke** [comment]
@talbp :  An ECDSA signature (r,s) is computed from a random nonce k: compute R = k*G and set r = (R.x mod ORDER) and throw away R.y.  To recover the public key one can use the formula 1/r*(sR - hG), but that requires to recover R from the signature.  If R.x < ORDER (which is almost always the case), then the missing part is R.y and there are two possibilities (one with low bit 0, one with low bit 1). 
So one has to store the low bit of R.y in v.

low s normalization:  If (r,s) is a valid signature then (r,(ORDER-s)) is also a valid signature, but it uses the "other R".  Ethereum (and Bitcoin) require for some time that one always uses the smaller value for s, and then one has to flip R.y bit.

**Comment by rustyx** [comment]
Too late to the party, but why hash 9 values with the last two fixed to `r = 0` and `s = 0` instead of just 7 values?

**Comment by wjmelements** [comment]
It's worth noting that if you do not use RFC 6979 you will get non-deterministic signatures that differ from the example.
