### ISSUE TITLE
EIP-1485 PR. Anti ETHASIC ethash upgrade to TETHASHV1

### ISSUE THREAD

**Issue by trustfarm-dev** [ethereum/EIPs#1590]
Here's EIP-1485 Proposals.

https://github.com/ethereum/EIPs/blob/7336cceac6c997252299a463ffe896a3414c479b/EIPS/eip-1485.md

Change FNV0 to FNV1A (Following Full specs).

Already made miner and pool, geth , parity , ethash patched things [here](https://github.com/tao-foundation)

Well running live mainnet.

**Comment by NEJAMUL37** [comment]
My name :- nejamul Hoque 
C/o:- kisholoy community center 
Chewk bazar, Chittagong, Bangladesh
Postel code :- 4203
Connected number within Telegram apps id:-  +8801706848037
Whatapps id :-+8801825044068

**Comment by trustfarm-dev** [comment]
@NEJAMUL37  please send a email 

info@trustfarm.net  ,   cpplover@trustfarm.net


thanks,

**Comment by trustfarm-dev** [comment]
What comments do you want?

This has been applied on teo (trust eth reorigin) chain.

Chain and Miner are here.
https://github.com/tao-foundation/rteo
https://github.com/tao-foundation/teominer

**Comment by MicahZoltu** [comment]
Please see [EIP-1](https://eips.ethereum.org/EIPS/eip-1) for details/instructions on how to create a new EIP.  Just creating an issue isn't the full process.  That being said, Ethereum is switching to Proof of Stake in the next network upgrade, assuming nothing goes catastrophically wrong, so changes to the Proof of Work algorithm are unlikely to get any real traction at this point.

**Comment by trustfarm-dev** [comment]
@MicahZoltu yes I know well. So close this thread then ok?

**Comment by MicahZoltu** [comment]
My recommendation would be to close this, since there is near 0 chance of it getting accepted at this point.
