### ISSUE TITLE
ERC1592 Address and ERC20-compliant transfer rules

### ISSUE THREAD

**Issue by sirhill** [ethereum/EIPs#1597]
### Simple Summary
We propose a standard and an interface to define transfer rules, in the context of ERC20 tokens and possibly beyond.

A rule can act based on sender, destination and amount, and is triggered (and rejects the transfer) according to any required business logic.

To ease rule reusability and composition, we also propose an interface and base implementation for a rule engine.

### Abstract
This standard proposal should answer the following challenges:

Enable integration of rules with interacting platforms such as exchanges, decentralized wallets and DApps.
Externale code and storage, improve altogether reusability, gas costs and contracts' memory footprint.
Highlight contract behavior and its evolution, in order to ease user interaction with such contract.
If these challenges are answered, this proposal will provide a unified basis for transfer rules and hopefully address the transfer restriction needs of other EIPs as well, e.g. EIP-902, EIP-1066 and EIP-1175.

This document proposes specifications for a standard of transfer rules and interfaces to both the rules and the rule engine, which was made to be inherited by a token, but may have a much broader scope in the authors' opinion.

The last section of this document illustrates the proposal with a rule template and links to rule implementations.

### Draft document
A draft already exist and can be found here #1592 
Its content can be discussed below.

**Comment by aquabu** [comment]
@sirhill This looks similar to #1404 #902 and #1066 which have some momentum.
