### ISSUE TITLE
EXP cost increase

### ISSUE THREAD

**Issue by vbuterin** [ethereum/EIPs#160]
EDITOR UPDATE (2017-08-15): This EIP is now located at https://github.com/ethereum/EIPs/blob/master/EIPS/eip-160.md. Please go there for the correct specification. The text below may be incorrect or outdated, and is not maintained.
-----

### Specification

If `block.number >= FORK_BLKNUM`, increase the gas cost of EXP from 10 + 10 per byte in the exponent to 10 + 50 per byte in the exponent.
### Rationale

Benchmarks suggest that EXP is currently underpriced by a factor of about 4-8.

**Comment by yaronvel** [comment]
If it is underpriced by a factor of 4-8 why do you increase it by a factor of 5?
4, 6 or 8 would make sense. Why 5?

**Comment by cdetrio** [comment]
## This EIP is now located at https://github.com/ethereum/EIPs/blob/master/EIPS/eip-160.md. Please go there for the correct specification. The text in this issue may be incorrect or outdated, and is not maintained.

**Comment by varo0000000** [comment]
Saltar al contenido
ethereum
EIP
Navegación del repositorio
Código
Cuestiones
18
 (18)
Solicitudes de extracción
427
 (427)
Acciones
Seguridad
Perspectivas
Aumento de costos de EXP #160
Cerrado
@vbuterin
Descripción
vbuterina
abierto el 20 de octubre de 2016 · editado por cdetrio
Colaborador
ACTUALIZACIÓN DEL EDITOR (15-08-2017): Este EIP ahora se encuentra en https://github.com/ethereum/EIPs/blob/master/EIPS/eip-160.md. Vaya allí para obtener la especificación correcta. El texto a continuación puede ser incorrecto o estar desactualizado y no se mantiene.
Especificación
Si block.number >= FORK_BLKNUM, aumenta el costo del gas de EXP de 10 + 10 por byte en el exponente a 10 + 50 por byte en el exponente.

Justificación
Los puntos de referencia sugieren que actualmente el precio de EXP está subvalorado en un factor de aproximadamente 4 a 8.

Actividad

oscurecer
mencionó esto el 20 de octubre de 2016
Horquilla dura EIP158 y 160 go-ethereum#3179

arvicco
mencionó esto el 20 de octubre de 2016
Repricing EXP, ECIP-1015 proyecto Ethereump/go-ethereum#88

chriseth
mencionó esto el 26 de octubre de 2016
Actualización del protocolo EIP 158 + 160 aleth#3381

Souptacular
mencionó esto el 27 de octubre de 2016
Agenda de la reunión 8 de AllCoreDevs pm#1
yaronvel
yaronvel comentó el 28 de octubre de 2016
yaronvel
el 28 de octubre de 2016
Si está infravalorado en un factor de 4 a 8, ¿por qué lo aumentas en un factor de 5?
4, 6 u 8 tendrían sentido. ¿Por qué 5?


gavofyork
mencionó esto el 30 de octubre de 2016
EIP 155, 160, 161 openethereum/parity-ethereum#2976

konradkonrad
mencionó esto el 31 de octubre de 2016
Implementar cambios de HF de "dragón espurio" en develop pieterio#417

pirapira
Se agregaron 2 confirmaciones que hacen referencia a este problema el 5 de diciembre de 2016
Actualice el cronograma de tarifas siguiendo el EIP 160


Verificado
a193fcf
Actualice el cronograma de tarifas siguiendo el EIP 160


Verificado
a7394ed

Souptacular
añadido 
editor-necesidades-de-revisión
 el 10 de febrero de 2017

pirapira
Se agregó una confirmación que hace referencia a este problema el 13 de febrero de 2017
Actualice el cronograma de tarifas siguiendo el EIP 160

3556fce

pirapira
Se agregó una confirmación que hace referencia a este problema el 22 de febrero de 2017
Actualice el cronograma de tarifas siguiendo el EIP 160


Verificado
c0f859b

pirapira
Se agregó una confirmación que hace referencia a este problema el 22 de marzo de 2017
Actualice el cronograma de tarifas siguiendo el EIP 160


Verificado
cdb2148

pirapira
Se agregó una confirmación que hace referencia a este problema el 31 de marzo de 2017
Actualice el cronograma de tarifas siguiendo el EIP 160


Verificado
1f57dc5

pirapira
mencionó esto el 31 de marzo de 2017
Spurious Dragon: EIP160 Actualiza la tarifa de EXP papel amarillo#281

cdetrio
mencionó esto el 17 de julio de 2017
Agregar archivo para EIP 160 (aumento de costo EXP) #674
cdetrio
cdetrio comentó el 15 de agosto de 2017
cdetrio
el 15 de agosto de 2017
Miembro
Este EIP ahora se encuentra en https://github.com/ethereum/EIPs/blob/master/EIPS/eip-160.md. Vaya allí para obtener la especificación correcta. El texto de este número puede ser incorrecto o estar desactualizado y no se mantiene.

U
Cerré esto como completadoel 15 de agosto de 2017

cdetrio
removido 
editor-necesidades-de-revisión
 el 15 de agosto de 2017

pipermerriam
mencionó esto el 26 de septiembre de 201
Implementar la horquilla dura Spurious Dragon
