### ISSUE TITLE
EIP1606 - Context based contracts in Solidity

### ISSUE THREAD

**Issue by James-Sangalli** [ethereum/EIPs#1606]
I have been thinking a lot lately about security flaws in contracts as well as the lack of context given to the average dapp user.

When interacting with a smart contract you cannot be sure exactly what the code does by looking solely at the ABI and developers are prone to creating untended bugs in their contracts. I think adopting a style that is a mix of Ricardian contracts and javadoc could be of great help to such an issue. 

What I am proposing is a way to write smart contracts which require a javadoc like description to be associated with each function. The solidity compiler could come with this in mind in the next release and prevent contracts from compiling when each of the following is not included (each @ point must be filled, like in javadoc):

   ```
/*
    *   @purpose: allow our users to donate or transfer example tokens 
    */
    contract example 
    {
        /* @functionName transfer 
        * @param address to the address to send tokens to 
        * @param uint amount the amount of tokens you wish to send
        * @visibility public
        * @payable false
        * @intention to allow users to transfer tokens to anyone
        * @returns void this function does not return anything
        * */
        function transfer(address to, uint amount) public;

        /* @functionName donate 
         * @param uint amount the amount of tokens you wish to donate
         * @visibility public
         * @payable true
         * @intention allow users to donate tokens from their balance
         * @returns void this function does not return anything
         * */
        function donate(uint amount) public payable;
    }

```
 
This would prevent security holes and provide much better UX for the following reasons:
- It gives the user more context about the intention of the contract and it's function. This prevents misunderstandings and enables a richer experience. 
- It prevents developer error as the developer is forced to document and think through everything he/she writes
- It allows for better readability and potentially more richer services to be built on top which rely on a context to perform functions 

**Further Optimisations**

ABI's: 

We could allow these keywords to generate a seperate ABI like structure or bolt on to the existing abi with extra fields. This would allow anyone to get the context easily. 

Signed contract hashes:

Since solidity will exclude comments when forming into bytecode, we could agree on a canonical structure that allows for the code plus comments to be hashed together, signed and added to the contract storage itself. 

Happy to hear suggestions or comments!

**Comment by onbjerg** [comment]
@James-Sangalli This already exists in the form of [Natspec](https://github.com/ethereum/wiki/wiki/Ethereum-Natural-Specification-Format) and its safer cousin [Radspec](https://github.com/aragon/radspec)
