### ISSUE TITLE
EIP1621: Referral Interface

### ISSUE THREAD

**Issue by mradkov** [ethereum/EIPs#1621]
```
eip: <to be assigned>
title: ERC-1621 Referral Interface
author: Milen Radkov (@mradkov) <milenradkov@me.com>
discussions-to: https://github.com/ethereum/EIPs/issues/1621
status: Draft
type: Standards Track
category: ERC
created: 2018-11-24
```

## Simple Summary
Suggests the addition of referral mechanism over smart contracts, storing account information. For example dApps.

## Abstract
Almost every platform/project/game/service on the web has some kind of referral mechanism used for marketing purposes, but not only. We believe that for a smooth transition from the current centralized internet model to a decentralized one, the users should have at least the same user experience or better. With this proposal we want to standardise a referral mechanism for Ethereum smart contracts that can be used for all sorts of bounty campaigns and reward systems for both tokens and Ethereum.

## Motivation
This EIP is motivated by the need for onchain tracking of referred user accounts on some dapps. Onchain saving the referrals will be able to verify information about a given address from a single trusted source without concerning that it could be manipulated, and to do so in as simple a manner as possible. It is also motivated by the desire to make user experience with dapps more flawles and user-friendly by both the simplicity of the interface as well as by the guarantees on uniqueness provided by the proposed standard.

No existing EIPs for storing referral accounts on-chain found.

This EIP proposes a light-weight interface for adding referrals functionality for smart contracts. This abstraction layer can sit on top of standards like ERC-20 and ERC-721 or others where account information is being stored.

## Proposal
I'm currently developing an example implementation for the referral interface proposed here. 

[Work in progress implementation](https://github.com/mradkov/onchain-referral)

I would like to start a discussion here for the viability and the merit of the proposal as well as design.

👋
@mradkov and the @hackbg team

**Comment by fulldecent** [comment]
"I would like to start a discussion here for the viability and the merit of the proposal as well as design." is the wrong stage to open an EIP.

Instead please open a specific question on StackOverflow or a discussion on /r/ethereum or Ethereum Magicians.
