### ISSUE TITLE
EIP 1637 - Adding chainId parameter to eth_sendTransaction

### ISSUE THREAD

**Issue by pedrouid** [ethereum/EIPs#1637]
Currently we rely in non-standard middleware to handle the state of the active chain of the Wallet. This state could be standarized in the current `eth_sendTransaction` JSON-RPC method by adding a second parameter to include the chainId.

EIP-155 already takes this into account to protect transactions from being replayed as this chainId is included in the signature `v` value however this is not communicated in a standard way between a Wallet and a Dapp

Dapps today would barely notice this change as the chainId could easily default to the middleware state already handled by libraries like web3.js, ethers.js, ledger.js and etc, but it would allow use to gain instant multi-chain compatibility for Dapps with a (IMO very small) change to the current method.

**BEFORE**
```js
{
  "id":1,
  "jsonrpc": "2.0",
  "method": "eth_sendTransaction",
  "params": [txn]
}
```

**AFTER**
```js
{
  "id":1,
  "jsonrpc": "2.0",
  "method": "eth_sendTransaction",
  "params": [txn, chainId]
}
```

This change would also target `eth_sendRawTransaction` and `eth_signTransaction`

**Comment by ligi** [comment]
A concern @holiman just mentioned in a call is that geth uses different keystores for the different chainID's. Solution could be that if the current chainID is not the chainID that is passed -> an error is thrown. Still think introducing new rpc methods in the wallet_ namespace is a cleaner solution.

**Comment by pedrouid** [comment]
Hey @danfinlay, I would like to revisit this EIP and start implementation for both Metamask and WalletConnect

**Comment by rmeissner** [comment]
I would prefer the solution mentioned by @ligi 

Having it as an optional parameter might cause issues, since wallets that are not using a strict implementation of the rpc (by rejecting additional parameters) would potentially submit the transaction to a wrong chain.

**Comment by pedrouid** [comment]
That is however a problem already with eth_sendTransaction and this is not just an improvement but fixing a problem. 

I think that creating new methods is the way to go for breaking changes. But this is a non-breaking change which middleware libraries like web3.js, ethers.js, etc can fill in the active chainId if the second parameter is undefined

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ligi** [comment]
yes it is a problem with the current eth_sendTransaction - but when introducing wallet_signTransaction with a mandatory chainID one would have the guarantee. I still signal this as the way to go.
