### ISSUE TITLE
Replay protection via high-order bits of nonce

### ISSUE THREAD

**Issue by vbuterin** [ethereum/EIPs#166]
### Specification.

Let CHAIN_ID = 18 for mainnet, 28 for testnet.

If `block.number >= FORK_BLKNUM`, then:
- For a transaction to be valid, it must be the case that `nonce // 2**64` is equal to either 0 or CHAIN_ID.
- The nonce of the transaction for verification purposes is now `nonce % 2**64`. That is, for the transaction to be valid, it must be the case that `account.nonce == tx.nonce % 2**64`, and after the transaction is processed we set `account.nonce == (tx.nonce % 2**64) + 1`.

**Comment by Nashatyrev** [comment]
@vbuterin Why do we need another replay protection together with https://github.com/ethereum/EIPs/issues/155 ?
