### ISSUE TITLE
ERC-1667 - Standardized Plasma MVP Proposal

### ISSUE THREAD

**Issue by hamdiallam** [ethereum/EIPs#1667]
# ERC - Standardized Plasma MVP Proposal
---
eip: 1667
title: ERC 1667 Standardized Plasma MVP Smart Contract
author: Hamdi Allam <hallam@berkeley.edu>, Wesley Graham <wgraham@berkeley.edu>
status: Draft
type: Standards Track
category: ERC
created: 12-03-2018

### Reading
[Minimum Viable Plasma](https://ethresear.ch/t/minimal-viable-plasma/426)

### Reference Implementation
https://github.com/fourthstate/plasma-mvp-rootchain

## Simple Summary
This standard defines a smart contract based on the original Plasma MVP specification. Allows developers to deploy their own plasma sidechain through a common contract interface. Sidechains can support any ERC20 asset.

## Motivation
A standard Plasma MVP interface enables support for a standardized wallet that can be used within any plasma sidechain. "Watch-Tower" services can also be run by third parties across multiple independent sidechains.

## Specification
The provided specification assumes that Ether is the native currency of this plasma-mvp sidechain.

```solidity
function submitBlock(bytes32[] blocks, uint256[] txnsPerBlock, uint256[] feesPerBlock, uint256 blockNum)
```
The validator submits a list block headers in ascending order along with the number of transactions and fee amounts. `blockNum` must be the intended block number of the first header in this call. Ordering is enforced on each call. `blockNum == lastCommittedBlock + 1`.

Each merkle tree can be of variable size(capped at `2^16 - 1` transactions). The fee utxo is given the last position in the block, `2^16 - 1`, so that it is has the worst priority for that block.

<br />

```solidity
function deposit(address owner) payable
```
Entry point into the child chain. The user can create a spendable utxo owned by the address, `owner`. `msg.value` specifices the amount of this deposit.

Each deposit is identified with an incremental nonce. Validators catch deposits through event handlers and maintain a collection of spendable deposits.

<br />

```solidity
function startTransactionExit(uint256[3] txPos, bytes txBytes, bytes proof, bytes confirmSignatures, uint256 committedFee) payable
```

Exit procedure for exiting a utxo on the child chain (not deposits). 

 `txPos` locates the transaction on the child chain. The leaf, hash(`txBytes`), is checked against the block header using the `proof`. Any included spend of this output followed by an exit(no broadcast of the confirm signature), must commit to the fee in the spend.
 
The `confirmSignatures` represent the acknowledgement of the inclusion by both inputs. An exit bond must be provided that is refunded for honest exits or awarded to the challenger.

<br />

```solidity
function startDepositExit(uint256 nonce, uint256 committedFee) payable
```

Deposits are  identified by their `nonce`. The caller's address must match the owner of the deposit. Any included spend of this deposit followed by an exit (no broadcast of the confirm signature), must commit to the fee in the spend. An exit bond must be provided that is refunded for honest exits or awarded to the challenger.

<br />

```solidity
function challengeFeeMismatch(uint256[4] exitingTxPos, uint256[2] challengingTxPos, bytes txByes, bytes proof)
```
An exit that commits an invalid fee can be challenged with this function. The `challengingTxPos` along with the `txBytes` and `proof` demonstrate a proof of an inclusion of a direct spend of the `exitingTxPos`

A deposit will have the first 3 fields in the `exitingTxPos` zero'd out and vice versa for a utxo. 
`exitingTxPos` - `[blockNum, txIndex, outputIndex, depositNonce]`
`challengingTxPos` - `[blockNum, txIndex]`

<br />

``` solidity
function challengeExit(uint256[4] exitingTxPos, uint256[2] challengingTxPos, bytes txBytes, bytes proof, bytes confirmSignature)
```

`exitingTxPos` and `challengingTxPos` follow the same convention as `challengeFeeMismatch`

A uxto or deposit that is initiating an exit after being spent using this  call. A successfull challenge awards the caller with the exit bond. The challenging transaction must be a direct spend of the exiting transaction.

The `proof` and `txBytes` is sufficient for a proof of inclusion in the child chain. The `confirmSignature` acknowledges the inclusion of the transaction's parent in the plasma chain and enables challenges of malicious child exits.

## Rationale 
In this contract, deposits are decoupled with block headers that contain sidechain transactions. An incrementing `depositNonce` is used to identify deposits.

This is to prevent a race condition that occurs when including deposit blocks before every `submitBlock` call by the operator. With the original MVP proposal, a plasma operator (with high probability) can inject a malicious block when a deposit transaction is in flight by increasing its `submitBlock` transaction fee. This would give every transaction in the malicous block a better priority than the deposit, potentially allowing the operator to steal funds.

Decoupling deposits from transactions and processing deposit exits in a seperate queue mitigates this issue. The operator is responsible for catching deposit events and adding them to the utxo store.

Plasma MVP transactions follow the following form:
- Block Numbering starts at 1. A full position consists of, `[blockNum, txIndex, outputIndex, depositNonce]`. The first three inputs and the depositNonce are mutually exclusive.

```
[
  [Blknum1, TxIndex1, Oindex1, DepositNonce1, Owner1, Input1ConfirmSig,

   Blknum2, TxIndex2, Oindex2, DepositNonce2, Owner2, Input2ConfirmSig,

   NewOwner, Denom1, NewOwner, Denom2, Fee],

  [Signature1, Signature2]
]
```

## Copyright Waiver
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

Further discussion can also be had in the ERC channel of our [Discord Server](https://discord.gg/YTB5A4P).

**Comment by gakonst** [comment]
I do not believe submitting multiple block roots in a single submitBlock call is safe. A miner colluding with an operator can potentially orphan multiple plasma blocks at the cost of 1 mainnet block if the reward of the attack in all blocks is greater than the mainnet block reward.

**Comment by hamdiallam** [comment]
Can you further elaborate on this vulnerability? If the plasma blocks where orphaned, then operator would have to re-commit those blocks. Additionally, none of the committed blocks are considered finals for the plasma users until the corresponding confirm signatures have been sent over. With an invalid commitment, users would exit their funds.

**Comment by gakonst** [comment]
N plasma blocks are committed simultaneously, all data is made available, confirmation sigs get exchanged, and thus all participants consider the transactions finalized.  At this point, you accept a payment and you give whatever product was involved.

Right after that, the operator/miner orphans the block, effectively cancelling the transactions. When they recommit, they skip the transactions they made, effectively double spending in the plasma chain.

Adding a finality period on wallets would be a good idea, agreed.

**Comment by hamdiallam** [comment]
A finality threshold should mitigate this issue. A confirm signature should not immediately be sent.

The batched `submitBlock` could be removed using large block sizes. However variable block sizes, batching smaller blocks together is beneficial, reducing the merkle proof size when exiting/challenging.
