### ISSUE TITLE
Improve feeds available from the EIPs website

### ISSUE THREAD

**Issue by bmann** [ethereum/EIPs#1688]
I filed a PR #1687 to fix the Last Call feed.

I'm now proposing a few other changes to feeds for the EIPs website.

Please add suggestions & feedback here, and I will reference it when I do a pull request.

The EIPs site uses the jekyll static site builder, so some of the language I am going to use is jekyll specific. Because EIPs are implemented as Pages rather than Posts, it makes a whole bunch of stuff harder. Long term, turning EIPs into a jekyll Collection is probably the right thing to do, but I'm not going to tackle that right away :) If someone is interested in working with me on this, let me know in a comment.

---

## Global Feed

There was an auto-generated ```feed.xml``` from the jekyll-feed plugin that only works with Posts, so I removed the plugin.

I'm suggesting a global feed that lists all EIPs in all status.

## Feed per Category, Status

Can also generate separate feeds per category -- Core, Networking, Interface, ERC, Informational, Meta.

Also a feed per Status, so there would be a feed for Draft, Last Call, Accepted.

## JSON Feeds

At the very least, a JSON feed that is a global feed that contains all the data around all of the EIPs -- this is useful for consuming programmatically in different ways, as a kind of simple API.

## Last Call Date as Metadata

I've suggested how to have a last call date show up in the Last Call feed in #1535 -- this would also mean updating process instructions a little bit, as Last Call authors will need to add a new metadata line. But would "work today" with Jekyll.

**Comment by fulldecent** [comment]
The last call review end date is only relevant when in last call status. And this is already documented in EIP-1. If people are not using it then that’s their error. 

As a test case can you please ensure that an EIP will show up in your RSS last feed AS A NEW FEED ITEM if the last call date is changed?

The current issue is that something can enter last call, then exit and then go through the entire last call process again without anybody noticing.

**Comment by fulldecent** [comment]
Thank you for taking this on
