### ISSUE TITLE
ERC-1690 - Mortability Standard

### ISSUE THREAD

**Issue by Felix-Franz** [ethereum/EIPs#1690]
# ERC-1690 - Mortability Standard

* eip: 1690
* title: ERC-1690 - Mortability Standard
* author: @Felix-Franz
* status: Draft
* type: Standards Track
* category: ERC
* created: 2019-01-11
* requires: [EIP-173 Contract Ownership Standard](https://eips.ethereum.org/EIPS/eip-173) 

## Abstract

A standard that allows the owner of a contract to completely remove it.

## Motivation

If someone wants to remove his Smart Contract after some time, the solidity function `selfdestruct(address);` needs to be called from inside the Contract.

This standard allows to remove a Smart Contract that is not needed or wanted anymore.

## Specification

This standard uses the [EIP-173 Contract Ownership Standard](https://eips.ethereum.org/EIPS/eip-173) to handle the owner management.
It provides two functions to kill the Smart Contract.
Both functions must only be executed by the owner.
One of the function allows to send the contract's ether to any provided address, the other should just transfer the ether to the owner.

```solidity
interface MortabilityStandardInterface {
    /// function to destruct the contract and send the ether to provided address
    function kill(address receiver) external;

    /// function to destruct the contract and send the ether to the owner
    function kill() external;


    /// following implementation can by used from EIP-173
    event OwnershipTransferred(address indexed previousOwner, address indexed newOwner);
    function owner() view external returns (address);
    function transferOwnership(address _newOwner) external;
}
```

## Implementation

Following sample implementation uses [EIP-173 Contract Ownership Standard](https://eips.ethereum.org/EIPS/eip-173) to handle owner management.

```solidity
import "../EIP173/EIP173.sol";
import "./MortabilityStandardInterface .sol";

contract MortabilityStandard is EIP173, MortabilityStandardInterface {

    /// function to destruct the contract and send the ether to provided address
    function kill(address receiver) public {
        require(msg.sender == _owner);
        selfdestruct(receiver);
    }

    /// function to destruct the contract and send the ether to the owner
    function kill() public{
        kill(_owner);
    }
}
```

**Comment by corollari** [comment]
In the following line of the implementation there's an extra zero before `.sol`:
> import "./MortabilityStandardInterface .sol";

**Comment by Felix-Franz** [comment]
Thanks @corollari, I fixed this!

**Comment by MicahZoltu** [comment]
`selfdestruct` has historically caused headaches for the core devs and foot guns for many app developers.  There is talk about getting rid of it or castrating it in some way so it causes less problems.  Given this, I'm not a fan of creating standards that *encourage* its usage.
