### ISSUE TITLE
EIP-1052 failed to go through the workflow

### ISSUE THREAD

**Issue by fulldecent** [ethereum/EIPs#1699]
[EIP-1052](https://eips.ethereum.org/EIPS/eip-1052) is currently listed as draft status, however according to announcement from @Souptacular at https://blog.ethereum.org/2019/01/11/ethereum-constantinople-upgrade-announcement/ the latest EF version of clients will support this hard fork on block 7,080,000.

@Arachnid @chfast please use the EIP workflow process outlined in EIP-1.

**Comment by axic** [comment]
These are addressed in #1689 (and #1642 to be merged after the hardfork goes live).

**Comment by fulldecent** [comment]
Thank you for the reference. I request please that in future, project managers will promote to LAST CALL and then ACCEPTED status /before/ an EIP will be announced as part of a hard fork.

**Comment by 5chdn** [comment]
addressed in #1689 and #1642 - will not happen again

**Comment by 5chdn** [comment]
1052 is final, it cannot be modified anymore.

**Comment by bmann** [comment]
@5chdn it can't be amended? What's the process for superseding it or amending it? A new EIP?

**Comment by 5chdn** [comment]
> A new EIP?

Exactly.

**Comment by bmann** [comment]
>> A new EIP? ...

@5chdn a new EIP which has a classification of “Supersedes”? Are there existing examples of this you can point me at?

**Comment by 5chdn** [comment]
EIP #98 versus #658 (Parity implements both and uses 98 on Kovan but 658 on Mainnet)

EIP #1087 versus #1283 versus #1706

**Comment by bmann** [comment]
Can we close this issue?

**Comment by 5chdn** [comment]
Yes. In future, the cat herders eip monitoring subcommittee will assist here. 

https://github.com/ethereum-cat-herders/hard-fork-checklist/issues/4

**Comment by axic** [comment]
Closing this now as I don't think it is relevant anymore. The problems raised are valid, but likely it should be discussed on the Ethereum Magicians forum or as part of a broader discussion regarding processes (and not specific to EIP-1052).

@fulldecent please let me know if you want to keep this open.
