### ISSUE TITLE
ERC1700: Non-Exhaustible Token

### ISSUE THREAD

**Issue by tina1998612** [ethereum/EIPs#1700]
> This standard is co-authored by @yhuag @Roger-Wu @dAAAb
## Preamble
    EIP: <to be assigned>
    Title: Non-Exhaustible Token Standard (NET)
    Author: Lee Ting-Ting <tleeae@connect.ust.hk>, Hu Yao-Chieh <yhuag@connect.ust.hk>
    Type: Standard
    Category: ERC
    Status: Draft
    Created: 2019-01-15
## Simple Summary
Non-Exhaustible Token (NET)
  - Each NET can have non-exhaustible copies 
  - Specify a pool of NET for copy creation 

### Solidity Interface
```
interface IERC {

  event PoolAdded(
    uint256 indexed photoPoolId
  );

  event PhotoAdded(
    uint256 indexed photoId,
    uint256 indexed modelId,
    uint256 indexed photographerId
  );

  event CardDrawn(
    uint256 indexed cardId,
    uint256 indexed photoId,
    uint256 rarityScore,
    address indexed to
  );

  event Transfer(
    uint256 indexed cardId,
    address indexed from,
    address indexed to
  );

  function addPhoto(uint256 _modelId, uint256 _photographerId) external;

  function addPhotoPool(uint256[] _photoIds) external;

  function drawCard(uint256 _photoPoolId) external payable;

  function transfer(uint256 _cardId, address _to) external;

  function drawnCardIdsOf(address _user) external view returns(uint256[] cardIds);

  function playerDrawnCardIdIsHeldOf(address _user, uint256 _cardId) external view returns(bool);

  function drawnCardsOf(address _user) external view returns(uint256[] cardIds, uint256[] photoIds, uint256[] rarityScores);

}
```

A sample implementation can be found on [CryptoBeauty](https://github.com/TronBeauty/CryptoBeauty). 

A [DApp](http://cryptobeauty.art/) sample based on the ERC1700 Standard on TRON.

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by yhuag** [comment]
Two press releases and articles can be found here (Mandarin):
- BlockTempo: [宅力爆表，一個台灣團隊將「制服女孩」製作成獨特的卡牌代幣上鏈收藏](https://www.blocktempo.com/cryptobeauty-use-nft-help-girls-launch-unique-virtual-cards/#)
- Medium: [表特區塊鏈的宅經濟：少女卡片創作交易平台「 你的女孩，一鍵擁有」(上)](https://medium.com/p/c7b239cc8442)

**Comment by flamingYawn** [comment]
Wait, so what's the use case?

**Comment by tina1998612** [comment]
@flamingYawn yeah exactly:) The duplicates are non-fungible and the ownership is transferrable just like ERC721. 
The use case would be having different rarity and different issuance number for the same card for collection purposes.
