### ISSUE TITLE
Document status of EIP-999

### ISSUE THREAD

**Issue by DemiMarie** [ethereum/EIPs#1708]
What is the status of EIP-999?  It seems like it won’t be included in the next hard fork.  Is it likely to be merged or not?

**Comment by bmann** [comment]
It is still in [Draft](https://eips.ethereum.org/EIPS/eip-999), and the author has listed the Discussions To link to the EthMagicians forum here: https://ethereum-magicians.org/t/eip-999-restore-contract-code-at-0x863df6bfa4/130

The [Istanbul Hard Fork](https://en.ethereum.wiki/roadmap/istanbul) to track is EIP1679.

Note: all EIPs that are properly formatted are currently accepted and published.

**Comment by axic** [comment]
Closing this as discussion for EIP-999 should be made to the URL listed in the EIP – the one @bmann linked here.
