### ISSUE TITLE
EIP-155 Eth compatible networks must have different Chain IDs right?

### ISSUE THREAD

**Issue by EnchanterIO** [ethereum/EIPs#1711]
I would like to ask for clarification to be sure I understand the topic correctly.

Going through https://github.com/ethereum/EIPs/blob/master/EIPS/eip-155.md any Ethereum compatible network, using the same hashing and encryption strategy but on a different chain MUST ENSURE a unique Chain ID different to the list above in order to prevent a replay-attack. 

Is my understanding correct? If yes, is there somewhere a list of all Chain IDs across all Ethereum compatible networks? E.g the ultimate list of all chain IDs of Ethereum, ETC, PoA, god knows how many more blockchains are there based on Ethereum code hashing/encryption/TX struct. 

Thx

**Comment by bmann** [comment]
We are maintaining https://chainid.network as a resource where networks can add their information.

**Comment by xinbenlv** [comment]
@bmann That's helpful! BTW, who is "we" here?

**Comment by bmann** [comment]
Myself, Pedro, & Ligi

**Comment by golashr** [comment]
Hi, @bmann Is this list widely followed? Does not look like a comprehensive? Correct me If I am wrong. I am from Ledgerium Blockchain team https://www.ledgerium.io/. Currently running our testnet with internal testing. I am just wondering if it really helps to register our chainIDs for testnet and mainnet to the list.

**Comment by bmann** [comment]
@golashr it’s the only list that exists. The main purpose is to not collide on IDs so that other systems like wallets will work with all chains.

**Comment by golashr** [comment]
Sure thanks @bmann I would like to get the ledgerium blockchain registered. What information that you may need? Email or any form etc to register etc?

**Comment by bmann** [comment]
File the information in the GitHub repo https://github.com/ethereum-lists/chains
