### ISSUE TITLE
EIP-1175 and EIP-1491 are duplicated

### ISSUE THREAD

**Issue by fulldecent** [ethereum/EIPs#1736]
These are both in the repository root and in the EIPs directory. Please delete the one in the repository root. And possibly overwrite the one in the EIPs directory.

	eip-1175.md	dApp Components (avatar) & Universal Wallet (#1438)	4 months ago
	eip-1491.md	Merge erc-hucap.md (#1491)	4 months ago

--

PING: @Nitro888 @cohabo / which version would you like to keep

---

P.S. this is message up our RSS feed. (Separate issue+PR coming.)

**Comment by cohabo** [comment]
Hi,

Yes, I was unable to merge into the EIPs directory when trying to resolve this duplication. I'd like to delete the one in the repository root and keep the one in the EIPs directory.
Thanks

**Comment by fulldecent** [comment]
@cohabo Thank you for the quick reply. PR at https://github.com/ethereum/EIPs/pull/1737 awaiting editor assistance.

**Comment by nicksavers** [comment]
@fulldecent @cohabo Hope the issue is solved now.

**Comment by fulldecent** [comment]
Thank you, solved
