### ISSUE TITLE
RPC Protection

### ISSUE THREAD

**Issue by 3junit** [ethereum/EIPs#175]
Hello. I have multy wallet system that work with ethereum too via JSON-RPC. Ethereum work on separated server. There is any way to set up allow ip for rpc or not? Like in bitcoin.

**Comment by miohtama** [comment]
Please see here https://gist.github.com/miohtama/ce612b35415e74268ff243af645048f4

**Comment by 3junit** [comment]
Well this is good solution, but i cant leave open ssh tunnel on server. Any other suggestions?

**Comment by miohtama** [comment]
Use `autossh` to have a daemonized tunnel.

**Comment by Recmo** [comment]
You can set up an `nginx` reverse-proxy that uses a self-signed certificate (or Let's Encrypt if you have a domain). Then lock down the RPC port to localhost (e.g. using `iptables`) so only nginx can access it.

**Comment by miohtama** [comment]
@Recmo Can you clarify how this would prevent anyone to connect into your node and doing transactions over `web3.personal` API? Using `.htaccess´ users?

**Comment by 3junit** [comment]
@miohtama Thank you for advice. I use autossh and it works completely fine for me!
