### ISSUE TITLE
Discussion: Why using the ethereum public chain for STO contracts is not a good idea

### ISSUE THREAD

**Issue by hyangl** [ethereum/EIPs#1760]
# On the Security Economics of Public Blockchains: Why using the ethereum public chain for STO contracts is not a good idea

by Handeric C from TrueChain research community

We coin the term “security economics” to mean the system of economic incentives designed to guarantee the security required for a public chain to operate. For example, with PoW (proof of work), honest miners are incentivized to contribute compute power for mining reward. The higher aggregate hash rate of a network, the more difficult it will be to perform a 51% attack. We will introduce a new framework to analyze this relationship, and study the limiting cases where the current security economic relationship might breakdown. 

In a given period T, the blockchain network will release n coins according to its predetermined mining schedule. For example, bitcoin currently reward 12.5 coins per block. Its mining difficulty is adaptively set so it produces 144 blocks per day, with a very small margin of error. Whether total network hashpower is 50 ExH/s or 5 ExH/s, total reward per day is always 1800 bitcoins. Only difference is that the expected reward per hash diminishes when total network hash increases. But hashpower cost money, 50 ExH/s will cost 10 times as much as 5 ExH/s, assuming they’re running on the same kind of hardware. The economic equilibrium is arrived when reward per day (RPD) = cost per day (CPD). 

We further breakdown CPD to its components: sunk cost (e.g. cost of the miner) and operating cost per day (OCPD). We make the following postulates about the mining process and miner’s behavior. 
1, When price of a coin goes up, temporarily RPD > CPD, new hash power will be introduced as it will be profitable. 
2, When price of a coin goes down, but RPD > OCPD, then nothing will happen. 
3, When price of a coin goes down so much, that RPD < OCPD, some miners will stop mining, total network hash will fall, until RPD > OCPD again.  
4, Mining hardware have a useful life of approximately 2 years, miners would only deploy new hardware if they can cover cost within 1 year of mining. 

Assuming the above behavior of miners, in the equilibrium state, the total hash power (per second) of a network is bounded above by the market value of expected reward (per second). To stage a 51% attack on the network, the adversary will need to match all of the existing hashpower on the network. The required investment is approximately equal to the market value of minable coins in 1 year. Take bitcoin for example, a total of 52560 BTC are released to miners a year, which equate to about $189m, assuming $3600 / BTC. The total hashpower of the bitcoin network is about 42 ExH/s, which equates to about 3 million Antminer S9’s. This is what it takes to stage a 51% attack, the cost of staging such an attack is a good measure of how safe a network is. 

Would anyone do it? Perhaps not, which is the ingenuity of Satoshi Nakamoto. Assume you did invest $189m, and compromised the bitcoin network. What returns will you get? Sure, you double spend bitcoins, but bitcoins will be worthless when people find out its security is being compromised. The delicate game theoretic equilibrium, which we shall call the Nakamoto equilibrium, is just as important as all the cryptographic wizardry in keeping a blockchain safe. 

The Nakamoto equilibrium design has a number of drawbacks, although none of them were of interest for Nakamoto to consider, they do not apply to bitcoin. 
1, Nakamoto equilibrium only guarantees the security of the public chain itself, and not the smart contract tokens which runs on it. 
2, Out of all the blockchains that use the same hash algorithm, only the one with the most honest hashpower is safe. 
We will focus the remainder of this paper elaborating point number 1, and leave 2 to another article. 

The utility tokens created in the ICO hype, were predominately ERC 20 contracts executed on the ethereum network. Despite of their huge speculative value, these tokens do not have much intrinsic value right now. They simply represent the access right to a particular utility, which will be built (if ever) far into the future. The aggregate market value of all ERC 20 tokens, have never exceeded that of ethereum. Hence, the hashpower required to guarantee the safety of ethereum is automatically extended to the ERC 20 tokens running on the network. 

We now consider a scenario with securities tokens produced from STO’s. A security token represent a share of a securitized asset. These could be company stocks, bonds, buildings, infrastructure etc, indeed everything in the world could be securitized and tokenized on a blockchain. The fundamental difference between securities token and utility token is that securities token have an intrinsic value attached to it. The intrinsic value of a securitized asset could be several times the market cap of the public chain it’s running on. 

For example, as of Feb 2019, ethereum have a market share of about $8 - $10 billion dollars. About 7 million ETH is minable a year (before the Constantinople fork), the total value at current market price of $120/ETH is about $840 million. The total network hashpower is 140 TH/s. A Bitmain E3 miner has an advertised performance of 180 MH/s, so total network hashpower is equivalent to about 777777 E3 miners, which would cost roughly $800 million (though the exact cost could be quite volatile). This is how much one would have to invest to stage a 51% attack on ethereum network. If the network consists of only ETH and utility tokens, whose value would plummet if such an attack were to be successful, nobody is incentivized to do so. But (imagine sometime in the future), if the ethereum network has securities token contracts, whose underlying asset worth a total of a trillion dollars, then carrying out such an attack would seem quite profitable.  

A new security economic model is clearly required for any public chain to run securities token. The biggest problem with ethereum, is that miners are not incentivized to contribute hashpower, as a function of total market cap of tokens running on ethereum. This is not a problem in the era of utility tokens, when they are worth significantly less than the main ethereum network. In the era of securities tokens however, this will become a significant risk, as securities tokens can easily worth several folds more than the public chain itself. We need to figure out a new economic model, where the public chain’s hashpower is a direct function of total token value running on the public chain.

**Comment by zhangjiannan** [comment]
There is a parallel thread on Raddit for this topic FYI
https://www.reddit.com/r/ethereum/comments/arsu33/on_the_security_economics_of_public_blockchains/

**Comment by Joachim-Lebrun** [comment]
While your technical points related only to blockchain tech and its limits are quite accurate, you cannot make this kind of conclusions for security tokens, as the smart contracts related to these tokens are not as simple as the smart contracts used for utility tokens. Security tokens are always permissioned tokens and each whitelisted address is identified by the token issuer, which means that no one could "steal" these tokens in total impunity. In addition you need to know that security tokens are securities and are subject to the same rules as real securities, we are very far from the crypto-anarchist way of thinking here, as token issuers should always know exactly who are the token holders and should keep total control on their assets (possibility to freeze/burn/mint the tokens). Double spending on DEX is still possible though and could result in the loss of cryptocurrencies for some traders but the security tokens would not be lost.
