### ISSUE TITLE
Assigning version numbers to EVM changes

### ISSUE THREAD

**Issue by axic** [ethereum/EIPs#178]
### Motivation

To have consistent and simple way referring to EVM versions in clients and tools.

### Specification

A limited subset of semantic versioning ([semver](https://semver.org)) is introduced for EVM versions. Only a `major` and `minor` version numbers are used, `patch` level is omitted.

In the past, almost each hard fork made a breaking change (and thus introduced a new `major` bump) to the underlying EVM implementation, but this is not necessarily a requirement for future hard forks.

The past changes are versioned as follows:
- `1.0` - Frontier
- `1.1` - Homestead (+ EIP7)
- `2.0` - EIP150.1c ("all but one", OOG changes)

### EVM version identifier

The #154 proposal can be extended to include the above version numbers in a binary format. A straightforward way is to store `major` and `minor` as an 8 bit value each. Setting certain restrictions would allow to pack them into a single 8 bit value.

**Comment by chfast** [comment]
Can wasm-like prefix be used. I.e. 4 bytes `"\x00evm"` + 4 bytes little endian version number?
