### ISSUE TITLE
ERC: Simpler Token Standard

### ISSUE THREAD

**Issue by maraoz** [ethereum/EIPs#179]
```
ERC: 179
Title: Simpler Token standard
Status: Draft
Type: Informational
Created: 18-11.2016
Resolution: https://github.com/ethereum/wiki/wiki/Standardized_Contract_APIs
```

# Abstract
The following describes standard functions a token contract can implement.
This ERC describes a simpler version of the [ERC20 standard token contract](https://github.com/ethereum/EIPs/issues/20), removing transfer approvals.

# Motivation
Some dapps need interfaces simpler than ERC20 as a base for their tokens. We've seen some projects take this approach already ([1]). The main problems with ERC20 standard token are: 
- Lack of reference implementation and tests
- Higher complexity due to `approve` functionality, which not all projects need.
- Returns boolean values to signal failure instead of throwing.
- Function `totalSupply()` could just be implemented as a state variable in most cases.

# Specification

## totalSupply
```javascript
uint public totalSupply;
```
The total token supply

### balanceOf
```javascript
function balanceOf(address who) constant returns (uint);
```
Get the account balance of another account with address `who`

### transfer
```javascript
function transfer(address to, uint value);
```
Send `value` amount of tokens to address `to`

### Transfer event
```javascript
event Transfer(address indexed from, address indexed to, uint value);
```
Triggered when tokens are transferred.

# Reference Implementation and tests
https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/contracts/token/ERC20Basic.sol
https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/contracts/token/BasicToken.sol
https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/test/BasicToken.js

As you can see, the code is simpler and very concise. Comments appreciated.

[1]: https://github.com/imapp-pl/golem-crowdfunding/blob/master/contracts/Token.sol

**Comment by sebs** [comment]
Having worked a bit wit the Standard, yeah +1

**Comment by Arachnid** [comment]
Implementing `totalSupply` as a variable instead of a function still seems like a bad idea to me: it exposes implementation details, and provides very little reduction in complexity.

**Comment by nmushegian** [comment]
@Arachnid Note `public` keyword actually does generate a function, it's just syntactic sugar to generate a getter.

I'm ok with a "reduced ERC20", but the most likely result is some standard wrapped version of your token becomes the more liquid one (I bet it will happen to ETH itself):  https://github.com/makerdao/token-wrapper

**Comment by Arachnid** [comment]
> Note public keyword actually does generate a function, it's just syntactic sugar to generate a getter.

In that case, it should be defined in the spec as the equivalent function.

**Comment by frozeman** [comment]
Concerning the `totalSupply`, @chriseth wrote:
"I think there are currently still some issues with inheritance and virtual functions related to accessor functions. I would advise to not use public variables in an interface because it will allocate a storage slot for that variable with is not the purpose of an interface."

So i would suggest making it a function for now

**Comment by maraoz** [comment]
@frozeman @Arachnid Sorry, I still don't understand the problem with using a variable.

You can still use the generated function like so:
```javascript
import '../token/ERC20Basic.sol';

contract Foo {
  function bar(ERC20Basic token) returns (uint) {
    return token.totalSupply();
  }
}
```

What are the "issues with inheritance and virtual functions related to accessor functions" that @chriseth mentions?

**Comment by Arachnid** [comment]
@maraoz The problem is that the token contract itself can't compute its value on demand; it has to store it.

However, I realised this is academic: The ABI for a variable is the same as that for the getter function it generates. So if you specify a function just like in ERC20, you can implement it with an autogenerated getter if you prefer.

**Comment by GriffGreen** [comment]
The Exchanges would flip if we remove approve() from the standard... they all use it to make their system work. If we remove it, it needs to be replaced with something... this is why GNT is not traded outside of the decentralized market BokkyPooBah made 

The places that do trade it use a wrapper... so the wrapper part might as well be included in the full spec.

**Comment by april52** [comment]
can i generate ERC20 tokens using termux?

**Comment by trc20ats** [comment]
dear sir, TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t this wallet i lost keyword phase recover mistaken any idea to recover

**Comment by Nizomuddiyn** [comment]
Can u teach me how generate flash usdt trc20 please. 
contact @ubeyd3212 on telegram.

**Comment by agg-arch** [comment]
Can you assist make a trace of my lost funds on a Trc20 particular wallet address to recovery? Kindly email to aggreyjos@gmail.com.  It really dealt me a blow to my knees begging
