### ISSUE TITLE
Dynamic ENS resolution

### ISSUE THREAD

**Issue by nikeshnazareth** [ethereum/EIPs#1825]
## Purpose

The purpose of this issue is to sanity check and gauge interest in the following proposal for dynamic ENS address resolution.

For it to be successful, it will require the support of wallet developers.

Any suggestions, clarifications or criticisms are most welcome.

## Motivation

Consider the ENS domain `mydomain.eth`.

This proposal would allow users to resolve any sub-domain to a unique address controlled by the domain owner. 

For example, the owner could request a payment to `roadtrip-supplies.mydomain.eth`, without first configuring the sub-domain. 

Moreover, additional requests to the same sub-domain would (usually) return a new address each time. This would allow the owner to use a natural subdomain for a repeated activity ( eg. they could receive bounties at `bounty.mydomain.eth` or donations at `donation.mydomain.eth` ) but still use fresh addresses.

This is useful for isolating different transactions and _may_ (see Security section) improve privacy.
Note: in most cases, the different addresses would be linkable with user-specific analysis. 

## Background

As I understand it, most (all?) wallets derive private keys and addresses using the [BIP32 Hierarchical Deterministic Wallets](https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki) structure.

This allows wallets to generate an infinite number of private keys from a single seed.

Importantly for us, this also allows someone with a full ECDSA public key (not just an address) and a random 32-byte chain code to generate additional public keys without knowing the private key.

## Protocol

The proposal is:
* participating users can publish a full public ECDSA key to ENS
* when wallets resolve a sub-domain:
   * if there is a resolver, use it ( no change to functionality )
   * if there is no resolver and the parent domain does not have an ECDSA key, resolution fails ( no change to functionality )
   * if there is no resolver and the parent domain has an ECDSA key:
      * use the namehash of the sub-domain as the chain code ( zero the top bit to ensure we don't produce a hardened child key )
      * calculate the first corresponding child public key ( i = 0 ) and address
      * keep incrementing i until a fresh address with no transactions is found
      * return that address
* when the private key holder wants to use the new addresses, they enter the sub-domain into the wallet software, which then:
   * uses the namehash of the sub-domain as the chain code ( and zeroes the top bit as before )
   * calculates the first corresponding child private key ( i = 0 ) and corresponding address
   * increments i until a fresh address with no transactions is found
   * displays all iterated addresses and allows the user to interact with any of them

## Custom Resolver

A reasonable question you might ask is: why don't you just embed that logic in a custom resolver? This would avoid requiring wallet support.

There are a few reasons why, in my opinion, this is an inferior solution:
* we would need to export a full ECDSA public key anyway, so the support of wallet developers is still required ( unless the user generates their own ECDSA key )
* the resolver cannot determine if an address has any transactions associated with it. It would have to simply check that the balance is non-zero.
* users cannot use existing wallets to jump to the address associated with a very high i value:
   * they would need to calculate the key directly, or
   * the resolver would restrict i to a small range that the user could reasonably click through, resulting in collisions
* every ENS resolution would involve a HMAC calculation per address generated:
   * the number of operations scales linearly with the number of previously used addresses
   * this could lead to a denial-of-service attack (if I send lots of transactions to a sub-domain, the resolver consumes more resources)
   * Note: this is still true if it happens inside a wallet, but it is much better than on the blockchain node through the EVM.

### Disclosure of a private key

One important security consideration is that revealing chain codes (or in this case, using public ones) exposes the relationship between private keys. In particular, if any private key generated by this method is revealed, the entire tree would be compromised.

### Race Condition

If multiple users query a sub-domain before any of them interact with the resolved address, they will all receive the same address. This is, of course, no worse than the current scheme where all users always receive the same address.

### Privacy

The proposed scheme involves users locally generating the resolved address, which means they do not reveal the sub-domain that they used. If the sub-domain has enough entropy, there is no information on chain to link the resolved address to the domain or published ECDSA key, which means it is effectively an anonymous address (to everyone who does not know and cannot guess the sub-domain).

Of course, any short string or any word (in any language) can easily be exhausted and should not be assumed to provide privacy.

### Unknown addresses

If someone sends funds to a sub-domain that the owner does not know about, the owner will not be able to access the address (or even know that a transaction occurred).

This is particularly worrying for mistyped sub-domains. Since every sub-domain will resolve to some address, there is no way to alert the user to a mistake.

## Backwards Compatibility

I don't think this proposal introduces any breaking changes.

All domains/sub-domains that currently resolve will still resolve in the same way. This proposal only affects sub-domains that do not currently resolve.

**Comment by Arachnid** [comment]
Thanks for bringing this up! I've been considering the prospect of wildcard subdomains for some time.

The 'custom resolver' approach you outline is, in my mind, very much the superior one; the only additional functionality it requires from ENS and from wallets is to do a lookup in the resolver of the parent domain if the leaf domain does not exist; all other functionality can be baked into the resolver. The first approach you outline, on the other hand, would require all resolvers to add in a large amount of additional functionality, but would only support one record type (`addr()`).

Using a custom resolver also permits many other use-cases for wildcard domains we may not have already considered - such as wildcard resolution for other record types such as contenthash.

**Comment by nikeshnazareth** [comment]
Thanks for the quick reply!

I think I might have conflated two issues which should be separated.

I completely agree with your flow. We should definitely not limit resolvers in what they can support. The way I phrased my proposal suggested that the wallet would follow a particular strategy when faced with a missing leaf node, and you're right - the (parent) resolver should decide.

But suppose we get to that stage and the resolver decides "generate a fresh address controlled by the domain owner and return that as the resolution", how would it go about doing that? Wouldn't it suffer from the challenges I mentioned? 

>  The first approach you outline, on the other hand, would require all resolvers to add in a large amount of additional functionality, but would only support one record type (`addr()`).

The way I was imagining it, no existing resolvers would change, and the ones that choose to support the proposal would simply add an ECDSA public key, which the owner exported from a wallet, as a record type. In fact, that key could be the ENS resolution. All of the new functionality would be in the wallet software, which already deals with BIP32 address generation. 

Just to be explicit, to accomodate your objection, I would change the proposal as follows:
> * if there is no resolver ~~and the parent domain does not have an ECDSA key, resolution fails ( no change to functionality )~~, use the parent resolver
> * ~~if there is no resolver and the parent domain has an ECDSA key:~~ if ENS resolves with an ECDSA public key:

Does that sound more sensible? Thanks for the feedback.

**Comment by Arachnid** [comment]
> But suppose we get to that stage and the resolver decides "generate a fresh address controlled by the domain owner and return that as the resolution", how would it go about doing that? Wouldn't it suffer from the challenges I mentioned?

Yes, it would - but in my mind that's a particular set of design decisions you've taken, when there are a number of other viable solutions. For instance, simply taking the name hash and using (part of) it as a key in an HD wallet to generate a single address, regardless of whether it's been used before, is both practical to implement and achieves the goal of instant addresses with no onchain overhead per name/address.

> The way I was imagining it, no existing resolvers would change, and the ones that choose to support the proposal would simply add an ECDSA public key, which the owner exported from a wallet, as a record type. In fact, that key could be the ENS resolution. All of the new functionality would be in the wallet software, which already deals with BIP32 address generation.

Sorry, I was overloading my terminology; I meant to say "client software", not "resolvers".

Bear in mind that HD wallets are not the only ENS clients; browsers, DApps, etc, all need to do this. Asking them all to add support for HD wallet derivation seems like unnecessary overhead, for one very specific use-case. Putting this on the resolver means the only change they need to make is a second resolution step if the first one failed because the name did not exist.

**Comment by nikeshnazareth** [comment]
> For instance, simply taking the name hash and using (part of) it as a key in an HD wallet to generate a single address, regardless of whether it's been used before

I'm not sure if that captures the use case - especially without a wallet mechanism to access the new address. I'll keep thinking about it.

Nevertheless, the point about other ENS clients is well taken. I'll close the issue - thanks for the feedback!

**Comment by bijeebuss** [comment]
Did anything ever come out of this? I would love to be able to use a wildcard ENS domain with a custom resolver.
