### ISSUE TITLE
EIPS WEBSITE IS DOWN

### ISSUE THREAD

**Issue by fulldecent** [ethereum/EIPs#1826]
https://eips.ethereum.org/all and other URLs are now down.

<img width="1055" alt="screen shot 2019-03-05 at 10 03 04 am" src="https://user-images.githubusercontent.com/382183/53814607-e5068a00-3f2d-11e9-979a-7cad7c593296.png">

**Comment by corollari** [comment]
Working fine for me currently, seems like it has already been fixed.

**Comment by nicksavers** [comment]
Fixed. Thanks for the report.
