### ISSUE TITLE
MathTeX does not render correctly

### ISSUE THREAD

**Issue by fulldecent** [ethereum/EIPs#1860]
# TEST CASE:

1. Fork this repo
2. `bundle install`
3. Edit any EIP and add `Hello, $x = y$` in the text
4. `bundle exec jekyll serve`
5. Load the page in your browser
6. View relevant source

# EXPECTED

The math equation is visible in all its TeX glory.

# ACTUAL

The source shows the code as `<script type="math/tex; mode=display">x = y</script>`, but it is not rendered in the browser.

# IMPACT

We are using math expressions in EIPs and TeX is the prettiest and most common way to render math expressions in academic publications.

---

# SOLUTION

Currently we use the vendor-provided gitbub-pages default.html layout. Please see the comments in `Gemfile` and do the commenting and uncommenting of lines (and rerun `bundle install`) to get the GitHub environment running on your computer.

We may need to copy-paste default.html into this repo's `_layouts` directory to make changes. Then we can add a script https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js into there. This should cause it to render properly.

**Comment by bmann** [comment]
It’s not the GitHub pages default it’s the Jekyll default theme “minima” and yes it would need to be included in _layouts to be edited. 

Did some reading on this: https://quuxplusone.github.io/blog/2018/08/05/mathjax-in-jekyll/

Also, Kramdown (the rendering engine) May already support this? See https://kramdown.gettalong.org/syntax.html

This should test it:
```
$$
\begin{align*}
  & \phi(x,y) = \phi \left(\sum_{i=1}^n x_ie_i, \sum_{j=1}^n y_je_j \right)
  = \sum_{i=1}^n \sum_{j=1}^n x_i y_j \phi(e_i, e_j) = \\
  & (x_1, \ldots, x_n) \left( \begin{array}{ccc}
      \phi(e_1, e_1) & \cdots & \phi(e_1, e_n) \\
      \vdots & \ddots & \vdots \\
      \phi(e_n, e_1) & \cdots & \phi(e_n, e_n)
    \end{array} \right)
  \left( \begin{array}{c}
      y_1 \\
      \vdots \\
      y_n
    \end{array} \right)
\end{align*}
$$
```

**Comment by fulldecent** [comment]
Thank you for checking this out. So basically we just need to copy the default file and then add that one CDn line?

**Comment by bmann** [comment]
Yes I believe so!

**Comment by fulldecent** [comment]
Cool. Here is a pull request https://github.com/ethereum/EIPs/pull/1866

Requesting assistance to test it.
