### ISSUE TITLE
EIP1474 Does not render correctly on main EIPs website

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/EIPs#1878]
See: https://eips.ethereum.org/EIPS/eip-1474

It appears the markup on that page is interpreting all of the *collapsible* sections as being nested.

I would advocate for removing the collapse functionality in favor of a table of contents and maybe links in each section to take you back to the TOC.

**Comment by fulldecent** [comment]
Please remove the collapse and TOC. If we will introduce a TOC later it will be done for all EIPS automatically using a preprocessor. Pull request is welcome to fix #1474. #1155 has this same problem.
