### ISSUE TITLE
Discussion: EIP 1881 - Introduce a sound money and store of value as secondary block reward

### ISSUE THREAD

**Issue by therealsovtoshi** [ethereum/EIPs#1894]
---
eip: 1881
title: Introduce a sound money and store of value as secondary block reward on Ethereum
author: Sovtoshi
status: Draft
type: Meta
created: 2019-04-01
---

## Simple Summary

It has been shown that store of value is the primary and only use for blockchain. This EIP proposes Sound Money Coin (SOV), an Ethereum token with the sole purpose of being sound money and a store of value. SOV is paid to miners or stakers as a secondary block reward.

## Abstract

Sound Money Coin (SOV) is a sound money and store of value in the tradition of Austrian economics. It takes the form of an ERC20 token on the Ethereum blockchain. The [Sound Money Coin smart contract](https://etherscan.io/token/0x010589b7c33034b802f7dba2c88cc9cec0f46673) allows 0.05 SOV to be minted *once per block* up to the max cap of 21,000,000, a number mathematically proven to be the ideal max supply for sound money. As the hardest money in existence, Sound Money Coin will inevitably supplant unsound currencies like Bitcoin and become the reserve currency of decentralized finance and, by extension, the world.

Game theory dictates that all Ethereum miners will eventually cheat by preferring their own SOV minting transactions. This EIP suggests making the cheating explicit, either by a formal declaration by the Ethereum community and mining pools, or implementing a hard fork to change the Ethereum node software such that SOV its paid to miners programmatically.
  
## Motivation

A long long time ago, ancient civilizations used shells, beads and other primitive forms of money. When gold came around the bead makers tried to convince the ignorant population that gold was no substitute for beads. However, due to its inherent hardness and scarcity, gold proved to be a better store of value and all wealth eventually moved into gold, much to the detriment of the bagholders of beads and shells.

Many years later, kings and governments duped the dumb masses into using a new form of government-controlled paper money a.k.a. fiat money. Mainstream economists embraced the writings of convicted child molester John Maynard Keynes while the classical teachings of Austrian economists were derided and banned from economics textbooks. 

Fiat money turned out to be the most devastating force in the Universe. By constantly printing money out of thin air, governments inflate the money supply causing high time preference in the population, world wars, Justin Sun, the breeding of inexcusable aberrations like the Sphinx and Pekingese, and ultimately the demise of mankind.

When Bitcoin arrived in 2009 many saw a light at the end of the tunnel: Finally, a sound money for the people, uncontrollable by governments. But is it really? In Bitcoin, the inflation rate is indirectly determined by the block reward which is specified in the code of the Bitcoin node software. The elephant in the room is that Bitcoin's issuance policy is mutable and can be changed by social consensus in the future: All it takes is some influential figureheads manipulating the stupid masses into installing a software upgrade. Indeed, already now [Bitcoin developers are advocating for perpetual inflation](https://www.trustnodes.com/2019/03/26/peter-todd-advocates-raising-the-21-million-bitcoin-limit-hence-the-blocksize-constrain), and the discussion will only intensify with every future halvening.

Meanwhile, Ethereum is facing a seemingly unsolvable dilemma of its own: Its native currency Ether functions as gas paid for computation. If ETH price increases too much, using the Ethereum blockchain becomes prohibitively expensive. What's worse, the monetary policy of Ether can be, and has been, changed by its developers at a whim.

Clearly, there is a glaring need for a digital asset that functions as a store of value for the decentralized finance infrastructure. In early 2019, a [white paper](http://www.soundmoneycoin.io/whitepaper.pdf) by mysterious Cypherpunk Safeideous von Mises presented an ingenious solution: Sound Money Coin (SOV). SOV isolates the store of value use case into a separate ERC20 token. Thanks to its eternally immutable hard cap, SOV immune to social consensus and is suitable as a reserve currency of decentralized finance.

History has [shown repeatedly](https://www.amazon.com/Bitcoin-Standard-Decentralized-Alternative-Central-ebook/dp/B07BPM3GZQ) that wealth always moves towards the hardest money. As Sound Money Coin exhibits one-of-a-kind scarcity and hardness superior to fiat, Bitcoin and other inflationary currencies, all that is needed is a short-term commitment by the Ethereum community to "get the ball rolling". The more Bitcoin inflates due to the effects of technical and economical realpolitik, the more users will be incentivized to store wealth in Sound Money Coin. Ironically, the presence of a hard money on the Ethereum blockchain will "eat" Bitcoin and firmly establish Ethereum as the world computer for decentralized finance.

Sound Money Coin is the apex predator of value. By approximately 2035, SOV will assume the role of a global reserve currency and even the most stubborn central banks will grudgingly buy SOV reserves. Soon after, we will see the end of wars, the-emergence of beautiful science and art, and the crafting of spaceships that fly us to the furthest corners of the Universe.

## Specification

Sound Money Coin is represented by the ERC20 token at address [0x010589B7c33034b802F7dbA2C88cc9cec0f46673](https://etherscan.io/token/0x010589b7c33034b802f7dba2c88cc9cec0f46673). The code:

```

pragma solidity 0.5.4;

/* CBSNews, 12/02/2019: National debt tops $22 trillion for first time in U.S. history */

import "openzeppelin-solidity/ERC20.sol";

contract SoundMoneyCoin is ERC20 {

  /* Sound money and store of value on the Ethereum blockchain. */

  uint256 constant public MINING_REWARD = 5000000;
  uint256 constant public DEV_FUND = 100000;
  uint256 constant public MAX_SUPPLY = 2100000000000000;

  string public name = "SoundMoneyCoin";
  string public symbol = "SOV";
  uint8 public decimals = 8;
  uint256 public lastMinedAt;
  address public treasury;

  constructor() public {
    treasury = msg.sender;
  }

  function mint() public {

     uint256 blockNumber = block.number;
     require(blockNumber > lastMinedAt);
     require(totalSupply() < MAX_SUPPLY);

     lastMinedAt = blockNumber;

     _mint(msg.sender, MINING_REWARD);
     _mint(treasury, DEV_FUND);
  }
}
```

For each 0.05 SOV minted, 0.001 are transferred into the a development fund treasury. In an unfortunate turn of events, cypher punk Safeidous van Mises was killed by a polar bear during a hunting expedition in Alaksa shortly after creating Sound Money Coin. However, before his death (perhaps anticipating it?), he shared his private key with worthy members of the Sound Money Coin [Discord community](https://discord.gg/UtwNCX3).

This EIP proposes that:

- **The Ethereum community shall decree that the ERC 20 smart contract at address 0x010589B7c33034b802F7dbA2C88cc9cec0f46673, and only this smart contract, is and can ever be Sound Money Coin.**

- **The Ethereum community shall declare Sound Money Coin to be a sound money and store of value for use in decentralized finance.**

- **The Ethereum community shall decide by consensus that Sound Money Coin be issued to Ethereum miners as a secondary block reward.**

- **The Ethereum community shall commit to a diet that is solely based on plants.**

## Implementation

Currenlty, Sound Money Coin is distributed via a [web3 dapp](https://mint.soundmoneycoin.io/). However, techniques for minting Sound Money Coin have already evolved to include automated minters and proxy (ghost) minters.

### Hard Fork

The elegant and recommended solution is an to implement SOV emission via hard fork. This would obsolete regular minters and keep prevent unnecessary strain on the Ethereum blockchain. We suggest the following trivial code changes to the Ethereum full node software:

- Discard all minting transactions sent to address 0x010589B7c33034b802F7dbA2C88cc9cec0f46673.
- With every new block, the Sound Money Coin balance of the miner is increased by 0.05 SOV. 

### Soft Fork

In case the Ethereum community unexpectedly fails to reach consensus on the hard fork, a soft rollout will organically occur  because the pull of the hardest money is inescapable.
 
As wealth gradually moves from inflationary money into Sound Money Coin, an increasing number of actors will attempt to mint new coins. As SOV becomes more valuable, Ethereum miners will demand to be paid Sound Money Coin as a secondary block reward. Mining pools will be incentivized to cheat by intentionally inserting their own SOV minting transactions first in every block they mine. From that point on, regular minting transactions are bound to fail and SOV will be firmly established as the store of value.

Because all of this is inevitable, it is reasonable to declare Sound Money Coin as the secondary block reward in the first place.

## Test Cases

Forthcoming.

## Copyright

Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by therealsovtoshi** [comment]
Fix typos

**Comment by flygoing** [comment]
"Decimals: 8"

The real April fool's joke here

**Comment by Arachnid** [comment]
Please file this as a PR, so it can be merged as a draft.

**Comment by therealsovtoshi** [comment]
@Arachnid see #1893.

**Comment by therealsovtoshi** [comment]
@flygoing the decimals are modeled after Bitcoin the current leading (but inflationary) store of value. It is mathematically proven that an ideal store of value must have exactly 21,000,000 maximum supply and 8 decimals.

And you are absolutely right, only minting transactions should be discarded.
