### ISSUE TITLE
Discussion: EIP 1901 Add OpenRPC Service Discovery To JSON-RPC Services

### ISSUE THREAD

**Issue by shanejonas** [ethereum/EIPs#1902]
# Add OpenRPC Service Discovery To JSON-RPC Services

    EIP: 1901
    Title: Add OpenRPC Service Discovery To JSON-RPC Services
    Author: Shane Jonas, Zachary Belford
    Status: Draft
    Type: Interface
    Created: 2019-02-25

# Abstract
### What is this?

This is a proposal to add [OpenRPC](https://github.com/open-rpc/spec) support to existing and future JSON-RPC services by adding the method [`rpc.discover`](https://github.com/open-rpc/spec#service-discovery-method) to the projects [JSON-RPC](https://www.jsonrpc.org/specification) APIs, enabling automation and tooling.

The OpenRPC Document that specifies all the methods an EVM-based blockchain should implement can be found [here](https://github.com/etclabscore/ethereum-json-rpc-specification).

# Motivation
This was first proposed [here as an ECIP](https://github.com/etclabscore/ECIPs/blob/master/ECIPs/ECIP-1053.md), but the benefits of this kind of tooling is apparent across Bitcoin, Ethereum Classic, Ethereum and other JSON-RPC accessible blockchains.

### What is the problem?

- Maintenence time and accuracy on:
    - documentation
    - APIs
    - clients
- Not all JSON-RPC servers return the same methods or return the same version of the API.
- There is nothing that provides both human *and* machine-readable interfaces to be able to interact with JSON-RPC.
- Communication between services in different programming languages is not easy.
- Implementation usually comes at the cost of user experience consuming the API.

# Implementation
### How do I Solve the problem?
JSON-RPC APIs can support the OpenRPC specification by implementing a service discovery method that will return the [OpenRPC document](https://github.com/open-rpc/spec#openrpc-document) for the JSON-RPC API. The method MUST be named `rpc.discover`. The `rpc.` prefix is a reserved method prefix for [JSON-RPC 2.0 Specification](https://www.jsonrpc.org/specification) system extensions.

### Use Case
This is the vision for the use case of OpenRPC and how it would relate to multi-geth:

![MultGethRpc-usecase](https://user-images.githubusercontent.com/364566/54172981-4605f480-443d-11e9-9e29-80c580f9edae.png)

# Specification

### What is OpenRPC?
The [OpenRPC](https://github.com/open-rpc/spec) Specification defines a standard, programming language-agnostic interface description for [JSON-RPC 2.0](https://www.jsonrpc.org/specification) APIs, which allows both humans and computers to discover and understand the capabilities of a service without requiring access to source code, additional documentation, or inspection of network traffic. When properly defined via OpenRPC, a consumer can understand and interact with the remote service with a minimal amount of implementation logic, and share these logic patterns across use cases. Similar to what interface descriptions have done for lower-level programming, the OpenRPC Specification removes guesswork in calling a service.

##### Structure
This is the structure of an OpenRPC Document:

![openrpc-spec-structure](https://github.com/open-rpc/design/raw/master/diagrams/structure/OpenRPC_structure.png)

# Rationale
### Why would we do this?
Services need to figure out how to talk to each other. If we really want to build the next generation of automation, then having up to date libraries, documented APIs, and modern tools are going to provide easy discovery, on-boarding, and enable end user and developer interaction.

Use cases for machine-readable [JSON-RPC 2.0](https://www.jsonrpc.org/specification) API definition documents include, but are not limited to:

- A common vocabulary and document will keep developers, testers, architects, and technical writers all in sync.
- Server stubs/skeletons generated in many languages
- Clients generated in many languages
- Mock Server generated in many languages
- Tests generated in many languages
- Documentation Generation

# Alternative
[OpenRPC](https://github.com/open-rpc/spec) documents just describe [JSON-RPC](https://www.jsonrpc.org/specification) APIs services, and are represented in JSON format. These documents may be produced and served statically OR generated dynamically from an application and returned via the [`rpc.discover`](https://github.com/open-rpc/spec#service-discovery-method) method. This gives projects and communities the flexibility to adopt tools before the [`rpc.discover`](https://github.com/open-rpc/spec#service-discovery-method) method is implemented.

# Resources
- https://github.com/ethereum/EIPs/pull/1474
- https://github.com/ethereum/EIPs/issues/1442
- https://github.com/ethereum/EIPs/issues/217
- https://github.com/ethereum/EIPs/issues/136
- https://ethereum-magicians.org/t/eip-remote-procedure-call-specification/1537/20
- https://github.com/etclabscore/ECIPs/issues/16
- https://github.com/ethereum/EIPs/pull/1901

**Comment by shemnon** [comment]
Can an OpenRPC document be composed of multiple other OpenRPC documents?  

IMHO this EIP should be one or more OpenRPC specs reflecting the already standard JSON-RPC calls for Ethereum.  Client Implementors then would then use those specific files and aggregate them with their own Admin RPCs.  The example linked externally should then include an example of including those standard OpenRPC documents.

If OpenRPC is not that flexible, and if the existing RPCs are not specced in some form in this EIP, then I don't think this EIP adds any value other than saying "please use OpenRPC"

**Comment by Tokens001** [comment]
Sory?? You talk about me ?

**Comment by shanejonas** [comment]
@shemnon you can use `$ref` to reference local or remote documents the same way `JSON Schema` allows.

As I'm writing the `openrpc.json` for `multi-geth` its definitely getting pretty hefty, lots of undocumented `debug_` methods for example, so I will try breaking it down to multiple files.

You can check that out here: https://raw.githubusercontent.com/etclabscore/multi-geth/feat/openrpc-discover/internal/openrpc/openrpc.json

or you can check it out in the playground: https://playground.open-rpc.org/?schemaUrl=https://raw.githubusercontent.com/etclabscore/multi-geth/feat/openrpc-discover/internal/openrpc/openrpc.json

**Comment by shanejonas** [comment]
@shemnon I took some time and narrowed it down to all the methods from #1474 and #1436 and `getRawTransaction*`, added it to the EIP, can be found in [assets/eip-1901/openrpc.json](https://raw.githubusercontent.com/ethereum/EIPs/dbf64faff4dfe2f832d752292a39b8d7b9b46d2a/assets/eip-1901/openrpc.json) on the PR

heres a link to the playground:
https://playground.open-rpc.org/?schemaUrl=https://raw.githubusercontent.com/ethereum/EIPs/dbf64faff4dfe2f832d752292a39b8d7b9b46d2a/assets/eip-1901/openrpc.json

**Comment by shemnon** [comment]
Those two eips are a great place to start.  
* Can the schema file name have some reference to the EIPs they are implementing, such as openrpc_eip_1474.json?  If they are intended for composition then the name of the file should provide clarity as to what is being included.  `opejrpc.json` could be, literally, anything.
* Do we need the server section?  Again, if this file is intended for composition then a partial file should be sufficient, providing only the standardized parts of the spec.  Opening on local host on 8545 is a standard port, but not a requirement for the service.
* Can we get an example of how multigeth would compose the standardized files?

**Comment by shanejonas** [comment]
@shemnon 

It is possible with to compose different files, here is an example:

here is a local reference
```
methods: [
{
      "$ref": "schemas/methods/eth_getProof.json"
}
]
```

and a remote reference

```
methods: [
{
      "$ref": "http://wayne-enterprises.com/methods/get_batmobile.json"

}
]
```

Although I'm not a fan of this approach if it includes relative paths, if `geth` returns `rpc.discover` with a relative `$ref` path, that will need to be served up to actually be resolved later. Or geth (or any client) needs to `dereference` relative paths before served. Maybe we can limit it to absolute urls/remote and link to EIPs with `.json` files?

My other thought is that EIP implements #1474 and #1436 as of now, and it could be the canonical place to update methods, (like 1474 is now).

**Comment by shanejonas** [comment]
Took the time to put this repo together to house the specification we've started to outline here: https://github.com/etclabscore/ethereum-json-rpc-specification

**Comment by BelfordZ** [comment]
@shemnon Just wondering if you have any time to review this?

As per your question about composition -- All OpenRPC tooling demands an entire OpenRPC document to be passed in. How you assemble the document is up to the user, and therefore is as composible as any other JSON document. For most cases, composition probably means splitting method definitions out into their own file, which is really as simple as concatenating the set of methods into the [methods array](https://spec.open-rpc.org/#openrpc-methods).

for the server section question  -- [it is not a required field](https://github.com/open-rpc/meta-schema/blob/master/schema.json#L4)

**Comment by BelfordZ** [comment]
Forgot to mention - Multi-geth is now implementing OpenRPC along with its service discovery method, so you can have a look at how it was implemented if you wish
https://github.com/multi-geth/multi-geth#openrpc-discovery

**Comment by shemnon** [comment]
If current OpenRPC tooling requires a singular text document to serve as a schema, then I feel that the OpenRPC tooling should be improved.  One doesn't put all their Go interfaces in one file after all.

**Comment by BelfordZ** [comment]
OpenRPC is language agnostic - where/how you implement your methods, where you store the OpenRPC Documents JSON, or how you construct it is entirely up to you. This is not a concern of the tooling, which handles generating clients, documentation, mock servers, etc etc.

What I think you are talking about is a tool which would convert go interfaces into JSON schemas + [MethodObjects](https://spec.open-rpc.org/#method-object). I'd love to chat about making such a tool for OpenRPC.

**Comment by shemnon** [comment]
Actually I'm a Java dev and our platform is Java, that wasn't a request for Go tooling.  

What I want the OpenRPC spec to be able to handle is that I want to say my schema is made up of multiple pieces, evaluated in aggregate.  And I don't want to have to go into the files and do any JSON querying or assembly.  For example, I want to include the byte identical definition of the core Ehtereum JSON-RPCs, the byte identical definition of the EEA extension RPCs, and a set of PegaSys specific admin RPCs and say that those three files, in aggregate, form the schema of the endpoint.  I'm OK making a fourth document pointing to the other three, but I don't want to have to cut and paste the three documents in any way, shape, or form into one mega-document.  If my tool has to do any manipulation of the spec documents and those byte identical documents need to be modified in any form I consider it a problem with the OpenRPC spec, not the tooling.

**Comment by BelfordZ** [comment]
@shemnon Understood, and I see your point about having to muck around merging JSON files together is not ideal when what you are looking for is a pattern to compose several documents into one.

give me some time to think of other ways we could achieve this.

**Comment by BelfordZ** [comment]
merging/composing the methods is really simple. What is hard to understand is how composing OpenRPC documents would handle merging fields such as `info`

**Comment by BelfordZ** [comment]
perhaps we could try a vendor extension to start with: `x-extends` which would allow you to specify a reference to another OpenRPC document from which to extend from.

OpenRPC tooling such as [parse](https://open-rpc.github.io/schema-utils-js/globals.html#parseopenrpcdocument) could then return a single document that has been composed as you describe.

**Comment by shanejonas** [comment]
🔔 just wanted to update this thread and show progress:

## Implementation
Multi-geth has full support for OpenRPC, for Ethereum, Ethereum classic, kotti, goerli, and many other chains: 
https://github.com/etclabscore/multi-geth#openrpc-discovery

### The Spec:
The repo itself is getting some contributors, added missing methods like `eth_pendingTransactions`:
https://github.com/etclabscore/ethereum-json-rpc-specification


#### The Tooling

The playground has gotten some upgrades to be able to hit JSON-RPC from within the docs:

![inspector_playground_1](https://user-images.githubusercontent.com/364566/64275019-7cf32980-cef9-11e9-9310-e13082f3b4c3.gif)

You can play with that here:
https://playground.open-rpc.org/?schemaUrl=https://raw.githubusercontent.com/etclabscore/ethereum-json-rpc-specification/master/openrpc.json

**Comment by shanejonas** [comment]
Would like to see this moved through the process as OpenRPC is now being used here: https://github.com/ethereum/execution-apis

**Comment by MicahZoltu** [comment]
@shanejonas I recommend checking out [EIP-1](https://eips.ethereum.org/EIPS/eip-1) to understand the EIP process and how to get this pushed through.  Make sure you are prepared to do the leg work championing it, or you know someone who is as this will require discussion with client dev teams.

**Comment by shanejonas** [comment]
I believe the client team devs are already involved with https://github.com/ethereum/execution-apis as it was used for EIP 1559 to ensure compatibility, and now for the ETH2 merge.

I've also had a chat with client devs on All Core Devs previously which sparked some interest, but now that its being used it would be great to chat again to see where client teams are in regards to the current execution-apis in terms of compatibility.
