### ISSUE TITLE
EIP for DApp Website URL and Web3 HTTP Extension

### ISSUE THREAD

**Issue by OFRBG** [ethereum/EIPs#1909]
DApp websites currently implement their own workarounds when using standard HTTP and URL formats. In order to foster the web3 identity, setting semi-cosmetic standards for DApps would serve as a cornerstone.

For example, instead of having a scattered collection of DApp links:

https://www.cryptokitties.co/
https://idex.market/
https://etheroll.com/

which do not explicitly state belonging to the web3 ecosystem, we could set the cosmetic standard:

https://web3.cryptokitties.co/
https://web3.idex.market/
https://web3.etheroll.com/

This is just semi-cosmetic. If DApps widely adopt the web3 subdomain, search engines such as Google might pick up on this. Even if it doesn't, simply by generating the identity can create a sense of unity.

Furthermore, DApps that are implementing sign-in authentication without third-party interaction i.e. message signing, don't have an HTTP method that cleanly represents such authentication scheme.

**Comment by nicksavers** [comment]
HTTP is a client/server protocol.
![HTTP protocol](https://cdn-images-1.medium.com/max/1600/1*JSnJtHpU7cWUnWIgGupu7w.png)
If an app is hosted on a distributed file system, the URL changes to `ipfs://` or `bzz://`. 
Would that be explicit enough?

**Comment by OFRBG** [comment]
I don't know if Cryptokitties would move to ipfs or bzz, for either the frontend or the API, at all. So yes, it is explicit enough, yet unfeasible in the foreseeable future.

**Comment by nicksavers** [comment]
My point being that if a centralized server is hosting a website over the HTTP protocol, we're not really talking about Web3. The website itself might be completely client-side, the domain that services it, is not.

**Comment by OFRBG** [comment]
If the benchmark for something being or not web3 is serving content over IPFS with blockchain as a DB, web3 isn't going to happen. Fortunately we can have a middle ground, and instead of cutting out everyone who doesn't use unstable, experimental protocols, we could begin to build a recognizable internet identity.

**Comment by bitcoinbrisbane** [comment]
Im working on something similar. Ill message you @OFRBG
