### ISSUE TITLE
EIP-1921 dType - Extending the Decentralized Type System for Functions

### ISSUE THREAD

**Issue by loredanacirstea** [ethereum/EIPs#1921]
Draft can be found at: https://github.com/ethereum/EIPs/pull/2267

In-work implementation examples, articles, video demos & related EIPs can be found at https://github.com/pipeos-one/dType.

**Comment by Arachnid** [comment]
You should post this as a draft, so it has a persistent URL, and specify a discussions-to address (possibly this thread?)

**Comment by loredanacirstea** [comment]
I made a PR request with the Draft at https://github.com/ethereum/EIPs/pull/2267.

@Arachnid, regarding your question from [another discussion](https://ethereum-magicians.org/t/case-discussion-on-the-eip-process-based-on-eip-1900-eip-1/3627/16):

> Can you give an example, then, of how you would define a DType type with, say, the ERC20 transfer method, and how multiple developers would implement this? I still don’t see how that’s possible in DType, so an end-to-end example would really help.

The original issue that we [were discussing](https://ethereum-magicians.org/t/case-discussion-on-the-eip-process-based-on-eip-1900-eip-1/3627/14?u=loredanacirstea) was:
> DType, in contrast, seems to assume each type will have exactly one implementation.

So, I will give a more appropriate example for the current state of the dType EIPs:


Uint256 is too general a type. In different contexts, it means different things. Using dType, the dev will be able to express the intent:

```
IntLength:: uint256
IntVolume:: uint256
```

In a comparison function:
```
moreThan(uint256 dim1, uint256 dim2) pure public returns(bool result);
```

We should not be able to compare the length with the volume. That is why we will use dType and the function will describe truthfully our intent:

```
moreThanLength(IntLength len1, IntLength len2) pure public returns(bool result);
moreThanVolume(IntVolume vol1, IntVolume vol2) pure public returns(bool result);
```

So, `moreThanLength` and `moreThanVolume` can be registered with dType with their ABI definition, but in this case, the implementation is left to the developer.

The ERC20 example is not covered by the functions extension yet. The current proposal targets `pure` / `view` functions.

**Comment by Arachnid** [comment]
So, it's not possible to express the interface of a standard like ERC20 in DType? This seems like a basic piece of functionality to me.

Can you give any end-to-end example of how someone defining a smart contract standard could use DType?

**Comment by loredanacirstea** [comment]
EIP-1900 only describes a data type system. EIP-1921 only describes the function type extension.
For standards like ERC20, you need an extension to interfaces and that will come in future EIPs.

**Comment by loredanacirstea** [comment]
Example of end to end use of EIP-1900 and EIP-1921: https://github.com/ethereum/EIPs/issues/1882#issuecomment-529840460
