### ISSUE TITLE
Consider EIP1344 for the next upgrade (Meta: EIP1679)

### ISSUE THREAD

**Issue by fubuloubu** [ethereum/EIPs#1935]
Per the proposed process for handling EIPs for Hardforks (detailed [here](https://github.com/ethereum/EIPs/blob/9233fd6aaa99161079e395f8733c26c9f4a3b17d/EIPsForHardfork.md)), we would like to propose [EIP-1344](https://eips.ethereum.org/EIPS/eip-1344) be formally considered for inclusion into the Istanbul hardfork (EIP-1679)

**Comment by Arachnid** [comment]
ISTM that this EIP is in no way ready for that. It needs to specify implementation details at a bare minimum; presently it's barely more than an idea.

**Comment by fubuloubu** [comment]
In the [discussion forum](https://ethereum-magicians.org/t/eip-1344-add-chain-id-opcode/1131), we talked about technical details of this proposal. The only outstanding concern was around the datatype that we might use to represent it from the opcode, opting for the full range of `uint256` to be maximally flexible with current use of chainId (some are more than `MAX_UINT32`) and also match with the EIP 712 specification.

You are correct that it lacks a current implementation, but the implementation details are fully specified as far as I am aware:

| Detail | Setting |
| --- | --- |
| Opcode | `0x46` |
| Stack args | 0 in, 1 out |
| Gas costs | 2 gas (`G_BASE`) |

Considering this is the first time we am hearing about a lack of specificity around this proposal, can you please suggest what information is missing so that we can ensure this proposal does not waste people's time? Consider adding discussion to the forum if it is extensive.

**Comment by fubuloubu** [comment]
I whipped up a quick implementation against Trinity here:
https://github.com/fubuloubu/py-evm/commit/eaab5ffa2164d4cc06ae5c855a49d030965be828

**Comment by Arachnid** [comment]
Sorry; the spec was so brief I missed reading it on the EIPs page.

You do, however, need to add the missing sections from EIP-X, such as tests, even if those sections are still 'TBD'. The formatting also needs fixing - the indentation and lack of linebreaks is causing it to render poorly on eips.ethereum.org.

**Comment by fubuloubu** [comment]
Will do! Do you see anything blocking it from a preliminary discussion tomorrow?

**Comment by Arachnid** [comment]
Not offhand, but I haven't been on an ACD call since I moved to NZ. :)
