### ISSUE TITLE
EIP-1958: Smart contract functions payable in tokens

### ISSUE THREAD

**Issue by ramvi** [ethereum/EIPs#1958]
```
eip: 1958
title: Smart contract functions payable in tokens
author: Jon Ramvi <jon@blockchangers.com>
status: Draft
type: Standards Track
category Core
created: 2019-04-21
```

## Simple Summary
Description of smart contracts being able to accept payment in ERC-20 tokens.

## Abstract
The following describes changes to the payable keyword in smart contracts so that payments can be made in ERC-20 tokens.

## Motivation
There's a clear divide between the first-class citizen currency ETH and tokens. Many proposals have been made to make ERC-20 tokens first-class citizens. This proposal is only about acknowledging ERC-20 tokens at the base layer. This proposal is not about accepting ERC-20 tokens for gas.

The 'atomicness' and finality of Ethereum payable methods are very slick. In a couple of lines, you're able to accept payment. The payment in itself is the receipt, and can also represent what you bought, which in today's web 2.0 are three different things that need to match up. 

This functionality is however only available for payments in ether. Hence, I propose we support the same easy 'atomicness' with stablecoins and other tokens. 

## Specification
The proposal is for the contract to define what payment's it accepts. 

```solidity
DAI("0x89d24a6b4ccb1b6faa2625fe562bdd9a23260359");
function method() public payable(DAI, ether);
```

## Rationale
Say you want to create a ticketing system which accepts the stablecoin DAI. The solution with all necessary security can be built with 21 lines of code and includes a solution for the second-hand market meaning these 21 lines of code includes more secure functionality than giants like TicketMaster.

```solidity
contract JaycTickets20200101NYC {

    uint numTickets;
    mapping (address => bool) ticketsSold;
    DAI = DAI("0x89d24a6b4ccb1b6faa2625fe562bdd9a23260359");
    
    constructor(uint _numTickets) internal {
        numTickets = _numTickets;
    }

    function buyTicket() payable(DAI) public {
        require(msg.value == 100 DAI);
        ticketsSold[msg.sender] = true;
    }

    function transfer(address _to) public {
        require(ticketsSold[msg.sender]);
        ticketsSold[msg.sender] = false;
        ticketsSold[_to] = true;
    }
}
```

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by Amxx** [comment]
require(msg.value == 100 DAI);

By design, `msg.value` is an amount of wei transferred by the transaction. It does not represent an ERC20 value.

If you do an ERC20 transfer, the ERC20 contract is the one receiving the transaction and updating its internal storage to account for the ownership change (of fungible tokens). The new owner does NOT receive any transaction. This is why you should not transfer ERC20 to a contract, but rather approve the contract and then ask the contract to do a transferFrom.

I doubt your proposal is even remotely applicable to ERC20 without any additional features (callback to the receiver)

**Comment by tjayrush** [comment]
I have no comment (yet) on this proposal, but I do think it would be improved if you referenced some of the "many other proposals" you mention here:

> Many proposals have been made to make ERC-20 tokens first-class citizens.

**Comment by PhABC** [comment]
>  This proposal is only about acknowledging ERC-20 tokens at the base layer.

Being an author of ERC-1155 token standard, I am obviously biased, but I consider the ERC-20 as ill constructed and would not support ERC-20 at the base layer. In fact, I would not support ERC-1155 either, as the base layer should not be modified based on the current hottest trend. Just my humble opinion.

As an alternative, by changing a bit how contracts are written, one can support calling functions on contract _while_ passing ERC-721 and ERC-1155 tokens, via the `safeTransferFrom()` methods in both standards. One would need to pass the function call signature + encoded arguments in the `data` field of the `safeTransferFrom()` method.

**Comment by ramvi** [comment]
@Amxx Thanks for your feedback. I propose: 

1. To represent DAI in the same way you can write `1 ether` (cite)[https://solidity.readthedocs.io/en/develop/units-and-global-variables.html?highlight=transfer#ether-units] you can write `1 DAI` meaning 1 + DAI's `decimals` variable
2. To represent DAI it's smallest / atomic form, you can write `100000000 DAI.decimals`

> I doubt your proposal is even remotely applicable

Why? My proposal is the change the EVM to understand and write directly to ERC20 contracts, to make them first-class citizens on the platform. Why would you need a transaction to the contract or a callback?

**Comment by ramvi** [comment]
> I have no comment (yet) on this proposal, but I do think it would be improved if you referenced some of the "many other proposals" you mention here

* https://github.com/status-im/status-react/issues/2464
