### ISSUE TITLE
eip-1767  miner of type Block seems not need a filter

### ISSUE THREAD

**Issue by zyfrank** [ethereum/EIPs#1964]
EIPS/eip-1767.md
seems 
```
 # Miner is the account that mined this block.
    miner(block: Long): Account!
```

should be `miner: Account!`  ?
In one block to query miner of another block?

**Comment by flygoing** [comment]
Consider posting this to that EIPs discussions-to page [here](https://ethereum-magicians.org/t/graphql-interface-to-ethereum-node-data/2710)
