### ISSUE TITLE
EIP-1352 doesn't have an associated registry?

### ISSUE THREAD

**Issue by chaals** [ethereum/EIPs#1981]
EIP-1352 reserves a block of address space for precompiles. However, there is no apparent mechanism to register that anyone intends to use (or is already using) part of that space.

This means that if say a private network client wants to use a given address for a function it implements, primarily serving one network, it will have to either flag the precompile by network or check everything else it connects to in case there is a different precompile at the same address.

I **think** the expectation is that precompiles would normally be useful across a lot of different networks (this would seem especially the case for e.g. EEA clients), so it seems to me that it would be useful to actually be able to register addresses in this space...

**Comment by axic** [comment]
I had this in mind, but figured that private chains would not want to reveal themselves to allocate specific numbers.

Can you please move this question to the discussion URL in the EIP and close this issue: https://ethereum-magicians.org/t/eip-1352-specify-restricted-address-range-for-precompiles-system-contracts/1151

**Comment by chaals** [comment]
Sorry for the noise in the wrong place - yes I'll move it...
