### ISSUE TITLE
EVM opcode: breakpoint

### ISSUE THREAD

**Issue by axic** [ethereum/EIPs#201]
### Motivation

To speed up debugging, if a breakpoint is expected there is no need to step through execution, but can safely stop at the breakpoint.

### Specification

A new opcode, `BREAKPOINT` is introduced at `0xfd`.

Option 1:

A virtual machine if run in debugging mode, should stop execution when encountering this instruction, otherwise it should ignore it.

Option 2:

It stays as an invalid instruction in a deployed contract, but special debugging EVM implementations are allowed to support it.

Alternatively, another good name is `DEBUG`.

**Comment by Arachnid** [comment]
Can't debuggers set breakpoints using external information? This method would require changing the code every time you want to add or remove breakpoints.

**Comment by gcolvin** [comment]
The C++ VM has hook for a callback function that can be and I think is used for debugging.  @yann300 ?

**Comment by yann300** [comment]
Yes. Though that would mean to readd the JavaScript interpreter I guess...

**Comment by gcolvin** [comment]
@yann300 I don't really understand, as the hook must already be used by any debugger that wants to single-step, inspect stack and memory, etc.  The hooked get's called for every instruction executed, so it can stop when the desired program counter is reached.  But do get that performance takes a hit.  But the breakpoint instruction there would need to be a way to call into the running VM to to modify the code, and probably a way to get the other information the hook provides.  Just stopping doesn't help if you can't inspect the state of the program.

**Comment by yann300** [comment]
Calling the running VM to modify the code on the fly sounds interesting.
When the user is is debug session, the bytecode could be updated as the user is writing new solidity code that is about to be executed... (not sure if it completely doable).
As remix is in JavaScript that would mean to add a JavaScript interpreter in a c++ code that could call JavaScript callback right? or maybe I misunderstood something....

**Comment by gcolvin** [comment]
I only meant modifying a single bytecode with this new BREAKPOINT opcode.

**Comment by yann300** [comment]
yes i know, I was just wondering if we could also update the bytecode as the user is writting. Some IDEs do that.

**Comment by nmushegian** [comment]
A general principle of ethereum and blockchains is if it can be done off-chain, do it off chain.

**Comment by kumavis** [comment]
`0xfd` is claimed by revert

**Comment by GNSPS** [comment]
I really like the idea of having a breakpoint opcode. I feel that option 2 kind of defeats the purpose of standardizing this though, I would go with 1.

Would it make sense to mimic x86 arch and have an `interrupt` opcode with a single byte param?

The VM, if run in debugging mode, would then have the opportunity to have stored routines given different interrupt values. (And we could have a single-byte version for the breakpoint interrupt much like `INT 3` in x86.

**Comment by InsidiousMind** [comment]
I like the idea of mimic-ing x86 functionality along with UNIX Opcodes. On UNIX, the process of breakpoints looks something like:

Create Breakpoint
```
    Compute location of the break point
    Read byte that was there and save it.
    Put 0xCC byte there (int3 opcode). If program is ptraced, executing int3 will freeze it.
```
disabling Breakpoints:
```
    Disable breakpoint (write back old instruction)
    Run single step (PTRACE_SINGLESTEP)
    Enable breakpoint (write int3)
    Continue (PTRACE_CONT)
```
It could look similar in EVM too.

**Comment by gcolvin** [comment]
It might be more useful to consider something more general like the Java Debug Wire Protocol.  The debugger asks the VM to set a breakpoint, single step, or whatever and it's up to the VM to make it happen however it likes.

**Comment by InsidiousMind** [comment]
@gcolvin Huhm, didn't think of that. Definitely a potential solution, but I worry about it's extendability. Would this be more of a solidity feature, or can it be extended to apply to other languages (IE: Viper)? I'm not totally familiar with the Java Debug Wire Protocol. Would it require making changes to the VM for every language that is to be debugged with?

I think the con of doing it the UNIX-way would be the potential need to implement a compile option for debug symbols in order to be able to step-over and into solidity code rather than the underlying assembly. However, once an interface is created, it may be easier to create debug symbols for other languages rather than modify an interface similar to the Java Debug Wire Protocol.

**Comment by gcolvin** [comment]
It's not a language feature, it's a wire protocol that all JVMs have to implement.  It could be optional if we wanted.  I implemented it for the Oracle JVM, and we also adapted it for PL/SQL.  That way any Java debugger could be used for either VM.  Another advantage is that debuggers (Eclipse, JSwat, etc.) aren't linked to the VM, but connect via a socket.  It's stood up to years of use and extension by now.

**Comment by gcolvin** [comment]
So yes, a protocol like that would be language and VM agnostic.  It would even be possible for an EVM to pretend to be a JVM and use the actual JDWP for the purposes of debugging.  We did that for PL/SQL at Oracle.  Lining up source and bytecode might be an issue - the Java class file format takes care of that and we don't.  At worst, the tool that created the code you are debugging could keep of that for the code it knows about, and perhaps disassemble other code if you don't want to work at the bytecode level.

**Comment by InsidiousMind** [comment]
@gcolvin Did some digging on this topic, and actually the functionality of mapping the bytecode to sourcecode may already exit, taken from the docs for solidity compiler:

> Furthermore, the compiler can also generate a mapping from the bytecode to the range in the source code that generated the instruction. This is again important for static analysis tools that operate on bytecode level and for displaying the current position in the source code inside a debugger or for breakpoint handling.

> Both kinds of source mappings use integer identifiers to refer to source files. These are regular array indices into a list of source files usually called "sourceList", which is part of the combined-json and the output of the json / npm compiler.

> The

 > source mappings inside the AST use the following notation:

> `s:l:f`

> Where s is the byte-offset to the start of the range in the source file, l is the length of the source range in bytes and f is the source index mentioned above.

> The encoding in the source mapping for the bytecode is more complicated: It is a list of s:l:f:j separated by ;. Each of these elements corresponds to an instruction, i.e. you cannot use the byte offset but have to use the instruction offset (push instructions are longer than a single byte). The fields s, l and f are as above and j can be either i, o or - signifying whether a jump instruction goes into a function, returns from a function or is a regular jump as part of e.g. a loop.

**Comment by gcolvin** [comment]
Does this mapping get stored on the blockchain?

**Comment by InsidiousMind** [comment]
afaik, it does not. It's just a compiler option and outputs to another file alongside solidity code/bytecode

**Comment by gcolvin** [comment]
OK.  Not so nice as what Java provides so far as debugging arbitrary code on the blockchain, but still very good for development.
