### ISSUE TITLE
Up-to-date JSON-RPC API spec

### ISSUE THREAD

**Issue by pedrouid** [ethereum/EIPs#2053]
There are have been multiple issues opened and closed around this issue but we currently lack an updated JSON-RPC API spec.

I'm happy with keeping the same Github Wiki we have right now for reference (https://github.com/ethereum/wiki/wiki/JSON-RPC) but it needs to include the latest methods that have already been implement by clients and other middleware. For example: `eth_signTransaction` and `eth_chainId`

PS - This issue has already been referenced by #728 over a year ago

**Comment by axic** [comment]
Can you check https://eips.ethereum.org/EIPS/eip-1474 if that satisfies these requirements? Please note Jekyll fails to render it properly (trying to fix that in #2059).

**Comment by pedrouid** [comment]
> Can you check https://eips.ethereum.org/EIPS/eip-1474 if that satisfies these requirements? Please note Jekyll fails to render it properly (trying to fix that in #2059).

Oh I never noticed the methods were included in 1474 because of the rendering. We should get some Jekyll folks in here to fix it.

Also is `eth_chainId` (#695) not included because it's not final yet?

**Comment by axic** [comment]
> Also is eth_chainId (#695) not included because it's not final yet?

Not included where? In 1474?

I'd say 1474 should be just the core spec and others refer to it. Later we could consider checkpointing a combined updated version of 1474 under a new number, which folds all those into one spec, if there's need.

**Comment by axic** [comment]
Closing this as the rendering issue is tracked in #1878.
