### ISSUE TITLE
EIP-2054 Add missing cheap unique ID and external call hierarchy introspection

### ISSUE THREAD

**Issue by k06a** [ethereum/EIPs#2054]
```
EIP: 2054
Title: Add missing cheap unique ID and external call hierarchy introspection
Author: CryptoManiacs team: Anton Bukov <k06aaa@gmail.com> and Sergej Kunz <info@deacix.de>
Type: Core
Category: Core
Created: 2019-05-20
Updated: 2019-05-20
```

I would like to avoid this situation and not to use `SSTORE` at all:

```Solidity
uint nextTaskId = 1;
function addTask(Task memory task) public {
    tasks[nextTaskId] = task;
    emit TaskAdded(msg.sender, nextTaskId, task.value);
    nextTaskId++;
}
```

I wish to have some kind of unique ID inside function for example to keep some task in mapping:

```Solidity
function addTask(Task memory task) public {
    uint256 key = block.number;
    tasks[key] = task;
    emit TaskAdded(msg.sender, key, task.value);
}
```

But several transactions will result a conflict, let’s imagine we even have a `tx.hash`:

```Solidity
function addTask(Task memory task) public {
    uint256 key =tx.hash;
    tasks[key] = task;
    emit TaskAdded(msg.sender, key, task.value);
}
```

But this also will not work in case of several calls from a different smart contract, but wait:

```Solidity
function addTask(Task memory task) public {
    uint256 key = keccak256(tx.hash, gasleft());
    tasks[key] = task;
    emit TaskAdded(msg.sender, key, task.value);
}
```

But this will not work again in case of implicit gas limit specification for call: `register.addTask.gas(100000)(task)`.

I wonder if we can introduce new opcode for this, like:
- external calls counter `msg.callnumber`
- external calls path (array of nested subcall counts) `msg.callnumber(i)`
- external calls introspection `getsender(i)`

**Comment by snjax** [comment]
`tx.origin + tx.nonce` seems to be enough for building such unique ID.

**Comment by k06a** [comment]
@snjax I mean it also should be unique for multiple subcalls inside single transaction
