### ISSUE TITLE
Discussion: Kickbacks for contract authors

### ISSUE THREAD

**Issue by charles-cooper** [ethereum/EIPs#2061]
It's often hard for dapp writers to monetize their dapps. Monetization can lead to legal difficulties, because the status of dapps is not well understood in many jurisdictions. In order to monetize, dapp writers need to create an ad-hoc payment schedule, and may need to incorporate and comply with laws across many jurisdictions for accepting payment.

On the other hand the mining system is robust, decentralized, and (for reasons unclear to me) is apparently accepted in many jurisdictions without the onus of conforming to money transmission laws.

This proposal is that the recipient of a message call receives some portion of the fees generated by the transaction. By having all recipients (not just contract accounts) receive this kickback, this enhances deniability for the contract author that they did not create an arbitrary payment schedule (which may or may not conform to some particular jurisdictions regulations), in turn enhancing decentralization of the dapp development ecosystem. What remains to be determined  is the exact mechanism for determining how to calculate the kickback and who the beneficiary is.

**Comment by MadeofTin** [comment]
Just a thought that this would be a great post for FEM. https://ethereum-magicians.org
You are likely to get more feedback there.

**Comment by karalabe** [comment]
Mining is a taxable event in most jurisdictions. Contract kickbacks break once you realize the deployer is often not the author.
