### ISSUE TITLE
List of EIPs/ERCs without a copyright statement

### ISSUE THREAD

**Issue by axic** [ethereum/EIPs#2062]
- 2
- 3
- 4
- 5
- 6
- 7
- ~~8~~ (fixed by #2416)
- 55
- 100
- 101
- ~~107~~ (fixed by #2068)
- 137
- 150
- 155
- 158
- 160
- 161
- ~~162~~ (fixed)
- 170
- ~~181~~ (fixed)
- 190
- 210
- 616
- 1014
- ~~1108~~ (fixed by #2067)
- ~~1191~~ (fixed by #2233)
- 1386
- 1387
- 1388
- ~~1702~~ (fixed by #2167)

Many of these are still drafts. I suggests that drafts cannot turn final without a copyright and license statement.

**Comment by xinbenlv** [comment]
I suggest any new draft cannot be merged into this repo without a copyright and license statement.

**Comment by axic** [comment]
> I suggest any new draft cannot be merged into this repo without a copyright and license statement.

I think that is the rule, but people make mistakes.
