### ISSUE TITLE
Extend contract ABI with structs

### ISSUE THREAD

**Issue by chfast** [ethereum/EIPs#21]
Extend contract ABI with anonymous structs / tuples.

Proposed syntax: `{address, uint, bool}`

The size of a struct is a sum of sizes of its elements (data is packed). Aligned to words.
### Rationale

There are cases when packed related elements are easier/cheaper to process. E.g. `function pay({address, uint96}[] payments)`.

**Comment by chriseth** [comment]
On the first read, this looks good and very useful. Devil could be in the details ;-)
Of course, the `X`, `Y` and `Z` in `{X,Y,Z}` should again be allowed to be any ABI type, including structs.

**Comment by chriseth** [comment]
It seems to be trivial to adapt the [encoding specification](https://github.com/ethereum/wiki/wiki/Ethereum-Contract-ABI) to that case (thee this [comment](https://github.com/ethereum/wiki/wiki/Ethereum-Contract-ABI#function-selector-and-argument-encoding)) and most of the encoders will probably also only need a recursive call - although parsing the types could be a bit more complicated.

**Comment by tgerring** [comment]
Single return variable:
```
    "outputs": [
      {
        "type": "bool",
        "name": "success"
      }
    ]
```

Multiple return variables:
```
    "outputs": [
      {
        "type": "address",
        "name": ""
      },
      {
        "type": "unit",
        "name": ""
      },
      {
        "type": "bool",
        "name": ""
      }
    ]
```

What would a tuple return of these values look like?

**Comment by chriseth** [comment]
A simple answer to that question would be ```{
  "type": "(uint256,(string,uint16)[10])",
  "name": "someParam"
}```, i.e. just don't name the internal types, but if we do that, we could also just forget about the json structure and simply give the function as `function f(abc: uint, def: (a: uint, b: (c: string, d: uint16)[10])))`.

Especially for arrays of structs, I'm not sure how to assign names to the elements.

**Comment by chriseth** [comment]
### Proposal for the json-formatted abi:

`inputs` and `outputs` is an array of objects with properties `name` (optional), `type`, `subtype` (optional, new) and `indexed` (for events). `type` can be any of the already used types (`"uint256"`, `"uint256[10][]"`, ...), but additional values are permitted:

 - `"[]"` or `"[k]"` for some integer `k`: If this is used, the object is of array type and the type of the elements of the arrays is specified under the property `subtype`.
 - an non-empty array of objects as described here - this models a tuple.

If the `subtype` property is used, its value cannot be `"[]"` or `"[k]"`, but it can be an array of length 1 whose element models the type one deeper in the array hierarchy.

### Example:

The signature `function f(abc: uint, def: (a: uint, b: (c: string, d: uint16)[10])))` is translated into json-abi as follows:

```
{
  name: "f",
  inputs: [
    {name: "abc", type: "uint256"},
    {name: "def", type: [
      {name: "a", type: "uint256"},
      {name: "b", type: "[10]", subtype: [{name: "c", type: "string"}, {name: "d", type: "uint16"}]}
    ]}
  ]
}
```

**Comment by chfast** [comment]
@chriseth if I understand your proposal, you want also name the elements of a struct/tuple? I don't have any objections but I thought is was not necessary.

In general, feel free to update the description of this issue.

**Comment by chriseth** [comment]
@chfast being able to name them makes the whole thing more symmetrical, basically the whole parameter set is just a tuple. Furthermore, it is easier to access elements by name from JavaScript.

**Comment by chfast** [comment]
@chriseth We might have alignment issues here. We want tuple elements on the top level to be 256-bit word aligned and elements on deeper levels to be packed.

**Comment by chriseth** [comment]
@chfast why should elements be packed? Even a `bool[]` has 32 bytes per element.

**Comment by chfast** [comment]
@chriseth I would like `(address, uint64)` to be fit in one word. In other words `(address, uint64)[]` to have 32 bytes per element.

**Comment by chriseth** [comment]
@chfast I see your concerns, but memory is actually not too expensive and we always pad everything outside of storage, so it would need quite some changes in Solidity.

**Comment by chfast** [comment]
I need that to define ABI-compatible functions with body optimized in EVM. Otherwise it has no use for me.

**Comment by chriseth** [comment]
Ah ok, now that I read the proposal again, I get that it is actually not so much about extending functionality but rather about reducing the padding.

My personal opinion is that structs in the ABI are a good feature for usability and type-safety purposes. Furthermore, I think it is important to add them in a backwards-compatible and consistent manner. For me, this means that we have to pad their elements just like everything else.

I guess that having `(address, uint64)[]` where all elements are padded is still better than using `(address[], uint64[])`.

**Comment by chfast** [comment]
@chriseth, yes, having `(address, uint64)[]` is better than `address[], uint64[]`.

Unnecessary waste of space stills worries me. I will try to write a benchmarks for both packed and aligned cases to see what the difference is.

**Comment by janx** [comment]
Packing is even more useful in case that functions cannot return dynamic array, and use large static array instead. And loading state from array of structs on dapp init seems to be a pattern?

An abi supports struct is very useful. Maybe this can go into a new proposal since the focus of this one is padding.

Is this allowed?

```
 {name: "a", type: "[16]", subtype: "uint32"}
// equals
{name: "a", type: "uint32[16]"}
```

**Comment by Souptacular** [comment]
Paged @chfast to check on this.

**Comment by frozeman** [comment]
What is that state on this @chriseth ?

**Comment by chriseth** [comment]
Solidity now went with the following:

The signature is using `()` for structs, i.e. `(uint256,bytes32,(uint8,string)[])` is a struct with three components, where the third component is a dynamic array of a struct with two components. In the json-abi we are able to name the components, and thus there is a key `components`, which has the same structure as the type list itself.

Examples and specification can be found at https://solidity.readthedocs.io/en/develop/abi-spec.html#handling-tuple-types
