### ISSUE TITLE
EIP-1996: Holdable token

### ISSUE THREAD

**Issue by daniel-iobuilders** [ethereum/EIPs#2103]
An extension to the ERC-20 standard token that allows tokens to be put on hold. This guarantees a future transfer and makes the held tokens unavailable for transfer in the mean time. Holds are similar to escrows in that are firm and lead to final settlement.

A hold specifies a payer, a payee, a maximum amount, a notary and an expiration time. When the hold is created, the specified token balance from the payer is put on hold. A held balance cannot be transferred until the hold is either executed or released. The hold can only be executed by the notary, which triggers the transfer of the tokens from the payer to the payee. If a hold is released, either by the notary at any time, or by anyone after the expiration, no transfer is carried out and the amount is available again for the payer.

The corresponding PR can be found here: https://github.com/ethereum/EIPs/pull/1996

**Comment by radeksvarz** [comment]
This EIP is stagnant - did the implementation get any traction?

**Comment by Pandapip1** [comment]
> This EIP is stagnant - did the implementation get any traction?

Stagnant EIPs are EIPs where the authors went AWOL. If you would like to champion the EIP, you can submit a PR adding yourself as an author.

**Comment by radeksvarz** [comment]
Thanks for the reply - I am not interested to champion that, however would like to have the place for long term on going discussion.

The discussion link from EIP page directs here (and not to https://ethereum-magicians.org/ ).

That confuses when someone wants to consider all possible ERC20 extensions.

PS - this is very common as I went through tens of EIP standards - would like to see a common approach on the discussions wrt stagnant EIPs.
