### ISSUE TITLE
ERC-2135: Consumable Interface

### ISSUE THREAD

**Issue by xinbenlv** [ethereum/EIPs#2135]
See latest version of full text at: 
- http://eips.ethereum.org/EIPS/eip-2135
- Work repo https://github.com/xinbenlv/eip-2135

**Comment by xinbenlv** [comment]
Adding a Open Zeppelin Draft at https://github.com/OpenZeppelin/openzeppelin-contracts/pull/1838

**Comment by Swiffers** [comment]
Are there any "Consumable NFT" ERC widely used ?

**Comment by xinbenlv** [comment]
Not that I have been seen yet. But event tickets should be one of the main
case when NFT can be transferred and consumed

**Comment by MicahZoltu** [comment]
Closing this for housekeeping purposes. Feel free to continue using this issue for discussion about EIP-2135.

Note: If 2135 is moved to review, the discussions-to link should be moved to a thread on Ethereum Magicians.
