### ISSUE TITLE
Opcode proposal: CREATE_INSTANCE

### ISSUE THREAD

**Issue by tawaren** [ethereum/EIPs#218]
# Proposal
I propose a new opcode `CREATE_INSTANCE` which works as `CREATE` but instead of having two parameters to say where in the memory the code lies and what the size of the code is it has a parameter with an address pointing to another smart contract whichs code is used for the newly created smart contract. 

# Motivation 
If we currently want to have multiple instances of a smart contract (with their own storage each) of a certain kind we have two options:

- Option 1: We copy the code from somwhere into the memory before calling `CREATE`. The copy can be done per `CODECOPY` or `EXTCODECOPY`
- Option 2: We just create a stub contract which forwards all calls with `DELEGATECALL` to the contract containing the code.

Option 1 makes it expensive to create these instances, because each time we pay the gas costs for the whole code and there will be multiple unecessary copies of the same code in the blockchain. This makes it impracticall to create a lot of smart contracts dynamically, especially if the contracts have a large code base.
Option 2 is relatively cheap two create a new instance, if we can generatea generic forwarder without reimplementing the complete ABI of the target contract, this can be done by passing as an additional parameter the expected return size. The drawback of this solution is, that calls into these smart contracts cost twice as much (for the call part not the actual execution) and increase the call stack by two elements instead of one.

The proposed opcode would have the benefit that the code only has to be stored once on the blockchain and could be used by different smart contracts without creating unecessary copies for it or using unecessary `DELEGATECALLS`. Additional it would be very cache friendly. Because of the additional lookup for the linked code a call to such a contract may still cost twice as much, but the additional call stack frame could be avoided and during thecreation of the contract would be much simpler, just one opcode instead of coping code around to prepare it in memory.

Especially standard contracts would benefit from that, like wallets or tokens.

**Comment by axic** [comment]
Please note that the code of a contract account is the runtime bytecode.

The `CREATE` opcode expects a "deployer bytecode". The deployer bytecode can do any state operations and whatever it will return using the `RETURN` opcode will become the code of the contract.

Additionally, the constructor code of contracts is part of this deployer together with the constructor parameters.

**Comment by tawaren** [comment]
A thanks for the clarification. I had their some missconceptions.
If I understand that right then the deployer code could in essence just do an `EXTCODECOPY` followed by a `RETURN` to create an instance of a contract. I assume that the cost of the `CREATE` would still depend on the size of the return and creating multiple instances of a large contract would still be very expensive and and forces multiple copies of the same code into the blockchain.

But now that my misconceptions how the `CREATE` opcode works are clarified this proposal does at least in the current form not make any sense, so I will close it. At least I have learned something more about the EVM wich will come in handy in the project I planned.
