### ISSUE TITLE
Ethereum Symmetric Key Agreement

### ISSUE THREAD

**Issue by inservice2t** [ethereum/EIPs#2184]
Proposal: add a new JSON-RPC method to return a session key derived from the ECDH value computed with the combination of one Ethereum private key and one Ethereum public key.

Nonce management would be critical.  We could use an HKDF taking as input the ECDH value, an application ID, the nonces from two recent transactions that used each key, and a minor-nonce from the application.

Applications would retain the minor nonce in local storage, but would need to publish a new transaction to the blockchain (such as refreshing an ENS registration) whenever they are re-initialized, and wait for that transaction to clear, before attempting to generate session keys.

Potential applications include in-browser messaging apps supporting end-to-end encryption.  Each message could be encrypted with a fresh session key that could be recovered by the recipient and used for decryption.  Messages could be exchanged off-chain using whatever mechanism (like leaving them on a Tor hidden server) that would not need to be trusted.

Soliciting early feedback on the idea before writing the EIP; please let me know what has been done in this area already.

**Comment by xinbenlv** [comment]
Sounds like an interesting idea. 

Motivation-wise, can you elaborate why does this 
>Potential applications include in-browser messaging apps supporting end-to-end encryption.
have to be coupled with Ethereum?

**Comment by inservice2t** [comment]
> Sounds like an interesting idea.
> 
> Motivation-wise, can you elaborate why does this
> 
> > Potential applications include in-browser messaging apps supporting end-to-end encryption.
>
> have to be coupled with Ethereum?

Key distribution for e2e encryption is a hard problem.  Ethereum can solve part of the problem because it maintains a database of public key (hashes) that is widely distributed and replicated and validated.

The app is just an example; in general I think lots of apps will want a way to generate a session key that is tied to an Ethereum identity.  See also issue #130 (old but still open) which I think would be addressed by this proposal.

**Comment by xinbenlv** [comment]
Thanks for a quick response. That's nice.

Sounds good.  I will add a few preliminary research I quickly done

- EIP-1202 (#1202) will benefit from this proposal for *able to perform session-key encrypted `commit` vote in a PLCR situation*
- EIP-1484(#1484), EIP-1775(#1775) etc will benefit from being able to create *derived (per-session) identity* 

Or in general, it allows Dapps to perform 1-way or 2-way handshakes by exchanging session-based keys for signature or encryption.
