### ISSUE TITLE
Discussion: Consider Moving EIPs to Another Medium

### ISSUE THREAD

**Issue by ghost** [ethereum/EIPs#2187]
(early draft)

background: https://github.com/ethereum/EIPs/pull/2172#issuecomment-510238703

* The current medium (github) does not meet the requirements for effective (technical) document collaboration.

## Requirements

(requirements should be as neutral as possibly. First, agree on the requirements, then go on to the candidates)

### General

* No special technical knowledge necessary to contribute (e.g. just an account-creation)
* Transparency (each and every step can be seen, either directly or from an history-archive)

### Authoring

  * Basic Editor knowledge should be enough (usable by anyone)
  * Convenient(!) Functionality for Tables
  * Data-Import (e.g. automated population of tables based from different sources like db, other documents)
  * nice: diagramming 

### Comments/Edits

Comments/Edits/Discussions

  * should point to the origin in the document (e.g. from a sidebar)
  * Discussions should be threaded
  * Discussions/Comments/Edits should be solvable (disappear e.g. to archive, once solved)

### Work-Flow

* Ideally: contains a simple work-flow-engine
* Allows for roles and permissions (Owner, Editor, Commenters, ...)

### License / Costs

* Should have 0 costs for any contributor

### Github (current medium)

Weaknesses

* PR work-flow not adequate for non-techs
* PR work-flow can be annoying on documents (even for devs)
* Discussion has no threading, sub-threads, sub-issues
* Professional-Grade Documents not possible
* Tables and other complex information difficult (within markdown)
* ???

### Google Docs (free)

* To avoid to much theoretical talk: this can be actually be tried for a few EIPs, just to see how it works in practice. If it's bad -> move back.

### Other Free Tools

...

### Commercial Tools

* Professional-Grade Documents, build with Professional-Grade Processes
  * can have cost for the Ethereum Foundation
  * no cost for viewers / contributors

**Comment by xinbenlv** [comment]
Thanks for starting it. This will help. 

One minor style / format suggestion is instead of proposing what's required for new medium, can you include a list of what's actually pain.

For example

> Simple Document-Authoring-Tool, ideally WYSIWYG
For example that this one, I will argue that Markdown makes it much easier to publish across other consumption, and WYSIWYG gives it too much flexibility such as different font size etc. Therefore, without discussion on **what's pain**, it's hard for me to support or propose against a requirement.

my 2gWei.

**Comment by lazaridiscom** [comment]
> (early draft)

patience!

**Comment by gcolvin** [comment]
I really can't see the editorial process moving off of Github and Markdown at this point, despite their weaknesses.  But authors are free to discuss and maintain their own drafts anywhere they choose, using whatever tools they choose.  Editors are generally happy to help with the PRs, but anything that could make that easier would be a good thing.

**Comment by lazaridiscom** [comment]
> I really can't see

No worries, many blind folks in the eth domain.

Focus on this for now

> First, agree on the requirements,

**Comment by xinbenlv** [comment]
Given the proposal account is deleted and lack completion, shall we consider this issue closed? The proposer can always revive if not the case.

**Comment by kevinsimper** [comment]
@xinbenlv I think we should :)

**Comment by xinbenlv** [comment]
Request close the issue. 
Ground: lack of activity, proposer account deleted, no further support.
