### ISSUE TITLE
Truffle is broken, I've checked out the blog but can't make anything work including a fresh install

### ISSUE THREAD

**Issue by jeffanthony** [ethereum/EIPs#219]
laptop@laptop-HP-Compaq-6730b-KS181UT-ABA:~/truffle$ sudo npm install truffle -g 
npm WARN deprecated libp2p-ipfs@0.15.0: Renamed to libp2p-ipfs-nodejs
npm WARN deprecated base-x@2.0.4: use base-x@v2.0.5
ls
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
/usr/local/bin/truffle -> /usr/local/lib/node_modules/truffle/cli.js
/usr/local/bin/truffle-exec -> /usr/local/lib/node_modules/truffle/exec.js
/usr/local/lib
└─┬ truffle@3.1.1 
  ├─┬ ethpm@0.0.9
  │ └─┬ ipfs@0.18.0
  │   └─┬ peer-id@0.8.2
  │     └─┬ libp2p-crypto@0.8.5
  │       └── webcrypto-shim@0.1.1  (git://github.com/dignifiedquire/webcrypto-shim.git#effe03d3401ccbfb4837191bc393bb347e0c0f0a)
  ├─┬ ethpm-registry@0.0.8
  │ ├─┬ solidity-sha3@0.4.1
  │ │ └─┬ web3@0.16.0
  │ │   └── bignumber.js@2.0.7  (git+https://github.com/debris/bignumber.js.git#94d7146671b9719e00a09c29b01a691bc85048c2)
  │ └─┬ web3@0.18.2
  │   └── bignumber.js@2.0.7  (git+https://github.com/debris/bignumber.js.git#94d7146671b9719e00a09c29b01a691bc85048c2)
  ├─┬ truffle-contract@1.1.10
  │ └─┬ web3@0.16.0
  │   └── bignumber.js@2.0.7  (git+https://github.com/debris/bignumber.js.git#94d7146671b9719e00a09c29b01a691bc85048c2)
  └─┬ web3@0.18.0
    └── bignumber.js@2.0.7  (git+https://github.com/debris/bignumber.js.git#94d7146671b9719e00a09c29b01a691bc85048c2)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/truffle/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
laptop@laptop-HP-Compaq-6730b-KS181UT-ABA:~/truffle$ sulssudo npm install truffle -g
sulssudo: command not found
laptop@laptop-HP-Compaq-6730b-KS181UT-ABA:~/truffle$ ls
laptop@laptop-HP-Compaq-6730b-KS181UT-ABA:~/truffle$ truffle init
Downloading project...
Project initialized.

  Documentation: http://truffleframework.com/docs

Commands:

  Compile: truffle compile
  Migrate: truffle migrate
  Test:    truffle test

laptop@laptop-HP-Compaq-6730b-KS181UT-ABA:~/truffle$ truffle compile
/usr/local/lib/node_modules/truffle/node_modules/truffle-compile/profiler.js:204
            dependency_path = source.resolve_dependency_path(import_path, dependency_path);
                                    ^

TypeError: Cannot read property 'resolve_dependency_path' of undefined
    at /usr/local/lib/node_modules/truffle/node_modules/truffle-compile/profiler.js:204:37
    at Array.map (native)
    at /usr/local/lib/node_modules/truffle/node_modules/truffle-compile/profiler.js:201:27
    at /usr/local/lib/node_modules/truffle/node_modules/truffle-resolver/index.js:77:5
    at /usr/local/lib/node_modules/truffle/node_modules/truffle-resolver/node_modules/async/internal/onlyOnce.js:12:16
    at /usr/local/lib/node_modules/truffle/node_modules/truffle-resolver/node_modules/async/whilst.js:63:18
    at apply (/usr/local/lib/node_modules/truffle/node_modules/lodash/_apply.js:15:25)
    at /usr/local/lib/node_modules/truffle/node_modules/lodash/_overRest.js:32:12
    at /usr/local/lib/node_modules/truffle/node_modules/truffle-resolver/index.js:62:7
    at /usr/local/lib/node_modules/truffle/node_modules/truffle-resolver/fs.js:41:12
    at tryToString (fs.js:455:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)

**Comment by cdetrio** [comment]
Try getting help at the [truffle repo](https://github.com/ConsenSys/truffle).
