### ISSUE TITLE
ERC-2193: dType Alias Extension - Decentralized Type System

### ISSUE THREAD

**Issue by loredanacirstea** [ethereum/EIPs#2192]
Discussion issue for https://github.com/ethereum/EIPs/pull/2193

**Comment by xinbenlv** [comment]
Repo maintenance suggestion:
* +label: `type:ERC`

**Comment by loredanacirstea** [comment]
Posting questions that arose in discussions on other mediums:

from @Arachnid
> - How would you do an address lookup for sending someone ether in dtype?
> - What prevents squatters from just grabbing popular names on the types that are most widely used?
> - Does this imply no portability? When I switch from Gnosis to Status for my wallet, do I have to tell everyone to use a new name?

from @makoto

> If I understand correctly, in ENS, once I own matoken.eth, I can own all types (contenthash,address,text, etc), whereas in dtype, I have to take them one by one (eg: md.matoken, addr.matoken, text.matoknen). 
> I think this is good and bad. Sure, squatters have to spend a lot to squat on all types for my name, but in reality all squatters have to do is to squat on addr.matoken which would be the most popular data type.
> From name ownership perspective, it's easy to attack (just squat on one type) but very hard to defend (own every sing type of my name).
