### ISSUE TITLE
EIP-684 is missing from the repository

### ISSUE THREAD

**Issue by GregTheGreek** [ethereum/EIPs#2220]
I'm going to refer to [this](https://github.com/ethereum/EIPs/issues/684) issue as EIP-684.

I've noticed that both Geth and Parity by default enable EIP-684, which is a consensus breaking change by default. EIP-684 was opened as an issue by Vitalik and promptly used as a patch 2 years ago, with no accompanying EIP.

Since this is in-fact a consensus breaking issue, we should have it documented as a valid EIP.

**Comment by RenanSouza2** [comment]
PR documenting this missing EIP https://github.com/ethereum/EIPs/pull/6784
