### ISSUE TITLE
EIP-1898: Precedence not specified for conflicting values

### ISSUE THREAD

**Issue by ryanschneider** [ethereum/EIPs#2247]
As discussed here: https://github.com/ethereum/go-ethereum/pull/19491#discussion_r315430283 the current version of the EIP does not specify how clients should behave if an object with both `blockNumber` and `blockHash` fields is sent as the block specifier.

In my opinion we have 4 options:

I see four options:

- Option 1: Block Number takes priority
- Option 2: Block Hash takes priority
- Option 3: If both blockNumber and blockHash are specified, return an error indicating these values are exclusive
- Option 4: If both blockNumber and blockHash are specified, enforce that both values are correct, otherwise return an error (i.e. lookup by hash, and return an error if returned header.Number != blockNumber).

I'm open to feedback on any of these options, but myself would lean towards Option 3 or 4.

**Comment by charles-cooper** [comment]
If I didn't include it in the spec, my mistake. My intention was to follow EIP 234, whatever it does.

**Comment by ryanschneider** [comment]
FWIW EIP-234 makes the number and hash options mutually exclusive (so Option 3).  I'm fine with that.
