### ISSUE TITLE
EIP-2270: Generate Ethereum account from Digital ID

### ISSUE THREAD

**Issue by ramvi** [ethereum/EIPs#2270]
```
eip: 2270
title: Generate Ethereum account from Digital ID
author: Jon Ramvi <jon@blockchangers.com>
status: Draft
type: Standards Track
category Core
created: 2019-09-09
```

## Simple Summary
Generation of Ethereum accounts from solutions for personal electronic ID for secure identification (Digital ID). This is one solution for solving recoverability. 

## Abstract
Many countries offer Digital ID to their citizens. Sweden and Norway have BankID. Denmark has NEM ID, Finland has TUPAS, the Netherlands has DigiD and Estonia has a Digital ID. These solutions are OpenID Connect (OIDC) implementations returning

1. true if the user is who she claims to be
2. some data fields about the user

This standard is a proposal for what goes into generating a seed for an Ethereum account so that it 

1. is recoverable 
2. has a high enough entropy to be secure

By adding together a mixture of parameters the seed should only be recoverable by the user, and no third party.

## Motivation
Many people are afraid of losing their mnemonic key. Having an Ethereum account connected to your Digital ID makes it so that you can always recover your funds.

## Specification

Do a sha256 of 3 parameters concatenated:
* The the Digital ID GUID e.g. `sub` for BankID Norway [something only the digital ID provider knows]
* Take the user's social security number [not really confidential, but not always known and adds to the seed's entropy]
* Take a user-generated password [something only the users knows]

Seed = `sha256([sub][ssn][password])`

This can be used directly as an Ethereum private key

### Increased security

Many of the Digital ID providers also provide signing. Send the Seed for signing with the Digital ID and use the returned data as the Ethereum key.

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by BrJu** [comment]
My 2 cents on this:
- On 1st case: UID and SS number being considered as public, this is the same as using the password with some public salt. With respect to guessing attack, the password is really a weak point
- on 2nd case: it has some advantages (leveraging the authentication to your digital ID provider to get access to the signing function) but means also that you trust your ID provider while providing the seed for being signed. Additionally a signature is not necessarily deterministic (it won't be the case for the common schemes, e.g. default version of ECDSA, DSA, RSA-PSS are not) so it might not work.

**Comment by PeterTheOne** [comment]
Have you considered using [PBKDF2](https://en.wikipedia.org/wiki/PBKDF2) with some more rounds instead of sha256?
