### ISSUE TITLE
(discussion) EIP-2280: erc-20 extension for native meta transactions support

### ISSUE THREAD

**Issue by mortimr** [ethereum/EIPs#2281]
This issue is meant to discuss the [EIP-2280](https://github.com/ethereum/EIPs/pull/2280).

**Comment by howy1993** [comment]
This def allows for better ux which is sorely needed. However rn gas deters overloading the network + puts a cost on spam. I assume with this design that dapps would have to either add 1. some internal rate-limiting system or 2. some other cost in not-ETH in their dapp to make it incentive compatible?

**Comment by mortimr** [comment]
@howy1993 
In this design, the incentive to relay is on the `gasPrice * gasLimit` and `reward` delta. 
A smart relay network (or dapp relayer) would pick transactions with the highest delta, meaning that for lower ERC-20 fees, you should also seek the lowest possible `gasPrice * gasLimit` to increase the delta. The relayers entity can publicly refuse meta-txs with low deltas.

I think It's easier and cheaper to overload the network without this protocol. And yes, dapps can set limits too.

**Comment by Nguyentiensy99** [comment]
Tôi là người Việt Nam liệu nó có thể thay đổi cuộc sống của tôi ,tôi không biết làm gì khi nó xảy ra ,chỉ là 1 nông dân ham học hỏi muốn thay đổi ,kết bạn mong các bạn giúp đỡ chân thành cảm ơn .tên tôi là nguyễn tiến sỹ chào các bạn
