### ISSUE TITLE
ERC 2307: Store data by logging to reduce gas cost

### ISSUE THREAD

**Issue by tak1827** [ethereum/EIPs#2307]
```
eip: <to be assigned>
title: Store data by logging for saving gas cost
author: tak <re795h@gmail.com>
status: Draft
type: Standards Track
category: ERC
created: 2019-10-06
```

# Simple Summary
Store data on a distributed storage, like IPFS.  Then store just the reference, like IPFS hash, to Ethereum by logging.

# Motivation
We will face two issues for using Ethereum as public ledger.
The fist issue is gas cost. Storing data to the storage is the most expensive operation. (see [`SSTORE` gas cost](https://github.com/crytic/evm-opcodes)) The second issue is capacity. Event solidity seems [not have any data size limitation](https://www.reddit.com/r/ethereum/comments/3kgxlx/in_solidity_does_bytes_have_a_maximum_length/), we restricted by gas limit.

So, current Ethereum is not suitable for large date or frequent storing.

# Specification
Store data on distributed storage, like IPFS. IPFS don't have any data size limitation. Then, store the hash to Ethereum for data integrity. IPFS hash is really small so that this contribute saving gas cost. This is the most likely taken solution. Etherum famous projects, like [Origin Protocol](https://github.com/OriginProtocol/origin/blob/master/packages/contracts/contracts/marketplace/V01_Marketplace.sol) or [Openlaw](https://media.consensys.net/introducing-openlaw-7a2ea410138b) are doing.

For reducing gas cost further, we propose to store data by event emission. Logging is enough, unless you delete data or operate data from a smart contract.

### Recorded
- eventSig is the first 4 bytes of the Keccak256 hash of event name
- createdAt is the the recorded time.
- ipfsHash is base58 decoeded IPFS hash
```solidity
event Recorded (bytes4 indexed eventSig, uint256 indexed createdAt, bytes32 ipfsHash);
```
Further Explanation: [Store data in Ethereum by logging to reduce gas cost](https://medium.com/@t.tak/store-data-in-ethereum-by-logging-to-reduce-gas-cost-b70a13884485)

# Implementation
```solidity
import 'openzeppelin-solidity/contracts/access/roles/WhitelistAdminRole.sol';

event Recorded (bytes4 indexed eventSig, uint256 indexed createdAt, bytes32 ipfsHash);

/**
 * @dev Write ipfsHash as log
 */
function writeHash(bytes4 _eventSig, bytes32 _ipfsHash) public onlyWhitelistAdmin {
    emit Recorded(_eventSig, uint256(now), _ipfsHash);
}
```

# Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by cryptogiddi** [comment]
what are your thoughts on storing data on Ethereum using hashes

**Comment by tak1827** [comment]
We can store variety of data.

### Case1. Certification
The certification hash stored on Ethereum never be changed so we can verify certification integrity. It's publicly available any time as long as the certification issuer operate IPFS node.

### Case2. Copyright
Similarly, we can verify the integrity of a copyright publicly.

### Case3. Token
We can invent ERC20 like token protocol on top of this.

For example, we define `eventSig` as concatenation of token name and function  
```
eventSig => First 4 bytes of Keccak256("token_name:transferFrom")
```

Then, we put other informations(from, to, value) to IPFS
```
{
  from: 0x825bBB7fdD9292ba18913c1E784D839DbEF82BbB
  to: 0x49Cb60853D1a527995F6CB784e9641bb408dBb51
  value: 10000000
}
```
