### ISSUE TITLE
ERC-2309: ERC-721 Consecutive Transfer Extension

### ISSUE THREAD

**Issue by pizzarob** [ethereum/EIPs#2309]
### **NOTE: This has been merged and is in Draft status. Please review https://github.com/ethereum/EIPs/blob/master/EIPS/eip-2309.md before commenting** 

Hi there. I'd like to get a feel from the community about a new extension for the ERC-721 standard. 

**TLDR**: I'm proposing a batch mint extension that includes a standardized event which supports the creation and transfer of many  tokens at one time. I am not proposing how to implement a batch creation or batch transfer function, only the `BatchTransfer` event which would emitted when a group of tokens is created or transferred. 

---

ERC-721 has great potential to create a digital representation for any unique asset in this world. New markets and jobs can be created with ideas that stem from creating digital representations of unique assets - either tangible, or digital. However, in its current form the ERC-721 standard is not scalable. Take this example: 

I sell lemons and have a farm with 10,000 lemon trees. I want to turn each lemon tree into a non-fungible token that people can own. Each person that owns one of my non-fungible lemon tokens will receive a quarterly percentage of each sale. The problem is that I would need to create each of these tokens individually - which will cost me a lot of TIME and MONEY. Wouldn't it be easier to mint 10,000 non-fungible lemon tokens at once while adhering to the ERC-721 standard? I think so. 

```solidity
pragma solidity ^0.5.10;

/**
  @title ERC-2309: ERC-721 Batch Mint Extension
  @dev https://github.com/ethereum/EIPs/issues/2309
 */

interface ERC721BatchMint /* is ERC721 */ {
  /**
    @notice This event is emitted when ownership of a batch of tokens changes by any mechanism.
    This includes minting, transferring, and burning.

    @dev The address executing the transaction MUST own all the tokens within the range of
    fromTokenId and toTokenId, or MUST be an approved operator to act on the owners behalf.
    The fromTokenId and toTokenId MUST be a sequential range of tokens IDs.
    When minting/creating tokens, the `fromAddress` argument MUST be set to `0x0` (i.e. zero address).
    When burning/destroying tokens, the `toAddress` argument MUST be set to `0x0` (i.e. zero address).

    @param fromTokenId The token ID that begins the batch of tokens being transferred
    @param toTokenId The token ID that ends the batch of tokens being transferred
    @param fromAddress The address transferring ownership of the specified range of tokens
    @param toAddress The address receiving ownership of the specified range of tokens.
  */
  event BatchTransfer(uint indexed fromTokenId, uint toTokenId, address indexed fromAddress, address indexed toAddress);
}
```

**Comment by pizza-r0b** [comment]
I will also point out that it's possible to create 2^255 NFTs at one time however it's not possible to emit that many Transfer events which are part of the original spec. Creating many tokens at once can be done using efficient data structures, however the original Transfer event keeps us locked into O(n) time.

**Comment by wighawag** [comment]
Nice,
I was thinking to propose something along these lines too.

The problem I see is that there is no retro-compatibility:

Wallet supporting ERC-721 but not ERC-2309 will not be aware of the token minted this way.
If this event is used for Transfer (see my comments below), then these wallets will also fails to track ownership changes.

I guess there is no way around but though important to mention it.

Regarding Transfers:
I don't think these should be considered.
I would rename BatchTransfer to BatchMint and would remove the `fromAddress` parameter
Because while it is indeed possible to implement a transfer method that transfer token if specified in consecutive order, it is a pretty limited form of transfer that should not be a standard.
Batch Minting should be enough to create a huge amount of tokens (2^256-1 even) and a batch Transfer with tokenId array might let you do 3000 token transfer per block (did not tested, just a rough estimation)

But if this is really important for your use case, I would rename it ConsecutiveBatchTransfer to be more explicit about its limitations.

**Comment by pizza-r0b** [comment]
Good points @wighawag. Yeah unfortunately platforms/wallets would need to update to support the new event. Like you said, no way around it. It seems that either you will have to support a new standard, or a new event. Eventually the platform or wallet will need to update.

I like ConsecutiveBatchTransfer. I will update to that. A token ID array would work for a lot of cases, but I think a consecutive batch transfer method has its place as the array will eventually fail. Not to mention you could complete a batch transfer in constant time rather than O(n) with that array. 

Thanks for the comments.

**Comment by pizza-r0b** [comment]
I think `ConsecutiveTransfer` covers it

**Comment by pizza-r0b** [comment]
Updated in https://github.com/ethereum/EIPs/pull/2310

**Comment by pizza-r0b** [comment]
Closing this issue. Future discussion should be made in #2310

**Comment by pizza-r0b** [comment]
I think the standard should state that when emitting the `ConsecutiveTransfer` event the `Transfer` event should NOT be emitted. This can lead to bugs when using these events to determine token ownership and would require unnecessary complicated logic.

**Comment by pizza-r0b** [comment]
^ added in https://github.com/ethereum/EIPs/pull/2522

**Comment by pizzarob** [comment]
Added backwards compatibility in https://github.com/ethereum/EIPs/pull/2717/files

**Comment by pizzarob** [comment]
Merged as final please re-open if this should be left open.

**Comment by MicahZoltu** [comment]
I believe discussions are intended to be left open... Though I'll ask around.

**Comment by arpu** [comment]
@pizzarob  is there any implementation guide for this?

**Comment by BotchM** [comment]
Some implementation examples would be helpful

**Comment by flockonus** [comment]
I understand how this EIP could be implemented for the **creation** of a range of NFTs, but how do you guarantee security on the transfer on a range of **existing items**?

Say in a contract there is a certain ownership of tokens:
```
id : owner
1: 0xAA
2: 0xAA
….
997: 0xAA
998: 0xFF (!)
999: 0xAA
```

Say `i` wants to makes an order to move 1 ... 999, how would the contract be able to verify that one item is incorrectly owned in this range and execute the transfer?

**Comment by fulldecent** [comment]
@flockonus That's an implementation detail. Please start your own implementation and ask questions on SE or elsewhere--feel free to ping me. 

But this EIP is final so GitHub Issues should not be the place to discuss implementations.

**Comment by froller** [comment]
Is there any canonical implementation of 2309?

**Comment by MadhvikNem** [comment]
Hey, I am really interested in talking to you about a opportunity, please let me know if you will be able to. 
You can send me a mail at madhviknem@gmail.com. 
Would love for you to get back to me.

**Comment by robzizo** [comment]
In comparing 2309 and 1155 contracts section the author points to undefined 2039 contract.

**Comment by Amxx** [comment]
I don't think the "sequence" is properly defined in the document. Is it `[fromTokenId, toTokenId[` or `[fromTokenId, toTokenId]`

In other words, would the equivalent loop be
```for (uin256 tokenId = fromTokenId; tokenId < toTokenId; ++tokenId) { ... }```
or
```for (uin256 tokenId = fromTokenId; tokenId <= toTokenId; ++tokenId) { ... }```

**Comment by TimTinkers** [comment]
I recently discovered this standard when my work-in-progress-NFT-marketplace's indexer failed to detect most of the items minted in the [GoonzSchoolPhotos](https://etherscan.io/address/0x36e5913bf48ccbd361875d09c0a20a4c144da896) collection, which emitted `ConsecutiveTransfer` events in its minting process.

I'd previously viewed the fact that ERC-721 and ERC-1155 could not mint an NFT without emitting an event for each unique token or (in the case of ERC-1155) type of token as a sort of backstop against denial-of-service attacks. If someone wanted to flood my indexer with bogus NFTs, they would need to at least pay proportional gas to do so.

Honoring EIP-2309 without limits feels impossible: for the gas cost of a single event, a collection could signal that it is minting a full `2^256 - 1` items. Conventionally, my marketplace would then try to collect the metadata for each newly-minted token that it sees. To prevent the `ConsecutiveTransfer` event from being abused to fill my metadata collection queue with `2^256 - 1` pending calls, the only reasonable solution I see is for a marketplace to truncate overly-large token ID ranges.

**Comment by Nate158digimon** [comment]
`/* CSS3_ style sheet for the output of Docutils HTML5 writer.  */
/* Generic responsive design for all screen sizes.                         */
/*                                                                         */
/* :Author: Gรผnter Milde                                                   */
/*                                                                         */
/* :Id: $Id: responsive.css 9079 2022-06-19 14:00:56Z milde $                                                               */
/* :Copyright: ยฉ 2021 Gรผnter Milde.                                        */
/* :License: Released under the terms of the `2-Clause BSD license`_,      */
/*    in short:                                                            */
/*                                                                         */
/*    Copying and distribution of this file, with or without modification, */
/*    are permitted in any medium without royalty provided the copyright   */
/*    notice and this notice are preserved.                                */
/*                                                                         */
/*    This file is offered as-is, without any warranty.                    */
/*                                                                         */
/* .. _2-Clause BSD license: http://www.spdx.org/licenses/BSD-2-Clause     */
/* .. _CSS3: https://www.w3.org/Style/CSS/                                 */

/* Note:     								   */
/* This style sheet is provisional:					   */
/* the API is not settled and may change with any minor Docutils version.  */



/* General Settings */
/* ================ */


* { box-sizing: border-box; }

body {
  background-color: #fafaf6;
  margin: auto;
  --field-indent: 6.6em; /* indent of fields in field lists */
  --sidebar-margin-right: 0; /* adapted in media queries below */
}
main {
  counter-reset: figure table;
}
body > * {
  background-color: white;
  line-height: 1.6;
  padding: 0.5rem calc(29% - 7.2rem); /* go from 5% to 15% (8.15em/54em) */
  margin: auto;
  max-width: 100rem;
}
sup, sub { /* avoid additional inter-line space for lines with sup/sub */
  line-height: 1;
}

/* Vertical Space (Parskip) */
p, ol, ul, dl, li,
div.line-block,
.topic,
.footnote, .citation,
div > math,
table {
  margin-top: 0.5em;
  margin-bottom: 0.5em;
}
h1, h2, h3, h4, h5, h6,
dl > dd, details > p:last-child {
  margin-bottom: 0.5em;
}

/* Indented Blocks */
blockquote, figure, .topic {
  margin: 1em 2%;
  padding-left: 1em;
}
div.line-block div.line-block,
pre, dd, dl.option-list {
  margin-left: calc(2% + 1em);
}

/* Object styling */
/* ============== */

footer, header {
  font-size: small;
}

/* Frontmatter */
div.dedication {
  padding: 0;
  margin: 1.4em 0;
  font-style: italic;
  font-size: large;
}
.dedication p.topic-title {
  display: none;
}

blockquote p.attribution,
.topic p.attribution {
  text-align: right;
}

/* Table of Contents */
nav.contents ul {
  padding-left: 1em;
}
ul.auto-toc > li > p { /* hanging indent */
  padding-left: 1em;
  text-indent: -1em;
}
main > nav.contents  ul:not(.auto-toc) {
  list-style-type: square;
}
main > nav.contents  ul ul:not(.auto-toc) {
  list-style-type: disc;
}
main > nav.contents  ul ul ul:not(.auto-toc) {
  list-style-type: '\2B29\ ';
}
main > nav.contents  ul ul ul ul:not(.auto-toc) {
  list-style-type: '\2B1D\ ';
}
main > nav.contents  ul ul ul ul ul:not(.auto-toc) {
  list-style-type: '\2B2A\ ';
}
nav.contents ul > li::marker { ` > ` ` - ` ` ` 
  color: grey;
}

/* Transitions */
hr {
  margin: 1em 10%;
}

/* Lists */

ul, ol {
  padding-left: 1.1em; /* indent by bullet width (Firefox, DejaVu fonts) */
}
dl.field-list > dd,
dl.docinfo > dd {
  margin-left: var(--field-indent); /* adapted in media queries or HTML */
}
dl.option-list > dd {
  margin-left: 20%;
}
/* run-in: start field-body on same line after long field names */
dl.field-list.run-in > dd p {
  display: block;
}
/* "description style" like in most dictionaries, encyclopedias etc. */
dl.description {
  display: flow-root;
}
dl.description > dt {
  clear: left;
  float: left;
  margin: 0;
  padding: 0;
  padding-right: 0.3em;
  font-weight: bold;
}
dl.description > dd:after {
  display: table;
  content: "";
  clear: left; /* clearfix for empty descriptions */
}
/* start lists nested in description/field lists on new line */
dd > dl:first-child,
dd > ul:first-child,
dd > ol:first-child {
  clear: left;
}

/* disclosures */
details { padding-left: 1em; }
summary { margin-left: -1em; }

/* Footnotes and Citations */
.footnote {
  font-size: small;
}

/* Images, Figures, and Tables */
img {
  display: block;
}
p > img, p > a > img,
figure > img, figure > a > img {
  display: inline;
}

figcaption,
table > caption {
  /*   font-size: small; */
  font-style: italic;
}
figcaption > .legend {
  font-size: small;
  font-style: initial;
}
figure.numbered > figcaption > p:before {
  counter-increment: figure;
  content: "Figure " counter(figure) ": ";
  font-weight: bold;
  font-style: initial;
}

table tr {
  text-align: left;
  vertical-align: baseline;
}
table.booktabs { /* "booktabs" style (no vertical lines) */
  border-top: 2px solid;
  border-bottom: 2px solid;
}
table.booktabs * {
  border: 0;
}
table.booktabs th {
  border-bottom: thin solid;
}
table.numbered > caption:before {
  counter-increment: table;
  content: "Table " counter(table) ": ";
  font-weight: bold;
  font-style: initial;
}

/* Admonitions and System Messages */
.admonition,
div.system-message {
  border: thin solid silver;
  margin: 1em 2%;
  padding: 0.5em 1em;
}
.caution p.admonition-title,
.attention p.admonition-title,
.danger p.admonition-title,
.warning p.admonition-title,
div.error {
  color: maroon;
}
div.system-message > p > span.literal {
  overflow-wrap: break-word;
}

/* Literal and Code */
pre.literal-block, pre.doctest{
  padding: 0.2em;
  overflow-x: auto;
}
.literal-block, .doctest, span.literal {
  background-color: #f6f9f8;
}
.system-message span.literal {
  background-color: inherit;
}

/* basic highlighting: for a complete scheme, see */
/* https://docutils.sourceforge.io/sandbox/stylesheets/ */
pre.code .comment, code .comment { color: #5C6576 }
pre.code .keyword, code .keyword { color: #3B0D06; font-weight: bold }
pre.code .literal.string, code .literal.string { color: #0C5404 }
pre.code .name.builtin, code .name.builtin { color: #352B84 }
pre.code .deleted, code .deleted { background-color: #DEB0A1}
pre.code .inserted, code .inserted { background-color: #A3D289}

/* Hyperlink References */
a {
  text-decoration: none; /* for chromium */
  /* Wrap links at any place, if this is the only way to prevent overflow */
  overflow-wrap: break-word;
}
.contents a, a.toc-backref, a.citation-reference {
  overflow-wrap: inherit;
}
/* Undecorated Links (see also minimal.css) */
/* a.citation-reference, */
.citation a.fn-backref {
  color: inherit;
}
a:hover {
  text-decoration: underline;
}
*:hover > a.toc-backref:after {
  content: " \2191"; /* โ‘ UPWARDS ARROW */
  color: grey;
}
*:hover > a.self-link:after {
  content: "\1F517"; /* LINK SYMBOL */
  color: grey;
  font-size: smaller;
  margin-left: 0.2em;
}
/* highlight the target of the current URL */
section:target > h2, section:target > h3, section:target > h4,
section:target > h5, section:target > h6,
.contents :target,
.contents:target > .topic-title,
[role="doc-biblioentry"]:target > .label,
[role="doc-biblioref"]:target,
[role="note"]:target, /* Docutils 0.18 ... 0.19 */
[role="doc-footnote"]:target, /* Docutils >= 0.20 */
[role="doc-noteref"]:target {
  background-color: #d2e6ec;
}

/* Block Alignment */
/* Let content flow to the side of aligned images and figures */

/* no floats around this elements */
footer, header, hr,
h1, h2, h3 {
  clear: both;
}

img.align-left,
video.align-left,
figure.align-left,
table.align-left {
  margin-left: 0;
  padding-left: 0;
  margin-right: 0.5em;
  clear: left;
  float: left;
}
img.align-right,
video.align-right,
figure.align-right,
table.align-right {
  margin-left: 0.5em;
  margin-right: 0;
  clear: right;
  float: right;
}

/* Margin Elements */
/* see below for screen size dependent rules */
.sidebar,
.marginal,
.admonition.marginal {
  max-width: 40%;
  border: none;
  background-color: #efefea;
  margin: 0.5em var(--sidebar-margin-right) 0.5em 1em;
  padding: 0.5em;
  padding-left: 0.7em;
  clear: right;
  float: right;
  font-size: small;
}
.sidebar {
  width: 40%;
}

/* Math */
/* for math-output=MathML (for math-output=HTML, see math.css) */
math .boldsymbol {
  font-weight: bold;
}
mstyle.mathscr, mi.mathscr {
  font-family: STIX;
}

/* Adaptive page layout */
/* ==================== */

@media (max-width: 30em) {
  /* Smaller margins and no floating elements for small screens */
  /* (main text less than 40 characters/line) */
  body > * {
    padding: 0.5rem 5%;
    line-height: 1.4
  }
  .sidebar,
  .marginal,
  .admonition.marginal {
    width: auto;
    max-width: 100%;
    float: none;
  }
  dl.option-list,
  pre {
    margin-left: 0;
  }
  body {
    --field-indent: 4em;
  }
  dl.field-list.narrow, dl.docinfo, dl.option-list {
    --field-indent: 2.4em;
  }
  pre, pre * {
  font-size: 0.9em;
  /* overflow: auto; */
  }
}

@media (min-width: 54em) {
  /* Move ToC to the left */
  /* Main text width before: 70% โ 35em โ 75โ€ฆ95 chrs (Dejavu/Times) */
  /*                  after:      โณ 30em โ 54โ€ฆ70 chrs (Dejavu/Times) */
  body.with-toc {
    padding-left: 8%;
  }
  body.with-toc > * {
    margin-left: 0;
    padding-left: 22rem; /* fallback for webkit */
    padding-left: min(22%, 22rem);
    padding-right: 7%;
  }
  main > nav.contents { /* global ToC */
    position: fixed;
    top: 0;
    left: 0;
    width: min(25%, 25em);
    height: 100vh;
    margin: 0;
    background-color: #fafaf6;
    padding: 1em 2% 0 2%;
    overflow: auto;
  }
  main > nav.contents > * {
    padding-left: 0;
    line-height: 1.4;
  }
  main > nav.contents a {
  color: inherit;
  }
}

@media (min-width: 70em) {
  body {
    --field-indent: 9em;
  }
}

@media (min-width: 77em) {
  /* Move marginalia to 6rem from right border       */
  /* .sidebar,                                       */
  /* .marginal,                                      */
  /* .admonition.marginal {                          */
  /*   margin-right: calc(6rem - 15%);               */
  /* }                                               */
  /* BUG: margin is calculated for break point width */
  /* workaround: variable + many breakpoints         */
  body > * {
    padding-left: 18%;
    padding-right: 28%; /* fallback for webkit */
    padding-right: min(28%, 28rem);
    --sidebar-margin-right: -20rem;
  }
  /* limit main text to ~ 50em โ 85โ€ฆ100 characters DejaVu rsp. โ€ฆ120 Times */
  body.with-toc > * {
    padding-left: min(22%, 22rem);
    padding-right: calc(78% - 50rem); /* fallback for webkit */
    padding-right: min(78% - 50rem, 28rem);
    --sidebar-margin-right: 0;
  }
}

@media (min-width: 85em) {
  body.with-toc > * {
    --sidebar-margin-right: -9rem;
  }
}

@media (min-width: 90em) {
  /* move marginalia into the margin */
  body > * {
    padding-left: min(22%, 22rem);
    --sidebar-margin-right: -23rem;
  }
  body.with-toc > * {
    --sidebar-margin-right: -14rem;
  }
}

@media (min-width: 99em) {
  /* move marginalia out of main text area */
  body.with-toc > * {
    --sidebar-margin-right: -20rem;
  }
  body > *, body.with-toc > * { /* for webkit */
    padding-left: 22rem;
    padding-right: 28rem;
  }
  .admonition.marginal,
  .marginal {
    width: 40%; /* make marginal figures, ... "full width" */
  }
}

@media (min-width: 104em) {
  body.with-toc > * {
    --sidebar-margin-right: -23rem;
  }
}`

**Comment by gatedude** [comment]
@pizzarob hey Bro, saw the post about the Bankr X account getting hacked.

Tagging Nikita or X isn't going to help tbh. Nikita gets plenty of tags and messages, he probably won't see it on X. You need to reach out to Nikita via email and the specific security department at X.

I might be able to help you reach out to them. I also emailed you, dunno if that's the correct email address but please check your email. I can help you!

**Comment by Lolo19p4** [comment]
Bonjour, quelle aide vous voulez faire?

Le lun. 27 juil. 2026, 02:47, David Davidson ***@***.***> a
écrit :
