### ISSUE TITLE
Draft EIP: BLS12-381 Deterministic Account Hierarchy

### ISSUE THREAD

**Issue by CarlBeek** [ethereum/EIPs#2338]
Discussion for Draft EIP-XXXX: BLS12-381 Deterministic Account Hierarchy #2334.

This is the proposed standard for BLS12-381 Deterministic Account Hierarchy (Account Paths) for use within Eth2 as well as by the larger blockchain industry. Please be considerate of the implications of this standard in both the Eth2 and wider contexts.

**Comment by mcdee** [comment]
I'm wondering if we should have a new coin type for Ethereum 2.

This does play in to 2334 a little, although given the different purpose it is possible for someone to differentiate between Ethereum and Ethereum 2 keys.  But there are other systems out there that use coin type as the sole differentiator, for example ENS' multicoin address lookup.

I don't think there are any real downsides to having a new coin type, and given keeping the same coin type will definitely cause some issues I think a new coin type might be the safe option.  Thoughts?

**Comment by mariano54** [comment]
We are planning to support this format as well as EIP-2333 for Chia. I was wondering how finalized these specs were and if there are still changes to be made.

**Comment by MicahZoltu** [comment]
I recommend modifying this to follow EIP-600, which defines how Ethereum HD Wallet derivation paths should be laid out.  If BLS12-381 HD wallets don't have a concept of hardened and non-hardened then we can probably just ignore the hardening of the path?

**Comment by MicahZoltu** [comment]
I should have read the motivation section before commenting 😬 

> The purpose needs to be distinct from these standards as the KDF and path are not inter-compatible and 12381 is an obvious choice.

Can you expand on the argument as to why the same path cannot be used?  Is the idea that a user who has a mnemonic + derivation path would not need to *also* know what crypto algorithm is used?
