### ISSUE TITLE
Draft EIP: BLS12-381 Keystore

### ISSUE THREAD

**Issue by CarlBeek** [ethereum/EIPs#2339]
Discussion for Draft EIP-XXXX: BLS12-381 Keystore #2335.

This is the proposed standard for BLS12-381 Keystores for use within Eth2 as well as by the larger blockchain industry. Please be considerate of the implications of this standard in both the Eth2 and wider contexts.

**Comment by mcdee** [comment]
How about adding `pubkey` to the keystore?  This will allow programs to access information related to the keystore without needing the user to unlock the private key.

And a UX enhancement: add `name`.  This will give wallets a way of allowing users to access their keys with friendly names.

**Comment by mcdee** [comment]
The secret for your test cases is incorrect.  It should be `000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f`

**Comment by CarlBeek** [comment]
>How about adding pubkey to the keystore? 

I don't think we should go down this route. Eth1 keystores used to have `Address` fields, but they were removed because they compromised privacy and reduced security as a `PubKey` field reveals the value of each key. The idea is to identify a file by its UUID and if need be, 3rd party software can maintain a UUID -> PubKey map.

>And a UX enhancement: add name.

This is something I am more amenable to, I can definitely see the UX upside of having a `name`. The downsides are much the same as those listed above for storing PubKeys. I will think about this more.

>The secret for your test cases is incorrect.

Indeed, you are correct. The implementation was using a new test vector, I had not updated the EIP, apologies.

**Comment by mcdee** [comment]
> I don't think we should go down this route. Eth1 keystores used to have Address fields, but they were removed because they compromised privacy and reduced security as a PubKey field reveals the value of each key.

Just checked with `geth` and it still creates the `address` field when it creates new accounts.

Not providing public keys in the keystore forces users to unlock their keystore whenever they wish to access their public keys.  This, to me, seems like a much larger security issue than storing the public key and forces users who want to carry out read-style operations against their public keys to expose their private keys (note this would still have to happen if the mapping was maintained in 3rd-party software, at least once per key).

**Comment by CarlBeek** [comment]
Interesting. So the [Keystore definition explicitly states that addresses were removed](https://github.com/ethereum/wiki/wiki/Web3-Secret-Storage-Definition#alterations-from-version-1), but it seems like clients implement it as an optional feature anyway. [Geth](https://github.com/ethereum/go-ethereum/blob/32d35c9c088463efac49aeb0f3e6d48cfb373a40/accounts/keystore/key.go#L67), [Parity](https://github.com/paritytech/parity-ethereum/blob/master/accounts/ethstore/src/json/key_file.rs#L45), [Nethermind](https://github.com/NethermindEth/nethermind/blob/master/src/Nethermind/Nethermind.KeyStore/FileKeyStore.cs#L227).

**Comment by CarlBeek** [comment]
Based on the prevalence of `address` within Eth1 keystores, I have added a `pubkey` field to the keystores.

**Comment by paulmillr** [comment]
Hey folks -- why isn't this using aes-gcm256?

**Comment by paulhauner** [comment]
I have noticed that [RFC3686](https://tools.ietf.org/html/rfc3686) specifies an 8-octet/64-bit`IV` whilst the test vectors here use a 16-octet/128-bit `IV`.

I would be interested to know if this is intended and how we should handle `IV`s of varying length, please?

**Comment by djrtwo** [comment]
Is there anything in particular blocking #2335 from being merged?

**Comment by MysticRyuujin** [comment]
I'm going to poke this thread to request the inclusion of the name field as an optional, and unique, key.

**Comment by Raymer-quezada-Amparo-master** [comment]
> Discussion for Draft EIP-XXXX: BLS12-381 Keystore #2335.
> 
> This is the proposed standard for BLS12-381 Keystores for use within Eth2 as well as by the larger blockchain industry. Please be considerate of the implications of this standard in both the Eth2 and wider contexts.
> 

Ok do

**Comment by davnex** [comment]
#8256
