### ISSUE TITLE
Yellow Paper and Potential EIP Licensing Violation

### ISSUE THREAD

**Issue by sorpaas** [ethereum/EIPs#2343]
The current editors ask all authors to publish their EIPs under public domain. However, given that many EIPs have to reference yellow paper, which is licensed under CC-BY-SA, it simply means many EIPs cannot be published, or published EIPs commit a license violation:

> If you remix, transform, or build upon the material, you must distribute your contributions under the same license as the original. 

Part of the EIP might still be able to be public domain. However, those materials that built upon yellow paper must be published under the same license -- CC-BY-SA.

Compared with the practice in this repo, the ECIP repository is much more friendly to all types of [permissive licenses](https://github.com/ethereumclassic/ECIPs/blob/master/_specs/ecip-1000.md#ecip-licensing), which we may want to learn from.

Another solution is to ask Gavin, and all contributors to yellow paper, to re-publish it in public domain.

**Comment by MicahZoltu** [comment]
I would love to see the yellowpaper re-published under CC0.  That being said, I believe that referencing the yellowpaper or even including an excerpt from it in an EIP does not constitute a "derivative works", thus is not subject to the share alike clause of CC-BY-SA.

**Comment by raymonddurk** [comment]
This has been a long and well documented discussion with Gavin. I am not a lawyer but I don't see the issue.
