### ISSUE TITLE
Inclusion of network ID in consensus and exposure as Opcode allows hard-fork voting with economic commitment

### ISSUE THREAD

**Issue by barryWhiteHat** [ethereum/EIPs#235]
## Preamble
    EIP: <to be assigned>
    Title: <Inclusion of network ID in consensus and exposure as Opcode allows hard-fork voting with economic commitment>
    Author: <barryWhiteHat>
    Type: <Standard Track | Informational | Meta>
    Category (*only required for Standard Track): <Core | Networking | Interface | ERC> 
    Status: Draft
    Created: <date created on, in ISO 8601 (2017-03-23) format>
    Requires (*optional): <EIP number(s)>
    Replaces (*optional): <EIP number(s)>

## Simple Summary
The replay protection introduced `CHAIN\_ID` as part of the transaction format to prevent transaction replay across chains.

By including `CHAIN\_ID` in consensus and exposing it in byte code we can build better systems to manage contentious hard forks.

Where people sell their tokens on one side of a fork to buy tokens on the other side of the fork.

We do all this before the hard fork occurs and propose leveraging this mechanism to vote for hard fork activation in a way where a vote for one side of the chain sells your token on the other chain for tokens on the chain you voted for. 

This allows the market to settle on a price before a hard-fork. We note that so far hash rate has followed price. If we define the price of both chains before a hard-fork the hash rate should respond to that. 
 
## Abstract
Contentious Hard forks are difficult. Currently we rely in imperfect voting systems. Including the `CHAIN\_ID` variable in consensus and exposing it to smart contracts will allow us to build smart contracts that can trade tokens on future forks before the fork happens. Using this we can develop better governance that will allow stake holders to come to consensus before a hard fork happens.

## Motivation
Currently we use: 
1. Carbon voting (where actors vote proportional to amount of ETH they hold), 
2. Node voting (where actors vote proportional to number node they control),
3. Miner voting (where actors vote proportional to their hash power). 

A current proposal is user voting, a token is made by burning a percent of each TX and assigning that as the total that users burns as that users weight. This token is then used in voting. 

Carbon voting is flawed because someone can vote for a hard fork and then sell all their coins on the chain that they voted for. Also it over represents whales, effectively 10 keys control 25.86% of ether. 

Node voting has sybil problems. Miner voting is flawed because it over represents the stake holders that have access to cheap electricity. Also as we mentioned above hash power tends to follow price, miners have nothing at stake here. If a hard fork results in reduction in the price of Ether they will just start mining something else.

Each of the 4 methods mentioned above is effectively a token weighted vote, however some of the "tokens" do not exists on the ethereum block chain (Miner vote, Node voting). But a token could be implemented for these. 

In the future we may want to use other tokens to decide how a split will occurs. If someone builds a better ethereum based user token we will want to be able to decide hard forks based upon that. For example we would be very interested to see reddit karma or github commit token holders views on a contentious fork.

Thus it is important that we develop a method to use staked voting to active hard forks which includes token abstraction and economic commitment when voting. Including of the `network_id` in consensus and exposure to opcodes will allow this.

## Specification
When block.number >= FORK\_BLKNUM, include `network_id` in consensus and expose it as EVM opcode `netID`

## Rationale
We propose the inclusion of the networkID in the EVM and consensus methods as well as its exposure to a new opcode `netID`. This will allow smart contracts to be developed that follows the flow:

1. Proponents of ether side of the hard fork call `deposit(id)` where `id` is the id of the network they want to move their funds to. 
2. After the hard fork each user can withdraw (call `withdraw()`) their coins only on that chain. They also get a share of the coins that the other side of the hard fork deposited on that chain, proportaional to the number of coins they deposited. 

They basically trade coins on the forked and unforked chain with each other. 

This way everyone has more coins on the chain they support. And no coins on the chain they don't support. The precise mechanism of how these contracts will work is outside the scope of this EIP. But a simple solution is described below:

```
def deposit(uint id) {
    dep[owner].owner = msg.sender;
    dep[owner].value += msg.value;
    dep[owner].id = id;
    chainTotal[id] += msg.value;
    total += msg.value;
}

def withdraw(uint id) {
    uint withdraw = (dep[owner].value +  (total - chainTotal[id])
                     * (dep[owner].value/chainTotal[id]);
    if (now < hardFork) throw;
    if this.netID != dep[owner].netID throw;
    dep[msg.sender].send(withdraw));
}
```
## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by tawaren** [comment]
Their is a flaw in your deposit function. If its called twice with different networkId's then the second call will transfer the deposited ether from the first call to the networkId from the second call, but the old deposit is still recorded under `chainTotal[id]` with the old networkId.
As an example: `deposite(0)` with `5 wei` followed by a `deposite(1)` with `0 wei` leads to a situation where `chainTotal[0] == 5` and `chainTotal[1] == 0` but `dep[owner].value == 5` and `dep[owner].id == 1`

**Comment by barryWhiteHat** [comment]
This is sudo code to explain the idea. I did not write it to be secure, or test it. I just wrote it to help explaining.

**Comment by KenKappler** [comment]
I am not sure this requires an op code - hard forks will usually have some change in behaviour of the network which is detectable by a smart contract. 

The dao hard fork had a very large balance moved and different code at an address, the bloat hard fork had new behaviour and gas prices for certain op codes etc...

Here is an implementation of a fork coin contract I built for the DAO fork:

https://github.com/KenKappler/fork-coins/blob/master/ForkCoin.sol

**Comment by barryWhiteHat** [comment]
I don't think the bloat HF or the gas price hard fork could have been detected from inside the EVM. Can you think of a way? 

I am proposing a method to allow all hard forks to be voted upon by the community. Currently the opcode is the only method that will allow 100% coverage.

**Comment by alex-miller-0** [comment]
Interesting, but does this require all ether holders to deposit ahead of the fork? That sounds like a nightmare. Also, who calculates the redistribution? That sounds expensive.

**Comment by barryWhiteHat** [comment]
It only requires those who want to buy or sell before the hardfork to deposit. If someone does not want to do that they can just keep eth in their wallet and be able to sell on both networks after the fact. 

The redistribution calculation is out of the scope of this proposal. In the example (which is just a place holder) the redistribution was proportional to the amount you deposited on your preferred chain. From a game theory point of view it may be required to add a first mover benefit to encourage this action.

**Comment by alex-miller-0** [comment]
Cool. That makes more sense.

> The redistribution calculation is out of the scope of this proposal

The algorithm may be out of scope, but the mechanism of the calculation should not be.

Perhaps something like this:

```
uint chain_a_sum;
uint chain_b_sum;
uint chain_a_deposits = mapping(address => uint);
uint chain_b_deposits = mapping(address => uint);

function deposit(bool chainA) {
  if (chainA == true && chain_a_deposits[msg.sender] == 0) {
    chain_a_sum += msg.value;
  } else {
    chain_b_sum += msg.value;
  }
}

function withdrawA() {
  if (block.number > FORK_BLOCK_NUM) {
    uint deposit = chain_a_deposits[msg.sender]; 
    chain_a_deposits[msg.sender] = 0;
    uint extra = (deposit * chain_b_sum) / chain_a_sum;
    msg.sender.send(deposit + extra);
  }
}
```

Of course this would probably run into some floating point problems, but we could hack something together that works.

**Comment by josojo** [comment]
Do I get it right, that there will be  link between network chain_ID and some logic(e.g. transaction processing and max block size)  in all clients run by miners/stakers?
If so, who guaranties that no malicious "CORE developer" changes the link/assignment of the chain_ID to the logic in the client?

**Comment by barryWhiteHat** [comment]
@alex-miller-0 that is pretty much what I had in mind when thinking about this. But there may be a requirement to give some advantage to first movers. Also after this is implemented I hope to see multiple competing mechanisms. 

@josojo right now if someone did that the transactions would never get mined due to the [replay protection EIP155](https://github.com/ethereum/EIPs/issues/155) using the chain_ID in the transaction format. 

If after this proposal is implemented someone edited a client to use another chain_ID that client would hard fork and not. If someone did this maliciously just before a hard fork. Their chain would get over taken due to larger hash rate and get ignored by all other clients.

**Comment by 3esmit** [comment]
related to #182

**Comment by jamesray1** [comment]
Hard fork voting seems like a good idea. Personally I've come to lean towards disapproving of non-trivial technical hard forks that return lost or stuck funds when there's no proof of who owns the funds and how the funds were lost/stuck. But that's a sub-issue of hard forks, it would also apply for other potentially contentious forks e.g. the transition to PoS.

**Comment by jamesray1** [comment]
I like user based voting, although I suggest that tokens are generated with a relatively fixed amount per transaction, similar to gas fees. (If you send 1000 ETH the gas fee isn't 1000x as expensive as sending 1 ETH.) I also like identity based voting as it creates a UBI of votes for everyone, which is truly democratic, providing liquidity.

**Comment by jamesray1** [comment]
Tokens for niche users would also have benefits, although users that participate more in commits, on Reddit, etc., a more likely to get delegated more votes.

**Comment by paulhauner** [comment]
You could use `ecrecover` to infer your current chain ID, without needing to expose an opcode. You can get some known good signature and then mutate the chain id component of `v` (from `v, r, s`) and test whether or not if failed. If it fails, you're not on that chain. See [here](http://solidity.readthedocs.io/en/latest/units-and-global-variables.html#mathematical-and-cryptographic-functions) for the `ecrecover` Solidity docs.

It's inelegant, but it means getting this opcode included doesn't block any interesting use-cases knowing the chain id may have.

**Comment by axic** [comment]
This was in the end solved by [EIP-1344](https://eips.ethereum.org/EIPS/eip-1344).
