### ISSUE TITLE
ERC-2350 Semantic contracts (ERC extension - draft)

### ISSUE THREAD

**Issue by danimesq** [ethereum/EIPs#2350]
# Simple Summary

Store relevant infos on contract, in hexadecimal or hash to IPFS/other network file, instead of relying on individual data provided by different blockchain explorers.

# Motivation

Tokens already stores the most basic useful information: name, symbol, decimals. This data is used by APIs, services and blockchain explorers. But other information (site url, email, blog, social networks) depends to be updated on individual blockchain explorers. It gives more work to contract developers, instead of just focus on development. It also makes discrepancy between different services with contrasting infos which can mislead users.

# Abstract

Info are hexadecimal fields. If they are big, refer to a hash for external file instead. All assets a token refers (such as icon), are hosted in Swarm, IPFS or other network.

* Type (contract, app, game, function)
* Category (different categories according to type)
* Icon
* Description
* Banner/cover
* Email (can add more than one, referring to a single file with emails)
* Blog (can refer to multiple places: hugo, Medium, Steemit - also in a single file if more than one)
* Social networks
* Developer (if contains fields or more than one, store in a file)
* Git repo
* Whitepaper

All data need to be in JSON format. Also, files such as git repo can have the same linked into multiple locations (same file in IPFS, Swarm, SSB, etc). 

# Specification

It is yet a draft. If you're technical skilled, please tell your thoughts to update this.

# Challenges

Exchanges and other services need to support new token standards otherwise only ERC20.

**Comment by DaniellMesquita** [comment]
This proposal on Ethereum Magicians: https://ethereum-magicians.org/t/erc-2350-semantic-contracts/7216

**Comment by nerdfiles** [comment]
sigh. skipped right over the semantic web, huh?

![FIk9dDHWUAUcwjx](https://user-images.githubusercontent.com/102306/149975561-68bc87af-b8c7-4278-b86a-f362b0a209e8.jpg)

lemme guess, gonna re-invent (y)UML2state-machines too?

![yuml--60o1vt](https://user-images.githubusercontent.com/102306/149975642-b3862eb1-40f0-4e8d-9bcc-92051e0a4c75.jpg)

**Comment by MicahZoltu** [comment]
Closing this issue for housekeeping purposes. People are welcome to continue discussing in this thread, but for additional visibility an EIP should be created or the conversation should be migrated to https://ethereum-magicians.org/
