### ISSUE TITLE
EIP-2364: eth/64: forkid-extended protocol handshake

### ISSUE THREAD

**Issue by karalabe** [ethereum/EIPs#2365]
This is a discussion thread for https://github.com/ethereum/EIPs/pull/2364

---

**Abstract**

The [`forkid` (EIP-2124)](https://eips.ethereum.org/EIPS/eip-2124) was designed to permit two Ethereum nodes to quickly and cheaply decide if they are compatible or not, not only at a genesis/networking level, but also from the perspective of the currently passed network updates (i.e. forks).

EIP-2124 only defined how the `forkid` is calculated and validated, but due to the numerous possible applications, it did not itself spec out how the `forkid` should be exchanged between peers. This current EIP requests the inclusion of the `forkid` as a new field in the Ethereum wire protocol (`eth`) handshake (releasing a new version, `eth/64`).

By cross validating each others' forks already during the handshake, incompatible nodes can disconnect before expensive block exchanges and validations take place (PoW check, EVM execution, state reconstruction). This furher prevents peer slots from being taken up by nodes that are incompatible, but have not yet been detected as such.

**Comment by fjl** [comment]
Spec update: https://github.com/ethereum/devp2p/pull/132

**Comment by lithp** [comment]
I haven't been following along very closely, so I'm sorry that this is a dumb question!

But, I believe this spec is not only implemented but it's already deployed to the network. Why is this still in the `Draft` status? It ought to be `Final`, there's no changing it now!
