### ISSUE TITLE
ERC: Open Grant Standard

### ISSUE THREAD

**Issue by JFickel** [ethereum/EIPs#2367]
Discussion for [Draft EIP-XXXX: Open Grants Standard](https://github.com/ethereum/EIPs/pull/2368) 

This is a proposed standard for proposing, funding and managing grants. 

https://medium.com/@jamesfickel/open-grants-standard-erc-6ed9e137d4fe

**Comment by NoahMarconi** [comment]
Following the conversations about composability and contracts we need to add a couple things to the standard:

- Pull withdraw payment `withdrawPayout` (same functionality as `withdrawRefund`)
- Refund handler for the contract itself `acceptRefund`
- `fundChild` method, send payment to a child grant. 

`acceptRefund` allows the parent grant contract to accept a refund from a child grant.

I'll add to the reference implementation and am open to interface / logic changes.
