### ISSUE TITLE
Discussion: Multiple contenthash records for ENS

### ISSUE THREAD

**Issue by filips123** [ethereum/EIPs#2393]
This issue should now contain discussion for the proposed multiple `contenthash` records EIP and its implementation.

Draft EIP is available in ethereum/EIPs#2520, andcontract implementation is available in ensdomains/resolvers#30.

---

<details>

<summary>Original EIP idea</summary>

## Abstract

This EIP would introduce support for multiple `contenthash` records for ENS. It would allow hosting a website on multiple distributed systems and accessing it from the same ENS domain.

It is an extension of the EIP 1577.

## Motivation

Many applications are resolving ENS names to content hosted on distributed systems. To do this, they use `contenthash` record from ENS domain to know how to resolve names and which distributed system should be used.

However, the domain can store only one `contenthash` record which means that the site owner needs to decide which hosting system to use. As even now, there are quite many ENS-compatible hosting systems available (IPFS, Swarm, recently Onion and ZeroNet), and there will probably be even more in the future, this could be problematic. Instead, domains should be able to store multiple `contenthash` records to allow applications to resolve to multiple hosting systems.

## [WIP] Specification

Setting a `contenthash` should be similar as with current ENS public resolver. However, the resolver should split hash into `protoCode` and `value`, and store it in `mapping`. This would allow storing multiple `contenthash` records for different types, but only one record per specific type.

When empty `contenthash` record is provided, the system should delete it from `mapping` but leave other records the same.

Resolve function should get additional optional parameter/function overloading to specify a type (`protoCode`)  of record to get. In case is it is provided, it should only return that `contenthash`. In case if it is not [TBD - Which record should be returned].

## [WIP] Implementation

If the application only supports one hosting system (like directly handling ENS from IPFS/Swarm gateways), it should request `contenthash` with a specific type. The contract would return it and application would correctly handle it.

If the application supports multiple hosting systems (like MetaMask), it should request `contenthash` without a specific type. The contract would return any of the records [TBD - Which record should be returned] and the application would then handle it.

</details>

<details>

<summary>Original things to be discussed</summary>

Things that need to be discussed:

* With that description, I tried to be as much compatible with current EIP 1577 as possible. This would mean that current applications should still work with new versions.
  One case where behaviour is different is that replacing existing record with new type won't replace it, but add a new record, unlike the current version which would replace it. Also, `contenthash` method would get overloaded with additional optional parameter to specify record type.

* Should multiple records for the same type be supported? How would the contract and application handle them?

* What should be done with applications that don't need any specific type (like MetaMask)? They should be able to request (and then handle) any record, but how would the contract determine which should be used.
  One way would be first/last that was added, but this would mean that changing default type would be hard.
  Another way would be to store them with priority, but this could be hard to implement.
  The third way, which I mostly like, is to also overload setting method with the additional parameter to set that content hash is default. That method should save the record in normal way, but also save it to special variable containing default record. And when the application would request the record of any type, it would return that default one.

</details>

**Comment by decanus** [comment]
I think it would make more sense to use fixed size bytes @filips123 for the key.

**Comment by filips123** [comment]
Which size should be used?

Possible problem with too small fixed size is that `protoCodes` does not define any size limit. So even if all `protoCodes` are currently small, this might not be the case in the future. So chosing the right size would be important.

**Comment by decanus** [comment]
you can hash the proto code and use a `byte32`

**Comment by filips123** [comment]
Ok, I will update EIP and contract tomorrow.

And one additional thing. Should hashing be done internally in contract to get/set methods still accept `bytes`, but hash it internally for storage, or should hashing be done in the application so get/set methods accept pre-hashed `bytes32` and just store it as-is?

Also, could you please check why tests for implementation are failing? I didn't have much time to investigate this, but it looks like that overloaded contract methods aren't functioning properly in JavaScript client.

**Comment by decanus** [comment]
@filips123 I don't have time to check your code. Sorry.

**Comment by filips123** [comment]
Any update?
