### ISSUE TITLE
Name for erc 20 won't update on any of the interfaces if updated after deployment

### ISSUE THREAD

**Issue by pr0toshi** [ethereum/EIPs#2415]
https://github.com/ethereum/EIPs/blob/master/EIPS/eip-20.md

If you update name after deployment no wallets or services will update it and show the new one.

**Comment by pr0toshi** [comment]
https://etherscan.io/token/0xac59fd3a14439352a08597be67e94c1b609224e4?a=0x9d31e30003f253563ff108bc60b16fdf2c93abb5#readContract

Look at name at the top then name under the contract store.

**Comment by axic** [comment]
I think this may be more of a particular behaviour of Etherscan. I'd suggest to raise this directly with them.
