### ISSUE TITLE
Discussions-to thread for EIP-2098 (Compact Signature Representation)

### ISSUE THREAD

**Issue by ricmoo** [ethereum/EIPs#2440]
This is a *discussions-to* thread (as per [EIP-1](https://eips.ethereum.org/EIPS/eip-1)) for: **[EIP-2098](https://eips.ethereum.org/EIPS/eip-2098) Compact Signature Representation**.

This topic section may be updated occasionally to reflect additional information which becomes relevant to interested parties.

**Comment by axic** [comment]
Ah, since this references the constraints of Homestead, should have added `requires: 2` to the header.

**Comment by frangio** [comment]
Is there any interest in moving this EIP to Final? We would include an implementation in OpenZeppelin but are concerned about breaking changes. Not sure if it would even be possible to introduce any breaking changes in this format though...

**Comment by ricmoo** [comment]
Yes, I was chatting last night with someone about moving it forward. I will add the `requires`, do one more round of reading it over and change its status to review. :)

**Comment by MicahZoltu** [comment]
If you do pick this back up, I recommend renaming `v` to `yParity` which is the nomenclature we have been using in new signatures like EIP-1559, EIP-2930, EIP-2711, etc.

**Comment by ricmoo** [comment]
Cool, I’ll make that change too then.

What do you think would make the most sense for a name for the composite? Right now I use `vs`, but `yParityS`?

**Comment by MicahZoltu** [comment]
I'm a huge fan of verbose names so in any code I write it would likely be called `yParityAndS` or something.  I know not everyone agrees with my desires for verbosity though.

**Comment by ricmoo** [comment]
I've updated the status to **Review**. I believe it requires an editor to approve the change. Do I need to ping someone directly, or will it be picked up on the next sweep?

**Comment by MicahZoltu** [comment]
An editor should see the change automatically, no need to do anything other than submit the PR that changes the status.

**Comment by sambacha** [comment]
Isn't this EIP already finalized? https://eips.ethereum.org/EIPS/eip-2098

**Comment by ricmoo** [comment]
Yes it is finalized. I guess this issue should be closed?
