### ISSUE TITLE
Mermaid (graphs) support in EIPs

### ISSUE THREAD

**Issue by 3esmit** [ethereum/EIPs#2450]
I am wanting to use some graphs in my EIP, but I dont want to put a JPG attachment. 
Can we add mermaid support to EIP's website? Or there is already? 

For example, I am using this in my EIP, on hackmd editor it works: https://hackmd.io/@3esmit/rJ4YBV_JI#User-secret-data-hashing

learn more about mermaid https://github.com/mermaid-js/mermaid https://mermaid-js.github.io/mermaid/#/

**Comment by 3esmit** [comment]
I had some progress on the specific issue.

I found out that, instead of using ` ```mermaid ` to specify the graph, I can directly use ` <div class="mermaid">` and include 
```html
<script src="https://unpkg.com/mermaid/dist/mermaid.min.js" crossorigin="anonymous"></script>
<script>mermaid.initialize({startOnLoad:true});</script>
```
anywhere in the EIP that will do it! Would be nice if this was done by `kramdown`.

I figured out that `gitlab-kramdown` is much more featureful than vanilla `kramdown`, and even support `plantuml`.

kramdown developer said that I could implement a module for syntax highlighter that could handle that ` ```mermaid `. 

I think that for short term solution, after merging an EIP, the editors should ask (or change themselves) this. 
Also, EIP editors must be aware that is possible to inject javascript in an EIP file, and this will result in the script being run whenever that specific EIP page is loaded.

**Comment by axic** [comment]
> I figured out that gitlab-kramdown is much more featureful than vanilla kramdown, and even support plantuml.

It seems that [gitlab_kramdown](https://gitlab.com/gitlab-org/gitlab_kramdown) also has gitlab specific features and what I do not clearly understand yet it even has a setting like the below:
> gitlab_url | https://gitlab.com | GitLab instance URL to build reference links

Currently *mostly* how the EIPs render on Github is identical to how they render on the eips.ethereum.org. Keeping this I think would be very useful, until we move off Github.

> kramdown developer said that I could implement a module for syntax highlighter that could handle that ```mermaid.

Did you by any chance made any progress on this?

Also instead of mermaid, potentially supporting graphviz is an alternative.
