### ISSUE TITLE
"Optional EIPs" field in header

### ISSUE THREAD

**Issue by 3esmit** [ethereum/EIPs#2472]
Hey, I am writing EIP-2470. 

At security considerations, I suggest the use of other EIPs, but only for that specific cases, so that would be optional EIPs linked to this. 

Should we have a dedicated field at header or I just link it at references?

**Comment by axic** [comment]
What would be an optional EIP?

**Comment by 3esmit** [comment]
Are EIPs that are recommended to use together with the EIP for achieving specific use-cases.
 
In the example of EIP-2470, it mentions EIP-1344 and EIP-1191 as optionals for security of specific use-cases. For context, 2470 defines a factory that uses CREATE2, which can be used to create a smart contract from a bytecode and salt, however some developers might want that every chain have a differnt address, while others might want to have the same address for all chains. 
Therefore, it's optional the use of EIP-1344 when developer wants a different address for deployed contracts, or the use of EIP-1191 when the developer wants the same address for every chain. 

It can also be called "Optional/Recommended EIPs".

**Comment by MicahZoltu** [comment]
@3esmit EIPs are meant to be technical specifications, not recommendations on how to build stuff.  For suggestions on how to compose various things, I generally recommend using a blog, youtube video, reddit thread, or other more appropriate medium for suggesting how to compose things.

If the EIPs truly are tightly coupled/related, you can just refer to them inline with a link.

**Comment by 3esmit** [comment]
I see, but these are security recommendations that may or may not be followed depending on the purpose of who is integrating with the EIP. Currently I just mention the EIPs in that field. I see that should be enough, but that field could be interesting to highlight an optional dependency.

**Comment by MicahZoltu** [comment]
Generally speaking, my recommendation to EIP authors who want an optional EIP is "consider splitting this into multiple EIPs".  Perhaps that same advice could be applied here?  Instead of one EIP that branches internally, have two EIPs.  Alternatively, per my feedback in discussion-to thread, consider not making this an EIP at all.  😄
