### ISSUE TITLE
Add support to PlantUML in EIP website.

### ISSUE THREAD

**Issue by 3esmit** [ethereum/EIPs#2501]
Similar to #2450, but regarding PlantUML.

**Comment by naddison36** [comment]
This is how GitLab integrates to a PlantUML render server https://gitlab.com/gitlab-org/gitlab-foss/-/blob/master/doc/administration/integration/plantuml.md

**Comment by naddison36** [comment]
BTW, here's my tool that generates a PlantUML sequence diagram from a transaction hash https://github.com/naddison36/tx2uml. The `-f puml` option will generate the raw PlantUML instead of the default png format.

**Comment by ngmachado** [comment]
Adding graphs feature to EIP process is an important step to involvement of the community.

Some concepts can be better explain with images.
