### ISSUE TITLE
Feature Request: Enable mining only when transactions are pending for Clique

### ISSUE THREAD

**Issue by moritz-mbw** [ethereum/EIPs#2557]
Related to #225 

Geth developer chain can be run with command `--dev.period 0` in order to only mine blocks when transactions are pending.

It would be a great feature for geth clique to allow this behavior in private networks.
For example with the following setting in the genesis block:
`
config: { 
  { "clique": 
    "period": 0 }
}
`

**Comment by lightclient** [comment]
I think you'd be more successful making an issue into the go-ethereum repo.
