### ISSUE TITLE
Add Ownbit Wallet as EIP-55 wallet

### ISSUE THREAD

**Issue by jtomtan** [ethereum/EIPs#2570]
As title. 

Ownbit as one of EIP-55 compatible wallets wants to be listed in the EIP-55 Wallets adoption. website: https://ownbit.io

Thanks.

**Comment by axic** [comment]
You'd need to open a PR which modifies the EIP and ask its authors to merge it. However, since the EIP is in final state, there has been little motivation from its authors to merge such PRs.
