### ISSUE TITLE
Add site search

### ISSUE THREAD

**Issue by samajammin** [ethereum/EIPs#2607]
This issue is specific to the web application eips.ethereum.org

I've had multiple conversations on improving the UX of the website & the biggest request I've heard is to add site search to this website.

I think the implementation could look very similar to https://blog.ethereum.org/search/

Algolia provides free DocSearch to public websites:
https://docsearch.algolia.com/

They're also both Jekyll sites. Here's the Jekyll plugin:
https://github.com/algolia/jekyll-algolia

Should be fairly easy to mimic that implementation:
https://github.com/ethereum/blog/pull/328

**Comment by samajammin** [comment]
If there's interest in this feature, I can try to prioritize this at some point within the next few weeks.

Otherwise, @evertonfraga - I don't want to volunteer you 😅 but perhaps when have some free time... I imagine this would be easy for you implement given your recent experience.

**Comment by evertonfraga** [comment]
That's #1 on my golden bucket list. I beg to implement this 😆

**Comment by evertonfraga** [comment]
The only caveat is that Jekyll-algolia plugin is not whitelisted by GitHub, so either:

a) the CI installs that gem, and makes the indexes updates
b) we get EIPs website migrated to Netlify (i wouldn't complain), just like we did with the blog

**Comment by Souptacular** [comment]
@evertonfraga I'm cool migrating this to netlify, but I want to understand more about how it is currently hosted/deployed. Do you have a background on that?

**Comment by axic** [comment]
Github pages, handled by github.

**Comment by Souptacular** [comment]
@axic does the CI happen in GitHub?

**Comment by Souptacular** [comment]
Oh wait I think I see. It uses GitHub pages to publish. If that is the case, how are they using the custom EIP gem: https://github.com/ethereum/eip_validator?

**Comment by axic** [comment]
That is not part of the Github Pages run, that is part of the pre-merge CI run.

**Comment by evertonfraga** [comment]
that's helpful. so I assume the CI job commits the resulting static site to gh-pages branch, and GitHub just published them. If that's the case, we shouldn't need to migrate over to another platform.

By the way, @axic what's your opinion on this issue's search proposal? Please take a look on the EF blog search for reference: https://blog.ethereum.org/search/

**Comment by axic** [comment]
Just checked again (I don't have access to the "Settings" page here) and I think it works as follows:
`master` **is the** github pages branch (and not the usual `gh-pages`). Since it is a regular github-pages compatible jekyll, github just picks it up without issues. This also means the problem raised by @evertonfraga is likely a problem (https://github.com/ethereum/EIPs/issues/2607#issuecomment-615392258). Also the CI for merge (see `.travis.yml`) is only used for PRs.

**Comment by Souptacular** [comment]
Where does the CI happen? I'm not skilled in CI programs so I can't tell.
