### ISSUE TITLE
Consider IANA registration of URI Scheme for ethereum? 

### ISSUE THREAD

**Issue by fred-wang** [ethereum/EIPs#2644]
@brunobar79 has requested to add ethereum to https://html.spec.whatwg.org/multipage/system-state.html#safelisted-scheme see https://github.com/whatwg/html/pull/4287

One suggestion by the WHATWG is to ensure schemes are registered as provisional schemes at https://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml so I drafted a request to be sent to IANA:

https://github.com/fred-wang/iana-uri-schemes-provisional-registration-requests/blob/master/ethereum.txt

Please take a look and tell me if that looks ok to you. In particular I listed @ligi as a "Change controller" (Organization or person including contact information, authorized to change this) since they wrote https://eips.ethereum.org/EIPS/eip-831 

cc @axic

**Comment by ligi** [comment]
Thanks for he initiative!
maybe just change:
```
Change controllers:
  - Frédéric Wang (fwang@igalia.com)
  - Ethereum Community (ligi@ligi.de)
```

to

```
Change controllers:
  - Frédéric Wang (fwang@igalia.com)
  - ligi (ligi@ligi.de)
```

as I am part of - but not the "Ethereum Community" ;-)

**Comment by fred-wang** [comment]
@ligi thanks done.

I guess I'll wait a bit more to see whether there is more feedback from the Ethereum community before sending the request to IANA.

**Comment by axic** [comment]
Why not create a public gist with the file so it can be discussed there (commented, and see the changes)?

**Comment by ligi** [comment]
> @ligi thanks done.

thanks!

> I guess I'll wait a bit more to see whether there is more feedback from the Ethereum community before sending the request to IANA.

maybe also post to eth-magicians to get more eye-balls on it

**Comment by fred-wang** [comment]
> maybe also post to eth-magicians to get more eye-balls on it

Done: https://ethereum-magicians.org/t/consider-iana-registration-of-uri-scheme-for-ethereum/4285

> Why not create a public gist with the file so it can be discussed there (commented, and see the changes)?

This is already stored in a github repo so people can send PRs or see the log history: https://github.com/fred-wang/iana-uri-schemes-provisional-registration-requests/blob/master/ethereum.txt

I think creating a gist would be easy, but I'm a bit afraid to confuse people by having two public versions of the draft. I think the file is small, so that's probably not necessary...

**Comment by fred-wang** [comment]
Registration request sent.

**Comment by fred-wang** [comment]
... and approved: https://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml

**Comment by ligi** [comment]
Do you know why the email addresses are rendered so badly there: https://www.iana.org/assignments/uri-schemes/prov/ethereum ?
In the gist it was good

**Comment by fred-wang** [comment]
@ligi Yes, I noticed that too. I didn't get any information from IANA about this change, but I suspect it's some kind of protection against spamming. Note that all the email addresses on https://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml have "@" replaced with "&", so it's definitely not specific to this request.

**Comment by axic** [comment]
@fred-wang any reason you have used Ethereum as a lower case name throughout? Obviously lowercase for the scheme name, but not as the name of the system.

**Comment by fred-wang** [comment]
@axic The template should have "This scheme name is used by the Ethereum platform", sorry about that. I don't think I have a control on "Description" and "Well-Known URI Support" columns, that was not part of the request form. In any case, feel free to send any update ; that's the reason why I wanted one community member to be "change controller".
