### ISSUE TITLE
CI fails for all builds due to current state of master

### ISSUE THREAD

**Issue by rekmarks** [ethereum/EIPs#2674]
CI currently fails for all builds due to the content of `master`. I say "content" because I don't believe that all things flagged as errors are in fact errors. This is preventing automatic approval and merging all otherwise eligible PRs, e.g.: https://github.com/ethereum/EIPs/pull/2673

Example: https://travis-ci.org/github/ethereum/EIPs/jobs/692012828
Relevant part of CI logs:
```
+codespell -q4 -I .codespell-whitelist eip-X.md EIPS/
EIPS/eip-1491.md:70: iam ==> i am, aim
EIPS/eip-1491.md:473: iam ==> i am, aim
EIPS/eip-1930.md:91: interepreting ==> interpreting
EIPS/eip-1753.md:143: ACN ==> CAN, ACNE
EIPS/eip-1155.md:573: Espace ==> Escape
EIPS/eip-1155.md:574: espace ==> escape
EIPS/eip-2333.md:71: stings ==> strings
EIPS/eip-1581.md:13: keypairs ==> key pairs
EIPS/eip-107.md:98: invisble ==> invisible
EIPS/eip-1613.md:89: keypair ==> key pair
EIPS/eip-758.md:72: notificaitons ==> notifications
```

**Comment by Arachnid** [comment]
Someone added spell check as a required check to the build some time ago. I'd be delighted to remove it.

**Comment by rekmarks** [comment]
Here, have my `n` of 1 statement of support!

**Comment by axic** [comment]
I strongly oppose removing the spelling checker. The quality of EIPs are already quite low in this repository and the spell check has caught countless annoying misspellings.

This is the first time codespell was updated upstream (in 2+ years) and I think **anyone who is bothered by this could have filed a PR fixing the above few cases**. Alternatively it would be possible to lock down a specific version to avoid this in the future.

Anyhow, I spent ~5 mins to create the PR closing this issue: #2683

**Comment by rekmarks** [comment]
I created this issue because I wasn't sure what to do about this problem. Now you've told me, and the problem is getting fixed, so everybody's happy. Thanks!

**Comment by axic** [comment]
Sorry it sounded rude, it is quite late here, and I am not happy when removing mostly well working checks is proposed when a tiny hiccup is encountered :wink:

**Comment by rekmarks** [comment]
All good man, we're all on the same team here. I deeply appreciate the work of the EIP editors, which I imagine can be quite thankless.
