### ISSUE TITLE
A binary format for EVM code

### ISSUE THREAD

**Issue by wanderer** [ethereum/EIPs#27]
# Abstract
The EIP gives EVM code a semantic container that enables quick population of memory and smaller amounts of initialization code. Partly inspired by [ELF](http://wiki.osdev.org/ELF)

# Motivation
This is low hanging VM optimization. Given defined sections in a binary VM implementers will be able to more efficiently allocate resources.

# Specification
The format has four main segments header, code, init, data . None of the segments are required.  They are to be encoded as array. The order does not matter.

## Prefixes
Each segment should start with a single byte prefix identifying it.
0x00 header
0x01 code
0x02 init
0x03 data

## header
Currently the header only holds information on where to load the data to. Head consists of an array of data segment headers. Data segments represent initialized data that is loaded directly from the binary into memory when the program starts.

header := [data segment headers]
Where each `data segment header` := [address, data offset, data, size]

* address - is the address in memory of where to start loading the data
* data offset - where the data starts in the `data` segment relative to the first byte in the data segment
* data size - the number of bytes to load starting at the offset.

If a data segment head points to an indice that does not exist then the binary is invalid. 

## code
The code to be stored for the contract. The code is saved in the current way; it is hashed and stored at its hash. If the program has no data segment only the `init` should run and the account should not be saved.

## init
The initialization code runs before the account creation is finalized. If the initialization code traps then the account should not be created.

## data
The data segment is a single continuous segment. The header and data should be saved in account after the stateRoot field. 

## fees
The fee for placing code in the state would include the header, data and the code e.i. `codedeposit_fee` * (num_of_bytes(data + header + code))

The fee for loading the data section to memory is just the cost of memory expansion.

# Rationale
* The main rationale is to aid in optimizing the VM.  Batched preallocation of memory will be faster than runtime allocation. Also it make less incremental gas calculations then incremental allocation.  Lastly the number of opcodes used to allocate memory in runtime are reduced.
* Encouraging the separation of data from logic should result in more reusable logic and make code deduplication easier.
* Data - The rationale for the data section is that it should be used to save globals variables and other initialized data.
* Initialization - Instead of forcing contracts to have creation code, it is now optional. This will save space by eliminating unnecessary setup code.

# Backwards Compatibility
 Already initialized programs will work the same way. Txs that have the old format will become invalid.

**Comment by axic** [comment]
As discussed on Gitter, I think some of the sections should be a bit more clear.

Some notes:
- Make it more clear that the *data* sections represent mutable data loaded to the EVM memory ever time the code is executed. The account is charged every time for memory expansion. Would it make sense to have some of these section loadable via special new opcodes?
- Can any sections apart from *data* be present multiple times?
- If multiple *data* sections are loaded non-continuously, the intermittent space must be allocated also with zeroes. The account should be charged for the total memory.
- The init section will be executed before or after the data is loaded? Will that have access to the data section? The fees would also include the gas fees for the init code.

**Comment by wanderer** [comment]
>Make it more clear that the data sections represent mutable data loaded to the EVM memory ever time the code is executed. The account is charged every time for memory expansion. Would it make sense to have some of these section loadable via special new opcodes?

data sections are **immutable** data loaded to the EVM memory every time the code is executed. 

> Can any sections apart from data be present multiple times?

no. And there is only data segment. There are multiple  `data segment headers` in the header. Each containing [address, data offset, data, size]

>if multiple data sections are loaded non-continuously, the intermittent space must be allocated also with zeroes. The account should be charged for the total memory.

Yes that happens currently with memory expansion.

>The init section will be executed before or after the data is loaded? Will that have access to the data section? The fees would also include the gas fees for the init code.

Then init section only gets executed before the account is created. And it is not saved in the state.

**Comment by axic** [comment]
>> Make it more clear that the data sections represent mutable data loaded to the EVM memory ever time
>> the code is executed. The account is charged every time for memory expansion. Would it make sense to
>>have some of these section loadable via special new opcodes?
>
> data sections are immutable data loaded to the EVM memory every time the code is executed.

Let me clarify:
- mutable from the perspective of the code, can be access/changed with MSTORE/MLOAD
- immutable from the perspective of the ethereum state, the same data section will remain with account

**Comment by wanderer** [comment]
> Let me clarify:
mutable from the perspective of the code, can be access/changed with MSTORE/MLOAD
immutable from the perspective of the ethereum state, the same data section will remain with account

yep!

**Comment by axic** [comment]
Regarding the actual file structure I would suggest to consider something along the lines of the following. Assuming these files should have some tools in the future processing them (not only nodes and compilers, but decompilers, optimizers, etc).

Option 1 (based on what you have suggested):
- have a simple fixed header (magic, version)
- have a simple TLV (tag-length-value) encoding: store the section type, followed by size, and content

```
- magic
- version
- 0x1
- <header size>
- <header>
- 0x2
- <code size>
- <code>
- 0x3
- <init size>
- <init>
- 0x4
- <data size>
- <data>
- 0x0 (end of file tag)
```

Option 2:
- have a simple fixed header (magic, version)
- size & offsets into the file where each of the sections are located (code, init, data)

For simplicity have all of them at 32 bits (or use more specific field widths, or even RLP):
```
- 32bit magic
- 32bit version
- 32bit code size
- 32bit code offset
- 32bit init size
- 32bit init offset
- 32bit data size
- 32bit data offset
```

Where size=0 means the section is absent.

In this case have your data section header at ```<data offset>```.

**Comment by wanderer** [comment]
@axic I made assumption that it would be RLP encoded. With RLP does LV so we don't need our own LV... just T.  Although if we didn't use RLP this would be the way to go. It might be a bit lighter. One thing I might add would be to use LEB128 to encode the sizes if there is chance of overflowing 32bits.

 I think `version` is a good idea.

**Comment by chriseth** [comment]
It would be great if you could hive a bit more information about why this is beneficial. I don't see it as "low hanging fruit". Currently, immutable data is stored in code and copied to memory using CODECOPY upon request. The _upon request_ is important here: Different functions in the same contract may require different data in memory and thus initialise it differently.

Please also provide some use cases where immutable data is important. One use case I can think of that makes use of a lot of immutable data (and thus provides a reason to think about optimisation in the first place) is lookup-tables. But for lookup-tables, it is much better _not_ to load them into memory completely - it is much better to only copy the parts we actually want to read.

One thing worth noting is that EVM code is different from traditional binaries: EVM code is loaded into memory / execution context each time a function is called and it is completely erased when the call is finished. Traditional binaries can stay in memory for weeks.

My opinion would be to keep the EVM itself as simple as possible and perform optimisations on the code itself. We can gladly talk about how compilers should generate the code so that it is easy to run for existing EVM implementations.

**Comment by wanderer** [comment]
> Different functions in the same contract may require different data in memory and thus initialise it differently.

Sure but there are often globals and statics that could take advantage of this. The idea is that there would be less operations (one big mem load at startup) then to load a static data word by word at runtime. `PUSH PUSH PUSH CODECOPY`

> Please also provide some use cases where immutable data is important.

Lets look at some real world binaries  `objdump -s -j .rodata ./solc >` [dump.txt](https://github.com/ethereum/EIPs/files/40888/dump.txt)  also `objdump -s -j .data ./solc`.  Also [this article](https://en.wikipedia.org/wiki/Data_segment) give some good examples and history on `.data`

>EVM code is loaded into memory / execution context each time a function is called and it is completely erased when the call is finished. Traditional binaries can stay in memory for weeks.

Yes EVM code is more ephemeral. Therefore it is more important to be able to quickly load EVM program.

**Comment by wanderer** [comment]
@chriseth re: ephemeral; another way you can look at is that we mapping the VM's topology to a format. This should allow for fast loads times since it reduces code needed it initialize the environment.   
>My opinion would be to keep the EVM itself as simple as possible

It doesn't add any functionality or complexity to the EVM itself; but it does demand more from the execution environment.

**Comment by chriseth** [comment]
Sorry, but I still do not see the benefits. I do see the benefits of a data section for software running on actual machines where the memory is not completely erased after each function call.

We already have a place where data is stored and that is the code. It will be loaded into memory automatically by the runtime environment and can be accessed from the program in a much more efficient way than if some fixed data would be copied to memory for every single function call, even for trivial storage accessor calls.

As I wrote in my previous comment: If you want to optimize these kinds of things, we can talk about a marker in code that distinguishes between code and data.

**Comment by wanderer** [comment]
what would a `marker in code` look like?

**Comment by chriseth** [comment]
The main problem this EIP wants to solve (or is there any?) seems to be that if you put data inside the code of a contract, a compiler might have a hard time because it is undecidable whether some portion of the code is reachable or not, so in the worst case, it would have to also compile the data.
A good compiler will compile just in time and only compile the data blocks if they are jumped into. To make it easier for a compiler to detect early on which blocks are unlikely to be jumped into, we could add a magic string after which there is no real code to be executed. Of course, this can only be a recommendation.

**Comment by wanderer** [comment]
sure but then you get back to defining a binary format. Why not just put all the data in a .data section? Either way the execution environment is holding both code and all the data in memory at start. If you separate the code data from the code and put the data to VM memory the execution environment will not be using any more memory... its will cost execution environment nothing extra.

**Comment by wanderer** [comment]
discussion has moved here https://github.com/ethereum/evm2.0-design/
