### ISSUE TITLE
Discussion for EIP-2786: Ethereum Provider Connect/Disconnect Events

### ISSUE THREAD

**Issue by MicahZoltu** [ethereum/EIPs#2787]
When an Ethereum Provider becomes connected or disconnected, it will emit a `connect`/`disconnect` event.

**Comment by MicahZoltu** [comment]
@rekmarks Would be great to get a review of this before last call ends to make sure it aligns with MetaMask's implementation.

**Comment by MicahZoltu** [comment]
I think we should remove the `chainId` from this event.  If a provider supports multiple chains, and it connects to them in parallel, then this event will be fired for a random chain and will not be fired for any other chains.  This makes relying on this event a bad idea, yet it is a trap that I suspect almost every dapp developer will fall into.  Instead, we should have a separate event for `chainConnected` and `chainDisconnected` or we should update this spec such that `connected` and `disconnected` are called once for every chain that a provider connects to/disconnects from and the `chainId` would be included in both `connected` and `disconnected`.

At the moment, I'm struggling to understand how this event is useful.  You could get a `connected` event for `chainId` `1` and then connect to `chainId` `2` but not receive an event for it, then disconnect from `chainId` `1` without receiving an event for it.  As currently designed, I don't think any dapp should subscribe to this event because it simply doesn't give them enough information to do anything useful.

**Comment by rekmarks** [comment]
I believe the original intention of this event was to cover cases when providers become disconnected from their RPC endpoints / whatever APIs they're using to communicate with the blockchain. The `chainId` was tacked on as an afterthought.

Given the points you've raised, I'm not against removing the `chainId` from the spec, and just referring to `chainChanged` for that. Indeed, MetaMask already emits `chainChanged` when a chain is first connected, making a `chainId` on `connect` redundant. Whether we need the event at all is a different question.

There's some previous discussion about this on the [1193 discussion issue](https://github.com/ethereum/EIPs/issues/2319). @alcuadrado [noted that some providers "need" `connect`/`disconnect` methods](https://github.com/ethereum/EIPs/issues/2319#issuecomment-544795458) (previously called `open`/`close`). I weighed in on the matter [here](https://github.com/ethereum/EIPs/issues/2319#issuecomment-561028949), referencing a PR by @pedrouid.

IIRC, the `connect`/`disconnect` events were intended to be paired with the corresponding methods. If the consumers can cause the provider to become connected or disconnected, we can imagine that the provider can become connected or disconnected for reasons beyond the consumer's control. Hence the need for the events for such providers.

Similar to what I said in my comment on the 1193 issue, the only time MetaMask is not connected is if the user's network is down. I think most providers are "connected" in this way. That said, it's certainly possible that the RPC endpoint / blockchain API provider goes down without the user's Internet connection also going down. The question is, do we want events to cover that case?

**Comment by pedrouid** [comment]
Providers, Wallets and Dapps have evolved a lot and with this evolution we definitely should have evolve these standards to reflect the current state of Ethereum applications

When I proposed `open`/`close` I intended to standardize the access control to a provider connected to a wallet. This may be a little narrow to WalletConnect protocol but it inherited a lot from Metamask injected provider.

In essence, the way I view these events and corresponding methods is to be more than just representing the availability of a node's remote connection but also its permission.

While in the case of Metamask injected provider the connection would be connected/open on page load and only disconnected/closed when internet connection is unavailable. But what about the case whether the user has blocked the application from using it or vice-versa? 

I would personally would like to see these events. and corresponding methods to be focused on the provider connection with the wallet itself rather than nodes they are proxying to

**Comment by MicahZoltu** [comment]
> I believe the original intention of this event was to cover cases when providers become disconnected from their RPC endpoints / whatever APIs they're using to communicate with the blockchain. The chainId was tacked on as an afterthought.

A provider can be connected to one chain and disconnected from another chain though, so I feel like this event doesn't actually solve that problem?  For example, if a provider is connected to Ropsten, but not connected to Mainnet, you'll get a connected event (for Ropsten) and no connected or disconnected event for Mainnet.  If the dapp wants to know about Mainnet connection status, it won't be able to use this event, and it is unclear to me when such a client would want to use this event.

I agree that we need connected/disconnected events, I just think that these events as currently specified aren't useful.  My recommendation would be to change the specification such that the connected/disconnected event is fired for *every* chain that is connected/disconnected and the chainId is included in the event.  My proposal to remove chainId from the specification was because it was backward compatible with the 1193 specification, but if other parties are amenable to it then I'm fine with breaking 1193 compatibility and saying that this event **MUST** fire for every chain that is connected/disconnected.

> In essence, the way I view these events and corresponding methods is to be more than just representing the availability of a node's remote connection but also its permission.

I have long lobbied for a capabilities system, which I feel like would be the right solution to this class of problems?  At any given moment a provider may provide access to some set of methods for a given chain (e.g., you can `eth_call` but cannot `eth_submitTransaction`) and a capabilities event that was broadcast anytime capabilities changed (for any chain) would enable applications to give useful error messaging to users and adjust behavior based on currently available capabilities.

----

Three options going forward for *this* EIP:
1. Maintain backward compatibility and remove `chainId` from the event.
2. Break backward compatibility and EIP-1193 compatibility and change the spec such that these events **MUST** be fired for every chain independently.
3. Drop this EIP entirely and create a new EIP for `chainConnected` and `chainDisconnected` events (exact name TBD).

cc @rekmarks @pedrouid @alcuadrado for thoughts on which path to take.

**Comment by MicahZoltu** [comment]
After discussion with @rekmarks in #2840 we have decided to withdraw this EIP due to the issues mentioned above.  There are very few situations where a provider can be fully aware that they are unable to connect to *any* chain as they cannot usually differentiate between a network partition and one or more chains being offline and their ability to connect to *any* chain being faulty.  On top of that, if there is a per-chain connect/disconnect, then the app would receive notification anyway, just at a more granular level.
