### ISSUE TITLE
@gcolvin @Arachnid @Souptacular @nicksavers I think this looks like a reasonable clarification in a "Final" ERC.

### ISSUE THREAD

**Issue by Jeedneux89** [ethereum/EIPs#2830]
@gcolvin @Arachnid @Souptacular @nicksavers I think this looks like a reasonable clarification in a "Final" ERC.

_Originally posted by @axic in https://github.com/ethereum/EIPs/pull/1744#issuecomment-468757998_

**Comment by MicahZoltu** [comment]
Closing as spam.
