### ISSUE TITLE
Add arbitrary aggregate contract calls

### ISSUE THREAD

**Issue by vporton** [ethereum/EIPs#2863]
See also #2711 (https://eips.ethereum.org/EIPS/eip-2711) or #2733 (https://eips.ethereum.org/EIPS/eip-2733).

I propose to add special contract calls (let's call it aggregate calls) that would have the following properties:

* Use `tx.origin` as `msg.sender` in other contract called directly by a contract called in an aggregate call.

* Pass with the call a set of contract addresses and allow such direct calls only to contracts in this set.

It is intended to be used like the following:

* web3.js initiates an aggregate call.

* To the user is displayed "aggregate call for contracts ..." where ... is the set of contracts.

* The call is made if confirmed.

Security:

* Using `tx.origin` as `msg.sender` is safe in this case as the user knows he is making an aggregate calls and which contract he calls.

Rationale:

* It allows to arbitrarily combine several contract calls into one, with unlike #2711 and #2733 arbitrary processing (by e.g. a Solidity code) the data between calls, for example a value returned by one contract call could be passed to another one.

* It is a complex feature to write a EIP and implement, but it is very important to do, because this is the only way to arbitrarily combine several contract calls into one.

* This feature allows the programmer to be free from the responsibility to guess all the possible combinations of contract calls, he would need to combine into one external function before the final contract is deployed.

**Comment by MicahZoltu** [comment]
@vporton Do you mean like https://eips.ethereum.org/EIPS/eip-2803 would allow?

**Comment by vporton** [comment]
> @vporton Do you mean like https://eips.ethereum.org/EIPS/eip-2803 would allow?

My proposal is different than EIP 2803:

* I don't propose to create a new contract every time such a transaction is done (this way we save gas on deployment).

* EIP 2803 misses using `tx.origin` as `msg.sender` and so EIP 2803 is not enough to make arbitrary contract calls from any address.

Thus my proposal is needed to be implemented independently on whether EIP 2803 will be implemented. These two proposals could even both be implemented and sometimes used together.

**Comment by MicahZoltu** [comment]
The idea with 2803 is that the vast majority of the time you would just do a single delegate call to an already deployed contract that executes some series of transactions in sequence.  This means that in all of those cases, you would not be deploying any bytecode and your transaction data would be just whatever is required to issue a delegate call.

> EIP 2803 misses using tx.origin as msg.sender and so EIP 2803 is not enough to make arbitrary contract calls from any address.

I believe this is incorrect (though maybe I'm misunderstanding).  See this line in 2803:
> `CALL` will set the `CALLER` to the EOA (not `x`).

**Comment by vporton** [comment]
> The idea with 2803 is that the vast majority of the time you would just do a single delegate call to an already deployed contract that executes some series of transactions in sequence. This means that in all of those cases, you would not be deploying any bytecode and your transaction data would be just whatever is required to issue a delegate call.

This looks like a bad in practice idea for me for the following reasons:

* It would require to (dynamically or statistically) to generate a separate EVM code for each of the call combinations (how to do this? create many small Solidity sources, compile and distribute the bytecode files? or generate EVM code dynamically from JavaScript? either is not good)

* The calls combinations in practice will be in some finite sets (as EVM programs are usually not to be generated dynamically), so deploying this entire set of calls would safe the total gas used. As such, the idea of passing EVM code every time seems bad.

> > EIP 2803 misses using tx.origin as msg.sender and so EIP 2803 is not enough to make arbitrary contract calls from any address.
> 
> I believe this is incorrect (though maybe I'm misunderstanding). See this line in 2803:
> 
> > `CALL` will set the `CALLER` to the EOA (not `x`).

Sorry, this misunderstood by me.

**Comment by MicahZoltu** [comment]
The *vast* majority of sequential calls are people interacting with dapps and the sequence of calls is the same or one of a small set for all users.  In all of these cases, a delegate call makes the most sense as the dapp developer can deploy a contract with their app that has the delegate functions available and then the UI can generate the delegate call transaction.  For example, people need to do an approval of some token prior to calling a contract function that then transfers that token away.

For the few times when you need to do a one-off call sequence, you can simply construct the bytecode necessary to do so and submit it as a transaction.  It is worth noting that this code is not "deployed" or saved on the chain, it is executed just for that transaction.

**Comment by vporton** [comment]
@MicahZoltu I do not see _any_ reason not to deploy some bytecode when the bytecode was anyway submitted to the blockchain. Every verifier sees the code anyway, so the cost to deploy it is expected to be negligible. If it is free, why not to deploy also?

**Comment by MicahZoltu** [comment]
IIRC, storing data permanently on the blockchain is significantly more costly than passing it to a block as transaction data.  While technically transaction data is stored as part of history, the *way* they are stored is different from deployed contracts and the accessibility requirements for transactions and transaction data is quite different.  They can, for example, be written to a slower disk I believe in most implementations rather than needing to be "hot" (e.g., HDD or NAS rather than SSD).

This is represented in the contract deployment costs which is 32,000 + 200 per byte vs transaction data which is 21,000 + 68 per byte (I think contract deployments *also* have to pay for the 21,000 + 68 per byte, which would put contract deployment at 53,000 + 268 per byte, but you should double check that rather than believing me since I'm not confident in it).

**Comment by vporton** [comment]
@MicahZoltu 

> IIRC, storing data permanently on the blockchain is significantly more costly than passing it to a block as transaction data. While technically transaction data is stored as part of history, the _way_ they are stored is different from deployed contracts and the accessibility requirements for transactions and transaction data is quite different. They can, for example, be written to a slower disk I believe in most implementations rather than needing to be "hot" (e.g., HDD or NAS rather than SSD).

Anyway, usually we need just max one contract deployment per a version of an application. Deploying once is indeed not expensive.
