### ISSUE TITLE
Discussion on ERC-2917: Staking Reward Calculation

### ISSUE THREAD

**Issue by skardas** [ethereum/EIPs#2925]
Discussion on ERC-2917: Staking Reward Calculation

**Comment by aliatiia** [comment]
I see two issues with this:

(1) prohibitive gas costs for increasing/decreasing/getting productivity. Verifying user-supplied proofs of productivity is going to be gas intensive. For example the EIP states:

```solidity
/// Note the best practice will be restrict the callee to prove of productivity's contract address.
function increaseProductivity(address user, uint value) external returns (bool);
```
This proof will be expensive to verify, even more so it if it's standarized in some way (overhead). It also introduces a dependency on either wallets of frontends to generate these proofs. 


(2) "Productivity" is contract-specific, so doesn't lend itself to standardization. 

Typically in DeFi, productivity is not accounted for at the user-level, but rather through the constant updates of global variables (like amount interest accumulated). Users are only given "shares" of the pool (typically as an ERC20 token, e.g. cDai on Compound). When a specific user withdraws for example, her "productivity" is readily determined by extracting a pro rata share from the interest accrued in addition to the principle. This determination is a simple `div`ision. By keeping track of only (1) initial user share and (2) interest accrued globally (this is updated anytime pokes the contract in any way), the "productivity" is determined easily and without any need to increase/decrease productivity at the user level.

**Comment by skardas** [comment]
The intention of this function (1) is not to verify the prove of productivity increase/decrease, but only allow verified other productivity provider contract to call to change. For instance, another staking/unstaking contract. The reason why we propose this interface is for decoupling the interests generation and the productivity providers.

One of the most important intention that why we've proposed the productivity rather than the current  share model is because the share model is not count for the time parameter.

You could think share model is one of the possible way of providing  productivities. When calculating a user's profit, our algorithm calculates a user's share during a time period compare to a instant snapshot of the share's distribution.

Also from what you've mentioned, if a total accumulated interests are 100, and user hold 1% share propotional, there is noway to determine how much he could receive if he constantly calls withdraw.
