### ISSUE TITLE
SHA3 Precompile

### ISSUE THREAD

**Issue by q9f** [ethereum/EIPs#2951]
I would like to propose and champion a SHA3 precompile that implements the SHA3-256 standard as specified in FIPS202: https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.202.pdf

Opening the discussion prior to writing the proposal to get a sense of the Ethereum community's sentiment towards this idea.

**Comment by MicahZoltu** [comment]
Fine with me, and I think there was talk about using sha3 in ETH2 (rather than keccak256).

**Comment by MicahZoltu** [comment]
ETH2 will be using SHA-256 (which is SHA-2 family).

**Comment by axic** [comment]
What is the use case of SHA3-256 on Ethereum? What feature/capability/product will be enabled by it? Can it be efficiently implemented on the EVM for those use cases?

**Comment by q9f** [comment]
Thanks for the questions, will answer in a bit.

I'm just wrapping my head around the advantages and disadvantages of having a pre-compiled contract versus a native opcode.

**Comment by mohamedelshami** [comment]
I would like to re-open this thread and propose an EIP add the SHA3-256, this is important for interoperability with SHA3-256 FIPS202 based blockchains.

Is there a particular reason or previous discussion on why SHA3-256 has never been added to Ethereum?

**Comment by q9f** [comment]
> Is there a particular reason or previous discussion on why SHA3-256 has never been added to Ethereum?

Nobody championed it.

**Comment by mohamedelshami** [comment]
hi @q9f happy to collaborate on drafting an EIP if there isn't one already, and see if it gets through the review process.
