### ISSUE TITLE
EIP-1: Include RFC 2119 recommendation into EIP-1 so EIPs do not need to duplicate it

### ISSUE THREAD

**Issue by axic** [ethereum/EIPs#2960]
Pretty much every "seriously written" EIP duplicates that paragraph from RFC 2119.

**Comment by MicahZoltu** [comment]
Just EIP-1, or also the template?

**Comment by axic** [comment]
The reason I created an issue and not a PR, because I'm not sure to handle it. If EIP-1 can assert (aka duplicate the assertions from RFC 2119?) the terms, then we do not need to have it in the template, nor in individual EIPs. That would be the goal.

**Comment by MicahZoltu** [comment]
Sounds good to me.  Create a PR to EIP-1 and I'll review it.

**Comment by axic** [comment]
So actually having thought about it, EIP-1 is quite a bit of a mess and not many people read it.  In conclusion perhaps leaving it in the template/files is more straightforward, especially that RFC 2119 demands/suggests the following:

> Authors who follow these guidelines should incorporate this phrase near the beginning of their document:
>
> The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED",  "MAY", and "OPTIONAL" in this document are to be interpreted as described in RFC 2119.
