### ISSUE TITLE
Archival of Abandoned/Withdrawn EIPs

### ISSUE THREAD

**Issue by axic** [ethereum/EIPs#2962]
The Abandoned (*name may change, see #2941*) status is introduced for EIPs which are no longer pursued due to various reasons.

There has been some concerns that the current process is designed at merging drafts as soon as possible (*even if we fail at that*) will eventually result in a lot abandoned EIPs.

In order to clean up eips.ethereum.org, one possible solution could be considering a process of "archival": after a certain time period, Abandoned EIPs are archived. Archived EIPs:
- are listed under a separate section called "Archive" on eips.ethereum.org and do not show up under the respective categories nor under "All"
- their title and header is displayed unchanged
- their body is replaced with a text explaining they are archived and can be found in github, also it would explain how to revive them (-> mark them draft)

**Comment by lightclient** [comment]
I like this idea.

**Comment by MicahZoltu** [comment]
I think this is more about how we present withdrawn/stagnant EIPs on eips.ethereum.org, and I am in favor of the idea as long as someone else implements it.  :)
