### ISSUE TITLE
sub-categorizing Informational EIPs

### ISSUE THREAD

**Issue by ethers** [ethereum/EIPs#30]
per https://github.com/ethereum/EIPs/pull/17#issuecomment-158084930 do we want a classification for "contract proposals/standards"?

Another category of Informational EIPs that come to mind, is retrospectives/post-mortems of events like forks, such as https://github.com/bitcoin/bips/blob/master/bip-0050.mediawiki, https://blog.ethereum.org/2015/10/22/security-alert-implementation-of-blockhash-instruction-in-c-and-go-clients-can-potentially-cause-consensus-issue-fixed-please-update  Would we want these to be Informational EIPs?

**Comment by Souptacular** [comment]
Closing per https://github.com/ethereum/EIPs/pull/183
