### ISSUE TITLE
provide a reserved range of opcodes for chain-specific extensions

### ISSUE THREAD

**Issue by saurik** [ethereum/EIPs#3002]
I noticed that Avalanche coreth has added a few new instructions to the EVM implementation used for their contract subchain, specifically to provide some kind of cross-chain communication. I found some code that indicated a year ago they were going to use 0xf6, but relatively-thankfully I see they have settled on some opcodes in the 0xc0-f range.

https://github.com/ava-labs/coreth/blob/93a7f324c06321023e2702f7989fdfad32573793/core/vm/opcodes.go#L211

I think it would be useful to provide a way to do this--whether for functionality that woudn't make sense on other chains or to experiment with new features--in a way that is guaranteed to not conflict with future extensions to the EVM specification, such as having a small range of reserved opcodes (maybe in that 0xc0 range, for "c"hain-specific).

(And yes, per all of the warnings about this from the issue tracker templates and repository setup and the such, if I'm the person who then ends up being required to write up some long document with some justification for having a reserved range of opcodes that the standard will guarantee never to add to a standard, I guess I'm willing to do that.)

That, or maybe someone can suggest a better way to add these kinds of VM extension features, and we can try to convince the Avalanche people to use that instead? I wasn't sure if maybe precompiled contracts might be a better way to go about this, but then it seemed like the implementation of those in geth wasn't done with random addresses (which would be nice to allow people to experiment with a number of unrelated feature extensions) but instead was packed into a small array, which I imagine would lead to the same problems.

**Comment by MicahZoltu** [comment]
This doesn't seem terribly unreasonable to me.  The biggest problem is that there is a finite space available in general and we don't want to partition *too* much of it away for "other chains".  That being said, this seems like a reasonable thing to create a PR for.  I am not a fan of picking a particular range because the leading letter happens to align with some word though, we should pick a range that makes sense for other reasons besides "naming".

**Comment by saurik** [comment]
@MicahZoltu FWIW, while I thought the "c" was cute, my reasons for choosing it were really 1) that Avalanche happened to already be trying to use 0xc[def] and 2) it happened to come after the "b" range that was being used internally by geth (it seemed). Do you have an opinion of what range it should be? I agree it doesn't need to be a very large range. I could even see an argument that it should be a single reserved opcode that can be used as an "escape" byte in the parser.

**Comment by MicahZoltu** [comment]
I don't have a particular preference.  I do kind of like an "escape byte" so EVM implementations can have their own entire numbering systems.  It makes contracts a bit bigger, but presumably these opcodes won't dominate contract bytecode content.

**Comment by qizhou** [comment]
Hi, I have opened a discussion in the magicians forum https://ethereum-magicians.org/t/eip-vendor-specific-opcodes/4478 to add vendor-specific opcodes, which serves the same purpose of this issue.  I think as more chains including open or permissioned chains are using EVM with customized features, I think this is a good improvement to widen the applications of EVM to more areas.

**Comment by qizhou** [comment]
In short, the EIP aims to ease the work of adding non-standard EVM features (i.e., extensions in x86). The EIP uses two opcodes OP_VENDOR and OP_VCALL:

- OP_VENDOR returns a uint256 indicating who is the vendor of the EVM. The vendor list can be registered similar to coin_type in HD wallets.
- OP_VCALL calls a vendor-specific extension (similar to CPU instruction extensions such as SSE, AVX). Which extension of the vendor and the arguments can be specified in the stack or data appended after OP_VCALL.

Note that this can be also used to tell which version of Ethereum the EVM is running on (such as Peterburg, Byzantine).
