### ISSUE TITLE
Create a standard for joining together two chains, if possible

### ISSUE THREAD

**Issue by vporton** [ethereum/EIPs#3011]
Mainnet was forked into Matic, Fuse, Celo, Pepo, and probably more.

It would be good in the future to join back all these chains into single ETH2 chain. It seems impossible to do this with existing forks, but I think we could do something with possible future forks.

I propose to investigate the following:

1. Create a standard like `address flexible` in Solidity for addresses that would be moved across chains possibly changing one address into another address simultaneously in all variables of the entire chain (we may need to change them, because there are often different balances on _the same_ address in two different chains; can we work around of this in another way?)

2. Think what to do for example if a new address is created out of two addresses with their joining and KECCAK.

Another possibility is to add extra bytes to address variables to identify the chain from which it was taken. This is however incompatible with existing byte layout (but Solidity syntax does not need to be changed).

**Comment by lightclient** [comment]
Does it make sense to join 2 chains together? How will people know what the canonical maker dao is or the canonical uniswap router? Once the chain's state deviate, I don't believe there a reasonable way to rejoin them under then same address space. 

Theoretically, this won't be a big deal in eth2. If there is enough demand, we'll just forked chain a shard. That will allow it to maintain it's own address / state space.

**Comment by vporton** [comment]
> Does it make sense to join 2 chains together? How will people know what the canonical maker dao is or the canonical uniswap router? Once the chain's state deviate, I don't believe there a reasonable way to rejoin them under then same address space.

We would have two uniswap routers in one chain. Better than two in two chains.
