### ISSUE TITLE
ERC: transferFrom Token Standard

### ISSUE THREAD

**Issue by gkucmierz** [ethereum/EIPs#3055]
## Preamble
```
Title: transferFrom Token Standard
Author: Grzegorz Kucmierz <gkucmierz@gmail.com>
Type: Informational
Category: ERC
Status: Draft
Created: 2020-10-18
Requires: ERC20
```

## Simple Summary
Allow tokens to be transferred from address, that have no ETH in it to cover gas for transaction, but it provides off-chain signature that is allowing transfer for specified `amount` and specified `recipient`.

## Abstract
This adds a new function to [ERC20](https://github.com/ethereum/EIPs/issues/20) token contracts, `transferFrom`* which can be called to transfer tokens from another address.

* This `transferFrom` have different signature than original `ERC20` `transferFrom`

```solidity
function transferFrom(address, uint256, uint8, bytes32, bytes32) returns (bool);
```

## Motivation
Using this function it is possible to deposit tokens to contract, and also contract can react to this transfer within one transaction.
Also single address is able to make transfer from any other address by providing additional signature, that confirms validity of this transfer.

#### transferFrom
```solidity
mapping (address => mapping (address => uint256)) public nonceOf;
  
function transferFrom(address recipient, uint256 amount, uint256 nonce, uint8 _v, bytes32 _r, bytes32 _s) public returns (bool) {
    bytes32 hash = keccak256(abi.encodePacked('transferFrom', recipient, amount, nonce));
    address from = ecrecover(hash, _v, _r, _s);
    return _transfer(from, recipient, amount, nonce);
}
```

`transferFrom` transfers tokens to `from`, which is calculated using `ecrecover`
Warning about this function is that created signature will be valid forever, so there should be another function also that limits signature validity to only specified block

#### transferFromUntil
```solidity
function transferFromUntil(address recipient, uint256 amount, uint256 untilBlock, uint256 nonce, uint8 _v, bytes32 _r, bytes32 _s) public returns (bool) {
    require(untilBlock <= block.number);
    bytes32 hash = keccak256(abi.encodePacked('transferFromUntil', recipient, amount, nonce, untilBlock));
    address from = ecrecover(hash, _v, _r, _s);
    return _transfer(from, recipient, amount, nonce);
}
```

## Backwards Compatibility
This proposal is backwards compatible for all ERC20 tokens and contracts. New tokens and contracts moving forward can implement the `transferFrom` functionality.

## Implementation

```solidity
contract ERCTransferFrom is ERC20 {
  mapping (address => mapping (address => uint256)) public nonceOf;
  
  function _transfer(address from, address recipient, uint256 amount, uint256 nonce) private returns (bool) {
    uint256 nextNonce = nonceOf[from][recipient] + 1;
    require(nonce == nextNonce);
    bool success = super._transfer(from, recipient, amount);
    if (success) nonceOf[from][recipient] = nextNonce;
    return success;
  }

  function transferFrom(address recipient, uint256 amount, uint256 nonce, uint8 _v, bytes32 _r, bytes32 _s) public returns (bool) {
    bytes32 hash = keccak256(abi.encodePacked('transferFrom', recipient, amount, nonce));
    address from = ecrecover(hash, _v, _r, _s);
    return _transfer(from, recipient, amount, nonce);
  }

  function transferFromUntil(address recipient, uint256 amount, uint256 untilBlock, uint256 nonce, uint8 _v, bytes32 _r, bytes32 _s) public returns (bool) {
    require(block.number <= untilBlock);
    bytes32 hash = keccak256(abi.encodePacked('transferFromUntil', recipient, amount, nonce, untilBlock));
    address from = ecrecover(hash, _v, _r, _s);
    return _transfer(from, recipient, amount, nonce);
  }
}
```

**Comment by zemse** [comment]
Is there any security consideration for replay protection?

**Comment by gkucmierz** [comment]
Design of this function do not allow to replay attack because in case when contract is transfering tokens to itself or other contract it controls flow of code. And no other contract code is run like for example in `ERC 223` or `ERC 667`

**Comment by zemse** [comment]
Oh, I think your reply sounds for re-entrancy explanation, pls correct me if I'm wrong. I meant to say when someone has the signature, they could simply call the function multiple times. Just in case, you can see how this is handelled by ethereum in the protocol level https://medium.com/swlh/ethereum-series-understanding-nonce-3858194b39bf.

**Comment by gkucmierz** [comment]
You are correct, it is not considered here, but it should be.

**Comment by MicahZoltu** [comment]
That would prevent the sender from sending the same amount of tokens to the same recipient twice in a row.

Consider adding a `nonce` variable instead to handle replay attacks in a similar way as to how Ethereum handles them.

**Comment by gkucmierz** [comment]
I fixed this by adding additional `nonce` to hash function.

```js
contract ERCTransferFrom is ERC667 {
  mapping (bytes32 => bool) transferred;
  
  function _transfer(address recipient, uint256 amount, bytes32 hash, uint8 _v, bytes32 _r, bytes32 _s) private returns (bool) {
    require(!transferred[hash]);
    address from = ecrecover(hash, _v, _r, _s);
    bool success = super._transfer(from, recipient, amount);
    transferred[hash] = success;
    return success;
  }

  function transferFromUntil(address recipient, uint256 amount, uint256 nonce, uint8 _v, bytes32 _r, bytes32 _s) public returns (bool) {
    bytes32 hash = keccak256(abi.encodePacked('transferFrom', recipient, amount, nonce));
    return _transfer(recipient, amount, hash, _v, _r, _s);
  }

  function transferFromUntil(address recipient, uint256 amount, uint256 untilBlock, uint256 nonce, uint8 _v, bytes32 _r, bytes32 _s) public returns (bool) {
    require (untilBlock <= block.number);
    bytes32 hash = keccak256(abi.encodePacked('transferFromUntil', recipient, amount, untilBlock, nonce));
    return _transfer(recipient, amount, hash, _v, _r, _s);
  }
}
```

This nonce needs to be handled outside of contract.

**Comment by MicahZoltu** [comment]
If someone decides to move forward with this as an EIP PR, I recommend adjusting the specification to only specify the interface and define what the parameters represent.  You can move the implementation into an `## Implementations` section if you think a reference implementation adds additional value.

**Comment by gkucmierz** [comment]
I removed `hash` as you suggested above.

```solidity
contract ERCTransferFrom is ERC20 {
  mapping (address => mapping (address => uint256)) public nonceOf;
  
  function _transfer(address from, address recipient, uint256 amount, uint256 nonce) private returns (bool) {
    uint256 nextNonce = nonceOf[from][recipient] + 1;
    require(nonce == nextNonce);
    bool success = super._transfer(from, recipient, amount);
    nonceOf[from][recipient] = nextNonce;
    return success;
  }

  function transferFrom(address recipient, uint256 amount, uint256 nonce, uint8 _v, bytes32 _r, bytes32 _s) public returns (bool) {
    bytes32 hash = keccak256(abi.encodePacked('transferFrom', recipient, amount, nonce));
    address from = ecrecover(hash, _v, _r, _s);
    return _transfer(from, recipient, amount, nonce);
  }

  function transferFromUntil(address recipient, uint256 amount, uint256 untilBlock, uint256 nonce, uint8 _v, bytes32 _r, bytes32 _s) public returns (bool) {
    require(untilBlock <= block.number);
    bytes32 hash = keccak256(abi.encodePacked('transferFromUntil', recipient, amount, nonce, untilBlock));
    address from = ecrecover(hash, _v, _r, _s);
    return _transfer(from, recipient, amount, nonce);
  }
}
```

In this implementation `nonce` handles replay-attack and also allow make transactions with the same `amount` and `recipient`.

**Comment by zemse** [comment]
Overriding the `transferFrom` method would make the contract incompatible as `ERC20`. I have a suggestion to rename it into `transferBySig`. This way, the contract stays `ERC20`, along with an added functionality. Also to classify between `transferBySig` and `transferFromBySig`, as `transferFromBySig` requires `approve` done. Though both could be added.

In this ERC20 extension, you could simply add these 4 methods into the `ERC3055` interface:

- `transferBySig`
- `transferFromBySig`
- `transferBySigUntil`
- `transferFromBySigUntil`

**Comment by gkucmierz** [comment]
@zemse I will consider changing names.

Actually we are implementing this in Wisdom token.

Here is our implementation: https://github.com/Experty/wisdom-contract/blob/main/src/ERCTransferFrom.sol

That implementation also utilizes EIP 712 https://eips.ethereum.org/EIPS/eip-712 which is making this more secure.

**Comment by gkucmierz** [comment]
@zemse can you explain difference between `transferBySig` and `transferFromBySig`?
If I understand correctly `transferFromBySig` is the same as `transferFrom` from my implementation right?
If so, what `transferBySig` should do?

Also `transferFrom` can be dropped completely, because actually its behaviour can be mimic by using `transferFromUntil` with very big `block.number`.

Since `block.number` is `uint256` it can cover ~5.5e70 years

```js
const uint256Size = 2 ** 256;
const blockPeriod = 15;
const secInMin = 60;
const minInHour = 60;
const hoursInDay = 24;
const daysInYear = (366 + 365 * 3) / 4;

console.log(
  2**256*15 / (
    secInMin * minInHour * hoursInDay * daysInYear
  )
);
```

**Comment by zemse** [comment]
By `transferFromBySig` I mean the one who is giving signature has an allowance from the `from` address. Just like the original `transferForm`

**Comment by gkucmierz** [comment]
I am not sure If I understand this.
Intention of this proposal is to not require any allowances. 
Allowance here can be signed off-chain.
I see potential that additional function can be implemented which is `pure` and `view` and can create signature. But this process can be done also off-chain in any other language.

**Comment by abbaskiko** [comment]
> ## Preamble
> ```
> Title: transferFrom Token Standard
> Author: Grzegorz Kucmierz <gkucmierz@gmail.com>
> Type: Informational
> Category: ERC
> Status: Draft
> Created: 2020-10-18
> Requires: ERC20
> ```
> 
> ## Simple Summary
> Allow tokens to be transferred from address, that have no ETH in it to cover gas for transaction, but it provides off-chain signature that is allowing transfer for specified `amount` and specified `recipient`.
> 
> ## Abstract
> This adds a new function to [ERC20](https://github.com/ethereum/EIPs/issues/20) token contracts, `transferFrom`* which can be called to transfer tokens from another address.
> 
> * This `transferFrom` have different signature than original `ERC20` `transferFrom`
> 
> ```solidity
> function transferFrom(address, uint256, uint8, bytes32, bytes32) returns (bool);
> ```
> 
> ## Motivation
> Using this function it is possible to deposit tokens to contract, and also contract can react to this transfer within one transaction.
> Also single address is able to make transfer from any other address by providing additional signature, that confirms validity of this transfer.
> 
> ## Specification
> ### Token
> #### transferFrom
> ```solidity
> mapping (address => mapping (address => uint256)) public nonceOf;
>   
> function transferFrom(address recipient, uint256 amount, uint256 nonce, uint8 _v, bytes32 _r, bytes32 _s) public returns (bool) {
>     bytes32 hash = keccak256(abi.encodePacked('transferFrom', recipient, amount, nonce));
>     address from = ecrecover(hash, _v, _r, _s);
>     return _transfer(from, recipient, amount, nonce);
> }
> ```
> 
> `transferFrom` transfers tokens to `from`, which is calculated using `ecrecover`
> Warning about this function is that created signature will be valid forever, so there should be another function also that limits signature validity to only specified block
> 
> #### transferFromUntil
> ```solidity
> function transferFromUntil(address recipient, uint256 amount, uint256 untilBlock, uint256 nonce, uint8 _v, bytes32 _r, bytes32 _s) public returns (bool) {
>     require(untilBlock <= block.number);
>     bytes32 hash = keccak256(abi.encodePacked('transferFromUntil', recipient, amount, nonce, untilBlock));
>     address from = ecrecover(hash, _v, _r, _s);
>     return _transfer(from, recipient, amount, nonce);
> }
> ```
> 
> ## Backwards Compatibility
> This proposal is backwards compatible for all ERC20 tokens and contracts. New tokens and contracts moving forward can implement the `transferFrom` functionality.
> 
> ## Implementation
> ```solidity
> contract ERCTransferFrom is ERC20 {
>   mapping (address => mapping (address => uint256)) public nonceOf;
>   
>   function _transfer(address from, address recipient, uint256 amount, uint256 nonce) private returns (bool) {
>     uint256 nextNonce = nonceOf[from][recipient] + 1;
>     require(nonce == nextNonce);
>     bool success = super._transfer(from, recipient, amount);
>     if (success) nonceOf[from][recipient] = nextNonce;
>     return success;
>   }
> 
>   function transferFrom(address recipient, uint256 amount, uint256 nonce, uint8 _v, bytes32 _r, bytes32 _s) public returns (bool) {
>     bytes32 hash = keccak256(abi.encodePacked('transferFrom', recipient, amount, nonce));
>     address from = ecrecover(hash, _v, _r, _s);
>     return _transfer(from, recipient, amount, nonce);
>   }
> 
>   function transferFromUntil(address recipient, uint256 amount, uint256 untilBlock, uint256 nonce, uint8 _v, bytes32 _r, bytes32 _s) public returns (bool) {
>     require(block.number <= untilBlock);
>     bytes32 hash = keccak256(abi.encodePacked('transferFromUntil', recipient, amount, nonce, untilBlock));
>     address from = ecrecover(hash, _v, _r, _s);
>     return _transfer(from, recipient, amount, nonce);
>   }
> }
> ```
