### ISSUE TITLE
Question on SHA3

### ISSUE THREAD

**Issue by axic** [ethereum/EIPs#31]
This is probably a bad place to ask this, but I don't seem to find anything related on the interwebs.

Back in Feb 2014 it was announced by @vbuterin that all crypto opcodes will be moved to pre-mined contracts. See [here](https://blog.ethereum.org/2014/02/03/introducing-ethereum-script-2-0/) and [here](https://blog.ethereum.org/2014/02/05/more-thoughts-on-scripting-and-future-compatibility/).

sha256, ripemd160 and ecrecover since have been moved to such contracts, but sha3 remained as an opcode.

The yellow paper defines separate gas costs for all of them, although in different places. For sha3 it is in Appendix G (Fee Schedule), while the others are explained in Appendix E (Precompiled Contracts).

Is there any memo somewhere explaining the design decisions leading to the current state?

**Comment by wanderer** [comment]
I think its one of those things that slipped through the cracks. RIPEMD160, SHA256, ecRecover where all opcodes at one point.

**Comment by vbuterin** [comment]
I think `sha3` remained as an opcode essentially because it was deemed "important" enough (eg. infinite data structures in solidity and serpent use it) that putting it into a contract would be far too inefficient.
