### ISSUE TITLE
Discussion for EIP-3143: Increase block rewards to 5 ETH

### ISSUE THREAD

**Issue by Terra854** [ethereum/EIPs#3145]
Discussion for EIP-3143

PR: #3143

**Comment by Aggrord09** [comment]
> Discussion for EIP-3143
> 
> PR: #3143

**Comment by ganmaf** [comment]
albertocuestacanada:erc3156-review

**Comment by hdfadi** [comment]
batter than burning transaction fees.
which will drops the network hashrate and will expose it to 51% attacks (again)

**Comment by axic** [comment]
The actual EIP has this discussion URL: https://ethereum-magicians.org/t/eip-3143-increase-block-rewards-to-5-eth/5061

**Comment by sebastianfelipe** [comment]
I think it's time to reopen this talk
