### ISSUE TITLE
Proposal for debt system in Ethereum

### ISSUE THREAD

**Issue by DGKSK8LIFE** [ethereum/EIPs#3182]
I am a new contributor to Ethereum. I would like to see some form of debt allocation within the blockchain; I believe you could integrate this into smart contracts where interest + deadline for payments could be stored. What do you all think about this? I desire to open this issue as a thread for discussion. Thanks in advance!

**Comment by DGKSK8LIFE** [comment]
Would it make more sense just to run this as a dapp over smart contracts?

**Comment by MicahZoltu** [comment]
Yes, there is no need for an EIP for this sort of thing, just build an application.  😄

**Comment by DGKSK8LIFE** [comment]
Yup. Sorry was brand new to Ethereum when opening this issue. Closing now. Thanks for responding @MicahZoltu !
