### ISSUE TITLE
nodejs deb not installing , please help

### ISSUE THREAD

**Issue by CryptoLeaks** [ethereum/EIPs#3183]
target/tools/v8_gypfiles/libv8_initializers.a -lm -ldl -Wl,--end-group
rm 849c0718e867ba5a1ca9c268d30a389de30aae5a.intermediate d6d644251409973247bb6b3c7495bdbace8304d7.intermediate ff56d4440474e6420b484686fcfe257e89d8086c.intermediate d8e0deb0ef32cbafc312304290da1679e14e7447.intermediate
if [ ! -r node -o ! -L node ]; then \
  ln -fs out/Release/node node; fi
/usr/bin/python3.9 tools/install.py install '' '/usr/local'
installing /usr/local/bin/node
Traceback (most recent call last):
  File "/tmp/tmp.SkHKoahN6R/node-v15.5.0/tools/install.py", line 235, in <module>
    run(sys.argv[:])
  File "/tmp/tmp.SkHKoahN6R/node-v15.5.0/tools/install.py", line 229, in run
    if cmd == 'install': return files(install)
  File "/tmp/tmp.SkHKoahN6R/node-v15.5.0/tools/install.py", line 137, in files
    action([output_prefix + output_file], 'bin/' + output_file)
  File "/tmp/tmp.SkHKoahN6R/node-v15.5.0/tools/install.py", line 76, in install
    try_copy(path, dst)
  File "/tmp/tmp.SkHKoahN6R/node-v15.5.0/tools/install.py", line 66, in try_copy
    return shutil.copy2(source_path, target_path)
  File "/usr/lib/python3.9/shutil.py", line 436, in copy2
    copystat(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.9/shutil.py", line 375, in copystat
    lookup("utime")(dst, ns=(st.st_atime_ns, st.st_mtime_ns),
FileNotFoundError: [Errno 2] No such file or directory
make: *** [Makefile:158: install] Error 1

****  Installation failed. Aborting package creation.

Cleaning up...OK

Bye.

**Comment by DGKSK8LIFE** [comment]
could you please elaborate/say what step this is happening on ? @CryptoLeaks

**Comment by CryptoLeaks** [comment]
> could you please elaborate/say what step this is happening on ? @CryptoLeaks

Thanks for quit reply , command below

sudo fakeroot checkinstall -y --install=no --pkgversion $(echo $(pwd) | sed -n -re's/.+node-v(.+)$/\1/p') make -j$(($(nproc)+1)) install

**Comment by DGKSK8LIFE** [comment]
Sorry why are you doing this? AWK stuff isn't in the docs @CryptoLeaks

**Comment by CryptoLeaks** [comment]
> Sorry why are you doing this? AWK stuff isn't in the docs @CryptoLeaks

I am trying to install Node.js to start coding my own crypto , and that command should be one of the steps according to tutorial https://ourcodeworld.com/articles/read/410/how-to-install-node-js-in-kali-linux

but am stuck !

**Comment by DGKSK8LIFE** [comment]
Please close this issue. This is completely unrelated to Ethereum EIPs

**Comment by CryptoLeaks** [comment]
> Please close this issue. This is completely unrelated to Ethereum EIPs

can you help me moving to the proper section ?

**Comment by DGKSK8LIFE** [comment]
This is completely unrelated to Ethereum; you are writing your own cryptocurrency. Find the creator of the article and contact him. Thanks

**Comment by DGKSK8LIFE** [comment]
Please close your issue

**Comment by CryptoLeaks** [comment]
On ETHEREUM blockchain!

**Comment by DGKSK8LIFE** [comment]
This doesn't have to do with EIPs
 @CryptoLeaks

**Comment by CryptoLeaks** [comment]
> This doesn't have to do with EIPs
> @CryptoLeaks

fine but can you help anyway ?

**Comment by DGKSK8LIFE** [comment]
I already told you. contact the author of the article. Close the issue please. Thanks

**Comment by DGKSK8LIFE** [comment]
Thanks
