### ISSUE TITLE
Eip: Socialistic gwei change to prevent “gwei sweeping”

### ISSUE THREAD

**Issue by moremoremomo** [ethereum/EIPs#3191]
---
eip: <to be assigned>
title: < Socialistic gwei change to prevent “gwei sweeping”>
author: <moremore@tutanota.com> (Moremoremomo)
discussions-to: <URL>
status: Draft
type: (Standards Track)
category (Core)
created: <(2021-01-05)>
---
Simple Summary-

The gwei system is changed so users can not set gwei, instead it is automatically set by the system.

Motivation-

I find this to be immoral because the person taken advantage of may have less.
 
 This new system should have less traffic jams & less tx errors.

Implementation-

Users don’t choose gas or stop allowing sensitive information to be viewed. Smh
 Why wait for eth2.0? It’s a one day fix... sigh.

**Comment by moremoremomo** [comment]
What do I need to do to get this judged? Is this not the biggest problem that has not yet been dealt with? Please tell me a bigger unsolved problem, I’ll be shocked.

**Comment by MicahZoltu** [comment]
EIP-1559 addresses the issue that I think you are referring to.  It is hard to say for sure though, because `gwei` is just a denomination of ETH (equivalent to nanoeth) and I'm not sure what exactly `gwei sweeping` is.  I think you are referring to gas price auction mechanics, which have some incentive changes coming in EIP-1559.

**Comment by moremoremomo** [comment]
Hi this is sensitive information... it’s getting the trade faster than another who put the trade in first. And easy way to do it... but I guess eth 2 doesn’t have miners so the gwei fee is removed. Is that true?
-- 
 Sent with Tutanota, the secure & ad-free mailbox: 
 https://tutanota.com


Jan 13, 2021, 19:27 by notifications@github.com:

**Comment by MicahZoltu** [comment]
Transaction fees will continue to exist in Ethereum even after moving to Proof of Stake.

**Comment by moremoremomo** [comment]
Do you mean unethical gwei sweeping? Do you understand what I told you? Please relay it back to me, also does eth 2 use miners? Will is have people able to choose gas? Eth has always been a weak token, ever since it came out... 
-- 
 Sent with Tutanota, the secure & ad-free mailbox: 
 https://tutanota.com


Feb 9, 2021, 00:36 by notifications@github.com:

**Comment by MicahZoltu** [comment]
Proof of Stake (ETH2) doesn't have miners anymore.  I do not know what "gwei sweeping" is, I have never heard this term before.

**Comment by moremoremomo** [comment]
I told you what gwei sweeping is in a previous email. Ya maybe it is best u do not understand. Besides it is for naive & deceitful sponges. -- 
 Sent with Tutanota, the secure & ad-free mailbox: 
 https://tutanota.com


Feb 10, 2021, 23:23 by notifications@github.com:

**Comment by moremoremomo** [comment]
Seems obvious that some main developers understand the problem and choose to allow it although easy one day fix that increased the systems efficacy. Why would they do this? I guess Bc they are doing this immoral system against their own systems users

**Comment by greenlucid** [comment]
Why is it immoral?
