### ISSUE TITLE
ERC777 based token standard that simplifies on-chain voting

### ISSUE THREAD

**Issue by seniorjoinu** [ethereum/EIPs#3196]
## Question
I have an implemented idea of ERC777-based token smart-contract that makes weighted (based on amount of tokens a user has) on-chain votings simple, cheap (~0.002 eth for a vote) and secure.

With this token any organization can also implement any other protocol that requires from its token holders some kind of proof of token possession at some point in time.

Should I submit it as an EIP (e.g. EIP-787)?

### The idea
The token is based on ERC777 standard and utilizes it's `_beforeTokenTransfer` hook to store account balance history on-chain.
Each time tokens move between accounts, so called `balance snapshots` for these accounts are stored. A `balance snapshot` is just a record 
```
{
    uint256 timestamp;  // block timestamp
    uint256 balance;    // account balance at this timestamp
}
```
Sequential `balance snapshots` form `balance history` of some account. This history is naturally sorted by `timestamp` and can be searched through in O(logn) time.

This enables us to introduce a new public token method `balanceAt(address account, uint256 timestamp)` that can provide the caller with reliable information about an account balance at any given point of time.

There is also `clearAccountHistory()` method that removes `balance history` of the caller except for the last entry. This method can be used when even a O(logn) search becomes pricy.

### Usage
The idea of a voting system based on this token is very simple. When a `Voting` object is created, it should also store a timestamp of its creation (or some other timestamp that would represent a moment in time from which it is legitimate to place votes). 

Then, when a user places a vote, the voting system should simply check the user's balance at the timestamp of `Voting` creation and use this balance as a value of voting power. This set of balances is used as a single source of truth for this particular voting process. 
One can see that it also very easy to `re-vote` or implement `one-account-one-vote` scheme in such a voting system.

##### There is also a little drawback.
> If a user decide to `clearAccountHistory` of theirs, `balanceAt` method might return 0 (if their last transfer was after the `Voting` creation timestamp), that would be recognized by the voting system simply as "no balance - no voting power". Users should be informed that they should make their votes before clearing their `account history`.

##### Why do we even need this?
> Let's imagine the same dead simple voting system that operates weighted votes (vote power) but without `account histories`. It wouldn't work, because there is a vulnerability - a malicious voter is able to vote multiple times simply voting and transferring their funds to another account and then voting again.

One can also easily imagine other use-cases for this token. For example, weighted dividends distribution system (the more tokens you possess, the more dividends you receive).

#### Are there another solutions?
> I believe there is, but I couldn't find them to be as simple as the proposed one. This is why I'm making this github issue instead of submitting a PR with EIP - if there is a better solution, someone will just leave a comment about it here.

#### Why is this cheaper?
> This particular design can be easily implemented in `gradual-fashion` - when no bulk reads/writes are performed and only a little portion of data is modified per transaction. Also, the design is very simple and can be done in very compact implementation; less code - less errors and cheaper execution.

#### Why should this token be an ERC?
> As I mentioned above, this token can be useful for many DAOs (or other organizations).

#### Who will be the champion of this EIP?
> I will.

**Comment by MicahZoltu** [comment]
You could save some gas by having `{ uint64 timestamp; uint192 balance; }` as a struct so it can be packed into a single storage slot.

I'm not sure an EIP is necessary here because there isn't a many-to-many relationship that needs to be satisfied.  Standards are useful when interop is necessary.  When no interop is necessary, then something can just be a Good Idea and shared via GitHub, blog posts, libraries, etc.

**Comment by seniorjoinu** [comment]
Thank you. One more opinion and I'm closing it.
