### ISSUE TITLE
Add deadline for ERC20 approve

### ISSUE THREAD

**Issue by jtomtan** [ethereum/EIPs#3197]
Hi,

I am from the Ownbit wallet team (ownbit.io). I am not sure if there's already some discussion about ERC20 approve() function. Currently the approve function is like this:

`function approve(address _spender, uint256 _value) public returns (bool success)`

This would allow the _spender to spend my token at anytime within the _value. For most of the usecases, I would like the _spender to spend my token within the _value  only in the following hours or days. 

For example, I approve the UNISWAP to change some tokens. In current design, I will approve the UNISWAP contract to spend my token forever until I clear the approval by sending another transaction. So I suggest a new approve function:

`function approve(address _spender, uint256 _value, uint256 deadline) public returns (bool success)`

Description: if the deadline = 0, it acts the same like the original approve. else if the deadline < 1000000000, it represents a blockNumber, otherwise it represents a timestamp.

After the current blockNumber or timestamp exceeds the deadline, the approval will get invalid automatically.

I think this new approve function would give more control to token owners, so that the security of DeFi can be improved.

**Comment by MicahZoltu** [comment]
I don't know of any standards for time limited approvals.  Feel free to create an EIP if you think it would add significant value.  😄

**Comment by jtomtan** [comment]
> I don't know of any standards for time limited approvals. Feel free to create an EIP if you think it would add significant value. 😄

OK, will try.
