### ISSUE TITLE
ERC20 Extending: token with fee on transfer

### ISSUE THREAD

**Issue by ducquangkstn** [ethereum/EIPs#3214]
# Simple Summary
Extending ERC20 interface for tokens with fee on transfer.
# Abstract
This standard defines new interfaces a token with fee on transfer should implement, while remaining backwards compatible with `ERC20`. This standard adds 2 new transfer methods and 2 view methods. 
- Existing transfer methods let the sender specify the source amount being sent. The new transfer methods will allow you to define the amount that will be received by the receiver.
- In addition to that, 2 new interfaces will allow you to check the expected received amount for a specific sent amount and required send amount for a specific receive amount. This will help dApps to return the exact exchange rate.
- Existing tokens with fee demonstrate the need of whitelisting options. This standard should account that matter.
- The standard will also discuss the behavior of `balanceOf` API for a token with fees.
# Motivation
Some tokens in the Ethereum ecosystem apply transfer fees, such as **DGX** and **CGT**. The **USDT** token also has the fee feature which is disabled at the time of writing.
These tokens implement the typical `ERC20` interface. However, when calling the `transfer` and `transferFrom` methods, the actual amount the receiver will get will be smaller than the sent amount.
```
function transfer(address _to, uint256 _value) external returns (bool success);
function transferFrom(address _from, address _to, uint256 _value) external returns (bool success);
```
- This leads to incompatibility with many DeFi services that expect the received amount to be equal to the sent amount. 
- Some DeFi projects have adapted by calculating the amount difference after the transfer, but this comes at the expense of higher gas usage and the returned rate is not accurate.
- In most cases, the balance of receiver will increase smaller than `_value` params (fee is included in the _value). The other type, the balance of sender will reduce bigger than `_value` params (fee is excluded in the _value). This also make harder for developer to handle all the cases.

This standard aims to create a more uniform and elegant way to handle tokens with fees.

# Specification
```solidity
interface IERCxxx is IERC20 {
function transferExactDest(address _to, uint _value) external returns (bool success);
function transferExactDestFrom(address _from, address _to, uint _value) external returns (bool success);
function getReceivedAmount(address _from, address _to, uint _sentAmount) external view returns (uint receivedAmount, uint feeAmount);
function getSendAmount(address _from, address _to, uint _receivedAmount) external view returns (uint sendAmount, uint feeAmount);
}
```
### transferExactDest
Transfers `_value` amount of token to address `_to` and **MUST** emit the `Transfer` event. The balance of `msg.sender` will be deducted by `_value + _fee`. Add `_value` amount to the balance of the receiver. 
If zero fees should be applied due to whitelisting, assume the above `_fee` to be zero. 
```solidity
function transferExactDest(address _to, uint _value) external returns (bool success);
```
### transferFromExactDest
Transfers `_value` amount of token to address `_to` and **MUST** fire the `Transfer` event. The balance of `_from` will be deducted by `_value + _fee`. If zero fees should be applied due to whitelisting, assume the above `_fee` value to be zero.
```solidity
function transferExactDestFrom(address _from, address _to, uint _value) external returns (bool success);
```
### getReceivedAmount
A query function that returns the amount of tokens a receiver will get if a sender sends  `_sentAmount` tokens. Note the `_to` and `_from` addresses are present, the implementation should use those values to check for any white listing.
```solidity
function getReceivedAmount(address _from, address _to, uint _sendAmount) external view returns (uint receivedAmount, uint feeAmount);
```
### getSendAmount
Returns the amount of tokens the sender has to send if he wants the receiver to receive exactly `_receivedAmount` tokens. 
Note the `_to` and `_from` addresses are present, the implementation should use those values to check for any white listing.
```solidity
function getSendAmount(address _from, address _to, uint _receivedAmount) external view returns (uint sendAmount, uint feeAmount);
```
# Behaviour of existing ERC20 transfer functions
The signature and behavior of `transfer` and `transferFrom` functions will remain the same. `_value` parameter in those functions will reflect the `_sentAmount` of the token.
### transfer
Transfers `_value` amount of token from msg.sender and **MUST** emit the Transfer event. Will add `_value` to the balance of `_to`, after deducting fee.
```solidity
function transfer(address _to, uint256 _value) external returns (bool success);
```
### transferFrom
Transfers `_value` amount of token from `_from` and **MUST** fire the `Transfer` event. Will add `_value` to the balance of `_to`, after deducting fee.
```solidity
function transferFrom(address _from, address _to, uint256 _value) external returns (bool success);
```
### balanceOf

Returns the exact token balance of the account, without fee considerations.
```solidity
function balanceOf(address account) external view returns (uint256)
```
### Query user balance after deducting fee
Another type of problem was encountered with the`balanceOf` function. For **CGT** token, `balanceOf` returns the balance for a user after fee deduction. They try to return a balance after deducting fee for the next transfer.

The point is `balanceOfWithFee` actually can be different depending on the transaction sizes. 
Example: transfer fee is 1%, max fee is 1 token, user has 10K tokens. If he sends all tokens at once, the actual fee would be 1 token. If he sends tokens in 10 transactions, the actual fee will be 10 tokens. 
Due to these reasons, we choose not to add additional any API to return `balanceOfWithFee`.

# Usage:
- When a user wants to send the exact destination amount to another person, he calls `transferExactDestAmount`.
- When a user wants to deposit a token to a contract or create a swap transaction: the contract calls `transferFromExactDestAmount` to get the exact amount from the user.
- When a DEX returns the exchange rate of a token, contract calls `getReceivedAmount` to get the received amount to contract, then calculate the amountOut.
# Test Cases
This [repository](https://github.com/ducquangkstn/fee-on-transfer-erc20) contains all the tests.
# Implementations
T.B.D
# Copyright
Copyright and related rights waived via CC0.

**Comment by VyomeshDua** [comment]
Great suggestion, but any adoptions for this?
