### ISSUE TITLE
Possible miner exodus and 51%

### ISSUE THREAD

**Issue by evergreen69** [ethereum/EIPs#3215]
There are many possibilities on what will happen to Ethereum after EIP-1559 is implemented, and the only way to know for sure is to implement it.  There are two things I know are certain, investors and miners both want to be paid.  Apart from fan boyism, we are both investors, just coming at it from different angles.  Miners provide a service, and investors provide an incentive.  While it is completely possible that implementation can happen with both parties being happy, it is not the future I see for EIP-1559.  My main argument for this is pure financial incentive.  Investors do not want to be separated from their money in the form of fees, while miners want to be compensated for the service they provide.  At the end of the day, it is not important what currency either party is involved in, they will gravitate to the currencies that work for their own personal use case.  I do not mine Ethereum because it is something that I hold an emotional tie to, I mine because it is profitable to do so with the funds and equipment available to myself.  If EIP-1559 is implemented, myself, and likely many other miners will migrate to where the new money is coming in.  While I do believe Ethereum has reached a point it is so engrained and invested into it is not going anywhere, it does not mean it is safe from the whim of the people supporting it.  If for whatever reason there was indication that Ethereum was not going to grow, or even hold its value investors would be running for the hills.  It is the same way with myself, if there was indication that mining Ethereum was no longer profitable, I would switch algorithm to whatever was profitable.  While there may be enough diehard Ethereum miners to keep the system going, the network performance and security will be greatly degraded.  There are already complaints within the community on the slow performance of the network.  With an exodus of miners, there would be even less protection from 51% attacks.  For example, a mining pool could decide based on the number of miners leaving the network they would have the hashrate to successfully implement a 51% attack.  With current complaints of network speed, and precedent set in Ethereum classic of 51% attacks, I do not feel that EIP-1559 will be good for the Ethereum community.  Like so many other things in life people are only happy when money is being spent and people are getting paid.  I do feel there is room for a middle ground, it will have to be competitive with the rest of the cryptocurrency ecosystem.

Edited to fit style guideline.

**Comment by MicahZoltu** [comment]
Comments on EIPs should occur on their discussions-to URL found in the header of the EIP.  For [EIP-1559](https://eips.ethereum.org/EIPS/eip-1559), the `discussions-to` URL is over at [Ethereum Magicians](https://ethereum-magicians.org/t/eip-1559-fee-market-change-for-eth-1-0-chain/2783)
