### ISSUE TITLE
Burning value in a world where some value is desperately needed.

### ISSUE THREAD

**Issue by Leozolt** [ethereum/EIPs#3255]
Issue as a thread for discussion. ..

I understand that since transaction fees on ethereum tend to go so high, eth is not usable to buy a pizza over a traditional ethereum transactinons.

I do not understand why transaction fees needs to be burned.
If a cap to transactions needs to be applied, why not attribute over gas price to:
The eth fund to build scools & houses for the poorests. maybe a lot less of poeple will die if some eth gets converted into food, instead of getting burned.

burn transaction fees? me: no
invest transaction fees? me: hmm

**Comment by MicahZoltu** [comment]
Figuring out how to distribute money is an incredibly hard problem that no human has perfectly solved, and there are 1000s of different solutions to the problem that each have their downsides.  If you want to create an EIP that proposes a dev fund, or humanitarian fund with ETH you will need to provide a much more thorough and concrete proposal with lots of details on exactly how the fund will be distributed/controlled along with how exactly the fund is funded.

**Comment by Leozolt** [comment]
Sadly, I am not able to create a concrete EIP. I just want to address EIP1559 in regards of simply burning transaction fees, instead of preventing high profit on absurdly high transaction fees by channeling the fees higher than a certain threshold to a fund that helps prevent starvation. How to manage such a fund without abuse is indeed a big task. I hope some people get the idea, and add a feature to EIP1559 to prevent simply burning assets.

**Comment by Az111z2** [comment]
A

**Comment by Kaspre** [comment]
I’m clearly late to the party and this EIP looks like a done deal.  But I agree with you.  Now, I’m no economist, and I admittedly haven’t read enough about this EIP to have an informed decision yet.  And perhaps burning tokens has some value to the platform beyond increased coin price for speculators.  But my first reaction is that it seems wasteful.  If some or all of those base fees could instead be directed into a development fund for the long-term health of the Ethereum ecosystem, and/or donated to various charities for a multitude of benefits, surely that would be preferable?
