### ISSUE TITLE
Time based switch EIP

### ISSUE THREAD

**Issue by ivorrr** [ethereum/EIPs#3286]
My colleagues and I are working on an inherent way for a user to have some secure switch that acts as a last line of defense against losing long-time access to an account. We want to provide standard interfaces and processes for safe, conditional transactions based on user predefined timestamps. It would enable users to secure their accounts from lockout after account activity ceased for a predefining fallback address to transfer the funds. 

As we are planning to submit an ERC standard proposal for it I would love to hear your thoughts on it and if you know about similar attempts from the past? Thanks

**Comment by MicahZoltu** [comment]
On the surface, this doesn't sound like something that needs to be standardized.  Any contract can add that functionality into it and there is little benefit to all contracts conforming to a single way of handling the situation.

**Comment by ivorrr** [comment]
Thanks for the feedback. As we already wrote the EIP proposal draft, I just created a pull request (https://github.com/ethereum/EIPs/pull/3290) where you can find a much detailed explanation of what we want to achieve. Please check it out.
