### ISSUE TITLE
To minimize redundancy, drop the first sentence in the security section of crosschain identification specification"

### ISSUE THREAD

**Issue by weijia31415** [ethereum/EIPs#3292]
Can probably drop this sentence as it is implied by the section title.
"Security are considered in the following areas:"

_Originally posted by @lightclient in https://github.com/ethereum/EIPs/pull/3220#r564079020_

**Comment by MicahZoltu** [comment]
I suspect this was meant to be included in a different repository?  EIPs repository issues aren't meant for notes on imporevements to EIPs, they should be pull requests against that EIP or tracked by the authors elsewhere.
