### ISSUE TITLE
Combine shared ownership & NFT divisibility

### ISSUE THREAD

**Issue by aniismr** [ethereum/EIPs#3375]
Hello everyone !
Issue as a thread for discussion. ..
I'm wondering if there is an existing  EIP that can provide shared ownership and divisibility of an NFT. 
Here is an example : 
Consider two people (person A and person B) who both own the same piece of land (which in my opinion can be considered as an NFT since it "respects" almost all the standards that define and NFT such as scarcity and uniqueness ). 
Consider now person A want to sell a part of their share in the piece of land. Is there an existing ERC standard that  combines all of these requirements ?

**Comment by PowerStream3604** [comment]
EIP-1633 makes NFT fractional by making an ERC-20 contract to be the owner of NFT and dividing ownership by the ERC-20 token of that contract.
[EIP-1633](https://github.com/ethereum/EIPs/issues/1634)

EIP-1513 also proposes to make NFT fractional.
[EIP-1513](https://github.com/ethereum/EIPs/issues/1528)

This EIP also proposes a royalty standard with Royalty-Distribution-System with fraction NFT and FT.
[EIP proposing royalty distribution system](https://github.com/ethereum/EIPs/issues/3601)
