### ISSUE TITLE
Add anchor tags to eip headings

### ISSUE THREAD

**Issue by lightclient** [ethereum/EIPs#3396]
Github markdown does this automatically and leads me to link to the github version of an EIP if I need to link to a specific section.

**Comment by MicahZoltu** [comment]
This feature was added recently and already exists (at least for me).  You can either grab an anchor link from the auto-generated table of contents, or hover your mouse to the left of any heading.  I can appreciate an argument for making this more discoverable...

**Comment by MicahZoltu** [comment]
![image](https://user-images.githubusercontent.com/886059/111323760-22698a80-86a5-11eb-8bf3-39673d238db9.png)

**Comment by lightclient** [comment]
Doh, why does it not work for me? :(

**Comment by MicahZoltu** [comment]
Hmm, I'm in Firefox?  Not sure if that matters?

**Comment by lightclient** [comment]
Haha okay I see now. You have to over the left side of the name, hovering over the header doesn't work (but does work on github).
