### ISSUE TITLE
Jekyll theme only supports headings up to `###`

### ISSUE THREAD

**Issue by lightclient** [ethereum/EIPs#3399]
This leads to EIPs with deeper subsections not looking very good.

**Comment by lightclient** [comment]
Also seems like there are issue rendering `code` in headers.

**Comment by MicahZoltu** [comment]
IIRC, the anchor limit to `###` was done intentionally when the anchor links were added.  If we desire deeper linking, it should just be a matter of removing that restriction.

**Comment by lightclient** [comment]
@MicahZoltu it's not just a matter of linking though, headers of size `####` just show up as paragraph text. This leads EIPs to look ugly online (see [EIP-3074](https://eips.ethereum.org/EIPS/eip-3074) for instance) - it's hard to tell where `Input` and `Output` starts, but it is very clear in the github markdown [rendering](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-3074.md).

**Comment by MicahZoltu** [comment]
Ah, you want to change the `h4` style then.  The headings *are* making it into the HTML, but the stylesheet for the page sets `h4` to be very subtly different from `p` elements and other text.

**Comment by MicahZoltu** [comment]
Actually, digging a bit it appears that Jekyll doesn't have any meaningful styles for h4 or h3, they are just browser default style.
