### ISSUE TITLE
Feature Request: Strict Smart Contract Address Check.

### ISSUE THREAD

**Issue by SiestaMadokaist** [ethereum/EIPs#3408]
Hello, I was wondering, if it make sense in ethereum to make it so that a transaction sent to a non-smart-contract-address, must have the field data = `0x`.

----
The reason being, since a non `0x` data, is normally a smart contract parameter, it doesn't make sense to be sent to a non-smart-contract address.

I understand, that maybe, some people somewhere used the field data, just like a "memo".
But to handle such scenario, I think it would be better to whitelist it with a specific headers, like `0xffff` or something, to notify the miner that this data is not intended as a smart-contract parameter.
(so, the only acceptable transaction to a non-smart-contract address, will be either `0x`, `0xffff*`)

---

Case Example:
1. Someone tried to convert their ETH to some token via Uniswap.
He called `swapExactETHForTokens` function in uniswap, along with some ETH to be converted.
However, unfortunately, he made a typo in the uniswap address, making it sent to an address not owned by anyone.
Without this feature: now he lost his money.
With this feature: the miner determined that the destination address is not a smart contract, and thus the transaction can be reverted.

2. Someone want to sent some ETH with some memo.
He sent some ETH, and put some memo in the field `data`
Without this feature: the transaction will be accepted.
With this feature: the transaction will be reverted, unless the field `data` starts with `0xffff`

----

I thought of this feature when I was swapping token in uniswap.
I'm safe when I swap Tokens for Tokens, at worst I'll just lost some gas fee, even if the transaction was sent to a wrong address, because the field data will be ignored by this non-smart-contract-address.
however, when I swap ETH for Tokens, if my transaction is sent to a wrong address, that ETH will be lost, likely forever.

I know that this issue is nothing urgent, but I think, it's nice to have more defensive mechanic to prevent a similar mistake.

**Comment by Dexaran** [comment]
I would like to support this proposal. This can prevent the most common user mistakes.

**Comment by zemse** [comment]
Regardless of the transaction success or "reverts", still that tx will anyway be included in a block (so any sort of data availability purpose is achieved). So `0xffff` be avoided. Just the `value` sent won't be deducted (which should be a fine behaviour imo).

`eth_call` errors when making call to a non-contract account with non-zero data, while sending tx to non-contract account with non-zero data doesn't, which seems like an inconsistent behavior. Now as there is movement to the L2 future, cases where a contract address is used on another network by mistake will start getting more common. (and as given example of a `swapExactETHForTokens` tx funds could be lost)

I think this proposal could be considered and I don't see any negatives yet.
