### ISSUE TITLE
How to write Security Considerations ?

### ISSUE THREAD

**Issue by sgmfinance** [ethereum/EIPs#3420]
Hi 
I would like to know, what to write in Security Considerations for an EIP proposal. It says:
 EIP submissions missing the “Security Considerations” section will be rejected. An EIP cannot proceed to status “Final” without a Security Considerations discussion deemed sufficient by the reviewers.

But I checked other Passed EIP, there are no Security Considerations written. 

Can someone tell me what to do?
THX

**Comment by MicahZoltu** [comment]
Initially you can just put something like:
```markdown
## Security Considerations
There are no known security considerations for this EIP.
```
Sometimes security considerations will come up during the authoring/feedback process that you can then add to the EIP.

**Comment by sgmfinance** [comment]
RE: #4858
