### ISSUE TITLE
New transaction parameter for latest block number inclusion

### ISSUE THREAD

**Issue by eyezick** [ethereum/EIPs#3447]
## Simple Summary
Allow users to specify the latest block a transaction can be included in.

## Abstract
Add an optional parameter for transactions to specify the max block number the transaction can be included in to improve UX.

## Motivation
Any valid transactions broadcasted by users provide no guarantee when they will be included in a block, if ever. This means transactions can linger in the mempool indefinitely, resulting in UX issues:

1. Subsequently broadcasted transactions are unable to be validated while pending tx is in mempool. 
 
Advanced users may resubmit tx and reuse the previous nonce, but this is still undesirable UX and not guaranteed to prevent the original from being validated (in cases where original tx becomes stale).

2. Lingering transactions become "stale" but can eventually be included in blocks anyway, both needlessly wasting gas and bloating the blockchain.
	
Many DeFi transactions are time-sensitive. Below from https://uniswap.org/faq/ :

```
My swap failed with code “EXPIRED”, what happened?
If a swap takes more than 20 minutes to execute, the router is programmed to fail the transaction. This is to protect the user from extreme swings in prices that can occur while the transaction is pending.
```

With the current UX, a user making such a financial transaction who desires to not waste gas must babysit their transactions live to ensure they are included, and resubmit with same nonce and higher gas price (possibly repeatedly) until the tx is executed.

Contrastly with this proposal, a user can simply set a block number, and have far more assurance their tx will execute based on a non-volatile context (as it will be mined within a certain block number), or simply not have any effect.

The second order benefit is that less failed transactions occur, which both relieves pressure on congestion and the blockchain state.

## Specification
Transactions currently include several parameters, some of them optional like `data` and `value`. A new optional parameter is to be included, `maxBlock`.

When validating transactions, if the `maxBlock` provided and is less than the current block height, the transaction is not includable in a new block and is discarded from the mempool. Similar to if a `nonce` of a tx is less than the tx count of the EOA that originated the tx, it is never mined/validated in a block.

**Comment by MicahZoltu** [comment]
A couple notes:
1. There are no "optional" parameters on a block besides the `to` field which really is overloaded to signify contract deployment.
2. A transaction that can expire by time means that an attacker could submit thousands/millions of otherwise valid transactions that they are very confident will never be mined due to their expiry, and potentially clog up the gossip network.

**Comment by eyezick** [comment]
Thanks for the reply @MicahZoltu.

Regarding a spam attack, is this necessarily more dangerous than existing avenues? Currently an attacker could submit countless of invalid transactions that validators would have to sift through as well. For the former, it would be possible to drop any txs that had a very low `maxBlock` before propagating them

**Comment by MicahZoltu** [comment]
> This seems analogous to spamming txs with a very low gasPrice of 1 gwei, they are still "valid", but will never be mined, and the network is handling that attack surface well enough currently.

An ultra low gas price transaction like that won't get gossiped in the first place because it won't survive the mempool of the first peer.  This greatly limits the effectiveness of the attack because you can basically only DoS your immediate peers, who will simply kick you if you become abusive.  If you submit a gas price that is high enough to fit in the mempool, you risk having to actually pay should gas costs decline.  If you have to pay, then the attack isn't free.  😄

**Comment by eyezick** [comment]
So there is definitely an amendment to this needed then, something like:

```
Security Considerations:

There is a DoS possibility where a node may broadcast high numbers of technically valid but
 "unmineable" txs if the txs have a low enough `maxBlock` that expire by the time a miner/validator picks the txs out of the mempool.

To mitigate this, each node can have a changeable `maxBlock` threshold, where if a transaction is set to expire too soon, it will not be broadcasted to its peers.

```

**Comment by Shymaa-Arafat** [comment]
I am not sure, but I think EIP-1559 included some handling to transactions deadlines thru the Fee-cap and variable block size.
I'm not a developer, but I recall deadlines were mentioned in 1559 discussions especially that of Tim Roughgarden technical report.
