### ISSUE TITLE
ERC: Antitoken - Representing debt in a token

### ISSUE THREAD

**Issue by hazae41** [ethereum/EIPs#3477]
https://github.com/ethereum/EIPs/pull/3476

## Simple Summary
Representing debt in a token. Like an ERC-20 but with `receive` instead of `transfer`. Thus, the token has a negative value: the less you have, the better.

## Abstract
Imagine a anti-currency blockchain where, instead of signing the sending, you sign the receival. 

You cannot send the currency to an address, you can only receive it from the given address.

Thus, the incentive is to spend it, nobody wants it, the currency has a negative value.

This ERC uses a smart contract to emulate an anti-currency on the Ethereum ecosystem.

## Motivation
An antitoken can be used to represent debt, bad reputation, or anything negative in relation to its owner. 

The incentive is to spend it and to have a balance of zero.

## Technical specification
For technical specification, see https://github.com/ethereum/EIPs/pull/3476

## Reference implementation
https://github.com/hazae41/ERC-Antitoken

**Comment by hazae41** [comment]
## What prevents me from receiving the token on a random address I own? 

This operation would be visible on the blockchain. 

Also, the contract MAY only allow transfers to known addresses.

**Comment by imkharn** [comment]
This would allow debt to be traded which sounds nice, however, debt must always be combined with collateral. Even once we have an identity system, the collateral at a minimum is a users reputation. 

Everyone who receives debt must have acceptable collateral. 
What is acceptable collateral is subjective and up to the platform that initially issued the debt token; there is no universal collateral valuing system. This platform must approve any transfers of debt. A user willing to receive is not enough to allow a transfer of an 'antitoken'.

Because proprietary transfer rules are needed for all commonly used debt tokens, perhaps literally all existing debt tokens, there is no point in having these universal transfer rules.

**Comment by coderintherye** [comment]
@imkharn Is there something specific to Ethereum or this ERC which would make true your statement "debt must always be combined with collateral"? There's nothing preventing collateral free debt in the current finance world and plenty of real world examples of debt without collateral. One could argue reputation is the minimum collateral but it is intangible and failing to pay back debt does not always destroy reputation. I guess I'm just curious why you think debt must always be combined with collateral.

**Comment by imkharn** [comment]
There is no one that would lend to someone both without knowing their identity and without traditional collateral. 

If identity itself is the collateral (the idea being their public reputation is harmed if they default, then the lending protocol will have some means of deciding the value of someones identity like a credit score. But this credit score and more specifically how much credit line to give them is subjective, and there wont be a universal methodology. 

Lets say you wanted to transfer identity based debt to someone else. Deciding if that someone else is allowed to receive that debt depends on their identity, and if the identity is sufficient enough to receive that amount of debt without financial collateral is a subjective decision that will have to be ran through proprietary code from the system that issued the debt token. A random person saying they will take all your debt off your hands is not enough to run a protocol.

I think the takeaway from your idea is that Aave and all other lending protocols (including identity/reputation based) should allow someone to transfer their debt tokens to another party providing two conditions are met:  first, the receiver authorizes the receipt, and second, that the protocol rules allow this much debt to this ethereum address. The second part is key, and what makes a antitoken transfer standard largely pointless.
