### ISSUE TITLE
Require at least one Github handle in author field

### ISSUE THREAD

**Issue by lightclient** [ethereum/EIPs#3494]
For a while now, @MicahZoltu has enforced that at least one author lists their github handle in the author field. This allows them to interact with the auto merge bot. EIP-1 should be updated to reflect this.

**Comment by MicahZoltu** [comment]
Recommend just creating a PR against EIP-1 and getting feedback that way.  In my experience, GitHub issues for EIP process changes tend to stall out while PRs create a sort of forcing function.

**Comment by ethosdev** [comment]
while updating EIP1 this too? https://github.com/ethereum/EIPs/issues/3517
