### ISSUE TITLE
Allowing multiple addresses to own one address.

### ISSUE THREAD

**Issue by hipHopPop** [ethereum/EIPs#3544]
To more align with the real world and to be self sufficient, multiple ownership of single address can be enabled. Some examples are, group ownership of NFTs, contracts and joint accounts.

**Comment by zemse** [comment]
Hey @hipHopPop, you can check out Multisig wallets. Some readings:

- https://medium.com/mycrypto/introduction-to-multisig-contracts-33d5b25134b2
- https://medium.com/block-journal/multi-sig-wallets-explained-5544c122a1de
