### ISSUE TITLE
[Discussion] Thread about the benefits of an EIP allowing Token Flagging at contract level, to notify aggregators (marketplaces, wallets & co)

### ISSUE THREAD

**Issue by dievardump** [ethereum/EIPs#3546]
Hello, I come today to open a discussion about an idea of EIP that I think would benefit the NFT space.

Idea:

Today, there are many marketplaces, wallets and aggregators showing data about tokens of all the collections they can find. However there is absolutely no easy way for collections managers to report a token on each and every of those platforms.

More, some collections are open (anyone can mint at any time) and decentralized (metadata on IPFS, Arweave or the likes) and it is not technically possible for the collection managers to remove the metadata linked to a token (and sometimes not legally possible if a purchase has been made).
This could sadly end up with the whole collection banned/removed from a big marketplace or a wallet because of one or a few of the tokens do not respect the law, do copyright infringement, non conformity to ToS, ...

Moreover, NFTs are still "booming" but we will probably soon see a lot of demands to take something down because of case such as copyright infringement, and we will need a way for it to be done on all platforms indexing the data, as fast as possible.

Therefore, this standard makes it possible in a very easy way for those collections to notify all platforms (marketplaces, aggregators, etc...) that a token is no longer supported/valid/recognized by the distributor (for any reason), and that those platforms should therefore update their database to either delete it or at least mark it as flagged.
It also allows other contracts to verify this state before, for example, allowing a sale.

This EIP idea would enable this flagging at the contract level, with the emitting of an event, that can be easily caught by any platform indexing the contract data, and a getter to get the current flag state of a token.

By providing an Event and a Getter, this EIP allows o-chain and off-chain verification of the state, and also make it easy for indexers to get the change of state "as soon as possible".
For platforms that are not indexing data in real time, the getter would be an easy check to add to the "metadata refresh" system they use.

Note: The right to change the flag state of a token should be given only to the collection owner. This is not meant to be publicly used, as it is a mechanism for collection owners to notify aggregators

Note2: as a safeguard, we could add a `string memory reason` with the flagging, that would help aggregators to understand why the flag has be made, and if it is legitimate or not to remove / hide it from their index.

_An example of the use case could be the Axies that have been banned from the game because of multi accounting or any other cheat. With a specification like this one, it would have been very easy for all these platforms to get notified of those ban, and show it._

Following, you can find a very quick draft that I put together to describe in depth how and why this would be important to have, and help us (platforms, creators and aggregators) a lot

---
title: Token Flagging
author: Simon Fremaux (@dievardump)
status: Idea
category: ERC
created: 2021-05-02
requires: 165
---

## Simple Summary

A standardized way to allow collections to Flag a tokenId to notify consumer platforms (Marketplaces & co) to remove it efficiently from their database or mark it as flagged by the token distributor.

## Abstract

This standard extends the NFT specifications ([ERC-721 specification](./eip-721.md) and [ERC-1155 specification](./eip-1155.md) and any other ID based token specification, to allow collection managers to publicly flag a token by its id.

By adding one event `event TokenFlag(uint256, bool)` and one getter `function isTokenFlagged(uint256) public view return (bool)` this specification allows collection managers to notify consuming platforms and to allow other contracts to query about a token current flag state.

## Motivation

Today, there are many marketplaces, wallets and aggregators showing data about tokens of all the collections they can find. However there is absolutely no easy way for collections managers to report a token on each and every of those platforms.

More, some collections are open (anyone can mint at any time) and decentralized (metadata on IPFS, Arweave or the likes) and it is not technically possible for the collection managers to remove the metadata linked to a token (and sometimes not legally possible if a purchase has been made).
This could sadly end up with the whole collection banned from a platform because of one or a few of the tokens do not respect the law, do copyright infringement, non conformity to ToS, ...

Moreover, NFTs are still "booming" but we will probably soon see a lot of demands to take something down because of case such as copyright infringement, and we will need a way for it to be done on all platforms indexing the data, as fast as possible.

Therefore, this standard makes it possible in a very easy way for those collections to notify all platforms (marketplaces, aggregators, etc...) that a token is no longer supported/valid/recognized by the distributor (for any reason), and that those platforms should therefore update their database to either delete it or at least mark it as flagged.
It also allows other contracts to verify this state before, for example, allowing a sale.

This EIP enable this flagging at the contract level, with the emitting of an event, that can be easily caught by any platform indexing the contract data, and a getter to get the current flag state of a token.

By providing an Event and a Getter, this EIP allows o-chain and off-chain verification of the state, and also make it easy for indexers to get the change of state "as soon as possible".
For aggregators that are not indexing data in real time, the getter would be an easy check to add to the "metadata refresh" system they use.

Note: The right to change the flag state of a token should be given only to the collection owner. This is not meant to be publicly used, as it is a mechanism for collection owners to notify aggregators

## Specification

The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL
NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED", "MAY", and
"OPTIONAL" in this document are to be interpreted as described in
RFC 2119.

**NFT contracts MAY implement this ERC for token flagging to provide a standard method of notifying platforms that a token might have become invalid.**

Marketplaces that support this standard **MAY** decide to not allow transfer of a token if it is flagged

Implementers of this standard **MUST** restrict the right to change the flag state to the collection owner. This is not meant to be publicly used, as it is a mechanism for collection owners to notify aggregators. Not for the public to report content to one platform.

Implementers of this standard **MUST** emit the `TokenFlag` event when a token flag state changes.

Implementers of this standard **MUST** have all of the following events and functions:

```solidity
pragma solidity ^0.6.0;
import "./ERC165.sol";

///
/// @dev Implementation of TokenFlagging
///
interface TokenFlag is ERC165 {
    /// ERC165 bytes to add to interface array - set in parent contract
    /// implementing this standard
    ///
		/// bytes4(keccak256("isTokenFlagged(uint256)")) == 0xcbb1d84c
    /// bytes4 private constant _INTERFACE_ID_TOKENFLAG = 0xcbb1d84c;

    /// @notice Called to return the current flagged state of a token
    /// @param tokenId - the NFT asset queried for flag
    /// @return isFlagged - boolean of the current flag state for the token
    function isTokenFlagged(uint256 tokenId) public returns (bool isFlagged);

    /// @dev This event MUST be emitted when a token flag state changes.
    event TokenFlag(
        address indexed tokenId,
        bool indexed flagged,
    );

    /// @notice Informs callers that this contract supports TokenFlagging
    /// @dev If `_registerInterface(_INTERFACE_ID_TOKENFLAG)` is called
    ///      in the initializer, this should be automatic
    /// @param interfaceID The interface identifier, as specified in ERC-165
    /// @return `true` if the contract implements
    ///         `_INTERFACE_ID_TOKENFLAG` and `false` otherwise
    function supportsInterface(bytes4 interfaceID) external view returns (bool);
}

```
### Examples

This standard being used on an ERC-721 during deployment:

#### Deploying an ERC-721 and setting the royalty amount and creator

```solidity
constructor (string memory name, string memory symbol, string memory baseURI) ERC721(name, symbol) {
        _setBaseURI(baseURI);
        // TokenFlagging interface
        _registerInterface(_INTERFACE_ID_TOKENFLAG);
    }
```

#### Checking if the NFT being sold on your marketplace is flagged

Note: checking about flagging when a sale occurs is completely **OPTIONAL**. This EIP is more about data aggregators and off-chain token display / representation.

```solidity
function checkFlag(address registry, uint256 tokenId) internal returns (bool) {
    (bool success, bytes memory data) = address(registry).call(abi.encodeWithSignature("isTokenFlagged(uint256)", tokenId));
		return success && bool(data);
 }
```

### Too many platforms aggregating data

Today, it is very complicated if not impossible to report a token on every marketplaces and aggregators there is. Also, most platforms have problems to keep up with the current market, and it can be days, if not more, before a token is removed from a platform after being reported.

For open collections that are allowing users to mint without proof-checking every mint before it happens, this is a big problem since one bad apple can result in the whole collection being banned or removed from a platform.

### Not every platform has access to Token Metadata

Some platforms have decided to decentralize the token Metadata, meaning that they store the metadata on decentralized systems (IPFS, Arweave, ...) before linking those metadata in the contract.
This results in the fact that they can not change those metadata to invalidate a token or destruct it, if it were to be something that does not respect the law or the contract manager Terms of Service.

### Ease of use for on-chain and off-chain checking

By providing an Event and a Getter, this EIP allows o-chain and off-chain verification of the state, and also make it easy for indexers to get the change of state "as soon as possible".
For aggregators that are not indexing data in real time, the getter would be an easy check to add to the "metadata refresh" system they use.

### Structure of the TokenFlag event

The `TokenFlag` event will help future-proof this standard and allow potential enhancements in future EIPs.

`tokenId` allows flagging per token, and indexing it allows all consuming platforms to easily react to a flag state change.

`flagged` enables to change the flagging state (for example after a period has passed)

## Backwards Compatibility

This standard is completely compatible with current ERC-721 and ERC-1155 standards and any token standard based on Token IDs.

## Security Considerations

The current proposal only enables the collection (contract) owner to change the flag statet of an NFT, this is due to the fact that fake would hurt the collection and the be a big problem for all platforms.

## Copyright

Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by lenifoti** [comment]
@dievardump Should the entity record the reason for flagging?  A bytes32 that could be standardised in some way perhaps?

**Comment by dievardump** [comment]
> @dievardump Should the entity record the reason for flagging? A bytes32 that could be standardised in some way perhaps?

that's why I wanted to add (in the note 2) maybe a string for the reason.

@agraignic mentioned on discord:

> Just a though about your Note2: wouldn't be interesting to change the bool in uint8 or uint256 to have a 0: not flagged and others values for categories like you said (1: nudity, 2: hate speech ... ), so platforms can get more info about it and get a long description in the string or an URI of the decision?
But I agree this kind of solution feel a bit redundant with the string

I think both your comments join and that it could be a good add

**Comment by anthonygraignic** [comment]
After sleeping on it, I think the `bool` flag is better in the way that consumer platforms won't be able to ignore willingly some category.
But we could include this category in the string.
 

I think the string should contain (or it can be a link to a JSON file):

- category
- reason
- decision URI or precision


A draft list of category from [a comparative study of the Council of Europe](https://rm.coe.int/CoERMPublicCommonSearchServices/DisplayDCTMContent?documentId=09000016806575b6):

- the protection of national security, territorial integrity or public safety (e.g.
terrorism),
- the prevention of disorder or crime (e.g. child pornography),
- the protection of health or morals,
- the protection of the reputation or rights of others (e.g. defamation, invasion of
privacy, intellectual property rights),
- preventing the disclosure of information received in confidence. 


NB: Some interesting reading and EU-related legislation (would love to get inputs from other countries)

- [Illegal content on online platforms](https://digital-strategy.ec.europa.eu/en/policies/illegal-content-online-platforms) 
- [Facebook Transparency Report](https://transparency.facebook.com/)
- [Google Transparency Report](https://transparencyreport.google.com/)
