### ISSUE TITLE
[Discussion] Increasing decentralization on ethv2 and future proofing by algorithmically reducing node costs

### ISSUE THREAD

**Issue by Nielsbishere** [ethereum/EIPs#3562]
Hello everyone,

I personally think PoS is a step in the right direction but it faces a major concern. Risk of centralization. Banks or people with lots of money are the only ones who can start up nodes; nobody has 32ETH laying around anymore especially since it crossed 3k€ (currently over 100k€ to start one node). Because of this, I think the requirement for nodes should in some way depend on the value of Ethereum or risk major centralization problems even more in the future (seeing as eth has a lot of potential to reach even higher). 
Yes, technically you could use an exchange if you don't have 32ETH, but that means that you're still at risk of these exchanges or staking platforms taking more control of this system (and also being dependent on their security). Reducing this to 2 or 4 ETH is already a step in the right direction to allow more decentralization, but it doesn't fight the real problem. This problem being that introducing a hardcoded limit like this isn't future proof and will have to continue being tweaked. 
Maybe there can be a formula that tweaks this value.
It's a difficult problem but I think solving it is important and will matter to make this PoS transition future proof. As well as ensuring huge exchanges like binance don't end up controlling more than 51%.

Thanks for reading, I appreciate any input.
-Nielsbishere

**Comment by Shymaa-Arafat** [comment]
I think I've heard Vitalik Buterin talking in Bankless about POS and a system that provides small contributers with more profit Similar to interest rate( he gave an example of 100$ when 1Eth was = 1000$+)
I'll try to find this certain interview and get back to u
