### ISSUE TITLE
[idea] Cryptonote-style block size and gas limit

### ISSUE THREAD

**Issue by jessielesbian** [ethereum/EIPs#3574]
I believe that using a cryptonote-style block size and gas limit will reduce gas costs greatly. The gas and size limit for a block should be double the average gas usage of the last 256 blocks. Miners can literally run smart contracts using their CPU and mine Ethereum using their GPU at the same time, and in the future, with the introduction of proof-of-stake, miners will have even more spare computational power. Lower gas prices can make a lot of things possible, such as day trading using Defi, and make the Ethereum ecosystem more accessible to people with less than 1 Ether.

**Comment by MicahZoltu** [comment]
Block size is limited partially to reduce state growth over time, which is why we cannot freely increase it.
