### ISSUE TITLE
[Idea] to use an additional consensus mechanism, which I call "additional block hardening" (along with the Proof-of-Stake)

### ISSUE THREAD

**Issue by vstoykovbg** [ethereum/EIPs#3585]
I described how the **additional block hardening** works in my whitepaper.

IPFS download of the whitepaper: [QmNNUEmfLGEbXqWCoSGa2AE8hxR7QuUjou3VVepZK4JrTf](https://cloudflare-ipfs.com/ipfs/QmNNUEmfLGEbXqWCoSGa2AE8hxR7QuUjou3VVepZK4JrTf).

Please note that the **additional block hardening** is different than the Auxiliary Proof of Work (AuxPoW) used in the merged mining.

(The merged mining by using AuxPoW only works with blockchains that both use PoW and the hash algorithm for the PoW is the same.)

The **additional block hardening** can be used by cryptocurrencies that are based on the Proof-of-Stake consensus mechanism - such as Ethereum 2.0. 

The parent blockchain can be selected to be Bitcoin (the blockchain with the most hashing power at the moment). Also, multiple parent blockchains can be used. Some of them may use different consensus mechanisms (not PoW).

To save resources only some of the blocks will be **additionally hardened**, most of the blocks will be validated only with the Proof-of-Stake consensus mechanism.

In [this article](https://academy.binance.com/en/glossary/merged-mining) are described some of the shortcomings of the merged mining:

> However, many developers disagree with such an idea, and claim that merged mining provides a false sense of security. Mainly because a relatively big mining pool that is not particularly dominant on Bitcoin could easily reach 51% hashing power on the smaller chain. A counterargument to this is that if the reward or incentive is good enough to mine this auxiliary chain, it will attract more miners, thus reducing centralization and increasing security.

> Other than that, some say that merged mining decreases security because the economic losses are removed from the process. For instance, Bitcoin miners can use their hashing power on the smaller chain without risking their Bitcoin block rewards. As a consequence, miners would have less reasons to act honestly on the smaller chain.

I think that these shortcomings do not apply to the **additional block hardening** consensus mechanism.

With the AuxPoW method, there may not be enough economic losses when mining "in the wrong direction" (the marginal cost of merged mining may be too small). This allows for abuse.

When using the **additional block hardening** consensus mechanism instead of AuxPoW, miners who perform **additional block hardening** "in the wrong direction" will realize losses (in the amount of the network fees to the parent blockchain). This will incentivize them to behave properly.

To save resources only 1 in 6000 blocks (on average) can be **additionally hardened** by recording the block hash on the Bitcoin blockchain. And 1 in 600 blocks (on average) can be **additionally hardened** by recording the block hash on another blockchain with less energy consumption (with less hashing power).

Moreover, 1 in 100 blocks can be **additionally hardened** by recording the block hash on another blockchain with even less energy usage - like another Proof-of-Stake blockchain.

Please note that the blockchain will not "hang" if no miners want to perform **additional block hardening**. The blockchain will continue to create new blocks validated only with the Proof-of-Stake consensus mechanism as usual because the **additional block hardening** is optional (I explained how it is incentivized in the whitepaper).

**Comment by MicahZoltu** [comment]
What attack vectors are present in Ethereum's Proof of Stake that this would mitigate?

If two miners include two different forks in their Bitcoin blocks, how does an Ethereum client identify which one is canonical?

How exactly would the Ethereum fork choice rule change with this proposal?

**Comment by vstoykovbg** [comment]
> What attack vectors are present in Ethereum's Proof of Stake that this would mitigate?

I assume that all PoS-specific attack vectors are present.

With the **additional block hardening**

> If two miners include two different forks in their Bitcoin blocks, how does an Ethereum client identify which one is canonical?

The Ethereum will follow Bitcoin's canonical fork. It is a rare occurrence for Bitcoin to have long-lasting problems of this nature. I assume that after several Bitcoin blocks it will be clear which is the canonical fork.

The phrase "in their Bitcoin blocks" is not correct, because we assume that the Bitcoin miners and Ethereum node operators are different entities. So, the Bitcoin blocks are not "theirs". The Ethereum nodes include the hash of their Ethereum block via Bitcoin transaction by paying the Bitcoin network fee. All Ethereum nodes monitor the Bitcoin blockchain for the presence of that hash and should achieve consensus that the hash is submitted to the Bitcoin blockchain.

If two Ethereum nodes create two conflicting **additionally hardened blocks** the canonical block will be the Ethereum block with the highest Bitcoin network fee paid for the additional hardening.

If the Bitcoin network fee is the same - the Ethereum clients will prefer the first broadcasted block.

If different Ethereum clients receive the broadcasts in a different order it will be a problematic situation. In this case, only waiting for the next block will solve the problem.

> How exactly would the Ethereum fork choice rule change with this proposal?

It is to be determined.

By performing additional block hardening by writing the Ethereum block hashes on multiple blockchains, more questions about the fork choice rules arise. One way to simplify this is "Via Negativa" -  to use only the Bitcoin blockchain as a **parent blockchain**.

However, using multiple parent blockchains can be beneficial. It will save resources if some of the additionally hardened blocks use less energy-efficient parent blockchains (with smaller network fees). Of course, by energy-efficient, I mean total energy efficiency - including the energy spend in the production of the hardware. On such blockchains, the network fees are typically smaller.

**Comment by axic** [comment]
@vstoykovbg I suggest to open a topic on https://ethresear.ch or https://ethereum-magicians.org, as those forums see more traffic for topics like yours.
