### ISSUE TITLE
EIP-3754: A vanilla non-fungible token standard

### ISSUE THREAD

**Issue by simontianx** [ethereum/EIPs#3753]
## Abstract
A vanilla NFT standard is proposed. In this standard, a non-fungible token stands as atomic existence and encourages layers of abstraction built on top of NFTs. Ideal for representing concepts like right, a form of abstract ownership. Such right, especially on-chain right, can then be made liquid because of this tokenization.

## Rationale
The primary intention of this proposal is not to make a technical improvement to ERC721, although a new technical direction in a subsequent proposal EIP-4341 does present new technical merits, but rather to improve the conceptual clarity of NFTs, i.e., NFTs for digital collectibles, crypto-assets are specified and known by ERC721, and NFTs for abstract ownership such as rights, membership, etc. are specified and known by EIP-3754.

## Use Cases
An example of applying this token to represent the right of making a function call to a contract is given [here](https://github.com/simontianx/ERC3754/blob/main/contracts/ERC3754Example.sol).

An on-chain subscription business model is also made possibe by adopting this token to represent quarterly or yearly membership (time-dependent right). An example can be fees per transaction for off-chain data via an oracle can be replaced by a long-term membership fee. Then as long as the caller has a valid EIP-3754 NFT, the consumption of data feeds is free (plus gas fees). NFTs can be transferred, so is the right of consuming data feeds. This has certain advantages over the current pay-as-you-go business model. An example can be found [here](https://github.com/simontianx/ERC3754/blob/main/contracts/OracleMembership.sol).

A mid-layer can be added between NFT buyers and NFT creators with this standard. Currently, NFT creators have difficulty setting up initial prices and NFT buyers have the fear of missing out good NFTs. A mid-layer can be added between the two sides by minting ERC3754 NFTs as rights to purchase NFTs. NFT creators can presale such rights at lower prices and set the initial prices higher. For NFT buyers, buying such rights is a small commitment and can sell such rights if they do not like the NFTs minted later on. It can be best understood as a call option on an NFT. Effectively, this is a market making layer by reducing the bid-ask spread. A similar but slightly different idea can be seen in "@0xKiwi_ designed for @uwucrewnft". An in-house toy example can be found [here](https://github.com/simontianx/ERC3754/blob/main/contracts/NFTOption.sol).

A virtual coupon can be built by this standard. Ownership of such NFTs can enjoy certain discounts over a preset period of time.

Another great illustration of this concept can be found in this [tweet](https://twitter.com/AndreCronjeTech/status/1432687892497895425) that Andre Cronje sold the naming rights to his Twitter account to FTX.

**Comment by abcoathup** [comment]
Metadata extension is optional in ERC721 (https://eips.ethereum.org/EIPS/eip-721#specification)

https://eips.ethereum.org/EIPS/eip-721#specification

> The metadata extension is OPTIONAL for ERC-721 smart contracts (see “caveats”, below). This allows your smart contract to be interrogated for its name and for details about the assets which your NFTs represent.

It looks like all this EIP is trying to do is remove reference to the tokenURI.  Can the use case not be met with either not using the metadata extension or the tokenURI returning some generic JSON?

Similar question asked in: https://ethereum-magicians.org/t/eip-3754-a-vanilla-non-fungible-token-standard/6926/2?u=abcoathup

**Comment by simontianx** [comment]
@abcoathup Hey Andew, thanks for the question. ERC-721 is indeed the super set to the proposed standard here. That also introduces problems in practice. I personally had experiences explaining this new way of using NFTs to people and received doubts and disbeliefs in return, even though `URI`s are technically OPTIONAL.

A simplification can actually reduce the concept of NFT to its core, which is a non-fungible token. It really does not have to be attached to any metadata or link to external media contents. This simplification can actually open up new possibilities on-chain by allowing layers of abstraction built on top of a non-fungible token.

We are building an application of this type. So I know it has a great amount of potential.

**Comment by simontianx** [comment]
One more point to add is yes, NFTs can technically have `URI`s being set as empty strings, but a strange phenomenon could arise that if such tokens are listed on NFT platforms, no media contents are going to be shown, even though they are totally ERC721 compliant.

The ERC3754 standard can help avoid such phenomenon.

**Comment by ndrslmpk** [comment]
Can you explain what the actual problem about the URI issue is? Isn't it an implementation detail on side of the actual NFT platform to show NFTs that are not associated to URIs, instead of establishing a new Token Standard to avoid that case handling?

**Comment by simontianx** [comment]
@ndrslmpk I think this is a situation that can be best described as "less is more".

NFTs are generally used to represent ownership of external media contents, or some other tangible items. They can also be used to represent abstract concepts like rights, a form of abstract ownership. An example of rights is having NFT#1 is allowed to do actions A, B, C, and having NFT#2 is allowed to do D, E, F. In such scenarios, `URI`s are truly redundant.

A clear separation between the two rather than blending both in one is good for conceptual clarity.

**Comment by abcoathup** [comment]
> @abcoathup Hey Andew, thanks for the question. ERC-721 is indeed the super set to the proposed standard here. That also introduces problems in practice. I personally had experiences explaining this new way of using NFTs to people and received confusion and doubts in return, even though `URI`s are technically OPTIONAL.

@simontianx there is already ecosystem support for ERC721, and this EIP is ERC721 without the optional components.
I am struggling to see the need and to see how this EIP would get ecosystem support.

In the use case described, with NFT#1 having actions ABC and NFT#2 having actions DEF, then including the actions in the metadata would appear to be worthwhile to describe how they can be used.

**Comment by simontianx** [comment]
@abcoathup 
> this EIP is ERC721 without the optional components.
The logical relationship between ERC721 and this standard can be expressed with notations from Solidity as `ERC721 is ERC3754`. 

> metadata would appear to be worthwhile to describe how they can be used
Heuristic speaking, the metadata idea is extending abstraction on the same level in the logic hierarchy and this standard encourages building abstraction on higher levels.

**Comment by zhaochengpro** [comment]
@simontianx hey simon, maybe i can understand what's you mean. you think the EIC721 standard should more kernalization. and More customized things(like URI,data fields) should be done by developer who need these. 
but i have some question that is it neccessary to remove these? 
Is it worth to remove these from EIC721?(maybe more kernalization) if the value of the change is minimal, i think it doesn't necessary.

**Comment by simontianx** [comment]
Hey @zhaochengpro , can you elaborate on kernalization? The intention of this proposal is more for marketing a new set of possibilities which would be drastically different from current use cases put up by ERC721 than for making a technical improvement. As mentioned in the first comment in this thread, a few critical use cases of NFTs are conceptually quite inconsistent with ERC721. A new proposal can help improve the conceptual clarity of NFTs, i.e., NFTs for digital collectibles, crypto-assets are specified by ERC721, NFTs for abstract ownership such as rights, membership, etc. are specified by EIP-3754.
