### ISSUE TITLE
EIP-1155 is subject to the Billion-dolar-mistake, risking value lost

### ISSUE THREAD

**Issue by earizon** [ethereum/EIPs#3974]
EIP-1155 chooses the arbitrary decision to use address 0x0 when burning/destroying tokens as well as when minting new ones.

**0x0 is a very risky address** since external clients can in different (and buggy) scenarios send a false 0x0 when a variable has not been properly initialized, an error or exception not managed properly, a parse fail, ...

An alternative address like: `address( uint160( uint256( sha256("burn_address") )))  ` will avoid this security risk as well as provide for cleaner and easier to read code.

Using an address (or set of addresses) based on a (set of) well-defined string/s can also allow for future enhancements of the API by adding new addresses with semantic meaning without breaking the interface.

**Comment by axic** [comment]
@earizon I'd suggest to comment on the discussion URL of the EIP (which in this case is #1155, IIRC).
