### ISSUE TITLE
Disable the bot

### ISSUE THREAD

**Issue by Garito** [ethereum/EIPs#4186]
I hope that after today's madness with the bot someone take an action and slow it down or totally disables it
It is crazy and stupid, IMO

**Comment by MicahZoltu** [comment]
Hopefully the bugs have been worked out and the bot won't close and re-open any more PRs.  😄  The work is done at this point, so disabling I don't think is necessary.  Feel free to re-open this issue if you would like to discuss further.

**Comment by Garito** [comment]
The bug haven't been worked at all
And i can't reopen this issue cause there is no button

**Comment by Garito** [comment]
200+ bot messages...

**Comment by MicahZoltu** [comment]
Yes, more bugs were found.  You don't see a green `New issue` button in the top right of this page?

**Comment by MicahZoltu** [comment]
The bugs are all fixed as far as we know.  However, more could pop up in the future.

**Comment by Garito** [comment]
Disable the bot then
How many will left next storm? One at least
