### ISSUE TITLE
Scripts as NFTs, looking for a standard.

### ISSUE THREAD

**Issue by DanielAbalde** [ethereum/EIPs#4209]
Hi there,

I develop a plugin for an algorithmic 3d modelling software, i.e. to program visually using a nodal editor to generate a 3d model, aka procedural design. These can be brought into a webapp to offer to the client a widget with the input parameters and the final 3d result that they can change to their preferences and buy, aka mass customizable product configurators.

I want to tokenise the blocks or nodes that make up these algorithms or scripts, so that the sale rewards the authors somehow. So, it seems to me that it is not exactly an archetypical NFT, since my point is not to resell the NFT, but to use it as a process/service, so when a sale is triggered, give a share of the profit to the authors.

**Is there a standard for this? Can someone direct me where to look?**

If you are interested in talking about this, you can find out how to connect with me on my profile.

Thanks!

**Comment by MicahZoltu** [comment]
There is no need for a standard for this, you can just build an app that does what you have described.  Standards make the most sense when there is a many-to-many relationship between clients and servers or providers and consumers.  In this case, you (the provider) would simply provide a service to all of your clients.  There is no need to go through the effort of standardization for that.

Also, https://ethereum-magicians.org/ is a more correct place for this kind of discussion topic, so I'm going to close this but if you want to continue I recommend creating a thread there.  😄
