### ISSUE TITLE
EIP registries

### ISSUE THREAD

**Issue by Arachnid** [ethereum/EIPs#4335]
Some EIPs require registries - lists of mappings relevant to the EIP. Examples include EIP 191 and EIP 634.

Currently, there's no good solution for this: changes to an EIP are prohibited after it's final, so the registry can't be kept inside the EIP itself, and external links are likewise prohibited, so the registry can't be kept elsewhere.

The IETF maintains a list of registries; each RFC can define one or more new named registries, and the registries are maintained separately from the (final) RFC. We should define a best practice for this with EIPs.

**Comment by Arachnid** [comment]
Tagging @MicahZoltu as the chief no-external-links agitator. :)

**Comment by Arachnid** [comment]
> If we just want to give control to some operator (or group of operators) things are simple

This is pretty much how EIPs work; I don't see a problem with replicating this for registries.

> A while back someone built a censorship resistant registry called ENS which did a pretty good job of protecting itself from future censorship and capture, could we just use that system? e.g., allow people to point at an on-chain registry from their EIPs and leave it up to on-chain contracts for access control.

I don't think there's any reason to have this onchain - and doing so doesn't really solve any issues that using Git doesn't.

**Comment by Arachnid** [comment]
Rather than adding it to the EIPs repo as a new type of EIP, I'd suggest a new repo specifically for registries, that EIPs can reference. Otherwise, agreed.

**Comment by Pandapip1** [comment]
> I would really rather avoid re-building something like ENS for every list, and I'm not a fan of EIPs that just point at some censorable/closed registry, as that feels like it goes against the ethos of Ethereum to me.

My proposal (#4835), would actually be a pretty good start for this. The `canSetDomain` and `canDeleteDomain` functions could always return false, and the `canCreateDomain` could implement some sort of check on the domain that would be set.

**Comment by Hgaras** [comment]
> تتطلب بعض خطط الاستثمار في الطاقة سجلات - قوائم بالتعيينات ذات الصلة بخطة الاستثمار في الطاقة. ومن الأمثلة على ذلك خطتا الاستثمار في الطاقة 191 و634.
> 
> لا يوجد حل جيد لهذه المشكلة حاليًا: يُحظر إجراء أي تغييرات على EIP بعد إقراره نهائيًا، وبالتالي لا يمكن الاحتفاظ بالسجل داخل EIP نفسه، كما تُحظر الروابط الخارجية أيضًا، وبالتالي لا يمكن الاحتفاظ بالسجل في أي مكان آخر.
> 
> تحتفظ مجموعة عمل هندسة الإنترنت (IETF) بقائمة من السجلات؛ ويمكن لكل طلب تعليقات (RFC) تعريف سجل جديد مُسمّى واحد أو أكثر، وتُحفظ السجلات بشكل منفصل عن طلب التعليقات (RFC) النهائي. ينبغي تحديد أفضل ممارسة لذلك باستخدام بروتوكولات تحسين البنية التحتية (EIPs).
