### ISSUE TITLE
[EIP-4381] General metadata container contract

### ISSUE THREAD

**Issue by 3rdstage** [ethereum/EIPs#4381]
Motivation
----
As more data come into on-chain, the need for data describing the data (metadata) is increasing more.
The existing approaches seem to be too simple or too complex.  Storing just a link to off-chain location is too simple to assure the sufficiency of the metadata or trace the change of metadata.  Using schema language and storing a single entire  metadata in JSON string into a property doesn't seem to be efficient to access metadata selectively.

One of the best references for such general meta-data container structure is [HTTP header fields](https://en.wikipedia.org/wiki/List_of_HTTP_header_fields). HTTP header fields can support any type of meta-data because they don't require type definition. HTTP header fields also support multi-value field effectively.

I want to suggest general meta-data container base contract named `IAttributeRegistry` following the behavior of HTTP header fields operations.

Specification
----
The `IAttributeRegistry` contract is a general meta-data container contract expected to be base contract for more concrete usage.

A meta-data is modeled to be name(key)-value pair and has no type concept currently. Both `name` and `value` are treated as string. Multiple values can be paired to a single `name`.

The interface for `IAttributeRegistry` contract would be like the following.

~~~~solidity

struct Attribute{
    string name;
    string value;
}

interface IAttributeRegistry is IERC165{

    event AttributeAdded(uint indexed id, string indexed name, string value, uint no);
    event AttributeRemoved(uint indexed id, string indexed name, string value);    
    event AttributesRemoved(uint indexed id, string indexed name);

    function getAttributeNames(uint id) external view returns (string[] memory);
    
    function getAttribute(uint id, string memory name) external view returns (string memory);

    function getAttributes(uint id, string memory name) external view returns (string[] memory);

    function getAttributesCount(uint id, string memory name) external view returns (uint);

    function setAttribute(uint id, string memory name, string memory value) external;
    
    function addAttribute(uint id, string memory name, string memory value) external;

    function removeAttribute(uint id, string memory name, string memory value) external;

    function removeAttributes(uint id, string memory name) external;
}
~~~~

Typically a single `IIAttributeRegistry` contract paired with a single `ERC721` contract.  The `id` in `IAttributeRegistry` can be `tokenId` in `ERC721` contract.

**Comment by akiszka** [comment]
Hello!

If you are interested in cooperating in making this an official EIP, please let me know. I would love to help in creating something like this.

Just a note: if you haven't done that yet, I think it would be a great idea to post on Ethereum Magicians to find out if there is demand for this EIP.

**Comment by MicahZoltu** [comment]
Please move this to Ethereum Magicians to discuss the idea, or create a pull request to create an EIP if you would prefer that.
