### ISSUE TITLE
Bug: Duplicate Event Topics for ERC20 and ERC721 Transfer Events

### ISSUE THREAD

**Issue by daweth** [ethereum/EIPs#4426]
I will keep this short and simple.

Basically, when an event log for Transfer is emitted from a contract that is ERC20, it has the Topics[0] ID of `0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef`, which is ultimately derived from `Transfer(address,address,uint256)`.

The problem is that ERC721 also has the exact same Topics[0] ID, but with a different use case. Namely, the uint256 is for TokenID and not for Amount.

Something should be added to the Topics ID such that it can be determined that the events are different.

If this is part of the design, please help me understand why?

**Comment by MicahZoltu** [comment]
This repository is for proposing new standards.  For discussing existing standards, I recommend posting a comment on the relevant `discussions-to` thread (in the header of every EIP).  In this case, I you would go to https://eips.ethereum.org/EIPS/eip-721 and click on the `discussions-to` link in the EIP frontmatter.
