### ISSUE TITLE
Discussions: EIP-4430

### ISSUE THREAD

**Issue by ricmoo** [ethereum/EIPs#4431]
A discussions issue to track comments on EIP-4430.

## Simple Summary

A technique for contract authors to enable wallets to provide a human-readable description of the effect of of a transaction with a given contract.

## Abstract

Use a contract method to provide *virtual funcions* which can generate a human-readable description at the same time as the machine-readable bytecode, allowing the user to agree to the human-readable component in a UI while the machine can execute the bytecode once accepted.

**Comment by SMALLjohnson** [comment]
> A discussions issue to track comments on EIP-4430.
> 
> ## Simple Summary
> A technique for contract authors to enable wallets to provide a human-readable description of the effect of of a transaction with a given contract.
> 
> ## Abstract
> Use a contract method to provide _virtual funcions_ which can generate a human-readable description at the same time as the machine-readable bytecode, allowing the user to agree to the human-readable component in a UI while the machine can execute the bytecode once accepted.

**Comment by uttaravadina** [comment]
So the idea is to generate a documentation-like information for a given contract at compilation time. But maybe not something like a doxygen-style doc generation, where the developer provides the comments for each of those members (functions + variables) in the solidity code.
Instead, the solidity compiler or an independent program itself should generate it for each of those members which can be used when a web3 user interacts using web2 components (web app).

Does that read like what you are proposing, is it different?

**Comment by ricmoo** [comment]
This is not at compilation time like doxygen, if I understand your question.

for some background, you can check out EIP-3224 which this was originally part of but was requested to be split into two separate EIPs.

This is a method the contract author adds, which is compiled into the contract though.

Imagine if your contract had a method like: `acceptProposal(bytes32 hash, bytes signature)` which would use ecrecovery to vote your address as accepting the proposal. The best things like MetaMask could do today is present you with a UX of “do you agree to this? { Scary Hash Goes Here }”.

This would allow a virtual function, which MetaMask can generically understand (i.e. MetaMask doesn’t even have to have know about your contract before and didn’t need to include any additional custom config) may look like `acceptProposal(string name, uint date, uint[] payouts, address[] recipients)`, which would return 2 things:

- the string to display to the user, “do you agree to the propose ‘pay the devs’, on November 11, 2021 to pay ricmoo.eth an amount of 1.21 eth, nick.eth an amount of 2.3 eth and 0x1234567…6754 an amount of 0.6 eth?”
- The bytes necessary from the non-virtual function, `approveProosal(bytes32,bytes)`

So MetaMask can give the user a meaningful description and once agreed, MetaMask can sign the payload, and do whatever the signed payload should do (likely submit them to a server which would then send the transaction or commit it to a state channel).

I’ll be adding more examples to this soon. Right now I’m just getting the EIP broken into the 4 separate EIPs I was suggested to do. :)

**Comment by ComplaintID** [comment]
Message them on Twitter about your complaints. Send them a direct message to get your issues resolved. I had the same issues too
https://twitter.com/messages/compose?recipient_id=884210741347332100

**Comment by mryalamanchi** [comment]
Hello Richard. This is an interesting eip, possibly, improving towards the UX for the web3 users. Thanks for the submission!

As I understand, per the original discussion on eip-3224, you are in the process of splitting it into 4 seperate EIPs to address the UX issue for web3 users.

web3 user's UX issue: "I want to know what's happening when I am interacting with the dApps, explained in plain words", if possible in the user's locale.

I am currently going through eip-3224 and it's pre-requisite eip to better understand. Please be patient, I will reach out to you shortly.

**Comment by MrStimuli** [comment]
Erc-1155 having issues with my string sha256

**Comment by MrStimuli** [comment]
Never received anything

**Comment by ricmoo** [comment]
This has been updated in the EIP; the discussions thread is now located on [Ethereum Magicians](https://ethereum-magicians.org/t/discussion-eip-4430-described-transactions/8762).

**Comment by Anitapita1973** [comment]
> A discussions issue to track comments on EIP-4430.
> 
> ## Simple Summary
> A technique for contract authors to enable wallets to provide a human-readable description of the effect of of a transaction with a given contract.
> 
> ## Abstract
> Use a contract method to provide _virtual funcions_ which can generate a human-readable description at the same time as the machine-readable bytecode, allowing the user to agree to the human-readable component in a UI while the machine can execute the bytecode once accepted.

I need my money back

**Comment by Pandapip1** [comment]
This should be closed. It is no longer a discussions-to link. CC @MicahZoltu
