### ISSUE TITLE
[EIP-2233] Stock Token

### ISSUE THREAD

**Issue by falstack** [ethereum/EIPs#4474]
## Abstract

The following standard allows for the implementation of a standard API for Stock tokens within smart contracts.

We refer to the equity distribution system of the entity company and divide the types of stocks into the following types:

- Shares allocated by percentage
- Shares distributed by amount

Shares distributed according to the amount are like the ERC-20 standard, but it is difficult to describe the shares distributed according to the percentage under the ERC-20 standard.

## Motivation

This standard is inspired by the ERC-20 token standard and by establishing new standards to support percentage tokens, it can make the issuance of tokens or the establishment of a company easier.

**Comment by abcoathup** [comment]
Please note:
EIP numbers are generally the PR number or, if preferred by the author, the Issue # if there was discussion in the Issues section of the EIP repository about the EIP
See: https://eips.ethereum.org/EIPS/eip-1#eip-editor-responsibilities

**Comment by falstack** [comment]
@abcoathup Thank you for your guidance, let me read the specification first
