### ISSUE TITLE
Unsecured Leasing NFT Promotes the Development of Metaverse's Sharing Economy

### ISSUE THREAD

**Issue by KKimos** [ethereum/EIPs#4509]
This standard adds a new right of Non-Fungible Token that the right to use. Through this standard, you can achieve :

- Separation of the right to use and ownership of Non-Fungible Token
- Non-secured lease Non-Fungible Token
- You can continue to use it after you mortgage the Non-Fungible Token
- Metaverse sharing economy

It is precisely because of the separation of ownership and use right that the utilization rate of assets can be greater. You must distinguish between the rights of the user and the owner.

Different from 2615, we only added a right to use, so that we can get all the functions of 2615, and reduce many unnecessary operations in 2615. The explanation is as follows:
 - The owner should not use some of the ownership rights when mortgage NFT, such as transfer, AXS-like breeding or weapon upgrade, because it is likely to change the status of the original NFT, so when the user mortgages the NFT, the ownership must be mortgaged in the contract middle.
 - In the case of mortgage or transaction, the owner has the right to continue to use it before returning the ransom or selling it

This is the result of my implementation, you can refer to https://github.com/cryptosharing/ERC9999

**Comment by MicahZoltu** [comment]
Please create a thread at https://ethereum-magicians.org/ to discuss this idea.

**Comment by wvans123** [comment]
Nice proposal for future metaverse sharing economy, wish a new era come
