### ISSUE TITLE
Only run github actions on the canonical EIPs repository

### ISSUE THREAD

**Issue by SamWilsn** [ethereum/EIPs#4526]
As @gcolvin noted in the Discord, the bots for the EIPs process will run inside third-party forks if Actions are enabled. This can be kind of annoying if you're working on a draft or proposal that isn't ready for review yet.

I suggest adding something like:

```yaml
if: github.repository_owner == 'ethereum'
```

to the jobs.

**Comment by alita-moore** [comment]
Send easy enough

**Comment by mryalamanchi** [comment]
@alita-moore did you pick this task or can I move forward with it?

**Comment by alita-moore** [comment]
Yea that's fine @mryalamanchi

**Comment by mryalamanchi** [comment]
This issue is resolved. Can we close this @SamWilsn @alita-moore?

**Comment by alita-moore** [comment]
Yep
