### ISSUE TITLE
EIP-3220 automatic generation of crosschainId

### ISSUE THREAD

**Issue by weijia31415** [ethereum/EIPs#4548]
EEA (Enterprise Ethereum Alliance) had a review of EIP-3220 and suggested that crosschain identifier should be generated unattended.  This means that the field of ChainType (2 bytes) and Governance identifier (2 bytes) should be replaced or removed.  This way, any blockchain crosschain id can be generated with genesis block header or forked block header in combination of current chainid.

**Comment by MicahZoltu** [comment]
Please discuss this at the discussions-to link for the EIP, which can be found in the header of the EIP at https://eips.ethereum.org/EIPS/eip-3220
