### ISSUE TITLE
I need to add the token icon, is there a detailed operation process

### ISSUE THREAD

**Issue by 5kkk** [ethereum/EIPs#4556]

**Comment by chee-chyuan** [comment]
i am not sure that your question is clear and am also not sure this is an eip related question

**Comment by mryalamanchi** [comment]
This question is not relevant to this repo.
I suggest you ask this on other relevant communities available here: https://ethereum.org/en/community/online/

**Comment by poojaranjan** [comment]
This doesn't seem like a real issue. Should it be closed?

**Comment by mryalamanchi** [comment]
Yes, it should be closed.
