### ISSUE TITLE
Hi @flexsurfer, that's because MetaMask implements [EIP-1102](https://eips.ethereum.org/EIPS/eip-1102). You have to call `ethereum.request({ method: 'eth_requestAccounts' })` first. Since you're asking about MetaMask specifically, I'll also refer you to the relevant section of our [documentation](https://docs.metamask.io/guide/ethereum-provider.html#using-the-provider).

### ISSUE THREAD

**Issue by amin1419** [ethereum/EIPs#4561]
Hi @flexsurfer, that's because MetaMask implements [EIP-1102](https://eips.ethereum.org/EIPS/eip-1102). You have to call `ethereum.request({ method: 'eth_requestAccounts' })` first. Since you're asking about MetaMask specifically, I'll also refer you to the relevant section of our [documentation](https://docs.metamask.io/guide/ethereum-provider.html#using-the-provider).

_Originally posted by @rekmarks in https://github.com/ethereum/EIPs/issues/2319#issuecomment-775257788_

**Comment by mryalamanchi** [comment]
@amin1419 this issue is not clear and just a repost of an old comment. This issue will be closed.

@poojaranjan @lightclient
