### ISSUE TITLE
Incorrect naming for eip-micropayments_standard_for_nfts_and_multi_tokens.md. 

### ISSUE THREAD

**Issue by mryalamanchi** [ethereum/EIPs#4614]
APMU, the EIPs are to be numbered and not contain the EIP title.
This EIP's filename has deviated from the common practice 
and has also generated a deviated link [eip-micropayments_standard_for_nfts_and_multi_tokens](https://eips.ethereum.org/EIPS/eip-micropayments_standard_for_nfts_and_multi_tokens)

Should this be handled the same way [eip-20-token-standard.md](../blob/master/EIPS/eip-20-token-standard.md) -> [eip-20](../blob/master/EIPS/eip-20.md) was handled?

**Comment by MicahZoltu** [comment]
Hmm, I'm surprised the bot allowed that to be merged.  PR to rename it would be very much appreciated!  Feel free to mention me on such a PR.  No need to do any complicated migration as the EIP is just a draft and only recently merged.

**Comment by mryalamanchi** [comment]
Alright! Will just rename the EIP now and later check with the bot issue.

**Comment by mryalamanchi** [comment]
Done: <https://github.com/ethereum/EIPs/pull/4619>

**Comment by MicahZoltu** [comment]
Related: https://github.com/lightclient/eipv/issues/40
