### ISSUE TITLE
Idea : Adding block in two way order of genesis block

### ISSUE THREAD

**Issue by saurabhburade** [ethereum/EIPs#4638]
### Focused Problem

- The current implementation for ANY sort of blockchain is considered to add blocks afterward of the genesis block.

### Solution Proposed [In Idea State]

- Allow the blockchain to add blocks on both sides of the blockchain (Left & Right) genesis block.
- Every block to contains the flag to represent the side on which it will get added.
- One of the calculation mechanisms will calculate the time to add block and transfer it to the most preferable side.

#### Basic overview
![alt text](https://raw.githubusercontent.com/saurabhburade/Eth-proposal/main/genesis.png)
#### Mechanism 
![alt text](https://raw.githubusercontent.com/saurabhburade/Eth-proposal/main/proposal2.png)

**Comment by MicahZoltu** [comment]
See comment from bot above for a more appropriate place for ideas.
