### ISSUE TITLE
Controllable Resolution Path For NFT Ownership

### ISSUE THREAD

**Issue by cucrisis** [ethereum/EIPs#4650]
Current NFT standards such as ERC721, ERC1155 use a mapping of the NFT owner wallet address and the asset `tokenId` to store and resolve representation of ownership. In both ERC721 and ERC1155 when a new instance is minted/created a new record is added to the ownership mapping. To display an NFT knowing the `tokenId` the entry-point to the contract is usually either through a call to `tokenURI` or `uri`,  both intended to return a `URI` that leads to the NFT metadata object. In observed NFTs implementations the full `URI` or a `fragment` of it can _sometimes_ be controlled by the owner of the collection, but **never by the owner of the NFT instance (token)**.  After the  NFT instance `URI` is resolved to the metadata object, the scheme most likely contains `pointers` to the location of the NFT instance digital asset object (JPG, PNG, MOV ...etc.), mostly in the form of a `URI`. Owners of the digital asset object have no control over the `pointers` value as well, **making it impossible to fully own the asset lifecycle.** 

**Problem** 
NFT owners have no **control/ownership** of their NFTs digital objects **resolution path**, leading to incomplete ownership representation and potential security risk.

 **Potential Solution**

- **Metadata reside outside of the contract:**  NFT standards should include methods that allow assets owners to change the result of `tokenURI`, `uri` and equivalent to their own specified value.

- **Metadata within the contract:**  NFT standards should include methods that allow assets owners to change the digital asset media object `pointers` without affecting the rest of the NFT collection owner resolution path.

```
contract OwnableNFT  {
    [...snip...]

    // 
    modifier onlyNftOwner() {
        require(NftOwner(tokenId) == _msgSender(), "Ownable NFT: only token owner can change location");
        _;
    }
   
     // Change the value of the digital object `pointers`
     function changeURI(uint256 tokenId, string memory newURI) public view onlyNftOwner {
         [...snip...]
     }
    
    // Rest URI to default location
    function resetURI(uint256 tokenId, string memory newURI) public view onlyNftOwner {
         [...snip...]
     }
}
````

**Comment by theCuratorCM** [comment]
This is a problem to be solved, ie. permissioned updating of metadata. However, what stops someone in your instance from changing their token's metadata to be the same as another NFT in the same collection (for example)?

**Comment by cucrisis** [comment]
indeed, the two proposed function are just the start to a change, i believe other controls has to be in place to complete the overall objective and achieve true ownership. I will move this discussion to Ethereum Magicians as recommended.

**Comment by cucrisis** [comment]
https://ethereum-magicians.org/t/controllable-resolution-path-for-nft-ownership/7945
