### ISSUE TITLE
ENUM as ABI type

### ISSUE THREAD

**Issue by alexvandesande** [ethereum/EIPs#47]
A [FAQ on the solidity docs](https://solidity.readthedocs.org/en/latest/frequently-asked-questions.html#if-i-return-an-enum-i-only-get-integer-values-in-web3-js-how-to-get-the-named-values): 

> **If I return an enum, I only get integer values in web3.js. How to get the named values?**
> Enums are not supported by the ABI, they are just supported by Solidity. You have to do the mapping yourself for now, we might provide some help later.

Enums would actually very useful types to be exposed on the ABI, specially for auto generated interfaces on the wallet and on abi2html, for example. On the read side, properties could be exposed as words instead of meaningless integers. On the execute side, enums could be rendered as drop down or radio boxes.

This would make interface creation easier.

**Comment by chriseth** [comment]
Any ideas for the notation?
`[Val1,Val2,Val3]`
`(Val1|Val2|Val3)`

**Comment by alexvandesande** [comment]
Well it's an array of strings right? Shouldn't it be '[ \'value 1\', \'value 2\', etc]' ?

**Comment by chriseth** [comment]
I would say that it is rather a list of identifiers instead of strings. Furthermore, I think it would be a good idea to differentiate enums from a tuple/struct types.
If `enum` or similar keywords are not used, the common way to notate such types is using `|`:
https://en.wikipedia.org/wiki/Sum_type

**Comment by tgerring** [comment]
On first glance, `[Val1,Val2,Val3]` appears to be a collection of objects. To avoid confusion with that common notation, I'd personally prefer the pipe-delimiter or something that is difficult to confuse with another type.

**Comment by axic** [comment]
> As we kind of settled for anonymous structs in the other EIP, enums should also be anonymous.

Which other EIP are you referring to? I've only found the timestamps prior to this one.

Would it be any harm making it more explicit such as `enum(Val1|Val2|Val3)` or `enum(Val1,Val2,Val3)` ?

Just trying to avoid a situation where new types will have a weird notation to avoid collisions.

**Comment by chriseth** [comment]
I was referring to this proposal here: https://github.com/ethereum/EIPs/issues/21

My reasoning behind not using explicit `enum` and `struct` strings was that names are always hard to get consensus on and different languages might use different names for these type constructs. You are right that explicit `enum` and `struct` prefixes avoid collisions (and also makes it easier to parse), but having to use `struct` at the inner level and not at the outermost level makes it a bit less elegant.

**Comment by axic** [comment]
I don't think it would hurt to have `struct` written out on all levels, but as it is a more frequent construct I can understand if that won't be the case.

However, usually `enum` is less frequently used and I think it makes sense to be explicit in that case.

**Comment by alextnetto** [comment]
This is very much needed. It would help UX a lot by making programmatic dropdowns for enums.
