### ISSUE TITLE
EIP 4337 typos

### ISSUE THREAD

**Issue by svskaushik** [ethereum/EIPs#4783]
Suggestion to fix the following typos in EIP-4337:

84 : worlflow -> workflow
89 : simulateWalletValidation -> simulateValidation
165 : valiation -> validation
172: comma position
176: can not -> cannot
180: period at the end of line
236: `must` -> **must**
238: `should` -> **should**
238: `should not` -> **should not**
275: addressed -> address

**Comment by poojaranjan** [comment]
Thank you for creating this issue, @svskaushik.

Do you think you can create a PR to make these changes added to the proposal? If you need any assistance, making a PR, let us know.

**Comment by Aniket21mathur** [comment]
Hii @poojaranjan. I think https://github.com/ethereum/EIPs/commit/8e31fb872433cdf9742193105d5a460f2bfc3a72 closes this issue.
