### ISSUE TITLE
EIP-4804: Web3

### ISSUE THREAD

**Issue by qizhou** [ethereum/EIPs#4804]
---
eip: 4804
title: Web3 URL to EVM Call Message Translation
author: Qi Zhou (@qizhou)
discussions-to: https://ethereum-magicians.org/t/eip-4804-web3-url-to-evm-call-message-translation/8300
type: Standards Track
category: ERC
status: Draft
created: 2022-02-14
requires: N/A
---

## Simple Summary

A translation of an HTTP-style Web3 URL to an EVM call message

## Abstract

The standard translates an HTTP-style Web3 URL like

```web3://uniswap.eth/```

to an EVM message such as 
```
EVMMessage {
   To: 0xaabbccddee.... // where uniswap.eth's address registered at ENS
   Calldata: 0x
   ...
}
```
## Motivation

Currently, reading data from Web3 generally relies on a translation done by a Web2 proxy to Web3 blockchain.  The translation is mostly done by the proxies such as dApp webistes/node service provider/etherscan, which are out of the control of users.  The standard here aims to provide a simple way for Web2 users to directly access the content of Web3.

## Specification

The specification here only specifies for the read EVM message.  Write message will be defined in the future EIPs.

A Web3 URL is in the following form

```
Web3URL = "web3://" [userinfo "@"] contractName [":" chainid] path
contractName = [ address | name "." nsProvider]
path = ["/" method ["/" argument_0 ["/" argument_1 ... ]]]
argument = [type "#"] value
```
where 
- "web3://" indicates the Web3 URL **schema**.
- **userinfo** indicates which user is calling the EVM, i.e., "From" field in EVM call message.  If not specified, the protocol will use 0x0 as the sender address.
- **contractName** indicates the contract to be called, i.e., "To" field in the EVM call message. If the **contractName** is an **address**, i.e., 0x + 20-byte-data hex, then "To" will be the address.  Otherwise, the name is from a name service.  In the second case, **nsProvider** will be the short name of name service providers such as "ens", "w3q", etc.  The way to translate the name from a name service to an address will be defined in future EIPs.
- **chainid** indicates which chain to call the message.  If not specified, the protocol will use the same chain as the name service provider, e.g., 1 for eth, and 333 for w3q.  If no name service provider is available, the default chainid is 1.

### Resolver Mode

Once the "To" address and chainid are determined, the protocol will check the resolver mode of contract by calling "resolverMode" method.  The protocol currently supports two resolver modes:
#### Manual Mode
The manual mode will not do any interpretation of **path**, and put **path** as calldata of the message directly.

#### Auto Mode
The auto mode is the default mode of resolver (also applies when the "resolverMode" method is unavailable in the target contract).  In the auto mode, if **path** is empty, then the protocol will call the target contract with empty calldata.  Otherwise, the calldata of the EVM message will use standard Eterheum contract ABI https://docs.soliditylang.org/en/v0.8.3/abi-spec.html, where
- **method** is a string of function method be called
- **argument_i** is the ith argument of the method.  If **type** is specified, the value will be translated to the corresponding type.  The protocol currently supports the basic types such as uint256, bytes32, address, and bytes.  If **type** is not specific, then the type will be automatically detected using the following rule
1. **type** = "uint256", if **value** is numeric
2. **type**="bytes32", if **value** is in the form of 0x+32-byte-data hex
3. **type**="address", if **value** is in the form of 0x+20-byte-data hex
4. else **type**="bytes"

#### Example 1
``` web3://uniswap.eth ```

The protocol will find the address of **uniswap.eth** from ENS, and then call the address with "From" = "0x00...0" and "Calldata" = "0x" with chainid = 1.

#### Example 2
```web3://opensea.eth:333```

The protocol will find the address of **opensea.eth** from ENS, and then call the address with "From" = "0x00...0" and "Calldata" = "0x" with chainid = 333.

#### Example 3
```web3://twitter.w3q/view/15235234234234```

The protocol will find the address of **twitter.w3q** from W3NS, and then call the address with "From" = "0x00...0" and "Calldata" = "0x" + keccak("view(uint256)")[0:4] + abi.encode(uint256(15235234234234)) with chainid = 333.

#### Exmaple 4
```web3://qizhou.w3q/files/index.html```

The protocol will find the address of **qizhou.w3q** from W3NS, and then call the address with "From" = "0x00...0" and "Calldata" = "0x" + keccak("files(bytes)")[0:4] + abi.encode(bytes("index.html")) with chainid = 333.

## Copyright

Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by MicahZoltu** [comment]
Please either open a pull request with this EIP if you are ready to submit a draft, or create a thread on Ethereum Magicians forum to discuss it if you aren't ready to create a draft yet.
