### ISSUE TITLE
Expandable Onchain SVG Images Storage Structure

### ISSUE THREAD

**Issue by Soohan-Park** [ethereum/EIPs#4816]
Let's discuss!

[https://ethereum-magicians.org/t/expandable-onchain-svg-images-storage-structure/8330](https://ethereum-magicians.org/t/expandable-onchain-svg-images-storage-structure/8330)

**Comment by MicahZoltu** [comment]
Issues in this repository are for discussing changes to the EIP process.  The thread on Ethereum Magicians is an appropriate place to engage in discussion on an idea for a future EIP.
