### ISSUE TITLE
IDEA: A Standardized Interface for On-chain Exchanges

### ISSUE THREAD

**Issue by thereturn932** [ethereum/EIPs#4828]
# Problem
Currently almost every on-chain exchange has their own interface to execute operations on exchange. Currently creating platforms supporting different on-chain exchanges is hard and supporting all of them is almost impossible since new on-chain exchanges also create their own interface.

# Proposed Solution
A standard interface to be used with current and future on-chain exchanges. Current exchanges can create a new smart contract with provided interface standard and future on-chain exchanges can support use the standardized interface.

[Related Ethereum-Magicians Post](https://ethereum-magicians.org/t/idea-a-standardized-interface-for-on-chain-exchanges)

**Comment by MicahZoltu** [comment]
This isn't the right place to strike up discussions about how to solve Ethereum problems.  It looks like you already have a post over at Ethereum Magicians, which *is* the right place though.  😀
