### ISSUE TITLE
EIPS-2612: wrong indentation for the typed structure

### ISSUE THREAD

**Issue by Smillence** [ethereum/EIPs#4856]
the indentation at https://eips.ethereum.org/EIPS/eip-2612 is incorrect and misleading

<img width="1726" alt="image" src="https://user-images.githubusercontent.com/3348295/155923032-270ff296-982b-4808-a550-694f10d355ba.png">

`primaryType` and `domain` should be at the same indentation level with `message`

**Comment by MicahZoltu** [comment]
Please submit a pull request to fix this, or comment in the EIP's discussions-to link.
