### ISSUE TITLE
Add a LICENCE file

### ISSUE THREAD

**Issue by Pandapip1** [ethereum/EIPs#4868]
I am aware that EIPs are public domain, but to make this explicit I suggest that ~~the Unilicence~~ CC0 be added. This would, for example, help GitHub display the licence in the repository metadata sidebar.

**Comment by MicahZoltu** [comment]
The License for EIPs themselves is CCO, not Unlicense.  I'm not opposed to adding a CC0 license to the repository so it shows up as such in tooling.

cc @lightclient @axic @gcolvin @SamWilsn

**Comment by Pandapip1** [comment]
As far as I'm aware, the Unilicence is actually more permissive (although now that I think about it, there's probably some conflict with CC0 as a result).

**Comment by MicahZoltu** [comment]
I think we should have the repository license match the EIP licenses just for simplicity.  Having multiple licenses can be problematic and confusing.

**Comment by Pandapip1** [comment]
Misclicked, sorry

**Comment by Pandapip1** [comment]
Since there isn't any objection, I've opened a PR: #4908

**Comment by Pandapip1** [comment]
#4908 was merged.
