### ISSUE TITLE
Proposal: How about having an ERC Meetup?

### ISSUE THREAD

**Issue by xinbenlv** [ethereum/EIPs#4917]
Hi wise authors who work on ERC drafting.

As per the progress of merge and layer 2 in the space, we seem to be increasingly close to the explosion of applications / dapps. Many of these future applications will benefit from ERC standards for interoperability. That explains why we see an increasingly active community of ERC standards being proposed.  

I also seem to see a gap for a live discussion regarding ERCs. Compared to the regular [AllCoreDevs Meetings](https://github.com/ethereum/pm/blob/master/README.md#all-core-devs-meetings) or [The Merge](https://github.com/ethereum/pm/blob/master/Merge/merge.md#merge-meetings) which are live and synchronized, ERCs are often asynchronized and offline. It took a while for one to get feedback or understand what to do next. 

Here is a few things I think we could talk about

1. For ERC authors to come to present their ERC drafts and solicit feedback 
2. For perspective contributors to give feedback or signup to collaborate.
3. For third-party to give feedback to ERCs or present their problems of interoperability
4. For newbee authors to meet Editors and other experienced authors of the community and learn.
5. For CoreDev / Merge / Fees workgroups to have a place to share lower level proposals with ERC authors and solicit feedback 
6. Review upcoming ERC last-calls, review stale EIPs and see if anyone is interested to takeover for reviving.

I checked the [ETH PM repo](https://github.com/ethereum/pm) and it seems we don't have such a meeting yet. 
I wonder if this community have previously considered starting a regular online meeting ERC side of the contributors of this repo?

Your feedback is greatly appreciated. If you are interested in participating, please comment here and share your timezones so we can gauge the interest and find a good time.

xinbenlv@

**Comment by xinbenlv** [comment]
> We kindly remind you to check out [EIP-1](https://eips.ethereum.org/EIPS/eip-1) for guidance. If this issue was created as a “discussions-to” for an EIP or to discuss an idea for an EIP, please close it and create a thread at [Fellowship of Ethereum Magicians](https://ethereum-magicians.org/).

Ack

**Comment by hileamlakB** [comment]
I would love that! I would classify my self as a newbee author, and I came across EIP-191 while I was thinking about a possibly new [EIP](https://ethereum-magicians.org/t/https-stp-data-channel-between-smart-contract-and-dapps/8620?u=hileamlakb).  I would love to meet other authors and discuss if my initial ideas are sensible.

**Comment by xinbenlv** [comment]
@hileamlakB what timezone are you in?

**Comment by hileamlakB** [comment]
I am in GMT-4 @xinbenlv, but anytime works for me.

**Comment by poojaranjan** [comment]
Just for public information, [EIPIP meeting](https://github.com/ethereum-cat-herders/EIPIP) is a bi-weekly meeting of all EIP editors coming together to answer any questions and respond to issues related to EIPs. 

ERC is a Standard Track EIP with ERC category and is within the scope of discussion for EIPIP meetings. Feel free to leave a comment to [meeting agenda](https://github.com/ethereum-cat-herders/EIPIP/issues) or create a [GitHub Issues](https://github.com/ethereum/EIPs/issues)  if you would like to discuss anything related to EIP - Core, Networking, ERC, Interface or any other EIP Type. 

Generally, EIPIP meetings are open for community to participate and meeting details are shared at ECH Discord & Eth R&D Discord.

**Comment by xinbenlv** [comment]
Withdrawn
