### ISSUE TITLE
Travis CI should not validate Git Submodules

### ISSUE THREAD

**Issue by Pandapip1** [ethereum/EIPs#4921]
See: https://github.com/ethereum/EIPs/pull/4835#issuecomment-1068900634

Currently, Travis CI validates all files - including Git Submodules which the EIP author has no control over fixing. I suggest that Travis CI parse the .gitmodules file (if it exists) and skip all files contained in submodules. This would allow EIP authors to simply add the target repository in their `assets` directory instead of having to provide an external link to it (discouraged by EIP-1).

The `.gitmodules` file will be edited every time someone adds a git submodule. The bot should not fail when this file is changed.

**Comment by MicahZoltu** [comment]
I don't think we should allow git submodules in this repository.  It adds a lot of complexity, and creates a hard dependency of this repository on some other git repository (which may move, be deleted, etc.).

**Comment by poojaranjan** [comment]
From the discussion in the EIPIP meeting 52, it appears that EIP editors are generally not in favor of the proposal. 

We will wait for other people to chime in and will be closing the issue after a week. If something comes into light later, feel free to reopen or create a new issue for discussion.

**Comment by Pandapip1** [comment]
Closed - see ethereum-cat-herders/EIPIP#116

**Comment by Pandapip1** [comment]
> From the discussion in the EIPIP meeting 52, it appears that EIP editors are generally not in favor of the proposal.
> 
> We will wait for other people to chime in and will be closing the issue after a week. If something comes into light later, feel free to reopen or create a new issue for discussion.

Huh, this didn't show up when I sent that comment. I'll reopen for now.
