### ISSUE TITLE
NFT Commission Standard

### ISSUE THREAD

**Issue by StEvUgnIn** [ethereum/EIPs#4939]
---
eip:            <to be assigned>
title:          NFT Commission Standard
description:    This standard defines an interface for NFT commision between the operator and the owner.
author:         Steve Huguenin <steve.huguenin-elie@protonmail.ch>
discussions-to:  https://ethereum-magicians.org/t/nft-commission-standard/8655
status:         Idea
type:           Standards Track
category:       ERC
created:        2022-03-23
requires:       165
---

## Simple summary
A standardized way to retrieve commission payment information for non-fungible tokens (NFTs) and operators to enable universal support for commission payments across all NFT marketplaces and ecosystem participants.

## Abstract
On decentralized NFT marketplaces, Royalty is respectively paid by the buyer and allows the owner to keep earning fixed percentage on the sale price of every next transaction. Commision is similar to royalty but is due only on the very first transaction conducted with the support of an operator.

There is currently no standard to describe given commission on-chain. The need for commission is based on the scenario that owners required technical expertise (e.g., refered as Token operator in `EIP-721`) to tokenize their artwork. Token operator
would like to earn commission from the first transaction (e.g., sale, aunction and mint) without directly accessing the owner wallet but to provide a public access that they need the commission in agreement with the owner must be sent directly to them.

## Specification
To be completed.

```solidity
///
/// @dev Interface for the NFT Commission Standard
///
interface NFTCommission is ERC165 {
    /// ERC165 bytes to add to interface array - set in parent contract
    /// implementing this standard
    ///
    /// bytes4(keccak256("commissionInfo(uint256,uint256)")) == <hex>
    /// bytes4 private constant _INTERFACE_ID_NFTCommission = <hex>;
    /// _registerInterface(_INTERFACE_ID_NFTCommission);

    /// @notice Called with the sale price to determine how much commission
    //          is owed and to whom.
    /// @param _tokenId - the NFT asset queried for commission information
    /// @param _salePrice - the sale price of the NFT asset specified by _tokenId
    /// @return receiver - address of who should be sent the commission payment
    /// @return commissionAmount - the commission payment amount for _salePrice
    function commissionInfo(
        uint256 tokenId,
        uint256 salePrice
    ) external view returns (
        address receiver,
        uint256 commissionAmount
    );
}
```

## Rationale
EIP-2981 proposed a royalty standard for Non Fungible Tokens. The idea behind this EIP is propose a NFT standard for commission. Commission are due only on the first transaction conducted with an operator contrarily to royalties which are paid on every transaction.

## Backwards Compatibility
This standard is compatible with current ERC-721 and ERC-1155 standards.

## Security Considerations
There are no security considerations related directly to the implementation of this standard.

## Copyright
Copyright and related rights waived via CC0.

**Comment by MicahZoltu** [comment]
See note from the bot, create a PR if you are ready, or discuss on Ethereum Magicians.
