### ISSUE TITLE
Diamond contracts cannot be verified in blockchain browsers.

### ISSUE THREAD

**Issue by dotc-dev** [ethereum/EIPs#4941]
I have been failing to verify on the bsc testnet. How can I verify successfully. Thank you!

Verifying DOTCFactoryDiamond@0xDaD59054b627e75C1cd1f233dA7DCE85447d03aC
Fail - Unable to verify
Failed to verify 1 contract(s): DOTCFactoryDiamond@0xDaD59054b627e75C1cd1f233dA7DCE85447d03aC

**Comment by abcoathup** [comment]
This repo is for Ethereum Improvement Proposals, so I recommend closing this issue.

For assistance with verifying a Diamond contract you could try contacting the EIP-2535 author: @mudgen
