### ISSUE TITLE
Three days after submitting code, no Travis CI results are available.

### ISSUE THREAD

**Issue by 0xanders** [ethereum/EIPs#4949]
last commit:  https://github.com/ethereum/EIPs/pull/4907/commits/0a47e31a1cdf7efc74ed1141f15c700c75bcbc53

https://github.com/ethereum/EIPs/pull/4907 : Travis CI - Pull Request Expected — Waiting for status to be reported

**Comment by MicahZoltu** [comment]
In the future, feel free to just comment on the PR when CI gets stuck.  An editor will probably pop in and take a look with that, no need to create a separate issue.
