### ISSUE TITLE
minting of NFT with on-chain auction

### ISSUE THREAD

**Issue by xuejunxie** [ethereum/EIPs#4991]
Inspired by the post from Vitalik: https://vitalik.ca/general/2021/08/22/prices.html

I propose a standard for the minting of NFT with an on-chain auction.

The proposed functions are as follows:

    uint public auctionDuration;
    uint public unWithdrawnFunds;

    mapping (uint256 => uint) public auctionEndTime;
    mapping (uint256 => uint) public highestBid;
    mapping (uint256 => address) public highestBidder;
    mapping (uint256 => mapping (address => uint)) public pendingReturns;

    event AuctionStarted(uint256 tokenId, uint256 auctionEndTime, uint256 highestBid, address highestBidder);
    event AuctionExtended(uint256 tokenId, uint256 newAuctionEndTime);
    event AuctionEnded(uint256 tokenId, address highestBidder, uint256 highestBid);
    event HighestBidIncreased(uint256 tokenId, address highestBidder, uint256 highestBid);
    event SubSpaceAuctionAllowed(uint256 tokenId);
    event withDrawalRequested(uint256 tokenId, address bidder, uint256 amount);

    function auctionStart(uint256 tokenId) public payable;
     /// This function should assign auctionEndTime[tokenId], highestBid[tokenId], highestBidder[tokenId]
     /// emit AuctionStarted

    function bid(uint256 tokenId) public payable;
     /// This function should update  highestBid[tokenId], highestBidder[tokenId], pendingReturns[tokenId][address]. It could also increase the auctionEndTime[tokenId] in the last few minutes of the auction.
     /// emit HighestBidIncreased
     /// may emit AuctionExtended

    function withdraw(uint256 tokenId) public;
     /// This function should zero pendingReturns[tokenId][address]. Prefereabily to be required after auctionEndTime[tokenId] to prevent racing condition.
     /// emit withDrawalRequested

    function auctionEnd(uint256 tokenId) public;
     /// In auctionEnd, safemint(highestBidder, tokenId) is called to mint, of cause after auctionEndTime[tokenId].
     /// emit AuctionEnded

      function ownerWithdraw(uint amount) public onlyOwner;
     /// In ownerWithdraw amount <= address(this).balance - unWithdrawnFunds should be enforced prevent owner overdraw of funds unwithdrawn by bidders

This way, we can create a fair auction without the "auction by other means".

**Comment by PradhumnaPancholi** [comment]
I have seen something like this and have worked on it as well. Can you please suggest some generalized use-case for this? Just curious as I haven't seen a lot of auctions.

**Comment by Andrel2s** [comment]
Go

**Comment by Andrel2s** [comment]
Jump

**Comment by xuejunxie** [comment]
> I have seen something like this and have worked on it as well. Can you please suggest some generalized use-case for this? Just curious as I haven't seen a lot of auctions.

I come up with this issue in my project: https://phanta.space/#/space

In order to sell a vast amount of items with large variations in the utility value, I need to use an auction that initiates a countdown when the user places a bid and mint at the end of the auction.

Here is the implemented smart contract: https://etherscan.io/address/0x0e34dd8c227856ca59e2476dc2e872fb76ea5bfa#code

**Comment by PradhumnaPancholi** [comment]
Cool project! I can see this being useful for some other cases as well.  However, I would suggest making this standard generic that can work with other token standards. I am happy to help with the EIP process.

**Comment by MicahZoltu** [comment]
Please either create a pull request to make this an EIP (see EIP-1) or create a thread in Ethereum Magicians to discuss it further first.
