### ISSUE TITLE
Should we discourage the word "standard" in EIP titles and descriptions?

### ISSUE THREAD

**Issue by SamWilsn** [ethereum/EIPs#5009]
I'd propose the following amendment to EIP-1:

```
title: The EIP title is a few words, not a complete sentence. Should not include the word "standard" or any variation thereof.
description: Description is one full (short) sentence. Should not include the word "standard" or any variation thereof.
```

I get slightly annoyed every time I see it because of how useless it is :rofl:

**Comment by Pandapip1** [comment]
I feel like the word has a nonzero amount of use. For example, a token is very different from a token *standard*.

**Comment by MicahZoltu** [comment]
> I get slightly annoyed every time I see it because of how useless it is

Is your problem with it that it is redundant?

**Comment by SamWilsn** [comment]
> I feel like the word has a nonzero amount of use. For example, a token is very different from a token _standard_.

Yes, but you can't put a literal token in an EIP, only a token standard (or, in some weird edge case, a standard place to find a token's address.)



> > I get slightly annoyed every time I see it because of how useless it is
> 
> Is your problem with it that it is redundant?

Exactly. Every ERC is a standard.

**Comment by xinbenlv** [comment]
I object that the Editors to have the power to impose such rule. If there is really a semantic problem with using *standard*, we shall change ERC721 and ERC20 first

**Comment by MicahZoltu** [comment]
> If there is really a semantic problem with using _standard_, we shall change ERC721 and ERC20 first

We generally try to follow a policy of not changing final EIPs to follow our latest ruleset/recommendations.  Often times, we don't know what will end up being a problem until much later, as is the case here where ERC-20 and ERC-721 both use "Standard" and now we realize that *everyone* wants to include "standard" in the name of their standard.  It definitely would have been great if we could have addressed this from the beginning, but hindsight is 20/20.
