### ISSUE TITLE
Formalize EIP Editor Apprentice Project

### ISSUE THREAD

**Issue by Pandapip1** [ethereum/EIPs#5048]
I suggest that the content of https://hackmd.io/@poojaranjan/EIP-ERC-Editor-handbook either become its own meta-EIP and be referenced in EIP-1, or be merged into EIP-1.

**Comment by MicahZoltu** [comment]
I personally dislike Meta and Informational EIPs, so I'm against that.  However, I know many of the other editors like them and I usually get overruled on this topic.

What do you think is the benefit of moving it from where it currently lives?  What problems are presented by having it live in HackMD?

**Comment by MicahZoltu** [comment]
Just realized there is a PR open for this as well (#5069).  Closing this in favor of the PR to facilitate discussion there.
