### ISSUE TITLE
Redirect legacy URLs

### ISSUE THREAD

**Issue by Pandapip1** [ethereum/EIPs#5054]
I'm not sure about the feasibility of this, but I imagine that it should be possible with a middleware (perhaps Cloudflare rules?):

The previous format for EIP files (eip-number-postfix.md) is no longer used. However, there may be dead links to those pages (such as with eip-20). I suggest that all paths that match the following regex (which are legacy URLs)

```regex
^(.*\/EIPS\/eip-\d+)[^\d\s\/][^\/]*$
```

be redirected to the value of the first capturing group (which will be the current EIP path).

See the following link for a demonstration: https://regexr.com/6klaf

See also: #5052

**Comment by MicahZoltu** [comment]
Closing this in favor of focusing the discussion on #5056.
