### ISSUE TITLE
EIP-644: A standard for permission token

### ISSUE THREAD

**Issue by chiro-hiro** [ethereum/EIPs#5062]
eip: 644
title: Permission Token Standard
author: Chiro <chiro@orochi.network>
type: Standards Track
category: ERC
status: Draft
created: 2022-01-19

## Simple Summary

A standard interface for permission tokens.

## Abstract

A new token standard that held the permission of an address in an ecosystem. A permission token can be transferred/granted/revoked by the permission owner to an grantee's address.

## Motivation

You may still encounter special roles like `Owner`, `Operator`, `Manager`, and `Validator` in many existing smart contracts because people still using permissioned addresses to construct and manage them. It is difficult to audit and maintain security since these permissions are not managed centrally in a single smart contract. 

To secure the communication between smart contracts, this EIP provides a straightforward, centralized, and scalable method for managing permissions.

### Methods

**NOTES**:

- The following specifications use syntax from Solidity `0.8.7` (or above)

#### name

Returns the name of the token - e.g. `"OpenPermissionToken"`.

OPTIONAL - This method can be used to improve usability,
but interfaces and other contracts MUST NOT expect these values to be present.

```solidity
function name() external view returns (string memory)
```

#### symbol

Returns the symbol of the token. E.g. `"OPT"`.

OPTIONAL - This method can be used to improve usability,
but interfaces and other contracts MUST NOT expect these values to be present.

```solidity
function symbol() external view returns (string memory)
```

#### permissionOf

Returns the account permission of the given `_owner` address.

```solidity
function permissionOf(address _owner) external view returns (uint256 permission)
```

#### transfer

Transfers a subset of `_permission` permission to address `_to`, and MUST emit the `Transfer` event.
The function SHOULD `revert` if the message caller's account permission does not have the subset of the transferring permission.

_Note_ Transfers of `0` permission MUST be treated as normal transfers and emit the `Transfer` event.

```solidity
function transfer(address _to, uint256 _permission) external returns (bool success)
```

#### approve

Allows `_delegatee` to act for the permission owner's behalf, up to the `_permission` permission. If this function is called again it overwrites the current granted with `_permission`.

**Note**:

- `_permission` MUST be a subset of all available permission of permission owner.
- `approve()` method SHOULD `revert` if granting `_permission` permission is not a subset of all available permission of permission owner.

```solidity
function approve(address _delegatee, uint256 _permission) external returns (bool success)
```

#### delegated

Returns the subset permission of the `_owner` address were granted to `_delegatee` address.

```solidity
function delegated(address _owner, address _delegatee) external view returns (uint256 permission)
```

#### Transfer

MUST trigger when permission are transferred, including zero permission transfers.

A token contract which creates new tokens SHOULD emit a `Transfer` event with the `_from` address set to `address(0x00)` when tokens are created.

```solidity
event Transfer(address indexed _from, address indexed _to, uint256 _value)
```

#### Approval

MUST trigger on any successful call to `approve(address _delegatee, uint256 _permission)`.

```solidity
event Approval(address indexed _owner, address indexed _delegatee, uint256 _permission)
```

### Storage

A `mapping` is used to store 256 bits of permission of an given address:

```solidity
mapping (address => uint256) permissions;
```

Each permission MUST be defined as a power of 2, the important permission SHOULD greater than the less important one.

_Note_ `0` value SHOULD use to represent none permission.

```solidity
uint256 constant PERMISSION_NONE = 0;
uint256 constant PERMISSION_CREATE = 2**0;
uint256 constant PERMISSION_SIGN = 2**1;
uint256 constant PERMISSION_EXECUTE = 2**2;
```

_Note_ You can define roles by combining defined permissions, e.g: `uint256 constant ROLE_OPERATOR = PERMISSION_SIGN|PERMISSION_EXECUTE`.

### Checking

We can check a permission of a subset permission by using `AND` operator with bitmark.

```solidity
if (permissionToken.permissionOf(msg.sender) & permission != permission) {
    revert AccessDenied();
}
```

### Implement

`ERC-644`'s interface in `./IERC644.sol`.

```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.7;

interface IERC644 {
  event Transfer(address indexed _from, address indexed _to, uint256 _value);

  event Approval(address indexed _owner, address indexed _delegatee, uint256 _permission);

  function transfer(address _to, uint256 _permission) external returns (bool success);

  function approve(address _delegatee, uint256 _permission) external returns (bool success);

  function name() external view returns (string memory);

  function symbol() external view returns (string memory);

  function permissionOf(address _owner) external view returns (uint256 permission);

  function delegated(address _owner, address _delegatee) external view returns (uint256 permission);
}
```

Simplest implement of Permission Token

```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.7;
import "./IERC644.sol";

contract ERC644 is IERC644 {
  error AccessDenied(address actor, uint256 permission);

  mapping(address => uint256) internal permissions;

  mapping(address => mapping(address => uint)) internal delegations;

  modifier onlyHasPermission(uint256 _permission) {
    if (permissions[msg.sender] & _permission != _permission) {
      revert AccessDenied(msg.sender, _permission);
    }
    _;
  }

  function transfer(
    address _to,
    uint256 _permission
  ) external override onlyHasPermission(_permission) returns (bool success) {
    address owner = msg.sender;
    // Clean subset of permission from owner
    permissions[owner] = (permissions[owner] | _permission) ^ _permission;
    // Set subset of permission to new owner
    permissions[_to] = permissions[_to] | _permission;
    emit Transfer(owner, _to, _permission);
    return true;
  }

  function approve(
    address _delegatee,
    uint256 _permission
  ) external override onlyHasPermission(_permission) returns (bool success) {
    address owner = msg.sender;
    delegations[owner][_delegatee] = _permission;
    emit Approval(owner, _delegatee, _permission);
    return true;
  }

  function name() external pure override returns (string memory) {
    return 'OpenPermissionToken';
  }

  function symbol() external pure override returns (string memory) {
    return 'OPT';
  }

  function permissionOf(address _owner) external view override returns (uint256 permission) {
    return permissions[_owner];
  }

  function delegated(address _owner, address _delegatee) external view override returns (uint256 permission) {
    // Delegated permission can't be the superset of owner's permission
    return (delegations[_owner][_delegatee] | permissions[_owner]) & permissions[_owner];
  }
}
```

## Copyright

Copyright and related rights waived via [CC0](../LICENSE.md).

**Comment by Pandapip1** [comment]
Sorry, but the current consensus is that the EIP number is equal to the PR number unless manipulation is suspected, in which case a random unassigned EIP number is given at the editors' discretion.
