### ISSUE TITLE
EIP-1's list of optional sections is inconsistent

### ISSUE THREAD

**Issue by SamWilsn** [ethereum/EIPs#5112]
For example, EIP-1 has `Motivation (*optional)` explicitly stated, but `Reference Implementation` doesn't have the `(*optional)` note.

The `Backwards Compatibility` section _seems_ optional (`All EIPs that [...] must`) but @lightclient usually marks it as required.

We should explicitly mark all optional sections with `(optional)`, and explain the requirements in the following text.

**Comment by MicahZoltu** [comment]
PRs welcome.  At the least, we should be consistent with how we present optionality.
