### ISSUE TITLE
Help about EIP-1559 

### ISSUE THREAD

**Issue by 3rror0x0** [ethereum/EIPs#5113]
I need some help about **Eth type-2 EIP-1559**.
Actually i want to make super fast transfer my balance (ETH/BNB). If any one can solve this issue please massage me telegram @lisahkelly
i'lI pay you if solved my issues ...
Thanks.

**Comment by MicahZoltu** [comment]
This isn't the appropriate place to seek help/guidance on how to use Ethereum.

**Comment by 3rror0x0** [comment]
ok...sir please contact me on telegram @lisahkelly
