### ISSUE TITLE
Close a few more issues

### ISSUE THREAD

**Issue by Pandapip1** [ethereum/EIPs#5119]
No EIP with discussion-to linked to issue (should be closed immediately as there is no EIP for them to be grandfathered in to):
- #864
- #958
- #1190
- #1238
- #1257
- #1411
- #1553
- #1631
- #1888
- #2350
- #4469

Final EIPs (should be closed):
- #225
- #2319
- #2907
- #3608 

Withdrawn EIPs (should be closed):
- None

Stagnant EIPs (should be closed as not implemented, can be reopened):
- #637
- #1523
- #1902
- #2337
- #3042
- #3132
- #3384
- #3590 

Last Call (should be merged as final):
- #2365 (Deadline 2021-11-19)
- #2465 (Deadline 2021-11-19)
- #2535 (Deadline 2020-08-15)

Draft EIPs (no action needed imminently, should be transferred to eth magicians):
- #2439
- #3225
- #3641 
- #3772 
- #3753
- #3782 
- #4431 

Review EIPs (no action needed imminently, should be transferred to eth magicians):
- #2613
- #2983

**Comment by MicahZoltu** [comment]
I don't consider #4917 to be stale yet, and I do think an issue in this repository is the correct place for such discussion (changes to the EIP process).

**Comment by SamWilsn** [comment]
I think we should grab all the issues, copy-paste them to ethereum magicians, and close the issues.

**Comment by Pandapip1** [comment]
> I think we should grab all the issues, copy-paste them to ethereum magicians, and close the issues.

Exactly my idea. Must've forgotten to put it in the actual issue itself.

**Comment by Pandapip1** [comment]
Hold off on the no EIP with discussions to. For some reason, GitHub doesn't fully search the repo and I missed some EIPs.

**Comment by Pandapip1** [comment]
Superseded by #5127
