### ISSUE TITLE
Possible duplicate EIP

### ISSUE THREAD

**Issue by Pandapip1** [ethereum/EIPs#5132]
Author cc: @simontianx

EIP-3754 might be identical to vanilla EIP-721. The motivation for EIP-3754 was that it removes the `tokenURI`, `symbol`, and `name` functions from the EIP-721 spec. However, unless I misinterpreted EIP-721, all three functions are actually part of the (optional) ERC721Metadata extension. The interfaces (unless I missed something) are therefore identical.

Thoughts?

**Comment by Pandapip1** [comment]
> between abstract ownership and a more concrete ownership.

Can you explain the difference to me? I'm afraid I don't completely understand.

**Comment by simontianx** [comment]
> > between abstract ownership and a more concrete ownership.
> 
> Can you explain the difference to me? I'm afraid I don't completely understand.

Abstract ownership such as rights especially on-chain rights is a type of ownership of performing functionalities such as calling a certain function or interacting with certain contracts. Other examples include on-chain membership, virtual coupons, and other options, etc.

A more concrete ownership can be best illustrated as ERC20 tokens or ERC721 NFT tokens.

**Comment by Pandapip1** [comment]
> Abstract ownership such as rights especially on-chain rights is a type of ownership of performing functionalities such as calling a certain function or interacting with certain contracts. Other examples include on-chain membership, virtual coupons, and other options, etc.

I'm not sure that's a meaningful differentiation. Applications wouldn't be able to tell the difference between EP-3734 tokens and EIP-721 tokens (they even have the same EIP-165 identifier), so I'd argue that ERC is the wrong type for that proposal. The EIP should instead be an Informational EIP formalizing the statement that abstract ownership can be represented with EIP-721 tokens.

**Comment by simontianx** [comment]
@Pandapip1 Well, looking at it now seems obvious but it was not so obvious when it was proposed. But hell yeah, no one has put any additional effort into it. Let it slide.

**Comment by Pandapip1** [comment]
No worries. It happens all the time.

**Comment by simontianx** [comment]
@Pandapip1 To be honest, this differentiation is more significant than what has been understood.

**Comment by simontianx** [comment]
> > Abstract ownership such as rights especially on-chain rights is a type of ownership of performing functionalities such as calling a certain function or interacting with certain contracts. Other examples include on-chain membership, virtual coupons, and other options, etc.
> 
> I'm not sure that's a meaningful differentiation. Applications wouldn't be able to tell the difference between EP-3734 tokens and EIP-721 tokens (they even have the same EIP-165 identifier), so I'd argue that ERC is the wrong type for that proposal. The EIP should instead be an Informational EIP formalizing the statement that abstract ownership can be represented with EIP-721 tokens.

The reality is although it can, no one is doing it since this capability is very much hidden. Making it explicitly written can benefit the bigger community. I think you underestimated the importance of conceptual clarity.

**Comment by MicahZoltu** [comment]
This should be a comment on the discussions-to link in that issue.  Ultimately, it is up to the author to decide if their EIP is different enough from existing standards to be worth standardizing.
