### ISSUE TITLE
EIP-1193

### ISSUE THREAD

**Issue by taweesakpintakam** [ethereum/EIPs#5144]
# Summary of Devcon 5 EIP-1193 meeting

## Participants

This is an incomplete list of people/projects that participated. Please feel free to add yourself or others: @alcuadrado, @nivida, @davidmurdoch, @joshstevens19, @adrianmcli, @iurimatias, @ricmoo, @spalladino, @javier-tarazaga, @ylv-io, and members from Alchemy, Chainsafe, Metamask, and possibly more projects. 

## Format of the discussion

Initially, every member raised what they thought were the most important concerns to move the EIP forward. After that, we discussed most of them and proposed possible solutions.

## List of concerns

1. EIP-1193 began as a spec on how to expose a provider in a dapp browser, but mutated into specifying its interface. It still depends on EIPs related to browser-specific stuff.

2. The way a provider is exposed (i.e. `window.ethereum`) only supports a single provider. This is in conflict with users installing multiple wallet extensions, and may be problematic with a multi-chain future.

3. The current provider implementations have different interfaces (i.e. `send` vs `sendAsync`).

4. There's no way to send batch requests in the current spec.

5. Some providers need `open`/`connect` and `close`/`disconnect` methods, and others don't.

6. How can a provider be known to be EIP-1193 compatible?

7. How can this EIP be extended in the future? How are those extensions going to be detected?

## Proposed solutions

1. EIP-1193 will only focus on the provider's interface. How to expose in browser environments will be part of another document, possibly an RFC. Any dependency on browser-specific EIPs will be removed.

2. As this EIP won't dictate how to expose the provider, this item is outside of its scope.

3. Finalizing this EIP and adopting ti will fix it.

4. There was a short discussion about this. We concluded that we don't know what to do yet. It may be just an issue with the UI controlling the provider. If a `sendBatch` method is needed in the future, another EIP can extend this one.

5. We concluded that every provider should provide these methods (/cc @pedrouid ). It's up to the provider implementation to document if they need to be called or not. If a certain provider doesn't need them, it can implement them as `no-op`s.

6 and 7. Most of the time was spent discussing these items. We considered different approaches like not doing anything at all, imposing a certain class name, and many other techniques. 

What we concluded is that providers would have a whitelist of the capabilities they offer. The most basic provider (i.e. HTTP-based provider) will have such a whitelist empty. More featureful providers will declare all of their extra features. For example, a websocket/polling-based provider that supports subscriptions, should declare that in the whitelist.

We analyzed the risk of this whitelist getting huge with time, but still decided to go with this approach. It's not clear that it will actually get huge, nor that this would even care.

We chose this approach over others, as it's more explicit and simpler.

## Next steps

* @pedrouid do you want to adapt https://github.com/ethereum/EIPs/pull/2261 so that it includes the `open` and `close` methods as described here?

* I will submit a PR removing any reference to browser-specific stuff.

* I will prepare a PR with the changes proposed in 6 & 7. We can discuss the details there. 

(Disclaimer: I will probably do these things next week, as I have to get back to Argentina and will be super jet-lagged).

_Originally posted by @alcuadrado in https://github.com/ethereum/EIPs/issues/2319#issuecomment-544795458_

**Comment by alcuadrado** [comment]
Is this just spam?

**Comment by MicahZoltu** [comment]
> Is this just spam?

Yes.
