### ISSUE TITLE
Example relative link in EIP-1 is rendered as absolute

### ISSUE THREAD

**Issue by SamWilsn** [ethereum/EIPs#5158]
In the [markdown source](https://github.com/ethereum/EIPs/blob/78bc7a8ecc0bea3c73e21a43258e4de5748afbfc/EIPS/eip-1.md?plain=1#L194), this link is relative, but in the rendered version of [EIP-1](https://eips.ethereum.org/EIPS/eip-1), it is absolute:

![image](https://user-images.githubusercontent.com/57262657/173617031-7ce3d9a5-2d01-4ebf-b738-1917c9c61a97.png)

**Comment by MicahZoltu** [comment]
WTF Jekyll markdown renderer....

**Comment by Pandapip1** [comment]
This is still an issue

**Comment by SamWilsn** [comment]
Still broken.
