### ISSUE TITLE
How should EIPs should be referenced?

### ISSUE THREAD

**Issue by poojaranjan** [ethereum/EIPs#5190]
Following the discussion from the [EIPIP meeting 59](https://youtu.be/FyyymmsU0Wo), creating this issue to invite recommendations from EIP editors and the community on **how to refer to an ERC category proposal** in another proposal (EIP). 

1. Allow using only "EIP-20" and not "ERC-20".
2. Allow using both "EIP-20" and "ERC-20"
3. Allow using only "ERC-20" and not "EIP-20" ([suggestion in comment section](https://github.com/ethereum/EIPs/issues/5190#issuecomment-1170384505))

In any case, the call will be for eip-20.md.

This recommendation is for documentation purposes only and may not affect how community wants to refer to a  proposal in other communication. It will be helpful for authors of new proposals (on extension of current Ethereum standard) and EIP editors apprentice. 

**Note**: 
In the present form, EIP-1 and eips.ethereum.org documents  as "EIP-20" instead of "ERC-20". 
The term ERC is used  to document "Category" which is only applicable when Type = "Standard Track". 

Refer
[<img width="716" alt="image" src="https://user-images.githubusercontent.com/29681685/176509464-c179b901-03d2-4c44-bb40-a06f9c6ec386.png">](https://eips.ethereum.org/EIPS/eip-1)

[<img width="406" alt="image" src="https://user-images.githubusercontent.com/29681685/176509540-e0420d6a-f89c-41ea-ab5d-2f03a6a66bc4.png">](https://eips.ethereum.org/EIPS/eip-20)

**Comment by Pandapip1** [comment]
I would personally prefer that it either be mandatory to refer to them as either `EIP-X` or `ERC-X`. Out of the two options, I would prefer 1, but I would also be fine with the following:

3. Allow using only "ERC-20" and not "EIP-20".

**Comment by poojaranjan** [comment]
Updated original post to include option 3

**Comment by MicahZoltu** [comment]
As I mentioned on the call, I am not passionate about ERC vs EIP, though I agree with Pandapip that we should pick one and apply it consistently, rather than having a mix.

**Comment by abcoathup** [comment]
> 3\. Allow using only "ERC-20" and not "EIP-20".

My preference would be to use an ERC prefix for the category to quickly distinguish between core and ERC categories, the prefix has widespread adoption (e.g. ERC20/721/1155).  It would make it easier to separate EIPs and ERCs in future as needed.

**Comment by will-edge** [comment]
> 3. Allow using only "ERC-20" and not "EIP-20".

Prefer this option, since the relationship between two ERCs is often quite different from the relationship between an ERC and a non standard-track EIP, the former always belongs to compatible/extends/requires/etc., while the later various. So refer to ERCs using the "ERC" prefix will help one to easily understand the purpose of the reference, distinguish from the reference to other EIPs.

**Comment by xinbenlv** [comment]
No strong preference.

**Comment by MDStone1993420** [comment]
> Prysm

> Either

**Comment by DeFiFoFum** [comment]
> > 3. Allow using only "ERC-20" and not "EIP-20".
> 
> Prefer this option, since the relationship between two ERCs is often quite different from the relationship between an ERC and a non standard-track EIP, the former always belongs to compatible/extends/requires/etc., while the later various. So refer to ERCs using the "ERC" prefix will help one to easily understand the purpose of the reference, distinguish from the reference to other EIPs.

I agree with this statement. It's nice to know that ERCs serve a specific purpose imho. 

"ERC: application-level standards and conventions, including contract standards such as token standards ([EIP-20](https://eips.ethereum.org/EIPS/eip-20)), name registries ([EIP-137](https://eips.ethereum.org/EIPS/eip-137)), URI schemes, library/package formats, and wallet formats." - https://eips.ethereum.org/EIPS/eip-1#eip-types

**Comment by Pandapip1** [comment]
I think we've converged on https://github.com/ethereum/EIPs/pull/5273

**Comment by Pandapip1** [comment]
We've determined it will be `ERC-X`.
