### ISSUE TITLE
Include a copy of RFC 822 and RFC 2119 in EIP-1's assets folder

### ISSUE THREAD

**Issue by Pandapip1** [ethereum/EIPs#5223]
Both RFCs are mentioned in EIP-1. Since they are somewhat important, I propose that a copy of them be included in this repository.

It would also let EIP authors link to _that_ instead of having to awkwardly have a reference to RFC 2119 without linking to it.

**Comment by Pandapip1** [comment]
From the IETF website
![image](https://user-images.githubusercontent.com/45835846/178603912-1b233be1-d8db-48d4-bfdd-b1b7c186189f.png)

**Comment by SamWilsn** [comment]
From further down the same page:

[![image](https://user-images.githubusercontent.com/57262657/178606675-43a43095-4234-4f06-b772-251d2cc05c57.png)](https://trustee.ietf.org/about/faq/#collapse3109)

RFC 822 was published before 1986, so I'm not sure exactly what the state of it is.

**Comment by xinbenlv** [comment]
+1 to @MicahZoltu . I am not a lawyer but I personally think it's a typical "fair-use" case for copyright.

**Comment by Pandapip1** [comment]
Closing in favor of https://github.com/ethereum/EIPs/pull/5272
