### ISSUE TITLE
Proposal for EIP Allow EIP Author to opt-in take over

### ISSUE THREAD

**Issue by xinbenlv** [ethereum/EIPs#5245]
To follow up the discussion we have today in the EIPIP Meeting July 13th

*The problem*: some EIPs are stagnant and some authors are not reachable.

*Constraint*: the EIP Editor group don't want to take people's number, they want them to own it.

*Proposal*: create the following checkbox in the template

```verbatim
[ ] if checked, we, the authors of this EIP, welcome other future authors to take over authoring this EIP if it becomes stagnant AND we the authors have not been able to respond on this pull request within 12 months supervised by the EIP.
```

FYI: @MicahZoltu @gcolvin @Pandapip1  @timbeiko 

@poojaranjan : could you also help me add if anyone I missed who commented on this issue during the EIPIP meeting?

Options for discussion

1. Should this signal be in the preamble section? Proposer lean towards yes
2. Should this signal be in the format of checkbox? Proposal leave to the eipbot builder to comment for whichever is more convenient. I have no strong preference.

**Comment by SamWilsn** [comment]
I think I'd prefer a preamble field or something less freeform, so tooling can detect it.

Perhaps something like:

```markdown
---
author: Foo (@bar), EIP Stewards (@ethereum/eip-stewards)
---
```

**Comment by Pandapip1** [comment]
I, personally, would prefer if this were an item in the preamble.

**Comment by xinbenlv** [comment]
The checkbox or any other format of signaling opt-in can be in the preamble section.
What I feel against is to require adding @ethereum/eip-stewards or any individual editor as "author" to keep the author field purely about authorship.

**Comment by SamWilsn** [comment]
If the "EIP Stewards" were to reassign authorship, then wouldn't they themselves become authors?

**Comment by MicahZoltu** [comment]
@gcolvin What do you recommend as a solution to the problem where someone wants to signal in advance that they are OK with someone taking over their EIP if they stop responding?  We can't after-the-fact figure out their intent, so we need *some* form of advanced signalling if we want to support this.

**Comment by xinbenlv** [comment]
> If the "EIP Stewards" were to reassign authorship, then wouldn't they themselves become authors?

Personally I wouldn't count the actions of permission control as "authoring" an EIP. I love to separate different type of contributions to the EIP drafting to recognize them properly
