### ISSUE TITLE
Pin all GitHub Action dependencies to hash version.

### ISSUE THREAD

**Issue by MicahZoltu** [ethereum/EIPs#5298]
All GitHub action references should be like https://github.com/ethereum/EIPs/blob/a182311ee869fa8e5c3e7d4717a1ba5d856be8b4/.github/workflows/auto-merge-bot.yml#L16
Not like https://github.com/ethereum/EIPs/blob/a182311ee869fa8e5c3e7d4717a1ba5d856be8b4/.github/workflows/ci-comment.yml#L15

This protects us from supply chain attacks against this repository as only GitHub (who already has the ability to completely screw us) could sneak in a malicious change to a dependency, which has privileged access.

**Comment by Pandapip1** [comment]
I feel like the more pressing issue is the fact that any of us editors can just arbitrarily change the CI on a whim. Want to add an action that deletes EIP-1? Go ahead! Want to add and/or remove other editors for the fun of it? Nobody's stopping you (except for the two editors with manual merge permissions who can undo it).

**Comment by Pandapip1** [comment]
> This protects us from supply chain attacks against this repository as only GitHub (who already has the ability to completely screw us) could sneak in a malicious change to a dependency, which has privileged access.

Tags can't be modified. If we target a release, then this would provide the required protection without being too... hashy.

**Comment by MicahZoltu** [comment]
> I feel like the more pressing issue is the fact that any of us editors can just arbitrarily change the CI on a whim. Want to add an action that deletes EIP-1? Go ahead! Want to add and/or remove other editors for the fun of it? Nobody's stopping you (except for the two editors with manual merge permissions who can undo it).

Yes, we should fix this as well.  I think there is already an issue for this somewhere?  If not, we should create one.

> Published tags can't be modified, as they are locked to a specific commit. If we target a release, then this would provide the required protection without being too... hashy.

Are you sure about this?  GitHub will happily let you delete a git tag and publish a new one pointing at a new commit.  I would be mildly surprised to hear that they follow a different set of rules for their actions system.

**Comment by Pandapip1** [comment]
> GitHub will happily let you delete a git tag and publish a new one pointing at a new commit. 

Huh, I didn't know this. Good to know!

**Comment by Pandapip1** [comment]
Needs reopening.

**Comment by Pandapip1** [comment]
Still an issue

**Comment by Pandapip1** [comment]
Anyone want to do this?

**Comment by Pandapip1** [comment]
Still an issue

**Comment by Pandapip1** [comment]
See #5797.
