### ISSUE TITLE
GitHub actions don't run for first time contributors

### ISSUE THREAD

**Issue by SamWilsn** [ethereum/EIPs#5310]
### Pull Request

https://github.com/ethereum/EIPs/pull/5164

### What happened?

`eipw` and friends didn't run automatically for this PR since this is the authors first time contributing.

**Comment by Pandapip1** [comment]
This is due to a branch protection rule. CC @MicahZoltu @lightclient

**Comment by SamWilsn** [comment]
I don't think so. I think this is just the default for GitHub actions.

**Comment by MicahZoltu** [comment]
Any idea what happens if a first-time-contributor submits a PR that touches a `.workflow` file, such as to print out secrets?  While the number of second time editors to this repo is incredibly high, at least the current setup makes it a *little* harder to execute such an attack...

**Comment by MicahZoltu** [comment]
We should probably limit the set of actions that can be run to protect against that attack vector more broadly, though I think there are actions that let you run arbitrary shell commands so I'm not sure that would help much.

**Comment by Pandapip1** [comment]
Needs reopening.

**Comment by MicahZoltu** [comment]
> We should probably limit the set of actions that can be run to protect against that attack vector more broadly, though I think there are actions that let you run arbitrary shell commands so I'm not sure that would help much.

The prescience of this comment is alarming.  😬

**Comment by Pandapip1** [comment]
Still an issue.

**Comment by Pandapip1** [comment]
Still an issue :|

**Comment by Pandapip1** [comment]
Still an issue

**Comment by Pandapip1** [comment]
Still an issue.

**Comment by Pandapip1** [comment]
Still an issue.

**Comment by Pandapip1** [comment]
Still an issue.

**Comment by lightclient** [comment]
What do we need to do to resolve this?

**Comment by Pandapip1** [comment]
Unsure.

**Comment by Pandapip1** [comment]
Still an issue :|

**Comment by Pandapip1** [comment]
I think this is still an issue.

**Comment by Pandapip1** [comment]
I actually haven't seen this happen recently, so I'll assume that something solved this.
