### ISSUE TITLE
Standardize April 1 EIPs

### ISSUE THREAD

**Issue by Pandapip1** [ethereum/EIPs#5315]
I know this is a random time to post about this but... can we please have April 1st EIPs? April 1st RFCs are a well-known thing: https://en.wikipedia.org/wiki/April_Fools%27_Day_Request_for_Comments

I suggest we do the same thing as IETF and merge April 1st EIPs based on cleverness and humor.

The following PRs would also be re-opened and merged on April 1, 2023:
https://github.com/ethereum/EIPs/pull/4963
https://github.com/ethereum/EIPs/pull/4962
https://github.com/ethereum/EIPs/pull/4961
https://github.com/ethereum/EIPs/pull/4959
https://github.com/ethereum/EIPs/pull/3455

**Comment by abcoathup** [comment]
We could standardize on a category with a prefix EAF (EIP April First/Fools)

**Comment by MicahZoltu** [comment]
It creates an unnecessary burden on EIP editors, which are already sorely understaffed.  If you want to create an April Fools joke standard, why not just use Hack MD and post a link to it on Twitter?  You can say you are "in the process of drafting a new EIP and looking for feedback" if you want it to be more "believable".

I like a good joke as much as the next guy, but I don't like it when a joke creates work for someone.  Jokes should ideally (IMO) be setup in a way that they don't interfere with anyone's ability to be productive and don't force themselves on anyone's workflow or life who isn't interested in participating in the joke.

**Comment by Pandapip1** [comment]
> I like a good joke as much as the next guy, but I don't like it when a joke creates work for someone. Jokes should ideally (IMO) be setup in a way that they don't interfere with anyone's ability to be productive and don't force themselves on anyone's workflow or life who isn't interested in participating in the joke.

If I didn't like the work, I wouldn't be volunteering :)

**Comment by SamWilsn** [comment]
I volunteer to clean up the mess from april fools jokes.

For the record, I still want to get [EIP-4959](https://github.com/ethereum/EIPs/pull/4959) merged, since it satisfies the requirements for an Informational EIP.

**Comment by MicahZoltu** [comment]
If we had a reliable mechanism for isolating jokes from real work I would care far, far less.  However, at the moment I get an email for *every single thing* that happens on this repository and my inbox fills up every day of the week except Sunday because of that.  On April Fools day, I get an even more full inbox but it is of stuff that I am supposed to ignore, but the effort required to identify which items should be ignored and which shouldn't is often *higher* than the effort required to do my regular work.

If I could somehow receive email notifications for everything *except* these then it wouldn't be a problem, but at the moment that isn't the case so just saying someone else will take care of it doesn't actually reduce my workload at all.

**Comment by MicahZoltu** [comment]
One option would be for me to simply not do any work from the start of March 31st to April 7th, and get a commitment from other editors to make sure all of the jokes are taken care of by then.  The problem with this however is the same problem that leads me to never take vacations, if I take a week off then it just means I have a 7 day backlog of work that I need to deal with when I get back.  😖  Maybe by next year we'll have better tooling/bots/rules/active editors such that the workload will be lower and the thrash won't be as impactful.

**Comment by Pandapip1** [comment]
How about requiring this as a prefix for any new PRs that are submitted as an April fools?

```md
<details>
  <summary>Click to reveal spoiler</summary>
  This PR was created as an April fools joke.
</details>
```

Preview:

<details>
  <summary>Click to reveal spoiler</summary>
  This PR was created as an April fools joke.
</details>

**Comment by MicahZoltu** [comment]
I think a lot of people explicitly want their April Fools jokes to not be obviously April Fools jokes.  I believe that is one of the indicators of a "good" April Fools day joke is that it is ambiguous whether it is a joke or not.

**Comment by Pandapip1** [comment]
(Hence I suggest putting it in spoilers)

**Comment by Pandapip1** [comment]
Alternatively, require beginning the PR title with the clown emoji, such as the following:

```
🤡 New Opcode: SUDO
```

Obvious at a glance, yet not explicitly stating it's a joke.

**Comment by SamWilsn** [comment]
I think the easiest solution is what Micah did this year: close every PR that was opened from March 31st to April 2nd. If there's something important in there, the author can re-open easily.

**Comment by Pandapip1** [comment]
> I think the easiest solution is what Micah did this year: close every PR that was opened from March 31st to April 2nd.

I think the easiest solution is to merge any newEIPFile PR that comes in on April 1 so long as the `status` is `Withdrawn`.

**Comment by MicahZoltu** [comment]
I think even Withdrawn EIPs should mete our editorial standards of the time as we would apply them to Draft EIPs (e.g., correct sections, no external links, etc.).  This is especially true since people can link to Withdrawn EIPs from final EIPs.  Creating a loophole to our normal process so people can troll for a day seems quite counterproductive.

**Comment by Pandapip1** [comment]
Well, it still has to go through eipw and the spell checker :)

**Comment by Pandapip1** [comment]
Seems like we have a resolution here.
