### ISSUE TITLE
[Bug]: Branch protection rules need updating

### ISSUE THREAD

**Issue by Pandapip1** [ethereum/EIPs#5318]
### Pull Request

https://github.com/ethereum/EIPs/pull/5312

### What happened?

The EIP Auto Merge bot got renamed. The branch protection rules need updating.

### Relevant log output

![image](https://user-images.githubusercontent.com/45835846/180609493-17380e64-e969-49cd-aa19-608360d3befe.png)

**Comment by MicahZoltu** [comment]
Done.  `EIP Auto Merge Bot` added and `EIP Auto-Merge Bot` removed.
