### ISSUE TITLE
Display a "citation" when hovering over links to other EIPs

### ISSUE THREAD

**Issue by SamWilsn** [ethereum/EIPs#5352]
@gcolvin suggested this in [EIPIP #61](https://github.com/ethereum-cat-herders/EIPIP/issues/161)

**Comment by xinbenlv** [comment]
This would be good. I am thinking whether github-favored markdown support such feature or would we need to make a pull request for github-favored markdown  @SamWilsn @gcolvin

**Comment by Pandapip1** [comment]
I think all we need to do is add the `title` attribute to the `<a>` tags, and that should work. Worst case, I could do something with popperjs.

**Comment by SamWilsn** [comment]
Still a nice to have.

**Comment by Pandapip1** [comment]
Would still like this. I could work on this.

**Comment by SamWilsn** [comment]
> Would still like this. I could work on this.

I am fully in support!

**Comment by sambacha** [comment]
GitHub supports a file called CITATION.cff that will generate bibtex/APA etc citations for you.

here is an example of usage for my Gas Reporting Index Survey — https://github.com/sambacha/gas-reporting/blob/master/CITATION.cff

Though this isnt exactly the requested feature your asking for, having at least a base would help 🤷‍♂️

**Comment by Pandapip1** [comment]
The problem with the github CITATION file is that it can't be customized per-file. In addition, this is talking about including citations in EIPs, not to EIPs. The format for EIP citations is already well-established, and is included at the bottom.

**Comment by Pandapip1** [comment]
Waiting for consensus.

**Comment by Pandapip1** [comment]
This is a comment to dismiss the stale review bot.

**Comment by Pandapip1** [comment]
This is a comment to dismiss the stale review bot.

**Comment by Pandapip1** [comment]
This is a comment to dismiss the stale review bot.

**Comment by Pandapip1** [comment]
This is kinda done now? There's a lot of stuff being proposed here, and it probably warrants being split into separate issues.
