### ISSUE TITLE
Create an EIP External Link Archive

### ISSUE THREAD

**Issue by xinbenlv** [ethereum/EIPs#5408]
Per https://github.com/ethereum/EIPs/pull/5272#issuecomment-1196279935 we propose to create a bot to archive external links in EIPs onto more persistent storages so the link will not become unavailable in the future, such as IPFS.

Persistent storage to explore
- [ ] Arweave
- [ ] IPFS

**Comment by Pandapip1** [comment]
I'd prefer something like arweave + IPFS.

**Comment by xinbenlv** [comment]
I am still working on this
