### ISSUE TITLE
EIP editors should explain that ERC was renamed to EIP

### ISSUE THREAD

**Issue by fulldecent** [ethereum/EIPs#5424]
### What happened?

The EIP editors have apparently decided that ERCs shall be renamed to EIPs. (I can see this in the CI bots' notices.)

That's fine and I respect your control of this naming.

Before I go around telling everybody that ERC-721 is now renamed to EIP-721, it will be helpful if the EIP official documentation does not contradict me. Please do these:

- [ ] Update https://github.com/ethereum/EIPs/blob/master/README.md to use this new wording
- [ ] Make a blog post documenting this significant change and link to it prominently from the README and EIP-1

**Comment by Pandapip1** [comment]
> Update https://github.com/ethereum/EIPs/blob/master/README.md to use this new wording

The official documentation about the EIP process is in EIP-1. Here is the reference you are looking for: https://eips.ethereum.org/EIPS/eip-1#eip-numbers

> Make a blog post documenting this significant change and link to it prominently from the README and EIP-1

The EIP editors don't have a blog. I know @MicahZoltu does, but he's no longer an editor. I guess I could submit a PR to the ethereum.org website repo.

**Comment by Pandapip1** [comment]
I would also hold off on telling people that it's EIP-721, as the naming is still a contentious issue: https://github.com/ethereum/EIPs/pull/5273

**Comment by xinbenlv** [comment]
@fulldecent the EIP Editor group has been discussing it yesterday EIPIP Meeting. It seems the raw unfinalized consensus in the EIP Editors are it will be flexible between ERC and EIP.

**Comment by fulldecent** [comment]
lol this is weak guidance from a group that is setting rules for people that make rules and guidance

**Comment by Pandapip1** [comment]
> this is weak guidance

We aren't here to guide anything that is outside the scope of the EIPs and related repositories. As discussed in the EIPIP 62 meeting, we don't care if you call the standard with number 20 EIP-20, ERC-20, or BANANA-20. For the purposes of EIPs, the standard must be referenced with the hyphenated form EIP-20, but the consensus is currently split.

**Comment by fulldecent** [comment]
Got it, thank you
