### ISSUE TITLE
Grant all EIP editors write permission

### ISSUE THREAD

**Issue by Pandapip1** [ethereum/EIPs#5452]
@SamWilsn for context, write permission was what you were given before you were given admin. It is the permission assigned to the @ethereum/eip-editors group (and that group is how I propose the permission to be given).

Rationale:
- Turns the editor approvals into green checkmarks and editor requests for changes into red checklists (much clearer for the user)
- Allows editors to assign / remove labels
- Allows editors to close spam PRs
- Allows me to potentially transfer issues to the EIP-Bot repository if they crop up here and belong there.
- Allows editors to be requested for review
- **Due to branch protection, does not allow manual merging.**
- **Due to branch protection, does not allow directly committing.**
- **Does not allow editing settings, or other sensitive stuff.**

**Comment by lightclient** [comment]
Seems okay with me if it does in fact not allow manual merging.

**Comment by Pandapip1** [comment]
@SamWilsn can confirm - he was originally unable to merge PRs.

**Comment by SamWilsn** [comment]
> @SamWilsn can confirm - he was originally unable to merge PRs.

I cannot confirm this. I can, however, confirm that I am dumb.

**Comment by Pandapip1** [comment]
(Permissions sheet: https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-roles-for-an-organization)

**Comment by Pandapip1** [comment]
> This is something I'd like to see completely implemented in bots. What labels do we want that we don't currently have?

The waiting for [person] tags.

**Comment by Pandapip1** [comment]
> This is a big one, although you can report spam PRs to GitHub without write permission and they do remove them eventually. In the interest of minimizing privilege, I think one person can be the designated spam remover?

I have had a success rate of about 25% with GitHub support.

**Comment by Pandapip1** [comment]
> I don't want to be requested for review. I already hate when people tag me directly (for routine things.) 🤣

By which I meant that it *allows* for you to be requested for review. Not that you *are* requested for review.

It still takes someone else with *at least* write permissions to request someone for review.

**Comment by SamWilsn** [comment]
> > This is something I'd like to see completely implemented in bots. What labels do we want that we don't currently have?
> 
> The waiting for [person] tags.

I think we can achieve that pretty easily with automation, no?

 - `waiting: author to review`: applied if there is no review from a named author.
 - `waiting: editor to review`: applied if there is no approval from an editor, or if there have been commits since the last review.
 - `waiting: changes requested`: applied if the most recent editor review is not approval and there have been no commits since then.

> > This is a big one, although you can report spam PRs to GitHub without write permission and they do remove them eventually. In the interest of minimizing privilege, I think one person can be the designated spam remover?
> 
> I have had a success rate of about 25% with GitHub support.

Ping me on discord, I'll do my best to remove them. Once I get annoyed, I'll concede this point :rofl:

**Comment by Pandapip1** [comment]
Okay then. Should we remove the eip-editors team then?
