### ISSUE TITLE
error in EIP3475

### ISSUE THREAD

**Issue by Bubble7777** [ethereum/EIPs#5546]
error in [EIP3475 ](https://eips.ethereum.org/EIPS/eip-3475) in the reference implementation in the Base example. - This demo shows only a minimalist implementation. In IERC3475 In the struct Transaction structure {
        uint256 classic;
        uint256 none Id;
        uint256 amount;
    }
is written as amount, but in erc3475 in functions in 14 places it is written as _amount.

**Comment by Pandapip1** [comment]
This appears to just be a typo. I'll fix it.
