### ISSUE TITLE
Automatically merge all new EIP drafts

### ISSUE THREAD

**Issue by Pandapip1** [ethereum/EIPs#5641]
### Proposed Change

Currently, the process for creating an EIP is not very simple and it is pretty time-consuming just to get an EIP to draft. I imagine a large part of the reason that a lot of EIPs end up stagnant is that the effort even to get an EIP into draft is a lot - more than is probably needed when the criteria for drafts, per EIP-1, is them being "properly formatted." We have tooling that lets users know when their EIPs aren't properly formatted, and we might soon have tooling to automatically *fix* the most common errors.

Currently, when an EIP is initially proposed is when things like "is this EIP ideal for its current purpose" are discussed and block the progress. Having an actual EIP that is being built and on which people can submit PRs that propose changes is, IMHO, better than the status quo, and would actually allow the community to take *some* of the burden off of the EIP editors.

**Comment by SamWilsn** [comment]
This seems reasonable. I'd like to have a bit of discussion on it before we make a decision though.

I think we need a few more checks in `eipw` before I'm comfortable enabling this:

 - ethereum/eipw#11
 - ethereum/eipw#27

**Comment by Pandapip1** [comment]
I agree that those specific checks should be required.

**Comment by SamWilsn** [comment]
@poojaranjan brought up a great point. A lot of EIPs die in the draft stage, so the first pull request is the only point editors have to influence these EIPs.

Plus we want to encourage discussion on magicians before draft, so we get bigger/more developed ideas in the repository.

I am now weakly against this proposal.

**Comment by xinbenlv** [comment]
I agree.

**Comment by Pandapip1** [comment]
I have to disagree here. Editors can always open PRs to modify EIPs like any other person.

I think that having drafts automatically merge would encourage more participation for draft EIPs, as it gives the Ethereum community a longer time to suggest and make changes formally. As such, the quality of Draft EIPs, on the whole, would be lower, but the quality of EIPs moving _to_ Review would be higher as more people would be able to participate in the horizontal review process.

**Comment by Pandapip1** [comment]
Would like to bump this.

**Comment by lightclient** [comment]
IMO, if we're going to "auto-merge" drafts they should not get an EIP number. Other standards bodies have a draft stage where the proposal has not yet been assigned an RFC number (see [Internet-Drafts](https://www.ietf.org/how/ids/)). I would like to adopt a similar scheme. I think this would be valuable _regardless_ if we move forward with the auto-merge.

**Comment by Pandapip1** [comment]
I would agree with them not getting an EIP number. And if they become stagnant, I think they could just be deleted. +1

**Comment by xinbenlv** [comment]
+1 

but in that case we need to suggest a standard way for them to create file name with

some mnemonic name, e.g. eip-some-name.md

**Comment by Pandapip1** [comment]
Nothing says that EIP "numbers" even have to be numeric. EIP editors, right now, could literally assign an EIP "number" of `hello`. We wouldn't since that would be stupid, but we could do this without too many changes.

CC @SamWilsn, how feasible would this be to add to EIPw?

**Comment by lightclient** [comment]
I think they should have a different prefix completely to avoid any confusion.

**Comment by Pandapip1** [comment]
> I think they should have a different prefix completely to avoid any confusion.

How about `EIP-draft-X` and `ERC-draft-X`?

**Comment by xinbenlv** [comment]
> How about EIP-draft-X and ERC-draft-X?

Sounds good. 

`X` could be a number or as mnemonic alias for the content.

**Comment by Pandapip1** [comment]
I was thinking of a mnemonic, like I-Ds.

**Comment by xinbenlv** [comment]
Mnmonecs sounds good to me. Better than a draft number, reducing chance of confusion with regular EIP number

**Comment by sambacha** [comment]
> @poojaranjan brought up a great point. A lot of EIPs die in the draft stage, so the first pull request is the only point editors have to influence these EIPs.
> 
> 
> 
> Plus we want to encourage discussion on magicians before draft, so we get bigger/more developed ideas in the repository.
> 
> 
> 
> I am now weakly against this proposal.

Yes good, kill them while the gestate. If you do not have the time to shepherd it through a GitHub pull request what chance do they have of championing it through all the factions in the greater community? 

Plus why make more work for yourself, lol.

**Comment by Pandapip1** [comment]
> Plus why make more work for yourself, lol.

That's the problem I have with having two gateways: you are doubling the workload. You have to review it once during draft, and again when it reaches review. The difference is that Review EIPs are typically nicer to review, having been somewhat proofread and shortened.

**Comment by Pandapip1** [comment]
Dismissing stale bot.

**Comment by Pandapip1** [comment]
Dismissing stale bot.

**Comment by lightclient** [comment]
Honestly it would be great for drafts to be in a completely separate repo, decrease the traffic to the main repo.

**Comment by Pandapip1** [comment]
> Honestly it would be great for drafts to be in a completely separate repo, decrease the traffic to the main repo.

How about a completely separate folder?

**Comment by Pandapip1** [comment]
Waiting on #6496

**Comment by lightclient** [comment]
I am very against this change if it assigns them an EIP number. I think it should give a DEIP number or something separate.

**Comment by Pandapip1** [comment]
> I am very against this change if it assigns them an EIP number. I think it should give a DEIP number or something separate.

It will not. It will assign them a string identifier.

**Comment by Pandapip1** [comment]
Dismissing stale bot

**Comment by Pandapip1** [comment]
Dismissing stale bot

**Comment by sambacha** [comment]
This is still being discussed is it not?

**Comment by lightclient** [comment]
Again, _I think they should have a different prefix completely to avoid any confusion and gaming of the system._

**Comment by Pandapip1** [comment]
I am +0 to a different prefix (not +1 because I would prefer a mnemonic instead)

**Comment by Pandapip1** [comment]
Bump

**Comment by Pandapip1** [comment]
Draft EIP numbers are being made possible by https://github.com/ethereum/EIPs/pull/6976
