### ISSUE TITLE
Dynamic Required Approvals

### ISSUE THREAD

**Issue by Pandapip1** [ethereum/EIPs#5651]
> My recommendation was to have changes to non-EIPs require a decreasing number of approvals based on how long they have been open.  Something like:
> 
> 1 week: 5 approvals
> 2 weeks: 4 approvals
> 4 weeks: 3 approvals
> 8 weeks: 2 approvals
> 16 weeks: 1 approval
> and a single rejection would prevent auto-merging.
> 
> The idea here is that if there is consensus among all editors then things would go through quickly and smoothly.  If, however, there aren't enough actively engaging editors then system doesn't permanently freeze/halt, it just slows down.

_Originally posted by @MicahZoltu in https://github.com/ethereum/EIPs/issues/5640#issuecomment-1245065644_

My suggestion is a little bit more general. If all editors approve, then a change gets instantly merged. If an editor approves, it starts a one-month countdown before it is automatically merged. If subsequent editors approve, it halves that countdown.  A "request changes" review pauses this countdown.

**Comment by xinbenlv** [comment]
Sounds reasonable. Maybe a function of `5- log(2, week)`?

**Comment by Pandapip1** [comment]
Dismissing stale bot.

**Comment by Pandapip1** [comment]
Dismissing stale bot.

**Comment by Pandapip1** [comment]
Dismissing stale bot.

**Comment by Pandapip1** [comment]
Dismissing stale bot

**Comment by Pandapip1** [comment]
Dismissing stale bot

**Comment by Pandapip1** [comment]
I think the consensus was that this is a good idea if it can be implemented.
