### ISSUE TITLE
Errata'd EIPs

### ISSUE THREAD

**Issue by Pandapip1** [ethereum/EIPs#5652]
### Proposed Change

I propose that with the approval of an original non-errata'd Final EIP's author, a new EIP can be created with the EIP "number" `<original-eip-number>-e<number-erratas>`, where `<original-eip-number>` is the original Final EIP's number, and `<number-erratas>` is a number that starts at `1` and increments by 1 every time an errata EIP for the given original EIP number reaches final, withdrawn, or stagnant.

So, instead of modifying EIP-721, a new EIP would be created with the number `721-e1`, referenced as "EIP-721-e1".

**Comment by SamWilsn** [comment]
If we decide the changes are errata, we can change a final EIP (and git keeps the history.)

If we decide it isn't errata, it's a new EIP and I think it deserves its own number.

---

I'm also concerned that complicating the EIP number namespace will just make things worse.

**Comment by Pandapip1** [comment]
> If we decide the changes are errata, we can change a final EIP (and git keeps the history.)
> If we decide it isn't errata, it's a new EIP and I think it deserves its own number.

The point here is that you might have something like EIP-712 where there are valid arguments for and against "it's an errata" vs "it's actually a major change." Skipping the discussion and letting the authors make that judgment call saves EIP editor brain bandwidth.

**Comment by DennisVonDerBey** [comment]
I love the idea. There will always be a chance for small formal errors in EIPs as we're all humans after all and EIP numbers are already being recognized in the heads of the people. Due to this a sudden change of the number for a new version of a well known standard might be damaging the communication.

**Comment by Pandapip1** [comment]
Dismissing stale bot.

**Comment by Pandapip1** [comment]
Dismissing stale bot.

**Comment by Pandapip1** [comment]
Dismissing stale bot.

**Comment by Pandapip1** [comment]
Dismissing stale bot.

**Comment by Pandapip1** [comment]
Dismissing stale bot

**Comment by Pandapip1** [comment]
Dismissing stale bot

**Comment by Pandapip1** [comment]
Bump.
