### ISSUE TITLE
EIP-4399: return the RANDAO value @specific block in evm

### ISSUE THREAD

**Issue by apiscerena** [ethereum/EIPs#5677]
### Proposed Change

It seems the PRERANDAO value is produced by mixing the previous block's PRERANDAO value and the RANDAO reveal. Normally developers use the method below as the random source of their dapps
`blockhash(uint blockNumber) returns (bytes32)?`
Hope [EIP-4399](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-4399.md) will add a similar function to support retrieving the RANDAO value @ a specific block as a random source.

**Comment by Pandapip1** [comment]
If you would like to create a new EIP, please review EIP-1.
