### ISSUE TITLE
This function tokenByIndex(index)  is not needed in ERC4671 implementation.

### ISSUE THREAD

**Issue by ronit9586** [ethereum/EIPs#5687]
### What happened?

In Implementation of ERC4671.sol file. I found little issue in function tokenByIndex(index). this function is do nothing. It just get **index** as parameter and just returned that index. 

URL: https://github.com/ethereum/EIPs/blob/master/assets/eip-4671/ERC4671.sol
line number: 129

**Comment by Pandapip1** [comment]
Issues are not the correct place to point out content errors. If you would like to fix this, then please submit a pull request.

I happen to think that this particular function *is* needed, as it's a required function in the EIP-721 enumerable extension.
