### ISSUE TITLE
Allow external links when archived link provided 

### ISSUE THREAD

**Issue by sambacha** [ethereum/EIPs#5733]
### Proposed Change

An errata field with external links that are archived would prevent linking to broken sites, etc.

**Comment by Pandapip1** [comment]
+1 from me. I suggested earlier that the archiving could even be done automatically by a bot that automatically points them to the archived version when the link rots. Copyright issues are nonexistent because this definitely falls under fair use.

**Comment by xinbenlv** [comment]
Great. #5408 is aligned with this purpose.

**Comment by Pandapip1** [comment]
I think the consensus is that this is a good idea.

**Comment by Pandapip1** [comment]
Dismissing bot

**Comment by sambacha** [comment]
We should differentiate between user requested links and crawled -- each link has to be intentionally added through a service like https://perma.cc

Additionally an allowlist of acceptable providers should be considered, along with prohibition of links needing user maintenance like ipfs pinning (not as a primary link maybe?) 

More crucially having the possibility of now linking cross repo with the specs etc provides an opportunity to revisit front matter possibly. 


Yea no URL shortening either, really the links need to be served by the domain, cant have an additional layer of abstraction like url shortening services or ipfs addressing. Example is with git.io -- github has shut down their url shortening service and now links may be useless.

**Comment by Pandapip1** [comment]
I was specifically suggesting that a copy be kept in the assets folder. Sites like archive.org and perma.cc are still susceptible to being taken down.

**Comment by sambacha** [comment]
> I was specifically suggesting that a copy be kept in the assets folder. Sites like archive.org and perma.cc are still susceptible to being taken down.

perma.cc provides a png of the entire site and a web bundle, which is a w3c standard for archiving sites. 

A full screen capture as an image is the most robust and easiest way to save said site. 

Additionally whatever folder holds the assets for that specific eip it may be advantageous to also provide a citations within that folder (though not included in the eip itself).

arxiv.org has a similar setup for submitted papers: a pdf is made available and through a separate link a zip file of the raw submitted files (images, individual latex files, everything to be able to reproduce the pdf in high quality)

**Comment by Pandapip1** [comment]
I would additionally like to support https://github.com/mozilla/readability as a website download method, which takes the main page content and strips the formatting.

**Comment by erkinalp** [comment]
External references should only be allowed if they refer to the ethereum spec itself, other EIPs, or a certain block in the agreed-upon branch of the ETH blockchain

**Comment by Pandapip1** [comment]
Dismissing stale bot.

**Comment by Pandapip1** [comment]
Dismissing stale bot.

**Comment by Pandapip1** [comment]
This is still a no-brainer.

**Comment by Pandapip1** [comment]
Dismissing stale bot.

**Comment by Pandapip1** [comment]
Dismissing bot.

**Comment by Pandapip1** [comment]
Dismissing bot.

**Comment by Pandapip1** [comment]
Dismissing bot.

**Comment by kdenhartog** [comment]
I'm generally a +1 to this as well. @Pandapip1 I'm not as familiar with Mozilla's Readability. Does this strip the header information as well? This information is useful for fragmented linking to particular portions of a document.

**Comment by Pandapip1** [comment]
It does not strip the header info.

**Comment by kdenhartog** [comment]
Sweet, no concerns from me on something like this then.

**Comment by Pandapip1** [comment]
I guess the best way to get this to occur is by submitting a PR.

**Comment by sambacha** [comment]
Whats the status on this, can we bring this forward during office hours?

**Comment by Pandapip1** [comment]
Not during office hours; EIP-1 changes are for the EIPIP meeting

**Comment by Pandapip1** [comment]
I think that we established at some point that this is okay. Closing and making a PR.
