### ISSUE TITLE
![image](https://user-images.githubusercontent.com/2758453/193269791-950f5e85-40f8-434e-96d9-f95df7186bd0.png)

### ISSUE THREAD

**Issue by blackdoc111** [ethereum/EIPs#5747]
![image](https://user-images.githubusercontent.com/2758453/193269791-950f5e85-40f8-434e-96d9-f95df7186bd0.png)
wagmi?

_Originally posted by @TimDaub in https://github.com/ethereum/EIPs/issues/721#issuecomment-1263510521_

**Comment by Pandapip1** [comment]
![image](https://user-images.githubusercontent.com/45835846/193809114-e92bfcaa-ab20-45d2-9f55-736a4834a749.png)
Spam.
