### ISSUE TITLE
 wrappedToken

### ISSUE THREAD

**Issue by sachinruhil11** [ethereum/EIPs#5754]
### Proposed Change

we can create an interface WToken(wrappedToken)  just like a wrappedEther(WETH) so that we can easily deal with the ERC20/ERC721 while transferring token  instead of a specific one token like ERC20 or a EREC721.
we can use this WToken  to transfer token either it is ERC20 or ERc721.

**Comment by Pandapip1** [comment]
If you would like to solicit feedback, please create a thread on [FEM](https://ethereum-magicians.org).
