### ISSUE TITLE
Propose a `contributor` field in pre-emble to allow author recognize contributors of an EIP

### ISSUE THREAD

**Issue by xinbenlv** [ethereum/EIPs#5762]
### Proposed Change
Add a `contributor` field in pre-emble. Using the same format as `author`

### Rationale
Recognize and honor a contributor culture

**Comment by Pandapip1** [comment]
This could be automatically populated by the git author/coauthor data at build time.

**Comment by lightclient** [comment]
I am against.

**Comment by SamWilsn** [comment]
@lightclient and I are against this proposal.

**Comment by xinbenlv** [comment]
@Joumax11 are you expressing your preference on this?
