### ISSUE TITLE
Privacy and security are often separate issues to be considered. This is why IETF cites the necessity for both of them. Even in the case where no known privacy or security issue is known a simple statement can be stated as such. For example, a document outlining how to define privacy considerations still defines a security considerations section even though it's defining how to write a document. https://www.rfc-editor.org/rfc/rfc6973.html#section-9

### ISSUE THREAD

**Issue by Joumax11** [ethereum/EIPs#5786]
Privacy and security are often separate issues to be considered. This is why IETF cites the necessity for both of them. Even in the case where no known privacy or security issue is known a simple statement can be stated as such. For example, a document outlining how to define privacy considerations still defines a security considerations section even though it's defining how to write a document. https://www.rfc-editor.org/rfc/rfc6973.html#section-9

I don't think it's unreasonable to require an author to include these sections. Even if it's as simple as stating that nothing needs to be considered.

_Originally posted by @kdenhartog in https://github.com/ethereum/EIPs/issues/5682#issuecomment-1250425387_

**Comment by Pandapip1** [comment]
There's already an issue for this. If you think there should be a separate issue, then please create a new issue from scratch.
