### ISSUE TITLE
https://gist.github.com/frozeman/090ae32041bcfe120824

### ISSUE THREAD

**Issue by Maxim17081983** [ethereum/EIPs#5812]
recent discussion from https://gist.github.com/frozeman/090ae32041bcfe120824

@vbuterin said:
Yeah, `createCheque` and `cashCheque` as above, plus `transferCheque(address _from, address _to, uint256 _value)` sounds good. In that case, we should probably remove the `_to` argument from `cashCheque`; generally, you can only cash cheques from your own bank account.

We probably also want `getChequeValue(address _from, address _for)`. We then have a choice of whether we want to keep the value argument in `cashCheque` rather than simply only allowing cashing in 100% of whatever is in there. If we want to fully follow the cheque analogy, this triad seems most intuitive to me:

``` js
function createCheque(address _for, uint256 _maxValue)
function cashCheque(address _from)
function getChequeValue(address _from, address _for)
```

Question: does running createCheque twice add the value of the two cheques together? Are there legitimate use cases for creating a cheque multiple times and then cashing either once or multiple times?

@nmushegian said:
All the functions that return uint should `return (uint, bool)` instead. You can easily make up scenarios where a 0 return value is ambiguous and significant. Is there any other simpler pattern for handling this?

@niran said:
I think the value parameter is useful in `cashCheque`. It absolves callers from having to verify that the amount they needed was provided, and from having to refund amounts greater than what was needed. cashCheque would only succeed if the provided value was remaining in the cheque.
Also, I think using `createCheque(2**100)` for the approve use case is going to lead to less clear code. It gets better if you make the magic number a constant, like `createCheque(UNLIMITED_CHEQUE_VALUE)`, but lots of people won't do that. I think it's worth having a createBlankCheque or something for the approve scenario. Most tokens will use the TokenLib to handle all of the cheque logic, so it doesn't really make things worse for token authors.

@caktux 
I also think there is a problem with the terminology of cheques since they imply one-offs. Cheques are also unique, and here cheques wouldn't return unique IDs or anything; those are merely approval methods for transfers using internal bookkeeping. I think the current approve/transfer terminology is accurate and simple enough, instead of ending up with a mix of transfer and cashCheque. Would we change unapprove to `tearCheque`? There's also that ambiguity of cheques adding up, where approvals more clearly override a previous one.

In the use case described by Vitalik of contracts charging fees in subcurrencies, it could easily cost more to have to call approveOnce each time (if we replace the current approve method with it) than the actual fee in subcurrency. For that reason I think we should keep both `approve` and `approveOnce`, but we could add the `_maxValue` argument to the former, that way subscriptions or fees could be taken in multiple calls but only up to a certain amount. Another reason to keep the approval terminology, as I think it's much simpler to describe approve and approveOnce than some createMultiCheque and createCheque. Regarding `isApprovedFor`, it would have to return the approved amount if we do add `_maxValue`, just as `isApprovedOnceFor` does.

_Originally posted by @frozeman in https://github.com/ethereum/EIPs/issues/20#issuecomment-158017280_

**Comment by Pandapip1** [comment]
Presuming spam. Please let me know if this is in error.
