### ISSUE TITLE
Stale review dismissal loop

### ISSUE THREAD

**Issue by lightclient** [ethereum/EIPs#5868]
### Pull Request

https://github.com/ethereum/EIPs/pull/5793

We need to clean up the PR output so there aren't a ton of stale review dismissals.

![Screen Shot 2022-11-02 at 07 56 29](https://user-images.githubusercontent.com/14004106/199508091-ffbec4c1-f64a-477c-b13f-08abfa8e3eb8.png)

**Comment by Pandapip1** [comment]
Not possible; this is a GitHub limitation.

**Comment by lightclient** [comment]
How is it a github limitation? How do other systems deal with this?

**Comment by Pandapip1** [comment]
> How do other systems deal with this?

They don't have reviews automatically dismissed on push. This is required for the EIPs repository, however, since PRs auto-merge.

**Comment by JEAlfonsoP** [comment]
Hi. 

Could ? we try this:

Settings ▶ Branches ▶ Branch protection rules ▶ Edit ▶ Uncheck "Dismiss stale pull request approvals when new commits are pushed".

Either way I will take a look into EIP-Bot to see if there is a way to do it from the Bot.

**Comment by Pandapip1** [comment]
No, we can't do that. That permission must be checked to ensure that reviews are dismissed when new commits are pushed to branches, as you can see in the screenshot @lightclient linked.

**Comment by JEAlfonsoP** [comment]
So, you want to dismiss but not being notify ( no echo ) ?

**Comment by Pandapip1** [comment]
I think that is the goal, yes.

**Comment by JEAlfonsoP** [comment]
Hi @Pandapip1 , I would like to explore two possible options to silent this alert (or any other one), 1st Have you tried/used Code Scanning (workflow) filters for the repo ? and 2nd There is a REST API for `alerts/{alert_number}` endpoint, have you tried/used it ? 
Sorry for the direct questions, I just do not want to expend time in something that you may be already has tried it.. Ty.

**Comment by Pandapip1** [comment]
Forgive me for the probably naive question, but how would enabling code scanning fix this problem?

**Comment by JEAlfonsoP** [comment]
Thanks for answering ! 
I would see if this (or any other alert) is listed in code scanning alerts and from there would use the `-tag: ` filter to silent it. 
But, as I said if you have not worked in it I will stop writing assumptions and will try to test it: implementing the code scanning workflow or coding the API into EIP-Bot. If you have any other idea please share it so I can either study it.

**Comment by Pandapip1** [comment]
This is unrelated to EIP bot; this is a GitHub feature (logging automatic review dismissals in the timeline) that we want to disable.

**Comment by JEAlfonsoP** [comment]
I believe that either, but I would like to find out each workflow's signal and see if we can silent (in case that is desired) it or not, one is what you mentioned above generated by GitHub itself. 
If you agree I can proceed with the testing and If you working on it, again I kindly ask you to let me know, in case that you want to coordinate this study, let me know so I can DM you and so all the work goes in the same direction. Ty.

**Comment by Pandapip1** [comment]
Feel free to do testing. It is almost certainly caused by the dismiss stale reviews branch protection option, however.

**Comment by JEAlfonsoP** [comment]
Ty. I will do

**Comment by Pandapip1** [comment]
I think this was a GitHub bug. The PR in question has been closed.
