### ISSUE TITLE
Automerge bot needs Administrator permissions

### ISSUE THREAD

**Issue by Pandapip1** [ethereum/EIPs#5975]
### What happened?

@eth-bot needs admin permissions to bypass CI checks for "move to stagnant" PRs.

### Relevant log output

I reran the stale bot recently, and due to a separate bug it didn't try to merge the PR it was continually trying to merge. So 3 months worth of stagnant PRs were opened.

**Comment by Pandapip1** [comment]
@SamWilsn would you mind fixing?

**Comment by Pandapip1** [comment]
Actually, I found https://github.blog/changelog/2021-11-19-allow-bypassing-required-pull-requests/. Is this possible to do with our current GitHub plan?

**Comment by SamWilsn** [comment]
Yeah, I think we could give the bot permission to push straight to `master` without a PR. Not sure if we want to go that route though.

Unless someone changed it recently, it looks like the bot already had admin:

![image](https://user-images.githubusercontent.com/57262657/202767985-0a8bd846-7ba5-479c-8b1b-320af1d00018.png)

**Comment by SamWilsn** [comment]
![Screenshot 2022-11-18 at 12-44-23 Branch protection rule](https://user-images.githubusercontent.com/57262657/202768778-8bfbdb24-70fe-4a35-b660-abc3a63ee406.png)

**Comment by Pandapip1** [comment]
Huh, weird. Must be some other bug. I'll look into it.
