### ISSUE TITLE
Markdown interpreter of EIP webpage does not write correctly latex formulas

### ISSUE THREAD

**Issue by Hardblock-IMSE-CNM** [ethereum/EIPs#5977]
### Pull Request

https://eips.ethereum.org/EIPS/eip-4519

### What happened?

The markdown of the [EIP-4519](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-4519.md) shows correctly the formulas of latex but in the [EIP webpage](https://eips.ethereum.org/EIPS/eip-4519) the formulas are not shown correctly.

**Comment by Pandapip1** [comment]
This is because it uses double `$$`. Please change this to use single `$`.

(We use a variant of LaTeX called MathJax)
