### ISSUE TITLE
ABI: 'byte' as an alias to 'bytes1'

### ISSUE THREAD

**Issue by axic** [ethereum/EIPs#60]
Latest Solidity has now an alias from `byte` to `bytes1` ( https://solidity.readthedocs.org/en/latest/types.html ).

It would make sense including this alias in the [ABI](https://github.com/ethereum/wiki/wiki/Ethereum-Contract-ABI) too, similarly how `int` and `uint` are an alias to `int256` and `uint256`, respectively.

It seems logical and there are some [demands](https://github.com/axic/ethereumjs-abi/issues/5) for having it available too.

**Comment by VoR0220** [comment]
I support this.

**Comment by chriseth** [comment]
`uint` does not exist as far as the ABI is concerned, it only knows about `uint256`.

**Comment by axic** [comment]
@chriseth it is an alias:
> uint, int: synonyms for uint256, int256 respectively (not to be used for computing the function selector).

**Comment by chriseth** [comment]
Perhaps we should clarify what we mean when we say ABI. For me this is the way to encode and decode abstract mathematical objects (numbers, strings, ...) to sequences of bytes for use in contracts and a way to address a function of a contract given its name and type. The type of a function is again an abstract mathematical object. Both `uint` and `uint256` are string representations of the 256-bit unsigned integer type, where the latter is its canonical representation, which has to be used when computing the hash of a named function type for means of addressing the function.

**Comment by axic** [comment]
Closing this as it seems to be well outdated.
