### ISSUE TITLE
MathJax incorrectly interpreting inline code as TeX

### ISSUE THREAD

**Issue by SamWilsn** [ethereum/EIPs#6021]
### What happened?

https://eips.ethereum.org/EIPS/eip-2464

![header of eip-2464](https://user-images.githubusercontent.com/57262657/203223510-f20319ec-ee42-4653-b5a0-662fb5d5923c.png)

I assume this is related to #5596 @Pandapip1?

_(originally reported by @adietrichs)_

**Comment by Pandapip1** [comment]
That's odd, and definitely related to #5596.

**Comment by Pandapip1** [comment]
A few things to note:

1. This is markdown in the preamble, which doesn't work. This should be fixed, first of all.
2. The delimeters appear to be set to `$`...`$` or `\(`...`)\`, so I don't know why the backticks are still triggering. I'll investigate.
