### ISSUE TITLE
Make Stagnant and Withdrawn EIPs less visible

### ISSUE THREAD

**Issue by Pandapip1** [ethereum/EIPs#6027]
### Proposed Change

Pretty self-explanatory. Just remove the `Stagnant` and `Withdrawn` sections.

Thoughts?

**Comment by xinbenlv** [comment]
Also, consider hiding `Draft`

**Comment by axic** [comment]
I think it is a bad idea. They are separated by status for a reason. Filtering could be added to the site, but hiding without any recurse defeats the purpose, imho.

**Comment by xinbenlv** [comment]
I think a filter to hide Stagnant, Withdrawn and Draft by default with option to show and search will a great way to go.

**Comment by Pandapip1** [comment]
I could make the toggle with relative ease. https://github.com/ethereum/EIPs/pull/6017 would need to be merged first, though, as it adds all the necessary stuff in order to be able to make these more advanced changes.

**Comment by gcolvin** [comment]
I'm with @axic, and then some.  It causes more harm and confusion than good to hide them.

**Comment by Pandapip1** [comment]
> It causes more harm and confusion than good to hide them.

What about the toggle? I think it causes more harm and confusion to *leave* them there, implying that they're still *mostly* okay to use (despite the big red warning).

**Comment by Pandapip1** [comment]
A toggle it is.

**Comment by Pandapip1** [comment]
Dismissing stale bot.
