### ISSUE TITLE
Define realistic limits for transaction and block header values

### ISSUE THREAD

**Issue by winsvega** [ethereum/EIPs#604]
**Summary**
Define realistic limits for transaction and block header values such as

**_Blockheader:_**
difficulty
number
gasLimit
gasUsed
nonce

**_Transaction:_**
nonce 
gasPrice
gasLimit
value?

Change the YP defenition of such values to be in range of u64

**Motivation**
Currently the limit of such values is u256. But I noticed that cpp vm converts gasLimit value to u64 and uses it this way. Vitalik also think that realistically such values would never reach the theoretical limit of u64

> Do you think that it is possible that gasLimit would overflow u64  ?
> Vitalik Buterin: realistically no

Using u256 values slows down the implementation. Greg made that change to the EVM specifically to increase the working speed. If values never exceed the theoretical limit then perhaps we should not use complex implementation of u256?

Such change would not affect any of the existing transaction or blocks. This is just a change to the protocol in YP. 

**Specification**
Change the YP defenition of such values to be in range of u64

**Comment by axic** [comment]
This is now covered by https://eips.ethereum.org/EIPS/eip-1985. I propose to close this issue, @winsvega.
