### ISSUE TITLE
Expose more EIP info via RSS

### ISSUE THREAD

**Issue by lightclient** [ethereum/EIPs#6068]
### Proposed Change

It's been requested that we have better hooks for interested parties to view EIP activity. Can we start with ERC category EIPs entering different stages.

**Comment by SamWilsn** [comment]
If we're allowed to migrate to [atom](https://www.rfc-editor.org/rfc/rfc4287), we could stick the abstract in `<summary>` and the whole document in `<content>`.

**Comment by Pandapip1** [comment]
+1 to adding more RSS feeds. It shouldn't be too hard to have separate RSS and atom feeds.

**Comment by xinbenlv** [comment]
+1 to adding more RSS feeds. 

I also think because of this, the `tags` field that @Pandapip1 is proposing, can help a lot if some authors/subscribe want to focus on certain domain.
