### ISSUE TITLE
Sponsored On-Chain Phishing Attacks

### ISSUE THREAD

**Issue by jonsats** [ethereum/EIPs#6069]
### What happened?

We're seeing a potential sponsored on-chain phishing attack that could be attempting to trick users to send ERC20 tokens to the wrong address.

How To Recreate:
1. User sends an amount of ERC20 tokens to a destination address
2. Several to 20 min later a 0 value ERC20 transaction could appear being sent from the user's address to a very similar address as the above destination address (last 7 characters match)

**Comment by SamWilsn** [comment]
Not exactly relevant to this repository.
