### ISSUE TITLE
Deprecate net_version API endpoint

### ISSUE THREAD

**Issue by karalabe** [ethereum/EIPs#611]
# Background

Currently our JSON RPC spec defines two "version" endpoints:

 * `net_version`: https://github.com/ethereum/wiki/wiki/JSON-RPC#net_version
 * `eth_protocolVersion`: https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_protocolversion

The latter is fairly obvious as it retrieves the specific `eth` version the node is running, but what does the former **mean**? 

> ### net_version
> Returns the current network protocol version.

The P2P protocol actually doesn't have a version number (at least none that it meaningfully useful to anyone). Looking at this endpoint's sample usage, it seems to just return the eth version again. But a) `eth` already has a version endpoint and b) `net` can be available even if `eth` is not (think whisper, swarm).

Lastly, `go-ethereum` and Parity too currently returns the **`eth`** network ID, which is probably the worse possible interpretation of this field based on its name and description.

# Proposal

~~Flat out drop `net_version`, being useless, redundant and misleading.~~

Deprecate `net_version` so that it works for a few more releases but possibly prints a huge warning so users can work towards not using this. This should help down the line for nodes not running `eth`, just some other protocols on top of devp2p.

Introduce `eth_networkId` that retains the current functionality of `net_version`, which could be used by Mist for example to figure out which network an underlying node it running on.

**Comment by chfast** [comment]
I think in case there no value to be returned for DevP2P, we should drop it.

**Comment by arkpar** [comment]
DevP2P base protocol has a version number which goes into the `Hello` packet. Most implementations support version 4

**Comment by karalabe** [comment]
@arkpar That may be the case, but even Parity returns the `eth` network ID, which imho is a very non obvious and wrong thing to return base on both the documentation and the name of the endpoint too. https://github.com/paritytech/parity/blob/master/rpc/src/v1/impls/net.rs#L39

**Comment by arkpar** [comment]
@karalabe We've changed it to return network id for compatibility. Also see discussion here: 
https://github.com/ethereum/interfaces/issues/6

**Comment by fjl** [comment]
I dont see the value of net_version and support removing it.

**Comment by arkpar** [comment]
I agree that this should be **deprecated**, but only after `eth_networkId` is introduced.

**Comment by karalabe** [comment]
I can accept deprecation + introducing eth_networkID

**Comment by karalabe** [comment]
Updated the proposal.

**Comment by flyswatter** [comment]
In MetaMask we're currently relying on `net_version` to get the network ID. It makes sense to replace it with `eth_protocolVersion`, but like @arkpar said, the replacement needs to be in place first for our service to continue without interruption.

**Comment by frozeman** [comment]
I'm also fine with deprecating if we have `eth_networkId `

**Comment by carver** [comment]
+1 for introducing `eth_networkId` and deprecating `net_version`. While we're at it, let's return the network ID as a hex `QUANTITY` instead of a string.

**Comment by Pipeliner** [comment]
Was net_version removed?
With `Parity/v1.7.3-beta-083b69f-20170921/x86_64-linux-gnu/rustc1.19.0`and `Truffle v3.4.9 (core: 3.4.8)`, I get the following error when I try to `truffle migrate` to it:
```
truffle migrate --verbose-rpc                                                 
   > {
   >   "jsonrpc": "2.0",
   >   "id": 1,
   >   "method": "net_version",
   >   "params": []
   > }
 <   {
 <     "jsonrpc": "2.0",
 <     "error": {
 <       "code": -32601,
 <       "message": "Method not found"
 <     },
 <     "id": 1
 <   }
Error: Method not found
    at Object.InvalidResponse (/usr/lib/node_modules/truffle/build/cli.bundled.js:37295:16)
    at /usr/lib/node_modules/truffle/build/cli.bundled.js:224765:36
    at /usr/lib/node_modules/truffle/build/cli.bundled.js:208348:9
    at XMLHttpRequest.request.onreadystatechange (/usr/lib/node_modules/truffle/build/cli.bundled.js:209773:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/usr/lib/node_modules/truffle/build/cli.bundled.js:67130:18)
    at XMLHttpRequest._setReadyState (/usr/lib/node_modules/truffle/build/cli.bundled.js:67420:12)
    at XMLHttpRequest._onHttpResponseEnd (/usr/lib/node_modules/truffle/build/cli.bundled.js:67575:12)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/truffle/build/cli.bundled.js:67535:24)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
```

**Comment by tzumby** [comment]
@Pipeliner, not sure if you still have this problem. For me it was because I didn't enable "net" in the json rpc config for parity. 

```
[rpc]
# Only selected APIs will be exposed over this interface.
apis = ["web3", "eth", "pubsub", "parity", "parity_pubsub", "traces", "rpc", "shh", "shh_pubsub", "parity_accounts", "personal", "net"]
```

**Comment by Pipeliner** [comment]
@tzumby I haven't worked with Parity recently. IIRC I haven't changed anything in the config, and this was the default behavior.

**Comment by andersonlthome** [comment]
"The method 'eth_networkId' does not exist / is not available."
