### ISSUE TITLE
Jekyll fails to render out-of-order list

### ISSUE THREAD

**Issue by lightclient** [ethereum/EIPs#6117]
### What happened?

Expected to list 1-8 as depicted in the raw text, instead chooses to render again at one after break.

<img width="925" alt="Screenshot 2022-12-12 at 06 23 38" src="https://user-images.githubusercontent.com/14004106/207055913-b4f8245f-3ae0-4abb-9592-b78a887e7d84.png">

**Comment by SamWilsn** [comment]
I believe you can indent the content of item 7 so it doesn't break out of the list.

That said, the [commonmark spec](https://spec.commonmark.org/0.26/#example-263) does allow setting the start number of an ordered list.
