### ISSUE TITLE
Editorial Issues with ERC3475

### ISSUE THREAD

**Issue by xinbenlv** [ethereum/EIPs#6128]
### Pull Request

https://github.com/ethereum/EIPs/pull/5385/files

### What happened?

As I am developing interfaces from various ERCS, I discovered a few editorial issues in the ERC3475 

1. [Burn](https://github.com/ethereum/EIPs/blob/7a9673e0bd7f1f8d7e699fb1271b320d63964dbc/EIPS/eip-3475.md?plain=1#L284) was a given as an example but no event was defined
2. [burnBond](https://github.com/ethereum/EIPs/blob/7a9673e0bd7f1f8d7e699fb1271b320d63964dbc/EIPS/eip-3475.md?plain=1#L104) in comment doesn't exist in any definition in this file 
3. [transferAllowanceFrom](https://github.com/ethereum/EIPs/blob/7a9673e0bd7f1f8d7e699fb1271b320d63964dbc/EIPS/eip-3475.md?plain=1#L68) was declared with "virtual override" which isn't an valid solidity interface
4. Usages of [`emit` implementation code and `event` with interface](https://github.com/ethereum/EIPs/blob/7a9673e0bd7f1f8d7e699fb1271b320d63964dbc/EIPS/eip-3475.md?plain=1#L267) renders non-compilable code in any place.
5. In consistency and mixure usage of `//` vs `/**/`.

A discussion for editorial policy / procedure: shall we consider impose a rule that for when a last-call EIP changes a lot, they shall not [go to Final in that same commit](https://github.com/ethereum/EIPs/pull/5385/files) and, maybe, revert to `Review` to give people more time for reviewing the updated version. I will file a separate issue for procedure proposal

Notify: @dhruvmalik007 @yuliu-debond

**Comment by SamWilsn** [comment]
I think policy is generally to restart the last call timer if there are substantial changes to an EIP, but it looks like that didn't happen here.

**Comment by dhruvmalik007** [comment]
Thanks, @xinbenlv for the notification, in fact we had the PR in order to resolve some of the changes in the [given PR](https://github.com/ethereum/EIPs/pull/5789).  

so we will do a final review of the inconsistencies that you have mentioned above and then insure from the next EIP proposal coming to final, there will be time for reviewing the updated version.
