### ISSUE TITLE
Last Call changes must be separate from the PR to move to Final

### ISSUE THREAD

**Issue by xinbenlv** [ethereum/EIPs#6129]
### Proposed Change

Shall we consider impose a rule that for when a last-call EIP changes a lot, they shall not [go to Final in that same commit](https://github.com/ethereum/EIPs/pull/5385/files) and, maybe, revert to Review to give people more time for reviewing the updated version. 

This issue was inspired in https://github.com/ethereum/EIPs/issues/6128

**Comment by Pandapip1** [comment]
I strongly agree with this. Minor changes can forgo the reset of the last call timer. Major changes should reset it.

**Comment by tecywiz121** [comment]
> Minor changes can forgo the reset of the last call timer. Major changes should reset it.

I'd approve a PR into EIP-1 for this.

**Comment by Pandapip1** [comment]
@xinbenlv are you making a PR, or should I?

**Comment by xinbenlv** [comment]
I could add it to EIP-1 as a rule. It would be nice if you could make a PR in the eipw or proper bot lint.

**Comment by Pandapip1** [comment]
Fixed in #6824.
