### ISSUE TITLE
"Requires" section should not accept `Withdrawn` EIP

### ISSUE THREAD

**Issue by poojaranjan** [ethereum/EIPs#6131]
### Proposed Change

The current EIPW bot allows `Final`, `Living` and `Withdrawn` EIP to be accepted in the "Requires" section.

While `Withdrawn` is a terminal status, it may not be an EIP which followed the standardization process and may not be a best proposal to be followed (and/or depend on).
 
Proposal: Active EIP should not be dependent on a `Withdrawn` EIP and not accepted in "Requires" section.

**Comment by Pandapip1** [comment]
+0.5

The only reason I can think of for allowing them is if the EIP was created through the "Old GitHub issue -> withdrawn EIP" pathway (which was made specifically so that those EIPs could be depended on).
