### ISSUE TITLE
How do we handle ancient Solidity versions in old final EIPs?

### ISSUE THREAD

**Issue by SamWilsn** [ethereum/EIPs#6138]
### Proposed Change

For example, in EIP-20, we have a very old Solidity version and the interfaces won't compile with recent Solidity versions.

We probably shouldn't rewrite old EIPs, but having our standards rot is also less than useful.

Some ideas:
 - Publish a new EIP with the same text, and updated Solidity.
 - Put a warning in the rendered Jekyll.

**Comment by Pandapip1** [comment]
See https://github.com/ethereum/EIPs/pull/5887 for how I would like this to be done. I would love interfaces to be rewritten--as long as the spec doesn't functionally change.

**Comment by satoshi-MAM** [comment]
As the master and creator of Ethereum all this çhànges  burning tokens and usèng Ethereum wallet that has 34 trillion belongs to me have you guys forgotten no one çan take them away from you no matter what.  You all think you have any right your wrong Ethereum was çreatéd for somethíng it wórked it pàssed and it was released as all other coins the main wallet belóngs to the çreator so why  do you all think you have the right to spend usé and move coins tokens stable coins Wich ever way you think. Wéll if that the case you like every one else should have their own wallets. Web 3 ís go to be like nothing before all those tríllions every one want to get their hands on. Belong to me I can release web 3 ànd I will release it soon. And no one will get any money out of it you want to çreate build get a loan and pay it of after all that how ít was all the time I wait thats wright you also steel take money that isn't yours and lie over your business  the whole system is build in lies steeling fraud and you expect stability please I will form the new path and I alone will sét thing how they will work régardless what any one has to say if politicàns agree or not I don't give a fuck it's çlear that is bad money bad economy bad systems bad leadership and to try to arrest me it clear that if it's bad and turn it to good it's legàl in this wày anything bad turñed to good we'll their is no reason to even waist their time and special mine
