### ISSUE TITLE
Change ABI to provide a string reason for a throw in Solidity

### ISSUE THREAD

**Issue by VoR0220** [ethereum/EIPs#62]
Currently a throw does not supply any particular reason why the contract threw, and this could get confusing not just for developers but for people who are utilizing contracts as they grow and become more complex. More information is a nice thing especially when dealing with something as new as Solidity. Would love to hear opinion on this.

**Comment by axic** [comment]
:+1:

**Comment by nmushegian** [comment]
This is not an ABI issue but an EVM issue. This requires adding a new opcode. It should allow you to revert all state changes in your scope while returning a value you specify. It may require adding special VM state to signify whether the last call was an exception or not.

**Comment by VoR0220** [comment]
Or why not just modify the current opcode used for throw?

**Comment by VoR0220** [comment]
ahhh...that's because it's BadDestJump...either way, is there any agreement that this should happen?

**Comment by axic** [comment]
I think it would be beneficial for an error reporting view. How do you propose to deliver that message though?

**Comment by VoR0220** [comment]
perhaps take a chunk of gas out of the thrown gas to pass an in memory string message back to the console? These are just initial thoughts. It would seem from the above comments that either a change to the opcode, or a new opcode, will be necessary.

**Comment by alexvandesande** [comment]
Could this be solved without a new opcode by having the EVM save any returns sent before the throw?
So you'd do something like this:

```
return(23, 'deadline not passed');
throw;
```

**Comment by VoR0220** [comment]
But then the throw won't be hit.

**Comment by axic** [comment]
Just throwing in: there could be a dedicated event topic set for this?

**Comment by VoR0220** [comment]
Maybe... @alexvandesande you seem to have better knowledge of the EVM than I, what would you propose?

**Comment by chriseth** [comment]
This is very hard to impossible to implement in the current exception setup (if you revert the state you cannot store any information) and I doubt we will extend the exception mechanism in the EVM as this is only a hack anyway.

**Comment by VoR0220** [comment]
@chriseth couldn't you just send the string back in memory?

**Comment by SCBuergel** [comment]
Getting a "bad jump dest" instead of "array index out of bounds" makes it close to impossible for new developers to figure out what is going on. We really need some solution to make runtime bugs more debuggable - or to build platforms which allow debuggable code to be written.

**Comment by janx** [comment]
+1. We really need some solution to make runtime bugs more debuggable.

Can we use `data` to pass reason string back (instead of set to `[]`) on OOG? https://github.com/ethereum/pyethereum/blob/develop/ethereum/vm.py#L140
