### ISSUE TITLE
Storage of SECP256k1 public keys in ENS: discussion

### ISSUE THREAD

**Issue by Arachnid** [ethereum/EIPs#620]
This issue exists for discussion of EIP 620, Storage of SECP256k1 public keys in ENS.

**Comment by vbuterin** [comment]
What is the issue here?

Also, I'd recommend switching to alt_bn128, as pubkeys for alt_bn128 can fit inside 256 bits so they're single-storage-slot-friendly, and they're also the raw elliptic curve operations for alt_bn128 will be available in metropolis.

**Comment by Arachnid** [comment]
See the PR at https://github.com/ethereum/EIPs/pull/619 for details.

It'd be worth considering the best option for supporting multiple curves. I considered making the function take a 'curve type' parameter, but punted a bit when I couldn't find a good natural identifier to use for different EC curves.

**Comment by MicahZoltu** [comment]
#619 was never merged it appears.  https://eips.ethereum.org/EIPS/eip-619 just is a 404.  Closing this unless someone can find an actual EIP (merged and available on website) that uses this.
