### ISSUE TITLE
pull request Issues about EIP Walidator error for Copyright section

### ISSUE THREAD

**Issue by JessicaChg** [ethereum/EIPs#6242]
## Pull Request

https://github.com/ethereum/EIPs/pull/6239/files

## What happened?

I have followed the format of Copyright section which metion in EIP-1, but when pull request, there is always hint the error 'error[markdown-rel-links]: non-relative link or image'

## Relevant log output

![img](https://user-images.githubusercontent.com/117890123/210101239-0f6e9d0f-7f30-452a-af79-fcc0ccb04754.png)

**Comment by JessicaChg** [comment]
I have fixed it by remove reference url link.  
It seems the EIP Walidator hint the wrong line problem.

**Comment by Pandapip1** [comment]
@SamWilsn please transfer this issue to the eipw repo.

**Comment by Pandapip1** [comment]
Seems to be fixed now.
