### ISSUE TITLE
Clarify & rationalize blob transaction hash computations in EIP-4844

### ISSUE THREAD

**Issue by roberto-bayardo** [ethereum/EIPs#6245]
[EIP-4844](https://eips.ethereum.org/EIPS/eip-4844) currently specifies how to compute the hash of a blob type transaction for the purposes of transaction signing as:

`keccak256(BLOB_TX_TYPE + ssz.hash_tree_root(tx.message))`

However it does not currently specify how to compute the hash of a blob-type transaction for non-signing purposes, which presumably should include the signature to avoid tx malleability issues.

Previous transaction types have their raw serialized form (including signature) hashed with keccak256 in order to obtain the tx hash. If we follow this model, we might compute the blob-type transaction hash as:

`keccak256(BLOB_TX_TYPE + ssz.serialize(tx))`

(see https://github.com/ethereum/EIPs/pull/6238)

Note that compared to the signing-hash, here we hash tx instead of tx.message in order to include the signature, and use ssz.serialize instead of ssz.hash_tree_root to obtain the hash preimage.

This brings up a second question surrounding the signing hash: why use ssz.hash_tree_root instead of ssz.serialize? Presumably this is to be consistent with how signing hashes are computed in the consensus layer, but this is a bit inconsistent with how execution layer obtains signing hashes for other transaction types.   We might therefore consider changing the signing hash to use straight serialization rather than hash_tree_root:

`keccak256(BLOB_TX_TYPE + ssz.hash_tree_root(tx.message))`

(see https://github.com/ethereum/EIPs/pull/6241)

We might also choose to use hash_tree_root instead of serialize for both the signing hash and the regular blob-type transaction hash preimages.

Another alternative would be to use RLP encoding instead of SSZ for blob transaction serialization which provides the most consistency with how other tx types are handled. This would however require the consensus layer have some understanding of RLP in order to extract the versioned hashes (see [tx_peek_versioned_hashes](https://github.com/ethereum/consensus-specs/blob/dev/specs/eip4844/beacon-chain.md#tx_peek_blob_versioned_hashes))

Whatever choices we end up making here here should be accompanied with appropriate justification within the EIP.

**Comment by roberto-bayardo** [comment]
cc @protolambda @timbeiko

**Comment by roberto-bayardo** [comment]
My preference is the solution from the PRs I linked in the issue:  Continue using SSZ encoding for blob type transactions, but use ssz.serialize for both signing-hash and regular tx hash in the EL.

Rationale:

On SSZ vs RLP: If SSZ is "the future" it makes sense to start adopting it now even in the EL, and since typed transactions are [opaque byte arrays](https://eips.ethereum.org/EIPS/eip-2718) it is reasonably straightforward to do so for this particular purpose.

On using ssz.serialize for both hash computations rather than ssz.hash_tree_root:  Other tx types use straight serialization for these computations in the EL, and maintaining consistency with the EL approach to tx-hashing rather than introducing a new approach keeps things conceptually simpler.   I don't see why we'd need to do merkle-like proving over transaction contents, so I'm not seeing any benefit of using the tree root here other than having more consistency with the consensus layer approach to signing.

**Comment by acolytec3** [comment]
I agree with the the logic suggested @roberto-bayardo above regarding the use of `ssz.serialize` over `hash_tree_root`.  The only scenario I can think of off hand where it might somehow be useful to have `hash_tree_root` over `serialize` would be if in the future we also migrate EL layer block serialization from RLP to SSZ.  We've already [sort of done this in the Portal Network spec](https://github.com/ethereum/portal-network-specs/blob/master/history-network.md#block-body) but I don't know if that's really where we're going to land longer term since there we're actually just wrapping RLP encoded transactions inside an SSZ container.  In any case, makes sense enough for now to just use `ssz.serialize` and move forward.

**Comment by roberto-bayardo** [comment]
Seemed we had consensus around the solution on the client-dev's call today. If there are any concerns please express them ASAP!

**Comment by asn-d6** [comment]
I think replacing `hash_tree_root()` with SSZ `serialize` is a reasonable change.

The only caveat is that there is an implicit assumption that SSZ `serialize` is an injective function (i.e. two distinct transactions must not serialize to the same object). While I didn't find any official SSZ documentation of this requirement it is mentioned in the [deserialize docs](https://github.com/ethereum/consensus-specs/blob/dev/ssz/simple-serialize.md#deserialization) and in [an SE thread by Paul](https://ethereum.stackexchange.com/a/82056).

**Comment by djrtwo** [comment]
It is injective within the type and noted here 

https://github.com/ethereum/consensus-specs/blob/dev/ssz/simple-serialize.md#deserialization

> Because serialization is an injective function (i.e. two distinct objects of the same type will serialize to different values) any bytestring has at most one object it could deserialize to.

**Comment by Pandapip1** [comment]
The GitHub issues are not a good place to discuss EIPs. I recommend you move the discussion to the relevant EIP discussion thread: https://ethereum-magicians.org/t/eip-4844-shard-blob-transactions-cancun-upgrade/10884
