### ISSUE TITLE
Some kind of incentive to perform a selfdestruct operation

### ISSUE THREAD

**Issue by VoR0220** [ethereum/EIPs#63]
If we view the blockchain as a public utility, would it not make sense that we should put in some kind of incentive for developers to "Clean up" once their contract has executed its function. This would reduce the load on the state, and help keep the protocol decentralized. Where this incentive would come from, I'm not certain, but I think it's definitely something that ought to be thought about. Any and all ideas I would love to have the discussion about.

**Comment by VoR0220** [comment]
I think I may have written this without some kind of attention to https://github.com/ethereum/EIPs/issues/35 Reading now...

**Comment by vbuterin** [comment]
One approach I had was keeping a counter in the account object header for how many state keys were full; that way you could give a gas refund on SUICIDE equal to all of the SSTORE clears that "would have happened". That said, this adds extra complexity to the protocol...

**Comment by VoR0220** [comment]
You know I was thinking about this, and I had an idea that kind of works like a tax credit...but the details are where this will be very hard to implement. If Suicide is written into the opcodes near the end of the codes, you get something like a tax credit on the amount of gas it would cost in terms of your opcode because you're alleviating storage costs. Again, the devil is in the details on this one.

**Comment by nmushegian** [comment]
> Where this incentive would come from, I'm not certain, but I think it's definitely something that ought to be thought about.

Maybe a fraction of the cost of each zero-to-nonzero store could be saved and then later paid to anyone who can get it to `suicide`.

**Comment by VoR0220** [comment]
As noted in #35 so elegantly by @vbuterin (I really love the wording here), 

```
During a block where transaction inclusion demand does not reach the gas limit (or even where the opportunity-cost gasprice is cheaper than average), miners have the incentive to fill up storage slots so as to use them as a "bank" that expensive transactions can use to grant themselves additional gas at a time when gasprice is expensive; essentially, conducting inter-temporal gas arbitrage with the additional negative externality of requiring all full nodes to store extra data in the meantime.
```

so again, we want to avoid anything holing it away....I think a discount proportional to storage saved should be given...but how to calculate that is tricky...near impossible actually without running into the problem above.

**Comment by alexvandesande** [comment]
I think this whole EIP is a duplicate of https://github.com/ethereum/EIPs/issues/35 as solving that one will make incentives for self destruct unnecessary..

**Comment by VoR0220** [comment]
I agree. I didn't see that one when I made this. I'll close this one.
