### ISSUE TITLE
> Minor changes can forgo the reset of the last call timer. Major changes should reset it.

### ISSUE THREAD

**Issue by regalwright** [ethereum/EIPs#6305]
> Minor changes can forgo the reset of the last call timer. Major changes should reset it.

I'd approve a PR into EIP-1 for this.

_Originally posted by @tecywiz121 in https://github.com/ethereum/EIPs/issues/6129#issuecomment-1351581110_

**Comment by Pandapip1** [comment]
This should be handled in https://github.com/ethereum/eipw
