### ISSUE TITLE
.json tests format

### ISSUE THREAD

**Issue by winsvega** [ethereum/EIPs#633]
This is an EIP about json keys and value encoding .json tests from ethereum/tests repository. 
This applies to the tests commonly used such are  **BlockChainTests**, **GeneralStateTests**, **TransactionTests**, **VMTests**

Here is an example file of a State Test:
https://github.com/ethereum/tests/blob/eip158/StateTests/stExample.json

**1. keys and values are string**
**2. values might be** 
- **hex encoded integers**  
0x prefixed 
two hex digits per byte representation of an integer. (allow leading zeros) 
zero value is 0x00
- **hex encoded bytes**
0x prefixed 
two hex digits per byte
zero value is "" (empty string)
zero byte value is 0x00

- **hex encoded hashes** (addresses, stateRoot, blockhash, etc..)
NO 0x prefix
two hex digits per byte

- **string**
contains name of the network, true or fals, name of the test, etc...

**3. keys might be**
- **hex encoded integers** (storage memory keys)
0x prefixed 
two hex digits per byte representation of an integer. (allow leading zeros) 
zero value is 0x00

- **hex encoded hashes** (addresses)
NO 0x prefix
two hex digits per byte

- **string** 
contains name of the network, true or falst, name of the test, etc...

**Some old tests and GeneralStateTests have some values as integers or bool.
like here https://github.com/ethereum/tests/blob/develop/BasicTests/hexencodetest.json

GeneralStateTests have values representing transaction indexes as integers (not as a string) 
to use -1 value to represent all of the possible indexes of a transaction
so far that is the only exception in the commonly used tests.

**Comment by chfast** [comment]
1. This is no about ".json tests format". It is about "Data encoding for JSON format".
2. Make a pull request.

**Comment by winsvega** [comment]
"Data encoding for JSON format". 
sound like it would apply for RPC methods as well.

**Comment by chfast** [comment]
That's the idea, unify JSON formatting for JSON RPC as well.

**Comment by fjl** [comment]
Would be better to use existing [RPC formats](https://github.com/ethereum/wiki/wiki/JSON-RPC#hex-value-encoding) for tests.

**Comment by chfast** [comment]
@fjl, I think @winsvega is proposing the same format as in "RPC formats", just weirdly distinct hashes and bytes.
