### ISSUE TITLE
Add draft background image to draft EIPs

### ISSUE THREAD

**Issue by Pandapip1** [ethereum/EIPs#6479]
### Proposed Change

A concern people have had about auto merging draft EIPs without editor review (#5641) was that they might be low quality, and might reflect poorly on EIPs as a whole. Therefore, to enable this change to happen, I propose this be added as a tiled background image on all Draft EIPs:

![draftv2.png](https://user-images.githubusercontent.com/45835846/217897048-a7b7800d-0744-4a97-8a4f-91ce8fda179a.png)

**Comment by Pandapip1** [comment]
(Yes, this is a serious proposal)

**Comment by abcoathup** [comment]
I don't mind a DRAFT watermark.  If you go down this path should also have watermarks to warn of any state a reader should be on the alert for when reading a standard, e.g. WITHDRAWN and STAGNANT.

**Comment by SamWilsn** [comment]
Completely agree with @abcoathup. Just the status, lightly watermarked, except for final.

**Comment by Pandapip1** [comment]
@lightclient @axic @gcolvin thoughts?

**Comment by lightclient** [comment]
This implies that other EIPs are peer reviewed :grimacing:. It just seems unnecessary. I would rather they get a draft identifier instead like `DEIP-XXXX`.

**Comment by Pandapip1** [comment]
> This implies that other EIPs are peer reviewed 😬.

Are the editors not peers?

**Comment by Pandapip1** [comment]
> I would rather they get a draft identifier instead like DEIP-XXXX.

Same here! If I had to pick between one or the other, I would pick draft identifiers.

However, we are lucky enough to be able to be able to support both! Even though you feel it is unnecessary, are you at all opposed to its implementation?

**Comment by lightclient** [comment]
Yes I strongly don't think we should watermark.

**Comment by Pandapip1** [comment]
> Yes I strongly don't think we should watermark.

Fair enough. I'll leave this open in case other editors strongly disagree with lightclient here, but I'm okay with letting this die out.

**Comment by SamWilsn** [comment]
> Yes I strongly don't think we should watermark.

Why @lightclient? I think a subtle watermark of "Draft", "Review", "Last Call", or "Withdrawn" would be great.

The "non peer-reviewed" part is probably misleading, like you mentioned.
