### ISSUE TITLE
Metropolis Difficulty Bomb Delay

### ISSUE THREAD

**Issue by 5chdn** [ethereum/EIPs#649]
Update: For implementation see #669

---

## Preamble

    EIP: #649
    Title: Metropolis Difficulty Bomb Delay
    Authors: Afri Schoedon (Champion), Vitalik Buterin (Specification)
    Type: Standard Track
    Category: Core
    Status: Draft
    Created: 2017-06-21
    Replaces: #186

_*Note,_ I'm just writing down this EIP, I'm not _the_ author. It has been discussed in several all-core-dev meetings. However, it clearly needs an EIP if this should be included in Metropolis. Previously discussed here:

- [All Core Devs Meeting #09](https://github.com/ethereum/pm/blob/master/All%20Core%20Devs%20Meetings/Meeting%209.md#metropolis-timing-and-roadmap-discussion)
- [All Core Devs Meeting #12](https://github.com/ethereum/pm/blob/master/All%20Core%20Devs%20Meetings/Meeting%2012.md#5-metropolis-update)
- [All Core Devs Meeting #13](https://github.com/ethereum/pm/blob/master/All%20Core%20Devs%20Meetings/Meeting%2013.md#3-eip-186-reduce-eth-issuance-before-proof-of-stake-hudson) (in context of #186)
- [All Core Devs Meeting #14](https://github.com/ethereum/pm/blob/master/All%20Core%20Devs%20Meetings/Meeting%2014.md#1-eip-186-reduce-eth-issuance-before-proof-of-stake-core-devs) (in context of #186)

## Simple Summary, Abstract, and Motivation
The average block time is 17.49 seconds and slowly increasing due to the _difficulty bomb_. That makes users sad. This EIP is suggesting to delay the bomb significantly, to reduce average block times below 15 seconds, and to allow more time for Serenity development.

## Specification, Rationale, Compatibility, Test Cases, Implementation
_To be specified asap:_ "Idea was that we add special rules to the difficulty calculation to effectively pause the difficulty between different blocks." (Peter)

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by Arachnid** [comment]
Could you open this as a PR instead of an issue?

**Comment by vbuterin** [comment]
I recommend, for the purposes of `calc_difficulty`, we simply replace the use of `block.number`, as used in the exponential ice age component, with the formula:

    fake_block_number = block.number - 3000000 if block.number >= METROPOLIS_FORK_BLKNUM else block.number

This will delay the ice age by 42 million seconds ~= 1.4 years, so we'd be back at 30 second block times at the end of 2018.

**Comment by Q015531637** [comment]
> អាប់ដេត៖ សម្រាប់ការអនុវត្ត សូមមើល #669
> 
> ## បុព្វកថា
> ```
> EIP: #649
> Title: Metropolis Difficulty Bomb Delay
> Authors: Afri Schoedon (Champion), Vitalik Buterin (Specification)
> Type: Standard Track
> Category: Core
> Status: Draft
> Created: 2017-06-21
> Replaces: #186
> ```
> 
> _*ចំណាំ_ ខ្ញុំគ្រាន់តែសរសេរចុះ EIP នេះ ខ្ញុំមិនមែនជា _អ្នកនិពន្ធ_ ទេ ។ វាត្រូវបានពិភាក្សានៅក្នុងកិច្ចប្រជុំស្នូល-អ្នកអភិវឌ្ឍន៍ជាច្រើន ទោះយ៉ាងណាក៏ដោយ វាច្បាស់ណាស់ត្រូវការ EIP ប្រសិនបើវាគួរតែត្រូវបានរួមបញ្ចូលនៅក្នុង Metropolis ។ ពីមុនបានពិភាក្សានៅទីនេះ៖
> 
> * [កិច្ចប្រជុំ Core Devs ទាំងអស់ #09](https://github.com/ethereum/pm/blob/master/All%20Core%20Devs%20Meetings/Meeting%209.md#metropolis-timing-and-roadmap-discussion)
> * [ការប្រជុំ Core Devs ទាំងអស់ #12](https://github.com/ethereum/pm/blob/master/All%20Core%20Devs%20Meetings/Meeting%2012.md#5-metropolis-update)
> * [កិច្ចប្រជុំ Core Devs ទាំងអស់ #13](https://github.com/ethereum/pm/blob/master/All%20Core%20Devs%20Meetings/Meeting%2013.md#3-eip-186-reduce-eth-issuance-before-proof-of-stake-hudson) (នៅក្នុងបរិបទនៃ [ការកាត់បន្ថយការចេញ ETH មុនពេលភស្តុតាងនៃភាគហ៊ុន ](https://github.com/ethereum/EIPs/issues/186)[ #186](https://github.com/ethereum/EIPs/issues/186) )[](https://github.com/ethereum/EIPs/issues/186)
> * [កិច្ចប្រជុំ Core Devs ទាំងអស់ #14](https://github.com/ethereum/pm/blob/master/All%20Core%20Devs%20Meetings/Meeting%2014.md#1-eip-186-reduce-eth-issuance-before-proof-of-stake-core-devs) (នៅក្នុងបរិបទនៃ [ការកាត់បន្ថយការចេញ ETH មុនពេលភស្តុតាងនៃភាគហ៊ុន ](https://github.com/ethereum/EIPs/issues/186)[ #186](https://github.com/ethereum/EIPs/issues/186) )[](https://github.com/ethereum/EIPs/issues/186)
> 
> ## សេចក្តីសង្ខេបសាមញ្ញ អរូបី និងការលើកទឹកចិត្ត
> ពេលវេលា​ប្លុក​ជា​មធ្យម​គឺ 17.49 វិនាទី ហើយ​កើនឡើង​យឺតៗ​ដោយ​សារ _​គ្រាប់​បែក​ពិបាក_ ។ ដែលធ្វើឱ្យអ្នកប្រើប្រាស់សោកសៅ។ EIP នេះកំពុងស្នើឱ្យពន្យារពេលគ្រាប់បែកយ៉ាងខ្លាំង ដើម្បីកាត់បន្ថយរយៈពេលប្លុកជាមធ្យមក្រោម 15 វិនាទី និងអនុញ្ញាតឱ្យមានពេលវេលាបន្ថែមទៀតសម្រាប់ការអភិវឌ្ឍភាពស្ងប់ស្ងាត់។
> 
> ## ការបញ្ជាក់, ហេតុផល, ភាពឆបគ្នា, ករណីសាកល្បង, ការអនុវត្ត
> _ដើម្បីបញ្ជាក់ឱ្យបានឆាប់៖_ "គំនិតគឺថាយើងបន្ថែមច្បាប់ពិសេសទៅនឹងការគណនាការលំបាក ដើម្បីបញ្ឈប់ភាពលំបាករវាងប្លុកផ្សេងៗគ្នាប្រកបដោយប្រសិទ្ធភាព។" (ពេត្រុស)
> 
> ## រក្សាសិទ្ធិ
> ការរក្សាសិទ្ធិ និងសិទ្ធិពាក់ព័ន្ធត្រូវបានលើកលែងតាមរយៈ [CC0](https://creativecommons.org/publicdomain/zero/1.0/) ។
