### ISSUE TITLE
Replace requires with a bibliography

### ISSUE THREAD

**Issue by Pandapip1** [ethereum/EIPs#6509]
### Proposed Change

I suggest that we replace the requires preamble item with a bibliography preamble item that uses a YAML version of CSL-json, to allow for #5733.

**Comment by Pandapip1** [comment]
(FYI - I'm trying to make the EIPs website index-able by Google Scholar)

**Comment by SamWilsn** [comment]
Having a simple field of EIP numbers makes it significantly easier for the common use case: referencing other EIPs. Making authors learn the whole CSL-JSON notation when what we have today works well is going to be a hard sell.

That said, I wholeheartedly support a more standard bibliography/references section in the generated HTML.

Is there some way we can combine the `requires` header with the CSL-JSON blocks, and automatically generate the proper citations in the rendered output?

**Comment by SamWilsn** [comment]
Oh, and I like the simple `key: value` format we've got going on in the preamble today. I think most people understand it. I know it's technically a full YAML document, but... maybe it shouldn't be.

**Comment by Pandapip1** [comment]
We can always make our own extension. For example, there's a shorthand for citing wikipedia articles; it shouldn't be too hard to copy that, use a different prefix, and modify the other stuff.

**Comment by Pandapip1** [comment]
@SamWilsn would you be okay if I made a prototype?

**Comment by SamWilsn** [comment]
You don't need my permission :rofl: 

I'd probably recommend with an example of what such an EIP would look like before diving into the implementation, so we can discuss that.

**Comment by Pandapip1** [comment]
Completely forgot about this. Don't know why the bot didn't trigger until 2 weeks ago and why I didn't get notified until now.
