### ISSUE TITLE
Contract code size remove fixed limit

### ISSUE THREAD

**Issue by BlameByte** [ethereum/EIPs#659]
### Parameters
`fork_block = TBA`
`max_code_size = 24 * 1024`

### Specification
**1a** - When current_block >= fork_block, make gas cost 200 per byte stored without a limit and use this calculation for gas cost on a call, callcode, delegatecall, extcodecopy, extcodesize: 
```sizeof(contract_code) <= max_code_size ? 700 : sizeof(contract_code) / 35```

**1b** - All the above except extcodecopy is a special case and instead of checking the size of the contract instead use the amount of bytes copied as the charged gas cost.

**1c** - All of the above and transactions sent to a contract with a size over max_code_size are also charged ```
sizeof(contract_code)``` before contract code is loaded into EVM.

**2a-c** - When current_block >= fork_block, make gas cost 200 per byte stored without a limit and use this for gas calculation on a call, callcode, delegatecall, extcodecopy, extcodesize:
```sizeof(contract_code) <= max_code_size ? 700 : (1 + sizeof(contract_code) / max_code_size) * 700```

### Rationale
The change made in EIP #170 should only be temporary as having a hard cap of 24,576 bytes on a contract will pose some issues on developers who want a lot of functions, libraries or just plain code and not being forced to use delegatecall, which can make code review harder as multiple contracts have to be checked and confusion over storage. The issue raised in that EIP was that there is a DoS issue if the contract size was too large as it has to fetch the entire code from disk, this fixes this by charging more depending on how much is stored.

Dividing the contract code size by 35 makes it so it costs 702 additional gas for a contract that is twice the max_code_size for a total of 1402 gas.

Proposal 1b makes it so that an extcodecopy does not require checking code size as it the amount of data copied can be read from the function which means that there is no need to check the code size.

Proposal 1c would provide a protection against transactions calling big contracts, which is not as big worry unless the contract code size is very large as it a lot harder to call as many contracts that way.

Proposal 2a-c makes it so the cost of gas would go up to 700, 1400, etc. This means that if you have a little over the max_code_size then you are charged 1400, but stops the possibility of finding a sweat spot to maximize disk I/O blocks.

Client specific implements can easily cache / store the code size of a contract as they will never change after creation, so checking the size of the contract code is extremely cheap and would not require much reads to the state.

It should be noted that only recently has the block gas limit raised enough to make the contract code size limit introduced in EIP #170 the limitation, at current gas limits ~ 6.6m so the max code size should be ~33k bytes.

**Comment by vbuterin** [comment]
> Client specific implements can easily cache / store the code size of a contract as they will never change after creation, so checking the size of the contract code is extremely cheap and would not require much reads to the state.

The problem is that there is one particular kind of verification that this is absolutely not true for: Merkle proofs (including fraud proofs). If I make a call with 800 gas, then inside that call make a child call that touches a 100,000-byte contract, then even though the inner call will immediately fail and OOG, creating the proof for that result still takes up 100,000 bytes of data.

**Comment by BlameByte** [comment]
> Now, if we added a code_size field to the account object, then I'd see no objections and would totally approve.
I would agree that is a better solution as it solves the above issue with merkle proofs which I did not take into account in the proposal, but I am concerned by how this would be added retroactively.

These are the ways I thought of which would be possible to implement, as adding it to all contracts at that block would obviously be infeasible.

1. Adding it to only to new contracts created since the hard fork.

2. Only adding it to new contracts created which exceed the max_code_size and if it lacks such a field we don't have to apply new rules.

3. Making it so a contract which is "touched" has the max_code_size stored.

But overall I am happy to add the code_size field to the proposal and once I clear up the above I will edit the original proposal to include the code_size field.

**Comment by ekreda** [comment]
Hi @BlameByte @vbuterin any update on this EIP ? (mind that for private net - it's even more needed)

We are trying to deploy a ~8.1m of gas contract on a private blockchain, where we control the gaspricelimit of the genesis block & the miners, but even with a higher values we're hitting the ~ 6.6m limit!

**Comment by ekreda** [comment]
@BlameByte @vbuterin anyone.. :)

We are on a private network (geth based)! if this value is hardcoded it's defiantly not suitable for private net and introducing a real drawback.

Is there a command line option or genesis file config to increase/override the EIP #170 limitation?

**Comment by nathanawmk** [comment]
hi guys i am building a sophisticated smart contract with quorum and I will prefer to have one smart contract instead of multiple ones. Any update on this? I tried maxCodeSize in genesis.json and it did not work.
