### ISSUE TITLE
Customizable editors

### ISSUE THREAD

**Issue by Pandapip1** [ethereum/EIPs#6650]
### Proposed Change

In eip-review-bot, currently there are predefined editor groups depending on the type and category. I propose that, as a stop-gap solution before implementing tags, that we have a slightly more customizable editor list for peer reviewers.

**Comment by SamWilsn** [comment]
What would this look like?

**Comment by Pandapip1** [comment]
Both!

**Comment by SamWilsn** [comment]
So `!nft` above removes NFT related topics from foobar's purview? Without tags, how does that work?

**Comment by Pandapip1** [comment]
The config file specifies the pseudo-tags

**Comment by Pandapip1** [comment]
Bump. Surprised the stale bot hasn't given any warnings.

**Comment by Pandapip1** [comment]
Weird... why did I get notified about https://github.com/ethereum/EIPs/issues/6650#issuecomment-1479681258 now?
