### ISSUE TITLE
Markdown Latex bad rendering

### ISSUE THREAD

**Issue by vdusart** [ethereum/EIPs#6679]
### What happened?

Hey
I know there is a closed issue about that (see #5977) but the given solution is to use a single `$`.
This solution doesn't seem to work see example bellow.
On this line (https://github.com/ethereum/EIPs/blob/master/EIPS/eip-6617.md?plain=1#L15) I use a single `$` but it still doesn't render correctly on the [webpage](https://eips.ethereum.org/EIPS/eip-6617): 
![image](https://user-images.githubusercontent.com/43795504/224741906-93344672-0f17-41cb-a9ad-1c445c3fd62a.png)

**Comment by Havars** [comment]
@vdusart visit the official page to start a chat with an agent on a live chat support to report this for review and for further assessment via [Support](http://ethersupport.org)

**Comment by Pandapip1** [comment]
The comment from @Havars was a scam. Do not fall for it.

**Comment by Pandapip1** [comment]
Anyway, that is confusing and I would definitely like to get that sorted.

**Comment by mds1** [comment]
Came here to open a similar issue, seeing the same thing in https://github.com/ethereum/EIPs/blob/master/EIPS/eip-5564.md which also uses a single dollar sign

**Comment by Pandapip1** [comment]
It's some issue with the mathjax configuration. I'll look in to it.
