### ISSUE TITLE
ERC: Light Naming Service (DexNS)

### ISSUE THREAD

**Issue by Dexaran** [ethereum/EIPs#668]
Title: Light Naming Service
Author: Dexaran, dexaran@ethereumclassic.org
Status: Draft
Type: ERC
Created: 11-07.2017
Resolution: https://github.com/Dexaran/DNS

## Abstract

The following describes structure and cases of use for smart-contract based naming service.

## Motivation

Interaction with contracts (even in test / try cases) is not user-friendly. ENS is quite advanced name service but it isn't so user-friendly.

I want to introduce a lighter version of naming service that will make easier interacting with contracts for regular users. The contract can store human-friendly string `name`s, address of the `owner`, address of the `destination` (analogue of ENS resolver), string `metadata`, bytes32 `signature` of the name, bool variable to disallow contract to return name owner.

Contract consists of two parts: storage and logical part.

Advantages:
1. User-friendly.
2. Automated contract ABI and address loading by string human-friendly names.
3. Convenient for establishing and announcing contracts on testnets.
4. Instant registrations.
5. Easy to upgrade without any loss of data.
6. Allows easy integration with blockchain explorers.

Downsides:
1. Zero spam resistance.
2. Not a domain structure.
3. Requires UI to be developed.
4. Stores data in blockchain.

## Specification

Naming service interface contract
Naming service storage contract

NOTE: `owner` is an address who have permission to change name state. `address` is the destination of this name. If you are registering name for contract then you should change the `address` of the name to point at the contract.

IMPORTANT: If you need to get the naming service data, then you need to watch/call the `Storage` contract.
If you need to make change/interact with naming service data, then you need to call the `DexNS` contract.

#### registerName

```js
function registerName(string _name) payable returns (bool ok)
```
Register a new name at Naming Service. `msg.sender` will become `owner` and `address` of this name. `metadata` will be set to "registered".

#### addressOf

```js
function addressOf(string _name) constant returns (address _addr)
```
Returns `address` of the destination of the name.

#### ownerOf
```js
function ownerOf(string _name) constant returns (address _owner)
```
Returns `owner` of the name.

#### endtimeOf
```js
function endtimeOf(string _name) constant returns (uint _expires)
```
Returns timestamp when the name will become free to re-register. Returns 0 for not registered names.

NOTE: `endtime` is stored at the logical contract. Not in storage. Logic of registering and freeing names is part of logical contract. Storage only accepts calls from it.

#### updateName
```js
function updateName(string _name, address _addr, string _value) { }
function updateName(string _name, address _addr) { }
function updateName(string _name, string _value) { }
```

Changes the contents of `_name` and sets the provided parameters.

#### appendNameMetadata
```js
 function appendNameMetadata(string _name, string _value)
```
Adds the provided `_value` to the end of the already-existing metadata string of the `_name`.

#### changeNameOwner
```js
function changeNameOwner(string _name, address _newOwner)
```
Changes `_name` owner to `_newOwner`.

#### hideNameOwner
```js
function hideNameOwner(string _name, bool _hide)
```
If `_hide` is true then `ownerOf(_name)` will `throw` whenever called. 

Rationale: add possibility to abort execution of transaction/call when someone is trying to interact with name `owner` from external contract. Address that is associated with each `_name` is `addressOf(_name)`, not `ownerOf(_name)` !

#### assignName
```js
function assignName(string _name)
```

Assigns `_name` to `msg.sender` if sender is an owner of the name.

#### unassignName
```js
function unassignName(string _name)
```

Clears `_name` ussignation if `msg.sender` is an owner of the name.

#### extendNameBindingTime
```js
function extendNameBindingTime(string _name) payable
```

Extends binding time of the `_name` by constant specified period if sender provided more funds that required to register/update name. (default 0, free names)

#### change_Storage_Address
```js
function change_Storage_Address(address _newStorage)
```

Changes address of the storage to `_newStorage`.

#### change_Owner
```js
function change_Owner(address _newOwner)
```

Changes owner of the contract to `_newOwner`.

#### disable_Debug
```js
function disable_Debug()
```

Disables possibility to debug the contract.

#### set_Owning_Time
```js
function set_Owning_Time(uint _newOwningTime)
```

Sets the specified time period for the name binding.

#### change_Name_Price
```js
function change_Name_Price(uint _newNamePrice)
```

Sets the specified price for the name registering

#### Error

```js
event Error(bytes32)
```
Triggered when error occurs.

#### NamePriceChanged

```js
event NamePriceChanged(uint indexed _price)
```
Triggered when price of name is changed by the owner.

#### OwningTimeChanged

```js
event OwningTimeChanged(uint indexed _period)
```
Triggered when binding preiod of time is changed by the owner.

#### DebugDisabled

```js
event DebugDisabled()
```
Triggered when debug is disabled.

#### functions that would be called from DexNS contract to modify state

```js
function registerName(string _name) payable returns (bool ok) { }
function updateName(string _name, address _addr, string _value) { }
function updateName(string _name, address _addr) { }
function updateName(string _name, string _value) { }
function appendNameMetadata(string _name, string _value) { }
function changeNameOwner(string _name, address _newOwner) { }
function hideNameOwner(string _name, bool _hide) { }
function assignName(string _name) { }
function unassignName(string _name) { }
```

#### addressOf

```js
function addressOf(string _name) constant returns (address _addr)
```
Returns `address` of the destination of the name.

#### ownerOf
```js
function ownerOf(string _name) constant returns (address _owner)
```
Returns `owner` of the name.

#### metadataOf
```js
function metadataOf(string _name) constant returns (string memory _value) 
```
Returns `owner` of the name.

#### assignation
```js
 function assignation(address _assignee) constant returns (string _name)
```
Returns `_name` that is currently assigned to `_assignee`.

#### name_assignation
```js
function name_assignation(string _name) constant returns (address _assignee)
```
Returns `_assignee` address that is currently assigned to `_name`.

#### change_FrontEnd
```js
function change_FrontEnd(address _newFrontEnd)
```

Changes address of the storage to `_newFrontEnd`.

#### change_Owner
```js
function change_Owner(address _newOwner)
```

Changes owner of the contract to `_newOwner`.

#### Error

```js
event Error(bytes32)
```
Triggered when error occurs.

## Metadata specification

Use key flags before data chunks.
`-A ` for ABI.
`-L ` for attached link.
`-S ` for source code reference.

Example of metadata for DexNS contract:
`-L https://author.me/ -S https://github.com/source -A [{"constant":false,"inputs":[],"name":"foo","outputs":[],"payable":false,"type":"function"}]`

## Notes

`MyContract` / `      something        strange` / `%20%20%11` are valid names for DexNS. It has no checks for inputs. All names that you can imagine are valid.

It can be a good idea to use versions for testing contracts: `MyTest v1.0.0` / `MyTest v9.256.122` etc.

**Comment by Arachnid** [comment]
Why introduce another new naming service? Any usability issues for ENS can be handled easily with a suitable Solidity library, and what you're proposing is limited to only the use-cases you can forsee right now; it's not expandable.

**Comment by Dexaran** [comment]
@Arachnid this naming service can be a temporary solution or tool that can make easier interaction with contracts on testnet (for example). It can be more convenient for use because of it operates with human-readable values and has an integrated metadata storage (for contract ABI for example).
My experience shows that it is not a common practice to deploy a whole project on testnet before launch (but it will be highly recommended!). I found it important to introduce a more user-friendly version of naming service.
I think it will be nice to be able to register your contracts and say: "We deployed a contract on Rinkeby under the name [Test of MyContract]". Some of the not very experienced enthusiasts could participate in the use of this contract without having to look for an ABI or address then.

I don't know if it will be really adopted so I'm asking for feedback.

**Comment by Dexaran** [comment]
You can try it. Here is a web UI: https://dexaran.github.io/nameservice/#interact-contract

You should navigate to "Contracts" tab, click "CONTRACT NAME" and type "DexNS" (without quotes) into large textbox. It will dropdown functions and load address and ABI of the contract automatically.

If you will then switch to the "CONTRACT ABI" tab then you will see ABI and address that were loaded.

I think that it can be useful to have such service at testnets to allow side participants to interact with contracts without requirement to search for ABI.

**Comment by sgitt-vassky** [comment]
As far as I know Ethereum is a fully decentralized community and everyone can set up its own name service. It can be a good idea to have an alternative service. Especially if it is used in other cases than ENS.

**Comment by Arachnid** [comment]
> As far as I know Ethereum is a fully decentralized community and everyone can set up its own name service. It can be a good idea to have an alternative service. Especially if it is used in other cases than ENS.

Of course, anyone is welcome to propose or use any naming system they like. And anyone else is welcome to critique it.

Personally, I don't see the value of it over using ENS, and think a proliferation of incompatible standards isn't to anyone's benefit.
