### ISSUE TITLE
Discussion for EIP6670 - Batched Transfers for ERC721

### ISSUE THREAD

**Issue by collect9** [ethereum/EIPs#6686]
# EIP6670

Although an EIP/ERC already exists for this (1412), I feel it is incomplete so I've created a new EIP for this.

## Quick Summary
Contrary to popular belief - proxy contracts do use more gas than is necessary, and the benchmarks in this EIP display that.

### The key thing that really needs official support is: _event TransferBatch(...)_

Without it, a lot of gas ends up getting wasted emitting events for every single transfer within proxy batches. And without official support, indexers will never know to look for such an event. The rest of implementation may be left up to the user, although I do believe something like this really should be standard. The savings from reducing the number of events emitted per just to just one only account for ~30% of the total gas savings seen - hence the full EIP.

Thank you!

EIP will pull requested soon (just getting discussion links added and checking my numbering is fine), and is located here until then:
https://github.com/collect9/EIPs/blob/master/EIPS/eip-6670.md

## Closing Note
I have no idea how the EIP numbering is done. Did I do this right? I see my issues link has '6686' in it so I am not sure if my EIP should be numbered that instead (I just picked a number that didn't look like it was taken yet in the repo). Thanks!

**Comment by Pandapip1** [comment]
Use https://ethereum-magicians.org/
