### ISSUE TITLE
Proposal for automatic ETH payments

### ISSUE THREAD

**Issue by jonasman** [ethereum/EIPs#680]
## Preamble

    EIP: <to be assigned>
    Title: Proposal for automatic ETH payments
    Author: Joao Nunes, joao3001@hotmail.com
    Type: Standard Track
    Category (*only required for Standard Track): Core
    Status: Draft
    Created: 2017-07-30

## Simple Summary
Automatic payments in ETH without breaking any security

## Abstract
My proposal is a new feature for ETH to support automatic payments without breaking any security

## Motivation
A user wants to use a service that needs a credit card. The service charges him every time he uses the service.

Example: Apple iTunes.
Every time the user buys an app, Apple will charge the user's card.

## Specification
Create a pay out address associated with my own account.

Rules

1) The payout address is linked to my own wallet
2) The payout can only be charged by only one merchant
3) There is a daily and monthly withdraw limit
4) There is a way to query if the payout address has enough funds to make the purchase
5) The wallet address cannot be known using only the payout address

## Rationale
1) it can only get coins from my own address
2) only one address can receive transfers from this payout address.
3) Added security
4) This will trigger a query to the wallet
5) Added security

## Backwards Compatibility
YES

## Test Cases
NA

## Implementation
NA

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by MicahZoltu** [comment]
A generalization of this proposal, I believe, would be the ability to give a contract rights to _pull_ funds from an account.  Something like approval.  One could then author the contract to have any ruleset it wants (including the rules proposed here).

One can already achieve this by transferring ETH into a wallet with these rules, but the disadvantage is that the user has to set-aside funds into the second contract, meaning they will no longer show up as part of the account holder's total balance.  If one has a lot of recurring subscriptions, then you quickly end up with a bunch of miscellaneous accounts.

Another option would be to create a standard wallet interface that supports constrained subscriptions.  This would be similar to ERC20 in that it would be an API standard that all wallets could implement that would allow functions like, "setup recurring subscription" and "setup withdraw allowance".  Then anyone that uses a compatible wallet would be able to use such services,

I think all of these solutions become more palatable once accounts can have contract code associated with them (I don't remember the EIP).

**Comment by zendevil** [comment]
Is work being done one this?
