### ISSUE TITLE
Stale last call deadlines

### ISSUE THREAD

**Issue by rencryptofish** [ethereum/EIPs#6840]
### What happened?

The following EIPs are in last call with a last call deadline prior to 2023-04-05. Should we bump their deadlines into the future?

| Number | Date       |
| ------ | ---------- |
| 1191   | 2019-11-18 |
| 2266   | 2020-12-31 |
| 3076   | 2021-11-03 |
| 5007   | 2022-09-25 |
| 5216   | 2022-11-12 |
| 5496   | 2022-11-29 |
| 1153   | 2022-12-08 |
| 2135   | 2023-02-01 |
| 747    | 2023-03-13 |
| 3651   | 2023-03-28 |
| 4910   | 2023-03-31 |
| 6105   | 2023-04-04 |

**Comment by Hektoreth** [comment]
.

**Comment by SamWilsn** [comment]
Some of those (eg. [EIP-747](https://github.com/ethereum/EIPs/pull/6700)) have open PRs.

Generally we let last call EIPs sit until someone wants to move them. Usually the authors take care of it, but anyone can open the pull request to move to final.

**Comment by Pandapip1** [comment]
Perhaps a bot should move them back into review after 6 months post-deadline.

**Comment by Pandapip1** [comment]
I think we agreed on this?
