### ISSUE TITLE
ERC-4337: What happens if an ERC20 token has a `burn()` function which allows contract owners to burn ERC20 tokens from any smart contract wallet as it doesn't require an `approve()` transaction to send ERC20 tokens to 0x00?

### ISSUE THREAD

**Issue by howardleejh** [ethereum/EIPs#6867]
### What happened?

I did a quick test with a simple ERC20 token contract, having an EOA(Metamask) mint and send some ERC20 tokens to another basic contract that just stores the ERC20 test tokens I made. Using the "owner" EOA that was used to deploy the ERC20 tokens, I can basically delete any ERC20 tokens that are stored by the smart contract via the `burn()` function. I wonder if this is also going to be the same behavior with ERC-4337 abstract smart contract wallets? 

My understanding is that for EOA non custodial wallets, either a manual `approve()` followed by `transferFrom()` is required or for newer tokens with `permit()`, for any EOA/contract to execute a `transfer()` on behalf of token owner, and as for the burn function for ERC20 tokens, burn = transfer to `0x00` account + affects total supply of token. 

Transaction can be found here:
https://sepolia.etherscan.io/tx/0xc206c8488dc17bccc979ed0435292737438c965cd5e09fc176ec98cb4bd9c177

**Comment by Pandapip1** [comment]
This is the wrong place to discuss EIPs. I recommend you join the Discord server dedicated to all things ERC-4337: https://discord.gg/kgCHfzzqpn
