### ISSUE TITLE
Make mend/renovate less frequent and less granular

### ISSUE THREAD

**Issue by SamWilsn** [ethereum/EIPs#6906]
### Proposed Change

Can do a once-a-week or once-a-month batch of updates? [The docs](https://docs.renovatebot.com/noise-reduction/) seem to suggest that it's possible.

**Comment by Pandapip1** [comment]
Why would this be desirable over granular PRs?

**Comment by SamWilsn** [comment]
I believe it was @lightclient who asked for it during an EIPIP. The idea being we get one update PR to go through every month, instead of a ton of small PRs.

I'm honestly not sure where I stand on this. I don't generally go through these PRs because I don't feel comfortable approving them unless I also go through whatever library is being updated.

**Comment by Pandapip1** [comment]
I'm okay with less frequent, but I want to keep the granularity. Otherwise, it's tricky to debug what causes what to fail, if/when a breaking change is introduced somewhere.

**Comment by Pandapip1** [comment]
@lightclient thoughts?

**Comment by lightclient** [comment]
I still think we should do this, about 20% of my last 25 github notifications for this repo is mend.

**Comment by Pandapip1** [comment]
> I still think we should do this, about 20% of my last 25 github notifications for this repo is mend.

Would you like me to seperate out CI from governance?

**Comment by lightclient** [comment]
I (and others) have notifications on for all PRs so it doesn't really matter if the bot tags me or not. I just don't think we need the frequency it is currently on.

**Comment by ProphetZX** [comment]
I‘m in favour of a separation, in the current setting, of CI from governance, preferably as quickly as possible. I think CI is damaging and hindering governance the way it is/was set up.

**Comment by Pandapip1** [comment]
> I think CI is damaging and hindering governance the way it is/was set up.

This is objectively false. CI, as it is currently set up, cannot hinder governance. How did you come to this conclusion?
