### ISSUE TITLE
Add RPC eth_chainId for querying the current blockchain chain ID

### ISSUE THREAD

**Issue by tcz001** [ethereum/EIPs#694]
## Preamble

    EIP: EIP694
    Title: Add RPC eth_chainId for querying the current blockchain chain ID
    Type: Standard Track
    Category: Interface
    Status: Draft
    Created: 2017-08-21

## Simple Summary

Add RPC eth_chainId for querying the current blockchain chain ID

## Abstract

Currently although we can use net_version RPC call to get the current network ID, there's no RPC for querying the chain ID. This makes it impossible to determine the current actual blockchain using the RPC.

## Motivation

An ETH/ETC client can accidentally connect to an ETC/ETH RPC endpoint without knowing it unless it tries to sign a transaction or it fetch a transaction that is known to have signed with a chain ID. This has since caused trouble for application developers, such as MetaMask, to add multi-chain support.

## Specification

As [Parity PR](https://github.com/paritytech/parity/pull/6329) and [ETC go-ethereum PR](https://github.com/ethereumproject/go-ethereum/pull/336), we can achieve cross-client compatible RPC API by using the same approach.
As described in ethereumproject/go-ethereum [PR](https://github.com/ethereumproject/go-ethereum/pull/336):

```
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": "0x3d"
}
```

**Comment by whilei** [comment]
I have submitted this a PR per the README instructions - https://github.com/ethereum/EIPs/pull/695.
