### ISSUE TITLE
Proposal for read only calls

### ISSUE THREAD

**Issue by leviadam** [ethereum/EIPs#697]
# Preamble
```
EIP: <to be assigned>
Title: Proposal for read only calls
Author: Adam Levi, leviadam@gmail.com
Type: Standard Track
Category: Core
Status: Draft
Created: 2017-08-25
```
# Abstract
A contract will have the option to call another contract, asserting that the internal call will not change the state.

# Motivation
We are now transforming from systems that were mostly single-contract, to complex systems composed of multiple contracts. In many cases a contract would like to make a call to another contract introduced by an agent, based on some standard. This can have many security risks.
In many cases, the calling contract only wants to read data from the called contract. It could be much better, security wise, if one could make such a call.
The only solution today is maybe to limit the gas, but I do not think it answers the need.

# Backwards Compatibility
Yes.

# Implementation
NA

# Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

#
Any feedback will be much appreciated.

**Comment by axic** [comment]
You should check out #214 and #195.

**Comment by leviadam** [comment]
Thank you, @axic. If think STATIC_CALL is very much answering the need.
I'm not sure though that I understand where on the pipeline this proposal is.

**Comment by holgerd77** [comment]
Guess this can be closed now?

**Comment by leviadam** [comment]
Yes, thank you!
