### ISSUE TITLE
EIP-698: Add opcode 0x46 BLOCKREWARD

### ISSUE THREAD

**Issue by realcodywburns** [ethereum/EIPs#698]
## Preamble
    
	EIP: 698
 	Title: OPCODE 0x46 BLOCKREWARD
	Author: Cody Burns <dontPanic@codywburns.com>
	Type: Standard Track
	Category: Core
	Status: Draft
	Created: 2017-28-08

## Simple Summary

This EIP adds an additional opcode to the EVM which will return a finalized blocks reward value. 

## Abstract

In the EVM, the 0x40 opcodes are reserved for `Block Information`. Currently reserved opcodes are:
* `0X40 BLOCKHASH`
* `0X41 COINBASE`
* `0X42 TIMESTAMP`
* `0X43 NUMBER`
* `0X44 DIFFICULTY`
* `0X45 GASLIMIT`

This EIP would add an additional opcode, `0x46 BLOCKREWARD`, which would return the block reward for any finalized block. The finalized block reward would include the base reward, uncle payments, and gas.   

## Motivation

Per EIP-649 ( #669 ) periodic block reward reductions/variance are now planned in the roadmap, however, this EIP is consensus system agnostic and is most useful in decentralized pool operations and for any contract that benefits from knowing a block reward payout(i.e. Merge mined tokens) 

## Specification

After block `n` all clients should process opcode `0x46` as follows:  

* Value: `0x46`
* Mnemonic: `BLOCKREWARD`
* δ:` 0` nothing removed from stack
* α:`1` block reward added to stack
* Description: `Get the block's reward emission` 
* GasCost: `G<sub>base</sub>`

Where:`µ'<sub>s</sub>[0] ≡ I<sub>HR</sub>`

### Contract Mining Pools

For distributed consensus systems(staking pools and mining pools) ad hoc groups combine resources in order to reduce variance in payouts. Broadly, pool operations function by allowing a collective of  miners / stakers  to verify their contribution to solving PoW or staking share by periodically submitting solutions which are is representative of the miners probability of finding a true block. 

In all these schemes `B` stands for a block reward minus pool fee and `p` is a probability of finding a block in a share attempt ( `p=1/D`, where `D` is current block difficulty).

Some common methods of mining pool payout are pay-per-share, `R = B * p`, proportional [`R = B * (n/N)` where `n` is amount of a miners shares, and `N` is amount of all shares in this round.], and pay-per-last-N-shares [`R = B * (n/N)` where miner's reward is calculated on a basis of `N` last shares, instead of all shares for the last round]. All of these methods are predicated on knowing the block reward paid for a given block. In order to provide a trust minimized solution, `0x46` can be used to call a blocks reward for computing payouts.     

### Merge mined tokens

Contracts could create tokens which could be variably ‘minted’ as a function of block reward by calling `0x46`  

### Currently deployed contracts

No impact

### Current clients

This EIP would be incompatible with currently deployed clients that are not able to handle `0x46` and would process all transactions and block containing the opcode as invalid. 

Implementation should occur as part of a coordinated hardfork.

## Further reading

[Mining Pools](https://en.wikipedia.org/wiki/Mining_pool)

The Yellow Paper Appendix H. Virtual Machine Specification section H.2

## Copyright

Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by 5chdn** [comment]
Doesn't this even make sense to include it in EIP-649 #669 ?

**Comment by realcodywburns** [comment]
It could be useful independent of 649. 649 seems more specifically focused on the mechanics of reward reduction on the mainnet ethereum surrounding the metro forks, whereas the opcode itself could be used universally: testnets and sister chains(etc, music, expanse, rootstock)

**Comment by realcodywburns** [comment]
For further clarity, `BLOCKREWARD` should return the total value of the Reward Applied(11.3) for block `n` as defined in section 11, Block Finalisation

**Comment by axic** [comment]
I'd suggest to consider writing this in a real EIP format (see the template here: https://github.com/ethereum/EIPs/blob/master/eip-X.md). That template contains more sections, including a rationale.

I'd also expand your motivation section with reasons about where this can useful - as you've mentioned it on the other thread, in designs like smartpool.

Lastly, probably it could be useful to have a way to get both the basic and the total reward, perhaps as a single parameter to the opcode (enum or boolean?).

**Comment by vbuterin** [comment]
I don't think this is worth the effort at the moment given the impending PoS switch. Once the exact long term consensus incentivization structure is finalized, I think it would make more sense to revisit something like this.

**Comment by realcodywburns** [comment]
The PoS switch has been "impending" for quite some time and seems to be delayed a bit longer. This eip is also applicable  to consortium chains, private chains, and others using multiple consensus algorithms.

**Comment by kylerchin** [comment]
wow....
This is cool. +1

**Comment by nicksavers** [comment]
Continue discussion in PR #700

**Comment by realcodywburns** [comment]
Bump

**Comment by axic** [comment]
@nicksavers This is the discussion URL for EIP-698.
