### ISSUE TITLE
Unlicensed code should NOT be allowed to be included in ANY proposals

### ISSUE THREAD

**Issue by sambacha** [ethereum/EIPs#7027]
Unlicensed code, meaning any copyrighted material, should be prohibited from being included in any sort of reference implementation or as part of any proposal.  

Example of unlicensed code being included in an EIP/ERC:

https://eips.ethereum.org/EIPS/eip-6551#registry-implementation

This also begs the question if all code should be included under the CC-0 license or some other permissive licenses be granted approval such as potential code samples from go-ethereum, etc.

**Comment by sambacha** [comment]
Additionally probably should have the bot check for SPDX license identifiers against allow list or some other search approximation.

**Comment by Pandapip1** [comment]
I would like to restate my previous opinion that I am still firmly against having any licenses other than CC0 used in the EIPs.

**Comment by jaydenwindle** [comment]
@sambacha my bad, I unintentionally copy/pasted this license in. Will update to remove the SPX modifier so that code is under the same CC0 license as the EIP by default.

**Comment by jaydenwindle** [comment]
Fixed for EIP-6551 in #7035. Would love to see a bot check added for this.

**Comment by SamWilsn** [comment]
> I would like to restate my previous opinion that I am still firmly against having any licenses other than CC0 used in the EIPs.

Even if we disagree on exactly which licenses to allow, we should definitely prevent `UNLICENSED` :rofl:

**Comment by sambacha** [comment]
> @sambacha my bad, I unintentionally copy/pasted this license in (it's added by default when using `forge init`). Had no intention to mark the code as copyrighted, it is definitely CC0. Will update to remove the SPDX modifier so that code is under the same CC0 license as the EIP by default right away.

ez oversight mate
