### ISSUE TITLE
Issues with CL Link Validation

### ISSUE THREAD

**Issue by timbeiko** [ethereum/EIPs#7064]
### Proposed Change

The regex used to [match CL spec links in EIP-1](https://eips.ethereum.org/EIPS/eip-1#consensus-layer-specifications) does not accommodate common CL spec linking practices. 

Two recent examples of issues: 

1. It's not possible to refer to a PR directly, which seems useful when things are in draft (see @dapplion's EIP here: https://github.com/ethereum/EIPs/pull/7044/files#diff-b9072b226494f022f46b59068e6f9144194aeb301e57ed74dbefe9fba49ef39dR27)

2. It's not possible to refer to feature directories, which are expected to be the canonical way to specify WIP features in the CL spec (see @djrtwo's EIP here: https://github.com/ethereum/EIPs/pull/6914/files#diff-768009de73cc7d111224f20db3c7f40c7eb3836aeaac51191810754ed62b8446R27) 

Proposed solutions: 

1. Allow linking to PRs (`https://github.com/ethereum/consensus-specs/pull/*`), potentially only for Draft EIPs? 
2. Allow linking to feature directories (`https://github.com/ethereum/consensus-specs/specs/_features/*`)

**Comment by SamWilsn** [comment]
> 1. Allow linking to PRs (`https://github.com/ethereum/consensus-specs/pull/*`), potentially only for Draft EIPs?

Would putting such a link in a TODO comment be acceptable? Something like:

```markdown
Execution clients MUST floop the pig as defined in <!-- TODO: https://github.com/ethereum/EIPs/pull/7044/files#diff-b9072b226494f022f46b59068e6f9144194aeb301e57ed74dbefe9fba49ef39dR27 -->.
```

> 2\. Allow linking to feature directories (`https://github.com/ethereum/consensus-specs/specs/_features/*`)

Not a terribly hard change, just need to modify EIP-1 and `eipw` to use this regex instead:

```regex
^https://(www\.)?github\.com/ethereum/consensus-specs/(blob|tree)/[a-f0-9]{40}/.+$
```

**Comment by g11tech** [comment]
Just explored if the PR commits hashes can be used to get a perma-link, following issues pop up

1. PR  could refer multiple files in very speadout folders
2. a permalink to commit is from the source repo for e.g. `https://github.com/dapplion/consensus-specs/tree/1c35eb1c3303fe1e0b101323106d766d8f848cd6` is the commit of a PR to `ethereum/consensus-specs` so would obviously fail current validation
3. If commit never is merged in main repo, it might get pruned out (even in merges github deletes source branch tag) and squash would anyway lead to new commit ?

**Comment by timbeiko** [comment]
> Would putting such a link in a TODO comment be acceptable? Something like:

I think so, @SamWilsn, but it might be simplest to simply allow `/pulls` for Draft and then require a folder directory to move to Review?

**Comment by g11tech** [comment]
Thanks to the input from @SamWilsn that the main repo to which PR has been made has the commit, we have come to consensus on the EIP editors call on May 31 that we can allow `compare` links in regex

`https://github.com/ethereum/consensus-specs/compare/53a9324cf0afd90ea06c5ebb0bfef8fc95a01fd1...1c35eb1c3303fe1e0b101323106d766d8f848cd6`

which basically generates the PR diff being refereed to

**Comment by g11tech** [comment]
I think this `https://github.com/ethereum/consensus-specs/compare/1c35eb1c3303fe1e0b101323106d766d8f848cd6~3...1c35eb1c3303fe1e0b101323106d766d8f848cd6`  (https://github.com/ethereum/consensus-specs/compare/1c35eb1c3303fe1e0b101323106d766d8f848cd6~3...1c35eb1c3303fe1e0b101323106d766d8f848cd6) this sort of diff would be best to include: which says last 5 commits including and preceding `96d29b7662f148842486d46117786ccb7fcc8018`

**Comment by Pandapip1** [comment]
> https://github.com/ethereum/consensus-specs/tree/1c35eb1c3303fe1e0b101323106d766d8f848cd6 seems to work for me. I believe GitHub adds commits from PRs to the destination repository under a weird ref.

Specifically, it's that the commits and objects from forks are stored in the parent repository, because GitHub logic.
