### ISSUE TITLE
Autonomous contract execution at each new block

### ISSUE THREAD

**Issue by Piliponful** [ethereum/EIPs#715]
Ability to make some function in your contract autonomously execute at each new block. Is that possible?

**Comment by onbjerg** [comment]
Who pays gas?

**Comment by Shrugs** [comment]
Various "scheduling" projects are attempting to solve this async excution issue (see: ZeppelinOS, others); but someone will have to pay the gas, and I doubt anyone is going to do it for free.

**Comment by GNSPS** [comment]
Check the Snow protocol.
