### ISSUE TITLE
Clarification about when touchedness is reverted during state clearance

### ISSUE THREAD

**Issue by pirapira** [ethereum/EIPs#716]
## Severity

* not posing forking threat on the mainnet
* causing failures in some conformance tests

## Problem

The state-clearing EIPs [158](https://github.com/ethereum/EIPs/issues/158) and [161](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-161.md) do not explicitly specify what happens to the "touched" accounts when OOG happens.

As a result, different implementations do different things.  Although they can all follow the mainnet, some tests fail (for example, `BlockchainTests/GeneralStateTests/stCreateTest/TransactionCollisionToEmpty_d0g1v0.json` reveals a difference between `geth` and `cpp-ethereum`).

It is not desirable to keep the unspecified corner in the specification.

## Possible solutions

Since no more empty accounts exist on the mainnet, the question here is how to specify what happened on the mainnet.

There are many ways to specify what happened on the mainnet.
a. [address 3 is special](https://github.com/ethereum/go-ethereum/blob/3c8656347f67dbc8e57c663ec5c26d24c4151678/core/state/journal.go#L97), although otherwise touched accounts become untouched after OOGs
b. [precompiled contracts are special](https://github.com/ethereum/cpp-ethereum/blob/9a13ce49082eee29e5d9159c3549087c675fa50c/libethereum/Executive.cpp#L274), although otherwise touched accounts become untouched after OOGs
c. [a certain transaction in a certain block is spceial](https://github.com/ethereum/yellowpaper/pull/288/files#diff-9f702e1491c55da9d76a68d651278764R2257), although otherwise touched accounts become untouched after OOGs
d. OOG in inner calls should keep touched accounts; OOG in the outermost call in a transaction untouches accounts.
e. OOG in the touching call and inner calls should keep touched accounts; OOG in a parent call context untouches accounts.

## Proposal

<del>The proposal here is to pick d. or e. because they do not involve magic numbers.  Perhaps `e.` is cleaner because it does not talk about the magic "outermost call".</del>

After seeing options, `a.` looks the simplest.

## Steps to be taken

* [ ] an experimental implementation of `a.` on cpp-ethereum is created will be tested on the mainet.
* [ ] an EIP will be written
* [ ] the EIP will be discussed in coredev meetings
* [ ] test cases will follow the EIP
* [ ] YP will follow the EIP

**Comment by holiman** [comment]
Some more context

## Background

At block 2675119, shortly after the planned “Spurious Dragon” hard fork, the state sweep to ‘touch’ empty account had just begun. The initial account sweeping went from 0x0 and up.
When a call to 0000000000000000000000000000000000000003 was made ([tx](https://etherscan.io/tx/0xcf416c536ec1a19ed1fb89e4ec7ffb3cf73aa413b3aa9b77d60e4fd81a4296ba)), the CALL went Out-of-gas. The reason being that 3 is the address of the RipeMD160 precompile.
Incidentally, both RipeMD160 (0x3) and Identity (0x4) were ‘empty’ accounts created by the attacker, whereas ‘0x1’ and ‘0x2’ already contained ether and were not ‘empty’.
At this point, even though the CALL to RipeMD160 went OOG, the effects were _not_ reverted, and both Geth and Parity deleted the account . 
**NB**: The actual transaction did not go out of gas, only the (inner) CALL.


At block 2686351, the state sweep of ‘seeded’ accounts was in progress. During the execution of these invocations of the Sweeper.sol contract, the number of ‘touches’ to perform is varying. An invocation was made which attempted to perform 1320 CALLs within 600K gas. This was insufficient, and the transaction went out of gas. So while the touches had been performed via `CALL`, the _outer_ context went `OOG`. 

* At this point, Parity reverted the effects of the call, thus not deleting the touched accounts
* Geth failed to revert the effects, and deleted the touched accounts, causing consensus-issue. 

As Geth implemented reversion of touch after OOG, the earlier case was discovered. 

## Possible solutions

I'd even split up d) into two options: either see it as topmost vs internal calls, or see it as call parent context vs call context. Consider the following scenario:

1. Tx -> Call A -> Call B-> Call/Create "empty but existing account"
2. Call B-> OOG

**Comment by pirapira** [comment]
@holiman I didn't get the further split options.  Is it like

1. Tx -> Call A -> Call B-> Call/Create "empty but existing account" -> OOG
2. Tx -> Call B-> OOG

?

**Comment by holiman** [comment]
```
Tx 
    Calls A
       which Calls B
            Which calls (or Creates into) an "empty but existing account". This is a touch. 
            And then, after the call/touch is done, goes OOG.
       but A has not gone OOG, but returns orderly
```

The question is if the distinction is between: 

1. Topmost calls versus inner calls
2. Parent context versus child context. (Could be topmost vs inner, but also inner1 vs inner2)

**Comment by pirapira** [comment]
Am I getting the words parent and child correct?  In your example, `Calls A` and `Calls B` are both parent contexts.  `Calls B` and `calls (or Creates into) an "empty but existing account"` are child contexts.  The OOG happens in `Call B`, which is at the same time a parent context and a child context.

**Comment by holiman** [comment]
Perhaps I should've examplified with `A->B->....M->N` . So the outer context runs fine, and so do all the child contexts, except for the last parent-contex (M)t. 

You wrote: 

`OOG in inner calls should keep touched accounts; OOG in the outermost call in a transaction untouches accounts.`

An alternative  _could_ be
`OOG in inner calls should keep touched accounts; OOG in a parent call context untouches accounts.`

I'm not saying it _should_ be, just that it's an option. Maybe. These things are so confusing. :confused:

**Comment by pirapira** [comment]
I was trying to understand your alternative.  If I can rephrase,

`OOG during touching is still touching, but an OOG in a shallower execution frame untouches.`

This one sounds less arbitrary because it doesn't rely on "the outermost level" (nothing else in EVM is aware of "the outermost level" I guess).

**Comment by pirapira** [comment]
So edited the description of the issue.

**Comment by holiman** [comment]
Also, a comment about option `b. precompiled contracts are special, although otherwise touched accounts become untouched after OOGs`.

This may be a bit hairy to implement, depending on where the 'fix' is applied; but potentially the journal would need to know what addresses are precompiles (which depends on blocknumber). It would be possible to state another rule: 

* `Addresses < `0x4` are special. A 'touch' on `<0x4` is never rolled back. 

One added complication to bear in mind, is that with the new precompiles, we have new errors (point not on curve etc), which supposedly behaves like OOG. If we were to use a `b`-like option, perhaps we should avoid phrasing the rule in terms of `OOG`, if possible.

**Comment by holiman** [comment]
Parity [uses precompiles are special](https://gitter.im/ethereum/AllCoreDevs?at=59c386f697cedeb0482986b5), option `b`.

**Comment by pirapira** [comment]
@holiman figured cpp does a very complicated thing.  It's so complicated that I don't want to describe it.

**Comment by pirapira** [comment]
I implemented `a.` in cpp-ethereum and now trying to sync the mainnet. https://github.com/ethereum/cpp-ethereum/tree/geth-style-cleanup-rule

**Comment by pirapira** [comment]
On https://github.com/ethereum/cpp-ethereum/tree/experiment-geth-rule (revision 0a90a234579e1f111d0cf1b6df9def609193168d) I get
```
  �  15:31:52.844|eth
                                                                                
                                                                                
    Import Failure     InvalidReceiptsStateRoot                                 
                                                                                
                       Bad Block #02675119.8ca3da34��                      
                                                                                
  �                                                                             
�  �  15:31:52.844|eth  #4dc73a02�� : Unknown parent #8ca3da34��
  �  15:31:52.845|eth  ODD: Import queue contains block with unknown parent.
�  �  15:31:52.845|eth  #a773968e�� : Unknown parent #4dc73a02��
  �  15:31:52.846|eth  ODD: Import queue contains block with unknown parent.
�  �  15:31:52.846|eth  #749df97d�� : Unknown parent #a773968e��
  �  15:31:52.847|eth  ODD: Import queue contains block with unknown parent.
```

**Comment by pirapira** [comment]
I can reproduce this.  Interestingly, under gdb, the special case about address 3 is not hit.

**Comment by pirapira** [comment]
Wow, cpp-ethereum doen't even touch it.

**Comment by pirapira** [comment]
I modified https://github.com/ethereum/cpp-ethereum/tree/experiment-geth-rule and passed block 2675119.
* [ ] check if the same version can pass block 2686351
* [ ] restart the same version from the gnesis block up to the tip of the mainnet

**Comment by pirapira** [comment]
I saw `ldb` errors and I couldn't sync further.  Maybe the problem might have been fixed in cpp-ethereum.  I'll rebase and try again.

**Comment by germsvel** [comment]
@holiman @pirapira sorry to revisit this after so much time has passed. I am trying to implement some code for [failed_tx_xcf416c53 common test](https://github.com/ethereum/tests/blob/develop/GeneralStateTests/stSpecialTest/failed_tx_xcf416c53.json) which deals with this issue.

Was consensus every reached as to whether option `a` (address 3 is special) or `b` (all precompiled contracts are special) is preferred?
