### ISSUE TITLE
Add rules regarding the anchor text for BIPs, W3C, IETF, WHATWG

### ISSUE THREAD

**Issue by SamWilsn** [ethereum/EIPs#7185]
Would still like the rules regarding the anchor text.

Originally posted by @Pandapip1 in: 
 - https://github.com/ethereum/EIPs/pull/7111#pullrequestreview-1457283430
 - https://github.com/ethereum/EIPs/pull/6907#discussion_r1186072144
 - https://github.com/ethereum/EIPs/pull/7113#pullrequestreview-1457262020
 - https://github.com/ethereum/EIPs/pull/7117#pullrequestreview-1457256735

**Comment by Pandapip1** [comment]
As is evidenced by the fact that I was the one suggesting this, +1. We have rules for referencing EIPs, so it only makes sense to do the same with other references.

**Comment by SamWilsn** [comment]
I thinking we re-use the same logic (for the most part) that we do for EIPs themselves:

 * > RFCs must be referenced with the form `RFC N` (not `RFCN` or `RFC-N`)
 * > BIPs must be referenced with the form `BIP N` (not `BIPN` or `BIP-N`)

Not sure how we want to handle WHATWG though.

**Comment by Pandapip1** [comment]
> Not sure how we want to handle WHATWG though.

Require that it use the spec's title?

**Comment by Karlitos88** [comment]
> ```
>           Would still like the rules regarding the anchor text.
> ```
> 
> Publicado originalmente por@Pandapip1en:
> 
> * [Actualización EIP-1: agregue W3C como origen permitido #7111 (revisión)](https://github.com/ethereum/EIPs/pull/7111#pullrequestreview-1457283430)
> * [Actualizar EIP-1: actualizar EIP-1 ​​para permitir el enlace a BIP #6907 (comentario)](https://github.com/ethereum/EIPs/pull/6907#discussion_r1186072144)
> * [Actualizar EIP-1: agregar IETF como origen permitido #7113 (revisión)](https://github.com/ethereum/EIPs/pull/7113#pullrequestreview-1457262020)
> * [Actualizar EIP-1: agregar WHATWG como origen permitido #7117 (revisión)](https://github.com/ethereum/EIPs/pull/7117#pullrequestreview-1457256735)
