### ISSUE TITLE
Change EIP 6 from "Draft" to "Accepted"

### ISSUE THREAD

**Issue by Souptacular** [ethereum/EIPs#72]
Both Solidity and Serpent have implemented the changes needed to alias suicide(). [SELFDESTRUCT has been added as an alias of SUICIDE opcode (rather than replacing it)](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-6.md).

https://github.com/ethereum/solidity/commit/a8736b7b271dac117f15164cf4d2dfabcdd2c6fd https://github.com/ethereum/serpent/commit/1106c3bdc8f1bd9ded58a452681788ff2e03ee7c

Because changes have been made to 2/3 Ethereum high level languages, I believe that is sufficient for the EIP's status to be moved from "Draft" to "Accepted"

**Comment by chfast** [comment]
Where is it also needed? EVM? LLL?

**Comment by Souptacular** [comment]
Afaik it would be difficult to replace the opcode at the EVM level. The spirit of the EIP is to replace the term where it is easy enough to replace and alias the term in other places. If it is easy to replace or alias in LLL I would be for that, but otherwise I think making the alias in Solidity and Serpent is enough.

**Comment by chfast** [comment]
EVM also names the opcodes. It still will be opcode `0xff` but can be renamed to `SELFDESTRUCT`.

**Comment by Souptacular** [comment]
I was unaware of that. Could someone rename that in the EVM? I don't have the skill to.

**Comment by bobsummerwill** [comment]
Please yes.   We should get this thread to a conclusion.

It would be great if the "Homesteaders" need never come across `SUICIDE` because it's gone.

**Comment by wanderer** [comment]
@Souptacular please put in a PR with the change

**Comment by nicksavers** [comment]
Done in commit https://github.com/ethereum/EIPs/commit/937e5bada93a42b89d0387c5672140a773b33f92

@Souptacular Can this be closed?

**Comment by Souptacular** [comment]
Yes

**Comment by bobsummerwill** [comment]
Myself, March 2016 ...

"Please yes. We should get this thread to a conclusion.
It would be great if the "Homesteaders" need never come across SUICIDE because it's gone."

It has grated on me AGAIN to see people still talking about SUICIDE in the ether-recovery gitter channel.

What exactly is still left, and why?   Please could you enumerate your understanding, @Souptacular?

Is this just a habit thing, where people are still using the old name, even though EVM and languages have been updated?

**Comment by Souptacular** [comment]
Nothing is left for this one. Unfortunately we weren't able to get the EVM opcode replaced so that is why it persisted.

**Comment by nicksavers** [comment]
@bobsummerwill 

It's been renamed in the yellowpaper, solidity & serpent, ethereumjs and py-evm

But not yet in most client implementations and tools
https://github.com/paritytech/parity/search?utf8=%E2%9C%93&q=suicide
https://github.com/ethereum/cpp-ethereum/search?utf8=%E2%9C%93&q=suicide
https://github.com/ethereum/go-ethereum/search?utf8=%E2%9C%93&q=suicide
https://github.com/ethereum/ethereumj/search?utf8=%E2%9C%93&q=suicide
https://github.com/ethereum/pyethereum/search?utf8=%E2%9C%93&q=suicide
https://github.com/web3j/web3j/search?utf8=%E2%9C%93&q=suicide

And StackExchange still has 125 results
https://ethereum.stackexchange.com/search?q=suicide

**Comment by bobsummerwill** [comment]
Thanks for that detail, @nicksavers.  Very good to know.

But there is no technical barrier here, right?   It is just renaming work to be done in particular codebases.

And just social language policing ... like "Hey!  Please say Fire Fighter not Fireman.  You are being sexist.  I am sure there is no ill intent, but please be part of the solution, not the problem."

**Comment by bobsummerwill** [comment]
Because this stuff matters.   Saying suicide all the time is NOT GOOD.
