### ISSUE TITLE
Unique tokens system to prevent forging tokens.

### ISSUE THREAD

**Issue by patpat8** [ethereum/EIPs#722]
ATTENTION! If you would like to submit an EIP and it has already been written as a draft (see the [template](https://github.com/ethereum/EIPs/blob/master/eip-X.md) for an example), please submit it as a [Pull Request](https://github.com/ethereum/EIPs/pulls).

If you are considering a proposal but would like to get some feedback on the idea before submitting a draft, then continue opening an Issue as a thread for discussion.  Note that the more clearly and completely you state your idea the higher the quality of the feedback you are likely to receive.

Keep in mind the following guidelines from [EIP-1](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1.md):

> Each EIP must have a champion - someone who writes the EIP using the style and format described below, shepherds the discussions in the appropriate forums, and attempts to build community consensus around the idea. The EIP champion (a.k.a. Author) should first attempt to ascertain whether the idea is EIP-able. Posting to the the Protocol Discussion forum or opening an Issue is the best way to go about this.

> Vetting an idea publicly before going as far as writing a EIP is meant to save the potential author time. Asking the Ethereum community first if an idea is original helps prevent too much time being spent on something that is guaranteed to be rejected based on prior discussions (searching the Internet does not always do the trick). It also helps to make sure the idea is applicable to the entire community and not just the author. Just because an idea sounds good to the author does not mean it will work for most people in most areas where Ethereum is used.

> Once the champion has asked the Ethereum community as to whether an idea has any chance of acceptance, a draft EIP should be presented as a Pull Request. This gives the author a chance to flesh out the draft EIP to make properly formatted, of high quality, and to address initial concerns about the proposal.

**Comment by patpat8** [comment]
It is very easy for anyone to create an exact copy of a pre existing coin. Take for example ATC token.
The same token can be identified by these 3 addresses :

https://etherscan.io/token/0x7ce88ceed1015ecebaed624459dd97435e77157b

https://etherscan.io/token/0xeaac5d6beab6f1b214152c8201ad1111028e6a1a

https://etherscan.io/token/0x379ca5d5f053f92a60388f4ca748060c6f6664b2

I am aware of the fact that there is an additional ✓ mark to signify the correct token but in case of direct trading between peers if the receiver has not received any tokens before can be misguided to believe what is being sent is legit one.

I hope you understand what I am saying if further clarification is required , then let me know.
Thanks.

**Comment by MicahZoltu** [comment]
Do you have a proposal to address this perceived problem?  The issue body is missing.

**Comment by patpat8** [comment]
Oops that's embarrassing. Actually this was my 1st ever issue reporting on GitHub. :)

I currently do not have an exact proposal to solve this issue because I am not familiar with the underlying code . 
It may be possible that whenever there is a new Token Contract being created , a method should be called that runs through database of pre-existing tokens and validates that the Name & Symbol being used is not already taken.

Point is to disallow creation of a new token which contain Exactly the same "Name" and "Symbol' of previously existing token.

For ex. If there is a ABCD coin already existing as a token with Symbol ABCD no-one else should be able to create another "ABCD coin" sym: "ABCD" . 

I think it's a much needed censorship that has to be brought .

I hope I am clear with the issue part. How to solve it I am not completely sure.

**Comment by MicahZoltu** [comment]
Ethereum is all about censorship resistance, and no one has more of a right to a token name/symbol that anyone else.  ENS provides a first-come-first-serve-ish mechanism for buying/renting namespaces, but I'm not sure there is value in embedding a complex auction/rent system like that into tokens.

In general, I suspect an EIP that attempts to limit freedom of choice for token names/symbols is likely to result in quite a bit of push back, especially since there are only ~17,000 3 letter symbols which means they'll be all bought up really fast in whatever auction system you had and then likely squated on.

**Comment by patpat8** [comment]
I understand your concern and practicality issue. 
Close this issue if you feel so.
Thanks.

**Comment by d-sfounis** [comment]
I'm only here because I mistuped 721 on the URL lel
