### ISSUE TITLE
Question on EIP137

### ISSUE THREAD

**Issue by agusputra** [ethereum/EIPs#723]
I see [EIP137](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-137.md) and the status is final. But why it is not added to Finalized EIPs on README.md?

**Comment by Arachnid** [comment]
Operator error. ;)

**Comment by agusputra** [comment]
What is "operator error" ?

**Comment by nicksavers** [comment]
This EIP has been added to Finalized on the README in commit https://github.com/ethereum/EIPs/commit/29754d7819a961abf7b0807197d24d3971baa9b8
