### ISSUE TITLE
add eth_signTransaction to the RPC API

### ISSUE THREAD

**Issue by wighawag** [ethereum/EIPs#728]
as mentioned here : https://github.com/ethereum/EIPs/issues/636
```eth_sendTransaction``` is doing 2 things: signing and sending

since we already have ```eth_sendRawTransaction``` we would just need the extra method : ```eth_signTransaction```

```eth_sendTransaction``` would then be used as a convenient option only.

Rationale:

```eth_signTransaction``` is useful in situations where you want to control when the transaction is broadcasted to the network. Currently there is no way to get a signed transaction out of the user without sending to the network at the same time.

**Comment by frozeman** [comment]
@bas-vk don't we have that already?

**Comment by onbjerg** [comment]
Doesn't seem to be documented at least. `eth_sign` adds a prefix to the message being signed, so wouldn't work for transactions.

**Comment by jojeyh** [comment]
Totally behind this.  I think there needs to be a more robust RPC interface in general.  This one in particular would be super useful for dapps that want to use Raiden-like capabilities in their code.

**Comment by leonardinius** [comment]
Just to drop the note, we also would like to see that as part of public (read documented) JSON-RPC APIs, also to simplify and prevent double spend issues.
