### ISSUE TITLE
Move Last Call EIPs into Review 6 months after the last-call-deadline passes

### ISSUE THREAD

**Issue by Tyemg** [ethereum/EIPs#7328]
Perhaps a bot should move them back into review after 6 months post-deadline.

_Originally posted by @Pandapip1 in https://github.com/ethereum/EIPs/issues/6840#issuecomment-1511785014_

**Comment by Pandapip1** [comment]
Obviously, as the person who suggested this, +1.

**Comment by Gogi33** [comment]
https://github.com/ethereum/EIPs/issues/7328#issue-1803836273

**Comment by poojaranjan** [comment]
It was discussed in EIPIP 79. EIP Editors on the call were mostly in agreement with the proposal, ref. [summary](https://github.com/ethereum-cat-herders/EIPIP/issues/226#issuecomment-1514878971). Someone should open a PR to propose this change.

**Comment by xinbenlv** [comment]
For the record, I am in favor too
