### ISSUE TITLE
Add definitions of SHOULD, MUST, OPTIONAL to EIP1

### ISSUE THREAD

**Issue by HaleTom** [ethereum/EIPs#736]
I noticed in #20 that the words SHOULD, MUST and OPTIONAL are used without explanation. They are capitalised, so I assume there is a special meaning attached.

No definitions are given in [EIP1 - EIP Purpose and Guidelines](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1.md).

I MUST know that they mean. SHOULD these terms be added to EIP1 or OPTIONALy somewhere else?

**Comment by HaleTom** [comment]
`THOUGH` is also used in the #20's `approve` description.

**Comment by RichHorrocks** [comment]
See [RFC-2119: Key words for use in RFCs to Indicate Requirement Levels](http://www.rfc-base.org/rfc-2119.html).

**Comment by carver** [comment]
Per the RFC, it's reasonable to be explicit about their usage.

> Authors who follow these guidelines
   should incorporate this phrase near the beginning of their document:
>> The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL
      NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED",  "MAY", and
      "OPTIONAL" in this document are to be interpreted as described in
      RFC 2119

**Comment by zhtet036** [comment]
Confirm

**Comment by nicksavers** [comment]
Good idea. @HaleTom Could you close this issue and create a pull request to incorporate this phrase near the beginning of EIP-1 so it can be reviewed and merged?

**Comment by axic** [comment]
I think this was covered by #2960.
