### ISSUE TITLE
TokenFallback Function

### ISSUE THREAD

**Issue by mariam-crissi** [ethereum/EIPs#744]
I am trying to create an ICO based on ERC223.

In my Token Creation Contract.I have defined an interface for CrowdSale with tokenFallback Function.

           interface CrowdSale {
                      function tokenFallback(address _from, uint _value, bytes _data);
           }
And also I have written the transfer function with respect to ERC223 syntax.

        function transfer(address _to, uint _value) {
        uint codeLength;
        bytes memory empty;
        assembly {
            // Retrieve the size of the code on target address, this needs assembly .
            codeLength := extcodesize(_to)
        }
        //Cheking Conditions
        require(balanceOf[msg.sender] > 0);
		require(balanceOf[msg.sender] >= _value);
		require(balanceOf[_to] + _value >= balanceOf[_to]);
        //Transfer Execution
        balanceOf[msg.sender] -= _value;
        balanceOf[_to] += _value;
        //If _to is a contract Address
        if (codeLength>0) {
            CrowdSale receiver = CrowdSale(_to);
            receiver.tokenFallback(msg.sender, _value, empty);
        }
        //Event Emitting
        Transfer(msg.sender, _to, _value, empty);
    }

Then I created CrowdSale Contract
Here I have defined to emit an event.

                   function tokenFallback(address from,uint value,bytes data) public {
                                            LOGTokenFallBack(from,value,data);
                                           //****************** */
                                           //Testing Transfer of Coins
                                          tokenReward.transfer(from,value);
                                          //****************** */
                      }

I can change the ownership of token as crowdsale contract..But I can't able to transfer tokens into crowdsale contract.How can I execute this?

Can you please help me?

**Comment by 3esmit** [comment]
You are asking questions in the wrong place. 

Also, to fix your problem the contract receiving tokens needs to extend from this interface: 
```
pragma solidity ^0.4.14;

/**
 * @title TokenReceiver
 * @dev Used by ERC223
 */
contract ERC223Receiver {
    function tokenFallback(address _from, uint _value, bytes _data);
}
```
Next time try asking here https://gitter.im/ethereum/solidity

**Comment by chriseth** [comment]
Not an EIP.
