### ISSUE TITLE
Specify the range of chain IDs

### ISSUE THREAD

**Issue by pirapira** [ethereum/EIPs#748]
[EIP155](https://github.com/ethereum/yellowpaper/pull/282/files#diff-9f702e1491c55da9d76a68d651278764R1405) introduces chain IDs.  The EIP does not define the biggest / smallest possible chain IDs.  This issue keeps track of defining the possible chain ID values.

**Comment by pirapira** [comment]
Go-ethereum uses unsigned 64 bit integers, I heard.

**Comment by realcodywburns** [comment]
geth-etc, geth-eth, quorum use [uint64](https://github.com/ethereum/go-ethereum/blob/4bc60e3aa8eb3929a4e040ef260807a36e3db1d8/cmd/puppeth/wizard_genesis.go#L126) 

cpp uses [uint256](https://github.com/ethereum/cpp-ethereum/blob/42b927d7aa103e21e34c8ba8c5469f532b49f966/libethereum/ChainParams.cpp#L132) 

To not fail a uint64 is needed. 
The max range is 18,446,744,073,709,551,615; that is, hexadecimal 0xFFFFFFFFFFFFFFFF 

If a chain wants to use a dynamic `chainID`  ie chainID = hash of last known fork header +1, they can prune it to a uint64 hex
