### ISSUE TITLE
Add a CLA

### ISSUE THREAD

**Issue by Limpisey77922321** [ethereum/EIPs#7510]
### Suggestion

The inclusion of a Larger Works concept facilitates use of a contributor license agreement (CLA), with contributors granting a patent license to the works to which they're contributing, and therefore creating a common & safe platform for collaboration where no one is going to assert infringement by the same project in which they're an active participant.

**Comment by Ramezaan7** [comment]
EIPS/eip-20.md

**Comment by SamWilsn** [comment]
This is a duplicate of https://github.com/ethereum/EIPs/issues/5662
