### ISSUE TITLE
Embed `discussions-to` threads on the EIP itself

### ISSUE THREAD

**Issue by SamWilsn** [ethereum/EIPs#7541]
Originally posted by @g11tech [on Discord](https://discord.com/channels/916516304972824576/916713912970412103/1146343292619980831):

> hey fellas, while having discussions with some people about how to best present the summary of the EIP it struck to me that  we can  render/open an a small `iframe` section to the discussion-to link, (or the right pane).
>
> this would very much provide the context to the EIP and would be very useful imo. would also provide more relevance to the `discussions-to` link

Looks like this should be possible: https://meta.discourse.org/t/embed-discourse-comments-on-another-website-via-javascript/31963

**Comment by SamWilsn** [comment]
@shemnon brought up the concern that if the discussion is presented on the same page, people might think the discussion is normative.

**Comment by Pandapip1** [comment]
How about we enable it for only Review and Last call EIPs?

**Comment by shemnon** [comment]
On the call there was discussion of multiple websites form the spec repos, and that one of them could be a "voltron" style website where all the repos are combined.  I think such additions would add value to this voltron website.

So we would have:
* EIP normative website (like todays website)
* ERC normative website (like todays, but at erc.ethereum.org)
* Future normative websites (like rollup, wallet, and RPC focused specs, at rip.e.o, wip.e.o, and iip.e.o, for example)
* "Voltron" that combines all of the above into one website, includes renderings or execution specs and consensus specs, and has other enhancements like this unrolled discussions in the EIP.  At "specs.ethereum.org" or some similarly generic umbrella name.

So my objection is not to the idea, but that it is in the wrong place on a website that is considered a canonical URL.

**Comment by Pandapip1** [comment]
> On the call there was discussion of multiple websites form the spec repos, and that one of them could be a "voltron" style website where all the repos are combined. I think such additions would add value to this voltron website.

I volunteer as maintainer of the voltron-style website, since I manage https://eip.info anyway.

**Comment by xinbenlv** [comment]
+1

**Comment by julco1928** [comment]
> Originally posted by @g11tech [on Discord](https://discord.com/channels/916516304972824576/916713912970412103/1146343292619980831):
> 
> > hey fellas, while having discussions with some people about how to best present the summary of the EIP it struck to me that  we can  render/open an a small `iframe` section to the discussion-to link, (or the right pane).
> > this would very much provide the context to the EIP and would be very useful imo. would also provide more relevance to the `discussions-to` link
> 
> Looks like this should be possible: https://meta.discourse.org/t/embed-discourse-comments-on-another-website-via-javascript/31963

**Comment by lightclient** [comment]
I feel like the link is sufficient.

**Comment by vlknurl** [comment]
chainco

**Comment by Bhaskary20** [comment]
can i take the issue?
