### ISSUE TITLE
brain wallet discussion

### ISSUE THREAD

**Issue by axic** [ethereum/EIPs#76]
I think it would be important and useful to discuss brain wallets and eventually settle on a method, which can be cross-application.

**Current implementations**

I am aware of three brain wallet implementations:
- [libethereum](https://github.com/ethereum/wiki/wiki/Brain-Wallet)

Run `sha3` on the seed 16384 times. Then run `sha3` until the first byte of the address is 0 (to be compatible with ICAP Direct).
- [Ether.Camp](http://live.ether.camp/)

A simple `sha3` over the passphrase.
- [Quorum](http://quorumwallet.com/)

Requires a passphrase and a userid, both at least 10 characters long. Use the concatenated userid and passphrase as the input to `PBKDF2` with 2000 rounds, 32 bytes key size and `sha256` hashing.

_(Note: the brain wallet part in Quorum is not supposed to have more Ether than what is needed to execute the contracts and therefore it wasn't made to be very complex)_

**Passphrase generation**

@alexvandesande has posted a [nice little tool](http://codepen.io/alexvandesande/pen/mymWEj) to generate memorable passphrases. There are many other dictionary tools.

**A common interface**

It would be important to define a common key derivation method with the inputs required. These inputs also should have minimum length/strength requirements.

Hopefully this can be a start to a discussion to devise such a standard.

cc @alexvandesande @ryancdotorg @romanman @Gustav-Simonsson 

**Update**: it seems like we were writing at the same time with @alexvandesande. https://github.com/ethereum/EIPs/issues/75 proposes a specific method.

**Comment by alexvandesande** [comment]
We wrote at the same time! https://github.com/ethereum/EIPs/issues/75

**Comment by axic** [comment]
The attributes I would be interested in personally:
- don't require email addresses, but require a username (which can be an email address)
- require a passphrase, which could be offered from a dictionary or generator (such as @alexvandesande's above)
- support for ICAP direct
- have key derivation, which is not too heavy on a browser, is small in terms of code size, but still provides adequate security

**Comment by alexvandesande** [comment]
We have a standard library that will convert hex addresses to ICAP addresses. I don't see the advantage of needing an address starting with 0

**Comment by axic** [comment]
To have addresses supported to ICAP Direct, the private key needs to fit into 155 bits.

**Comment by alexvandesande** [comment]
I see. What's the advantage of doing so? A bank would still need to implement ethereum, it's not as if magically we can receive direct transfers just because our address fits into theirs..

**Comment by alexvandesande** [comment]
> don't require email addresses, but require a username (which can be an email address)

Of course, using email as a username is just a suggestion, it doesn't need to enforce the rule

**Comment by axic** [comment]
I haven't chosen a side yet which address format to prefer (checksummed, ICAP or something else), but as ICAP might get a bit of following, it probably makes sense to design the brain wallet in conformance.

**Comment by christianlundkvist** [comment]
Shall we close this one in favor of https://github.com/ethereum/EIPs/issues/75 ?
