### ISSUE TITLE
Unbounded total supply for EIP20

### ISSUE THREAD

**Issue by clesaege** [ethereum/EIPs#761]
On EIP 20, no condition is set on the total supply. However a lot of dapps consider that we should be able to multiply 2 balances.
I think we should require that total supply be less than 2^127 to allow dapps to assume there would not be an overflow while multiplying 2 balances.

**Comment by Shrugs** [comment]
Can you give some examples of when you'd want to multiply a balance by two? I'm not aware of any, personally.

**Comment by clesaege** [comment]
Simplest example:
To give a dividend.
We have n users, who have put x1, x2, ..., xn amount of tokens on a contract. The contract can keep track of its internal token balance B. The contract won G amount of tokens.
The dividend di of user i would be : 
di= (xi * G) / B

Note can we can change it to di= (xi / B) * G or di = (G / B) *xi, as (xi/B) would always be rounded down to 0 and (G/B) would also be rounded down to 0 if G<B (which is not a crazy assumption that the gains are lower than the total invested).
