### ISSUE TITLE
EIP20 wiki example could use improvements

### ISSUE THREAD

**Issue by drozdziak1** [ethereum/EIPs#762]
Hi!
**I'd like to help improve https://theethereum.wiki/w/index.php/ERC20_Token_Standard, but I couldn't find an option to register on your MediaWiki instance.**
First of all, I've found this article very helpful (thank you! :+1:) - but there is some places where the example EIP20 implementation is wasting the user's money and possibly setting a bad example, e.g.:
```solidity
function transferFrom(
    address _from,
    address _to,
    uint256 _amount
) returns (bool success) {
    if (balances[_from] >= _amount
        && allowed[_from][msg.sender] >= _amount
        && _amount > 0
        && balances[_to] + _amount > balances[_to]) {
        balances[_from] -= _amount;
        allowed[_from][msg.sender] -= _amount;
        balances[_to] += _amount;
        return true;
    } else {
        return false;
    }
}
```

## My concerns
* In the checks at the beginning of the function we could easily cut down on gas by swapping `cond1 && cond2 && cond3` to something like `(!cond1 || !cond2 || !cond3)` via de Morgan's law. 
* Checking if `balances[_to] + _amount > balances[_to]` is pretty much pointless given the `_amount > 0` condition above it. 
* I can see how a transaction of `_amount == 0` can be optimized, but it shouldn't (in my opinion) constitute an invalid transfer (like the `_amount > 0` condition implies) - merely a trivial one.

## My questions
* How can I register on the wiki? (so that I can progress from only complaining here :smile:)

**Comment by drozdziak1** [comment]
My bad, it seems like that Wiki runs separately from official Ethereum resources (therefore, **this issue can probably be closed**). Does anyone happen to know a contact to someone who could add me?

**Comment by asifmallik** [comment]
`balances[_to] + _amount > balances[_to]` checks for [integer overflow](https://ethereum.stackexchange.com/questions/7293/is-it-possible-to-overflow-uints) actually.

**Comment by nicksavers** [comment]
@drozdziak1 message **bokkypoobah** on https://daohub.slack.com, or **BokkyPooBah** on https://www.reddit.com.
