### ISSUE TITLE
EIP ( draft ) SelfDestruct Waiting List ( a Garbage Filter for Statically Referred Common Libraries )

### ISSUE THREAD

**Issue by ghasshee** [ethereum/EIPs#771]
## Preamble

    EIP: <to be assigned>
    Title: SelfDestruct waiting List ( a Garbage Filter for 'Statically Referred Common Libraries' )
    Author: ghasshee@gmail.com
    Type: Meta
    Status: Draft
    Created: 2017-11-17

## Simple Summary

To be a common web tool, Ethereum would have various kinds of safety nets which guarantee the data, especially that of library contracts, is safely kept. In this issue, I would like to propose one kind of safety net, which is `SelfDestruct Waiting List`. When `SELFDESTRUCT` is called, the contract will get held by the list in some term `t`.

## Abstract

We have 2 new Lists, `ListOfReferrers` and `SelfDestructWaitingList`.

The `ListOfReferrers` is a list of sets, each set is named with a contract address e.g. `A`.
the set `A` is a set of contract addresses which statically call contract `A` directly.
* Every time a contract is deployed, we add its static reference information to the list.
* If contract `A` executes `SELFDESTRUCT`,  then add `A` to the `SelfDestructWaitingList`.
Then for all member `x` of the `SelfDestructWaitingList`,
  - make a new list `AllReferrers(x)` which lists all direct and indirect referrers,
  - and if `AllReferrers(x)` ⊆ `SelfDestructWaitingList` then `SELFDESTRUCT` `x` and clean `x` completely from both lists else do nothing.
  - After the term `t` has passed, Remove `A` from `SelfDestructWaitingList`.

## Motivation

The problem is we do not have a proper `Garbage Filter`.
This is an attempt to formalize how to deal with what is going to be garbage.

## Specification

e.g. 1
~~~
let ListOfReferrers(A) = {}

if contract 'A' which statically refers only contract 'A' is deployed, then
ListOfReferrers(A) += {}  // Do not include itself to Referrers

So if SELFDESTRUCT 'A' is called,
AllRefers(A) = {} and 'A' self-destructs immediately,
and clean 'A' from both lists completely.
~~~

e.g. 2
~~~
let ListOfReferrers(A) = {}, ListOfReferrers(B) = {}, ListOfReferrers(C) = {}
if contract 'A' which statically refers 'B' is deployed, then ListOfReferrers(B) += A
if contract 'B' which statically refers 'C' is deployed, then ListOfReferrers(C) += B
if contract 'C' which statically refers 'A' is deployed, then ListOfReferrers(A) += C

now the whole List is like;
ListOfReferrers = {
    A : {C},
    B : {A},
    C : {B}
}

then call SELFDESTRUCTs.
let SelfDestructWaitingList = {}

if SELFDESTRUCT 'A' is called
then SelfDestructWaitingList += A and make AllRefers(A) = {B,C}.
Then 'for all x ∈ SelfDestructWaitingList, if AllReferrers(x) ⊆ SelfDestructWaitingList then SELFDESTRUCT x else do nothing' is executed.
For now nothing happens.

if SELFDESTRUCT 'B' is called
then SelfDestructWaitingList += B (so = {A,B})
and make AllReferes(A) = {B,C} and AllReferes(B) = {C,A}.
Then 'for all x ∈ SelfDestructWaitingList, if AllReferrers(x) ⊆ SelfDestructWaitingList then SELFDESTRUCT x else do nothing' is executed.
For now nothing happens.

if SELFDESTRUCT 'C' is called
then SelfDestructWaitingList += C (so = {A,B,C})
and make AllReferes(A) = {B,C}, AllReferes(B) = {C,A}, and AllReferres(C) = {A,B}.
Then 'for all x ∈ SelfDestructWaitingList, if AllReferrers(x) ⊆ SelfDestructWaitingList then SELFDESTRUCT x else do nothing' is executed.
Now all A, B, C self-destruct.
And remove A,B,C from SelfDestructWaitingList.
And clean A,B,C from ListOfReferrers completely.
~~~

e.g. 3
~~~
if contract A dynamically refers from contract AA to contract AZ
then do nothing.

So if SELFDESTRUCT 'AA' then 'AA' self-destructs immediately and clean.
~~~

e.g. 3 shows that this is a limited safety net only for statically referred common library.

## Rationale

I think we all who will use library contracts on Turing completeness decentralized consensus machines in the future might have potential to have responsibility for the vulnerability which anyone could cause at libraries on such a new technology.

## Backwards Compatibility

I am not sure but this might need a hard fork because of creating new two database. I would like to keep them in another place, e.g. `~/.ethereum/gf/` ( `gf` denotes `garbage filter` ) at the first implementation of this issue.

## Test Cases

Just I thought that it could be suitable with ⊂ rather than with ⊆.

## Copyright
Perhaps or maybe, Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by flygoing** [comment]
You may want to clarify what you mean by "refer". It may be hard to define this as a contract can dynamically refer to any address and call any addresses code.

**Comment by ghasshee** [comment]
Thanks. It seems to be a first good point. 
And I think we can start from assume references are static and we can develop it.
Let me consider and keep advising it.

**Comment by ghasshee** [comment]
Thanks. It seems to be a first good point. 
And I think we can start from assume references are static and we can develop it.
Let me consider and keep advising it.

**Comment by ghasshee** [comment]
I mean "referring" as "(a contract) calling (another Contract)" 
Right now this could be limited to a static reference.
So the title might be modified to 
' a suicide filter for Common Library which is statically called by some contracts'

**Comment by ghasshee** [comment]
I added e.g. 3 ( a common library is dynamically referred )

**Comment by mikhail-vladimirov** [comment]
Suicide, or politically correct “self destruct”, is one of those features that should never be there, because it breaks fundamental principal of immutability of smart contract's code.  The code of deployed contract may not be changed in general (which might actually be very useful in many cases), but may be wiped out (which is not useful at all but is actually extremely dangerous).  It also breaks the rule that contract's code is executed every time ether is being sent to the contract and contract may always reject ether transferred to it by reverting the transaction.
Just avoiding using self destruct and printing at compile time bold warning about self destruct usage would be much simpler and much better protection from accidentally killed contracts.

**Comment by ghasshee** [comment]
I think it might be a good point since I do not know right now how to motivate that full nodes should keep the DB small in the term of blockchain. And I also think that this could be a restarting point of discussing about Garbage Collection. ( I remember someone has mentioned 'why not have GC?' before, maybe about 2 years ago. )

**Comment by gcolvin** [comment]
I have not read the detailed spec yet, just trying to get the concept, which is that if a contract SUICIDEs the suicide does not have any effect until there are no static references to the contract?
If so, does your algorithm handle circular references?  And what about static references made after the contract has committed suicide?

**Comment by ghasshee** [comment]
Maybe I consider the circulation problem with `e.g.2`.

**Comment by gcolvin** [comment]
OK.  I've written GCs for computer memory, but this is different, as it's automatic collection of manually deleted objects.

**Comment by ghasshee** [comment]
Thanks. I just thought I should rename `preGC`.

**Comment by gcolvin** [comment]
I don't think actual garbage collection, as usually defined, is possible.

**Comment by ghasshee** [comment]
Did you mean that EOA also refers contracts?

**Comment by gcolvin** [comment]
EOA?

**Comment by gcolvin** [comment]
Right.  Garbage collection operates in a closed world, so you can know for sure that an object can no longer be referenced.  EOAs break that assumption.  The motivation here seems to be making it possible to write contracts that call other contracts with a guarantee that they won't SUICIDE out from under you.

**Comment by ghasshee** [comment]
Thanks. It could sound the power word for my business.

**Comment by gcolvin** [comment]
Of course other way to do that is to copy the contract you want to call.

**Comment by gcolvin** [comment]
Hard fork that says after some block number SUICIDE will be an invalid instruction.

**Comment by flygoing** [comment]
An anti-SUICIDE EIP does sound pretty noble, but "deprecating" SUICIDE all-together (invalidating transactions that use the SUICIDE opcode) sounds dangerous because then functions in contracts that currently work will make the transaction invalid. More realistic IMO is leaving it a valid opcode, leaving the functionality for it to forward ETH, but still have the contract be usable.

The follow-up question is whether we would want previously suicided contracts to be resurrected.

**Comment by gcolvin** [comment]
It would remain valid for older contracts.  Resurrecting previously suicided contracts is under consideration, but it's not clear it can be made safe.

**Comment by tomisme** [comment]
Would it be possible to reword this EIP to use SELFDESTRUCT, 'self destruct' etc. (https://github.com/ethereum/EIPs/blob/master/EIPS/eip-6.md)

**Comment by ghasshee** [comment]
Thanks. I will try it.

**Comment by ghasshee** [comment]
Just I thought that it could be suitable with ⊂ rather than with ⊆.
