### ISSUE TITLE
Create an Estimated Gas Modifier Standard

### ISSUE THREAD

**Issue by GriffGreen** [ethereum/EIPs#776]
## Preamble

    EIP: <to be assigned>
    Title: Create an Estimated Gas Modifier Standard
    Author: Griff Green
    Type:Standard Track
    Category: ERC
    Status: Draft
    Created: Nov. 20th 2017

## Simple Summary
This is a very simple request. I would love to be able to create a modifier in solidity smart contracts that interact with the estimateGas function to suggest a default gasLimit.

## Abstract
See Above.

## Motivation
When using functions that have extra functionality, sometime the gasLimit requirements change and it would be great for the smart contract designer to be able to suggest a gasLimit to improve the user experience.

## Specification

Looking for help here :-D

## Rationale

Will flesh out more.

## Backwards Compatibility
Should be 100% backwards compatible, it might be an upgrade to the estimateGas function

## Test Cases
Will flesh out more.

## Implementation
Will flesh out more.

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by wowa1983** [comment]
Mit was für Modul macht Mann das ?Befehl? Oder kann Mann denn auf bestimmte Zahl runter regeln ? Bitte um info
