### ISSUE TITLE
Am I doing this right

### ISSUE THREAD

**Issue by maristonimoura** [ethereum/EIPs#7839]
Am I doing this right? Need some guidance

_Originally posted by @Simpdaddyjosh in https://github.com/ethereum/EIPs/pull/658#pullrequestreview-1630129308_

**Comment by abcoathup** [comment]
If you want to create an EIP/ERC please see the following guide: https://medium.com/ethereum-magicians/comprehensive-guide-on-writing-and-submitting-an-eip-9474163771f0
