### ISSUE TITLE
Probably created by a bot. Closing until the author responds.

### ISSUE THREAD

**Issue by jrichy1** [ethereum/EIPs#7931]
Probably created by a bot. Closing until the author responds.

_Originally posted by @Pandapip1 in https://github.com/ethereum/EIPs/issues/5767#issuecomment-1272078812_

**Comment by jrichy1** [comment]
im jrich223 this is my old github ?

**Comment by jrichy1** [comment]
@Pandapip1 its under a outlook account by microsoft

**Comment by Pandapip1** [comment]
Whichever account opened that PR is now deleted. The PR was spammy (it touched too many files), had no description, and had literally hundreds of commits.

If you would like to reopen a similar PR, I highly encourage you to read EIP-1 first.
