### ISSUE TITLE
Feature: Add an 'Edit on GitHub' link to pages

### ISSUE THREAD

**Issue by sambacha** [ethereum/EIPs#7955]
### Proposed Change

Edit on GitHub page button can be:

- create a fork and edit the page
- create an issue for that page

Example: I visit the page <https://eips.ethereum.org/EIPS/eip-6466> and see that it does not include in its 'Security Considerations' an audit done by Dedaub (https://docs.google.com/document/d/1p-1VvOGwI5GHkwaGMzJYDL7Affofm6rVLa6cvnmoqGI/edit) - This takes me a few steps as I have to go to GitHub repo manually, making me less likely to even bother.

**Comment by sambacha** [comment]
Another example, I am reading the EIP page for https://eips.ethereum.org/EIPS/eip-6493 and check the required EIP https://eips.ethereum.org/EIPS/eip-2718 and notice that the required EIP-2718 makes no list of Transaction Types like EIP-6493 - should I ask the author @MicahZoltu to update or what? This sort of EIP is esp. important as what is considered 'valid' (meaning recognized by the community, etc). I do not believe there is a requirement on EIP Authors to go back to the required EIP to update its list or how it is handled in the first place absent explicit directive from the EIP itself (maybe @SamWilsn can pls explain).

**Comment by SamWilsn** [comment]
Continuing on from @MicahZoltu's comment, [EIP-5069](https://eips.ethereum.org/EIPS/eip-5069#what-we-dont) tries to clear up some of our reasoning for what we do and do not allow.

There is actually an edit-like button on EIPs:

![image](https://github.com/ethereum/EIPs/assets/57262657/e8791e8f-8d25-4eb9-9a45-4a625ba9896e)

(the little `< >` symbol)

It's just not very prominent.
