### ISSUE TITLE
is Ethereum sharding on roadmap yet 

### ISSUE THREAD

**Issue by loveyandex** [ethereum/EIPs#7974]
### Proposed Change

eth docs say:

Sharding was on the Ethereum roadmap for a long time, and was once intended to be shipped before The Merge to proof-of-stake. However, the rapid development of layer 2 rollups and the invention of Danksharding (adding blobs of rollup data to Ethereum blocks that can be very efficiently verified by validators) has led the Ethereum community to favour rollup-centric scaling instead of scaling by sharding. This will also help to keep Ethereum's consensus logic simpler.

**Comment by vlknurl** [comment]
chainco
