### ISSUE TITLE
List of EIPs for each hard fork.

### ISSUE THREAD

**Issue by jamesray1** [ethereum/EIPs#800]
May we please have EIPs for Byzantium and other hard forks in separate lists for the finalized ones? It doesn't need to be in the main readme, but a link to such lists in the readme would be good. I didn't get around to reading through all of those Byzantium EIPs.

**Comment by nicksavers** [comment]
That is already a pull request for that https://github.com/ethereum/EIPs/pull/676 but it depends on https://github.com/ethereum/EIPs/pull/779/ to be merged.
