### ISSUE TITLE
Identity based Standard Global Dictionary - Localisation / Categories / Descriptions

### ISSUE THREAD

**Issue by juanfranblanco** [ethereum/EIPs#81]
To have a global dictionary which can be used as an standard for wording of keywords, titles, descriptions, categories and localisation.

For example:

I have a contract which allows for categorisation for example an Augur Event (pick another business domain for your liking ie: Insurance, Zoo Animals, Tracker).

The market can be of many categories, ie Political, Election, Country, Regional, etc..

If we have a global standard dictionary:
Political could be 1, Election can be 20, US, 31, UK 32... etc.

Then a market could be assigned an array of multiple identifiers which can be easily identify, translated, make accessible and data mine.

**Comment by juanfranblanco** [comment]
The words do not need to be stored physically in Ethereum (just in case), this could be hosted in IPFS, github, etc

**Comment by dryajov** [comment]
I've been thinking about something similar, but more from the stand point social graphs. I think this requires 1) a standard for identity providers, 2) a standard for interlinking identities, 3) a standard for accessing data from external sources. Where the global dictionary/registry are interactions that an identity has, i.e. posts, likes, shares, buys, sells, etc... 

Whats the best way of putting together ERCs/EIPs around this use cases from the project stand point? Anyone else interested in discussing persuing these goals?

**Comment by MicahZoltu** [comment]
I think these are good ideas, but I don't think they are appropriate for an EIP.  If you think there is value in throwing up a global localization dictionary, my recommendation is to just do so and try to encourage others to use it.

**Comment by dryajov** [comment]
Thanks for the insight @MicahZoltu. 

My current thinking is that at the very least there should be a standard way of interacting with identities. For example, there might be many identity providers such as uport, but from my application/contract I shouldn't care what and how this identity is being sourced, but I should still be able to interact with it consistently. For example, a contract might want to request access to someone's profile picture and user name, different identity providers will probably store and handle that information in different ways, but I should be able to access that information and not a care about each providers specifics. I think, an EIP that defines how those interactions happen, how permissions to certain things are requested and granted, and how information gets passed back and forth is valuable, and would enable greater interoperability.

**Comment by MicahZoltu** [comment]
I don't get the impression that this EIP is for a standard mechanism for address => personal details mapping.  I'm _less_ opposed to that as an EIP, though I do think that EIPs lately have been inundated with contract standards proposals so I'm hesitant to get on board with any of them.  In this case, a localization mapping is (IMO) too far out of scope at this stage in the lifecycle of Ethereum.

**Comment by dryajov** [comment]
@MicahZoltu I get your sentiment regarding EIPs, but I think thats more a question of weather EIPs are suitable for _all_ proposals or a different mechanism is in order for application level things such as this. I'm new to this community, so I'm not sure if there is already such a mechanism/avenue. 

I think it is premature to try to standardize on this, but it would be good to have a place were we can brainstorm it and see were it leads, I'll open a new issue and see what other people's thoughts are. Would you say this would be a good way of introducing it to the community for discussion or are there better avenues?

**Comment by MicahZoltu** [comment]
That is a good question that I don't know the answer to.  I suspect that you aren't alone in wanting a place where the community can discuss best practices, and at the moment this GitHub tracker has the most highly-technical eyeballs on it.  I think something like a forum (e.g., Reddit) would be better for general discussions like this but I fear that something like `/r/Ethereum` would see all interesting discussion trolled by non-technical people or quickly buried.

Perhaps that is why all of these best-practice EIPs are cropping, up... people are _looking_ for a place to talk about their ideas and don't have any other outlet that has the right subscriber base.  Anyone interested in starting up/moderating a community for this type of discussion (highly technical, best practices, shared standards, etc.)?

**Comment by juanfranblanco** [comment]
Just to clarify the OP (a year old) was aiming to have data dictionary which can be localized. Nothing to do with Identities, I think the title when changed (whilst good) might have been a cause for confusion.

I see the point on "you start" and see if it catches on. But smart contracts are not easy to change, so if an initiative is started here, everyone can be aware of it and develop towards it. Also, all the tooling around can be built to support that in a "generic" way.

**Comment by dryajov** [comment]
Perhaps an r/ethcontracts is in order, if there is not one already.
