### ISSUE TITLE
ERC: Functions as first class citizens

### ISSUE THREAD

**Issue by rumkin** [ethereum/EIPs#829]
```
EIP: 829
Title: Functions are first class citizens
Status: Active
Type: ERC
Author: Rumkin <dev@rumk.in>
Created: 2018-01-13
Updated: 2019-11-15
```

First class citizen function is designed to bind `msg.caller` (or `this` for contracts) to some function.

It helps to interact with several contracts in a single transaction. This will extremely simplify contract creation and interaction.

## Example

User wants to deposit tokens in some DeFi service. Doing this user should send two transactions: first with token transfer approval and second with Defi service deposit.

```solidity
contract IToken {
  function approve(address from, address to, uint amount) public;
}

contract IDefi {
  function deposit(address from, uint amount) public;
}

function deposit(uint amount, address token, address defi) {
    require(IToken(token).approve(msg.sender, defi, amount));
    require(IDefi(defi).deposit(msg.sender, amount));

    // Do something on success
    notify();
}

// Other demonstration logic

contract ILogger {
  function verify(string memory notification) public;
}

// Dummy example function
function notify() {
    ILogger(address(0x1)).emit("Transfer completed");
}
```

**Comment by tawaren** [comment]
This is already done in some multisig contracts without the need of lambdas.
Simply put the target address and the byte array containing the function identifier (4 Bytes) and the parameters into the queue and when you need to execute it send the bytes to the address

**Comment by rumkin** [comment]
Yes, but you cannot to receive a result of such call.

**Comment by tawaren** [comment]
You can, just not with Solidity, but the EVM supports it if you know how much bytes you except in return and in which format to interpret them. However, I don't know if you can access the result by using inline assembly or not

**Comment by ligi** [comment]
> Yes, but you cannot to receive a result of such call.

this is possible: https://github.com/gnosis/gnosis-safe-contracts/blob/master/contracts/Proxy.sol#L19  @rmeissner also mentioned today that there might be a new way that does not need assembly

**Comment by rmeissner** [comment]
it seems that wont be the case for quite some time :(

**Comment by rumkin** [comment]
@ligi Thanks for your comment.

It looks I should to spend some time to look closer at EVM to produce explicit solution.
