### ISSUE TITLE
A clearer naming convention for events

### ISSUE THREAD

**Issue by devzl** [ethereum/EIPs#839]
The only convention that differentiates triggering an event from calling a function now, is the capital letter at the beginning of an event.

I think it will be a better thing, to make the code of a Solidity snippet more clear, and make a developer's intentions explicit, is to prefer another naming convention for events such as:

* Putting an "E_" at the beginning. Example: E_Transfer
* Ending the name with "Event". Example: TransferEvent

What do you think of this proposition?

**Comment by flygoing** [comment]
I think this would fit better as an issue in the Solidity repo regarding the [Solidity Style Guide](https://github.com/ethereum/solidity/blob/develop/docs/style-guide.rst). Events are specific to Solidity (the actual language in the yellow paper is *logs*) and naming conventions for languages that compile to EVM bytecode fit under preferred styling and not so much as an EIP. I believe the accepted convention that events begin with a capital letter avoids function confusion, but there may still be confusion with similarly capitalized constructors, so reposting this in the Solidity repo for discussion may be useful.

**Comment by devzl** [comment]
I reposted it in the Solidity repo, you are right, it will fit better over there.
