### ISSUE TITLE
ERC: Search interface standard

### ISSUE THREAD

**Issue by vst42** [ethereum/EIPs#857]
## Preamble

    EIP: <to be assigned>
    Title: Search interface standard
    Author: Vincent Stark <vince@xiveti.com>
    Type: Standard Track
    Category: ERC
    Status: Draft
    Created: 2018-01-28

## Simple Summary
Define a search interface standard to be used by Ethereum search engines. This would provide a way to search for data inside smart contracts' history.

Each smart contract that supports this ERC defines `search()` function:
```solidity
function search(address _addr, string _query) external view returns (result)
```

It takes either one of `_addr` or `_query`, or both. It returns `result` formatted in Markdown. Markdown is chosen due to the unknown structure of `result`: it can be a list, an image, a list of images, a text blob, or anything else.

The details of `search()` function implementation will be different, based on specific smart contract functionality.

## Use Cases
You would ask a big **"WHY?"** Why do we need this standard?

DApps and smart contracts are hard to discover and find. It's like Internet in 1990s. We have catalogs, directories, some references here and there, and then bookmarks for our favourite apps.

What is needed a universal search engine that would:
* Discover DApps (outside of scope of this ERC) - like crawling the Web
* Search for data inside DApps - like querying a search database for data from Web pages

Use cases:
* *Find all the DApps that I ever transacted with.*
* Find blockchains where my nickname or email has been ever mentioned.
* Find transactions with a specific note in my company's ledger.
* Find messages containing a specific string in Ethereum-based blog.
* ...even find CryptoKitties with certain words in their name.

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by fulldecent** [comment]
I don't see any use case. Always start with the use cases.

**Comment by vince-stark** [comment]
@fulldecent I've updated the issue with some more examples. I think there is value there. This `search()` function is a very important piece of the upcoming Ethereum infrastructure, providing a unified interface to search data within any smart contract.

**Comment by fulldecent** [comment]
These are all supposed use cases. Presently, Crypto Kitties has not identified a need for searching historical kitty names, Crypto Kitties users have not expressed a similar need, people do not use Ethereum for blogs, newspapers have not talked about Ethereum being used for blogs. Usually the actual use cases come first, then competing implementations happen, and then when everybody has made their mistakes, then a standard emerges.

# Philosophy aside, now for technical discussion

* This would require a list of all contracts to search. Contracts to hyperlink to others so you would need to search the web to find them.
* Implementing search on even one contract would require an unfathomable amount of gas.
* Implementing search on even one contract would require recording history forever (e.g. immutable data structures everywhere) even EVM does not have this much storage.
* Implementing search on even one contract would require a significant number of lookup tables and it would only ever work on full word queries. 

# Alternate solution

A website makes a list of many known contracts and allows you to search them. It uses contract-specific code to search each contract using the full history of that contract (and all logs).

After the alternate exists in the wild, that might be the time to start talking about a search standard.

**Comment by MrTibbles** [comment]
[Etherscan](https://etherscan.io/) springs to mind....

**Comment by fulldecent** [comment]
This initiative looks dead. Can this issue be closed?

**Comment by vst42** [comment]
@fulldecent I agree.
