### ISSUE TITLE
EIP712, motivates switching chain for signing 

### ISSUE THREAD

**Issue by Aniket965** [ethereum/EIPs#8610]
### What happened?

first of all sorry i know its not a bug, but i am not able to create post on ethereum magician portal so made it here ,feel free to close it. 

EIP712, introduced `eth_signTypedData ` which takes on typed data, this method is used by wallets and they show nice ui where they show this typedData to user, this make easier for user to undestand what they are signing. 
problem is when they have to sign it they have to switch to that chain although i dont see a very clear point why they have to do it eip712 takes domain seperater which have chainId, which makes it a chain specific signature which is good but it only takes chainId which should not require connecting to that chain.

it is possible to sign eip712 message without switching chain but rn do which means finding message hash of this signedTypeData and aksing user to sign it, the wallet doesnt show typed data ui for it. i think EIP712 motivates wallets to use   `eth_signTypedData ` so they implements it that way. it will be good if this behaviour can be changed

**Comment by KARINACAREPOTO** [comment]
> ### Solicitud de extracción
> _Ninguna respuesta_
> 
> ### ¿Qué pasó?
> En primer lugar, lo siento, sé que no es un error, pero no puedo crear una publicación en el portal de magos de Ethereum, así que la hice aquí, no dudes en cerrarla.
> 
> EIP712, introducido, `eth_signTypedData `que acepta datos escritos, este método lo utilizan las billeteras y muestran una interfaz de usuario agradable donde muestran estos datos escritos al usuario, esto hace que sea más fácil para el usuario entender lo que está firmando. El problema es que cuando tienen que firmarlo, tienen que cambiar a esa cadena, aunque no veo un punto muy claro por qué tienen que hacerlo. eip712 toma un separador de dominio que tiene chainId, lo que la convierte en una firma específica de la cadena, lo cual es bueno, pero solo toma chainId que no debería requerir la conexión a esa cadena.
> 
> Es posible firmar el mensaje eip712 sin cambiar la cadena, pero puedo hacerlo, lo que significa encontrar el hash del mensaje de este TypeData firmado y pedirle al usuario que lo firme, la billetera no muestra la interfaz de usuario de los datos escritos. Creo que EIP712 motiva a las billeteras a usarlo, `eth_signTypedData `por lo que lo implementan de esa manera. Sería bueno si este comportamiento se pudiera cambiar.
> 
> ### Salida de registro relevante
> _Ninguna respuesta_

Confirma

**Comment by xinbenlv** [comment]
@Aniket965 this is a technical comment on EIP-712, can you post it on Ethereum Magician? If you have difficulty posting it on Ethereum Magician please let us know.  (I'd also suggest you clarify "this behaviour can be changed" what is required here)

**Comment by bumblefudge** [comment]
hey @Aniket965 , yeah this will be closed as off-topic.  eth-magicians is powered by Discourse, which by default doesn't let brand-new users post new threads. Check your inbox for instructions, all new users get a message like this explaining the rules:

![image](https://github.com/ethereum/EIPs/assets/37127325/7738bffe-8db7-4c82-bf58-cc3cb7e17c77)

Your question sounds like it might actually be a question for metamask or viem, tho, I'm not sure EIP712 has any opinion about network connections (which should be on a lower layer?)

**Comment by jxom** [comment]
> Your question sounds like it might actually be a question for metamask or viem, tho

Definitely a question for the Wallet.

**Comment by bumblefudge** [comment]
@jxom sorry to trigger your google alert here, i was just throwing out ideas at random not really understanding the question 🙈

**Comment by Dropkick13** [comment]
Ok

**Comment by Dropkick13** [comment]
****

**Comment by Aniket965** [comment]
thank you, make sense
