### ISSUE TITLE
Multichain EIP

### ISSUE THREAD

**Issue by APYieldFarmer** [ethereum/EIPs#8874]
Hello there,

I would like to address some improvement proposals as followed: 

Multichain Ethereum instead of bridged Ethereum has many advantages layer 2 scalability and transactions cost with layer 1 security. Instead of multiple ethereum tokens on multiple chains you have one ethereum token without the need for liquidity on multiple chains or multiple bridge sides if the liquidity resides on layer 1 and only the transaction occurs on layer 2 this solves the blockchain trilemma scalable, secure and decentralized. With this approach only bridges are more or less deprecated but still necessary between different ecosystems this could be addressed with dedicated liquidity pools where Multichain transactions occur on different chains but the liquidity resides on the origin chain provided by the protocol itself. 

Multichain liquidity pools are better than bridged assets because the assets reside on the origin chain wich also solves the blended token and cTokens or reminting a token this is not necessary anymore with chainlinks proof of reserve for example this solves multiple issues and you are able to choose between multiple solutions on transaction & protocol level for the Multichain approach. 

There are multiple problems with liquidity pools as an liquidity provider you have to split your investments this results in asset pairs, impermanent loss, liquidity slippage opportunities and slippage has also potential for piggy boxes enabled through ghost bugs. The solution is to aggregate liquidity pools on layer 1 due to this solution approach exchanging two assets from single sided liquidity pools instead of swapping asset pairs. 

Multichain bridged liquidity could be combined with AMM liquidity with the previously mentioned approach considering the multichain ethereum solution and dedicated multichain liquidity pools with the protocols and chains as an liquidity provider makes it easier and bridges are more or less deprecated. Combining the two solutions for multichain liquidity pools and multichain Ethereum transactions with layer 1 security solves both issues. 

The approach to aggregate and provide multiple single sided liquidity pools is also a solution for low liquidity decentralized exchanges they could reuse the liquidity from other DEXs using code snippets and this is not an advantage for centralized exchanges anymore or disadvantage for decentralized exchanges. 

Kind regards
J.W.

**Comment by poojaranjan** [comment]
@APYieldFarmer 
Appreciate sharing your thoughts. I'd recommend creating a discussion thread at [Fellowship of Ethereum Magicians](https://ethereum-magicians.org/) and you may also make a Pull Request in [EIP GitHub](https://github.com/ethereum/EIPs/pull) or [ERC GitHub](https://github.com/ethereum/ERCs/pull) depending on the `Category` of the proposed standard. Feel Free to reach out at [EthCatHerders-EIP Editors Discord](https://dsc.gg/ech ) for any further support. 

This discussion should be moved to FEM page and the issue can be closed.
