### ISSUE TITLE
 Request for Assistance in Recovering Mistakenly Sent USDT

### ISSUE THREAD

**Issue by Danju777** [ethereum/EIPs#8885]
### Pull Request

https://tronscan.org/#/transaction/bc284a16a7c75c508683d40767ca924594bd2a0fa3aadf16e5dcb9f28babe3f7

### What happened?

Unfortunately, by mistake, I copied and used the token ID (TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t) instead of the intended wallet address (TKVMacPgTRiftd6v8hvEBG67EFnd6nuLPA), causing my USDT to be sent to an incorrect smart contract or address.

Here are the transaction details:

Amount Sent: 4435 USDT
My Wallet Address: TNPDHsbNaimj6obo3NuJSYG7hg5NhpAoer
Date of Transaction: 13.09.2024
Token ID Used in Error: TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t
Correct Wallet Address: TKVMacPgTRiftd6v8hvEBG67EFnd6nuLPA
I kindly request your assistance in recovering these funds or guiding me on the next steps I should take to retrieve them. I would greatly appreciate your help in resolving this issue.

Please let me know if you require any additional information to investigate the transaction.

Thank you in advance for your support and attention to this matter.

**Comment by poojaranjan** [comment]
This Issue section is to report "Bugs" related to EIP GitHub & Bots. Unfortunately, this isn't the correct forum for help and we may be unable to help you recover. Please reach out to the exchange/wallet provider.

**Comment by Danju777** [comment]
Can you please forward my email to correct department?

Thank you, Faleminderit

**Comment by abcoathup** [comment]
@Danju777 unfortunately your funds are likely stuck forever.  
Be aware that any DMs offering to assist with recovery are likely scams.

The only people who may be able to help you with USDT on Tron is Tether, though this is unlikely unless they have this functionality in the contract and offer it as a service.

This issue can be closed as it is not related to Ethereum improvement proposals.
