### ISSUE TITLE
ERC 892: Permission Standard

### ISSUE THREAD

**Issue by clesaege** [ethereum/EIPs#892]
EIP: 892
    Title: Permission Standard
    Status: Draft
    Type: Informational
    Category: ERC
    Authors: Clément Lesaege <clement@kleros.io>, Dean Eigenmann <dean@tokenate.io>
    Created: 2018-02-21

Abstract
--------------

This standard specifies that the standard naming of a public function indicating that an element is permitted is `isPermitted`.

Motivation
--------------

Some contracts require calling others in order to know if an element is permitted. A contract can need to know if an address has the right to interact with it or if an item belongs to the list of permitted items (ex: curated list).
This standard is straightforward but required for interoperability.

Specification
--------------

### isPermitted

This function returns `true` if the element is permitted, `false` otherwise.
Specific types can be used instead of`bytes32` as long as they are not longer than 32 bytes.
``` is
function isPermitted(bytes32 _element) returns(bool permitted)
```

Rationale
--------------
- Contracts and interfaces sometimes need to know if some particular element is permitted or not.
- The standard allows the abstraction of the permission brick of a dapp. It allows parties to choose a contract with arbitrary complex rules to determine if an element is permitted or not.
- Allowing types others than bytes32 provides better typing, thus better readability, without breaking interoperability.

Implementations
--------------
- https://github.com/kleros/kleros-interaction/tree/master/contracts/standard/permission
- https://github.com/ensdomains/blacklist/blob/master/contracts/Blacklist.sol

**Comment by Bradymck** [comment]
If this is a bit out of context please excuse I'm still learning but out of curiosity, is this referencing a way to block certain contract functions based on external data from an oracle or user facing UI components or something?

**Comment by decanus** [comment]
@Bradymck This standard could be used to block certain functions yes, in ens it is currently implemented to tell us which ENS names we are permitted to resolve and which we aren't.

**Comment by Bradymck** [comment]
@decanus Ah, interesting. Seems like the path to programmatic compliance and self regulating systems.

**Comment by adamdossa** [comment]
Isn't the restriction to a single bytes32 value in `isPermitted` quite restrictive? It is possible to think of use-cases when e.g. a couple of addresses are needed to check whether an operation is permissable or not (e.g. when checking whether a token transfer is allowed, we may want a function of `address _from, address _to, uint256 _amount`)?

An alternative approach would be to have `isPermitted` take `bytes` instead perhaps.

**Comment by clesaege** [comment]
It is restrictive, but using ’bytes’ would significantly increase gas cost.
If something takes more, you can just use its hash instead, that's the case for ENS for example.

**Comment by clesaege** [comment]
@adamdossa 
That's a good point, but decoding bytes is not that simple. The standard is about an element, so basically a list of what is allowed or what is not. For this use case, no need of bytes.
@decanus What do you think?

**Comment by adamdossa** [comment]
I think perhaps this is the bit which I am not getting - what exactly is the definition of an element? The use-case I had in mind was:
Contract A wants to know whether a particular operation `op` on Contract B is valid. Instead of calling `op` and hoping it doesn't throw, it can call `isPermissioned` with relevant args first, which returns a `bool` to determine whether the subsequent call to `op` will work or not.

For this use-case, obviously a fairly flexible `isPermissioned` is needed (whose logic would depend on the details of `op`). If you have a simpler use-case could you give a bit more detail on it?

**Comment by adamdossa** [comment]
A general approach would be to have `bytes` represent the call which we wish to check is valid or not, and then `isPermissioned` can deconstruct it in a fairly standard way (e.g. first 4 bytes are function sig, remainder are args). I agree this is potentially complex though, and possibly not worth generalising.

**Comment by decanus** [comment]
@clesaege I feel in this situation I would need to agree with @adamdossa. We are not dynamic enough with ```bytes32```

**Comment by clesaege** [comment]
I was not thinking about an operation but stuff like addresses, elements in a list. For the future bytes would be way better, but for now without decoder, it's not practical from a gas point of view.
A solution would be to modify the standard such that every type can be used (bytes32, bytes, address).
@decanus @adamdossa What do you think
