### ISSUE TITLE
EIP 909: New opcode STORREVERT (Draft)

### ISSUE THREAD

**Issue by SilentCicero** [ethereum/EIPs#909]
## Preamble
```
EIP: 909
Title: New opcode STORREVERT - Revert contract state back to specific block
Author: Nick Dodson <thenickdodson@gmail.com>
Category: EVM
Created: 2018-02-28
Updated: 2018-02-28
```

## Abstract
The following EIP describes an opcode which would revert a contracts memory storage and layout (state) back to a specific block.

## Motivation
Many contract systems are growing in complexity and will want a simple way to revert and reset contractual changes or upgrades. Having a simple opcode which can do this would greatly increase the capability of the Ethereum virtual machine. This would also allow Ethereum contracts to be extremely amorphic in nature (if used in tandem with delegatecall like functionality).

## Specification
Introduce a new `STORREVERT` (memory revert) flag to the virtual machine. This opcode has no default values. It has one required parameter which is the block number to revert contract memory to.

Opcode: `0xfc`

The single parameter, block number, is invalid if it is set past the contract deployment block or ahead of the current block number.

## Example
1) A delegate proxy is deployed with memory storage slot `master` (which defines the delegatecall target) at block A
2) The delegate proxy P defines it's master variable to contract Y at block B
3) Now the delegate proxy P is effectively contract Y
--- The proxy owner now wants to change P's `master` to contract Z
3) The delegate proxy P calls `STORREVERT A` and then assigns the `master` to contract address of Z
4) The delegate proxy P is now effectively contract Z

## Rational
This allows contracts to easily reset and revert memory / storage slots back to a specific block in time with relative ease.

## Implementation
When processing this opcode, the client would simply ignore all state changes between the STORREVERT block number and the current transaction block number in which the opcode was processed.

## Alternatives
If this is far to complex to implement in the client, an alternative would be to have a STORREVERT, whereby the memory of a contract is simply reset to the memory layout / state when it was deployed (which would take no parameters). 

It seems after learning more about VM processing, the above proposal would be very computationally heavy, as VM's are not required to hold historical state transitions. Another alternative would be a complete wipe of all contract state and storage layout. This would definitely put it in the class of SUICIDE and other similar calls to it. I do believe for upgrade purposes it would be useful.

## Test Cases
To be written.

**Comment by GNSPS** [comment]
I see the reasons to have both the options of opcodes described above (MEMBLOCK and MEMREVERT) but favour an initial implementation of MEMREVERT.

Also I’d recommend changing all the verbatim to use the term `storage` instead of `memory` since the latter gets reset per each transaction and there’s no _block_ reference to revert it to.

Awesome proposal, as always, @SilentCicero! 👏🙌

**Comment by izqui** [comment]
> gets reset per each transaction and there’s no block reference to revert it to 

Actually per execution context :) I think there is a lot of value in having volatile memory that can be shared between contexts but dies at the end of the transaction execution. I think @chriseth made some comments about this in some EIP but I cannot find it right now!

**Comment by axic** [comment]
I think the naming is misleading, you are talking about replacing storage with an earlier versions. Memory is never persisted.

The current proposal seem to put all the work on the clients and it doesn't seem to be compatible too much with light clients.

How about having explicit checkpointing and loading from those checkpoints? It could be done via a contract similarly how to the blockhash refactoring is proposed.

**Comment by GNSPS** [comment]
+1 for explicit checkpointing.

**Comment by SilentCicero** [comment]
@izqui I agree this would be a huge load to implement client side, but I think this would be extremely useful on the VM side.
@GNSPS thanks! On the naming point:

Currently I chose this name as I sometimes conflate memory and state, when I'm sure in client/evm/metaphysical terms it is called/identified as something else.

I'd be open to change the name to `STATEREVERT` or `STATREVERT`

@axic the name can be adjusted, as I mention above.

Re: lightclients, I agree, this would challenges most lightclient design right now. If we used checkpointing, I think that is an interesting middleground. But I would still like to clean out existing storage slots / pointers before reverting to a checkpoint.

**Comment by Arachnid** [comment]
As you note in the proposal, this isn't really practical: it would require all nodes to be archive nodes.

Checkpoints would be possible, but a major engineering effort; personally I'm skeptical about the value of doing that when you can implement equivalent functionality at the contract later if desired.

**Comment by GNSPS** [comment]
How do you feel about the "erasing all storage" part, tough, @Arachnid ?

You can't achieve that in the EVM without **a lot** of overhead, currently.

**Comment by ivica7** [comment]
Not sure, but wouldn't this be too powerful? Allowing developers to "hack" too much. Could be a smart contract trust killer from the user's perspective if it's potentially possible to revert the storage (thinking about a token contract).

**Comment by SilentCicero** [comment]
I also think explicit check pointing would be worth it here. Even if the checkpoint is simple "bring me back to the initial deployment state" to start.

A clear out of all storage layout and pointers would be another option, to enable the proxy example I stated above, but with no revert to block functionality.

As for things being too powerful, contracts can already be whipped, and manipulated to no end with delegate call. If your worried about consumer trust, those calls are equally dangerous in their own way.

Reverting to checkpoint could be very useful for efficient storage handling situations. However, it would involve a major engineering effort on the part of the client. And so some middle ground to achieve the wiping of contract storage completely could be a nice compromise.

**Comment by flygoing** [comment]
> Reverting to checkpoint could be very useful for efficient storage handling situations. However, it would involve a major engineering effort on the part of the client. And so some middle ground to achieve the wiping of contract storage completely could be a nice compromise.

I'm not sure explicit check pointing is the most useful method to achieve full state reversion. More useful in my opinion would be a SSTORE-like op that takes a memory start/length and a storage location that stores a range in memory to a range in storage. You can then have your initial state as push/mstore opcodes in the contract code itself. I'm not sure how efficient this would be for large ranges (maybe price it depending on range size?). There's also the issue of what to do about hash based indices in the storage.

**Comment by flygoing** [comment]
> These make data sparse and scattered all throughout the addressable space making a variable length SSTORE be as ineffective as the current 32-bytes-sized one making you have to define iterable support structures like arrays to erase all the storage sections already written (which is unfeasible and the whole point we're trying to avoid 😄).

It's also unfeasible for clients to store entire snapshots of the storage as checkpoints 😉 Maybe this could be avoided by having a storage clear opcode as well, no need to reset all the values at random indices. Either way, I'm not sure of a proper use for checkpointing (or emulating checkpoints). Do you have a use case for it?

**Comment by SilentCicero** [comment]
I think I'm leaning on more of a wipe everything opcode, as that would solve the initial example use case / problem of "resetting" a contract and turning it into something else. Which is very relevant for contract proxy designs and how we construct upgradable contractual systems.

The hope of this discussion was to settle on what is reasonable and achievable at the client level to solve some of the use cases listed above.

Also, I am renaming this to STORREVERT as that name seems most relevant now, over the original and somewhat misleading MEMREVERT.

**Comment by ivica7** [comment]
@SilentCicero did you take a look on #905 ? It would allow you to make a snapshot of the state at any time and revert it later. Moreover, it would allow to clone the storage for upgrade purposes.

**Comment by SilentCicero** [comment]
My only issue with this is two fold, one, sometimes you don't know when the right snapshot time is and secondly, if I could just wipe out all storage in a contract, like a full refresh, it would serve the similar purpose for upgrading. I don't believe we actually need a revert per say to fork daos or contracts. I think Aragon would agree as well. You can just take state from the last set of contracts and implement new state and logic in the new dao. The MiniMe token is a good example.

**Comment by ivica7** [comment]
Not sure if I understand exactly what you're trying to achieve... if you wish to wipe out all data with the machanism from #905 , you could ``SCLONE`` storage from a contract like ``contract Empty {}``. If you wish to revert to the state after the initialisation of the contract, you could make a snapshot with ``SCLONE`` directly after the initialisation and reset it later with ``SCLONE`` again to this snapshot. Sure you're not flexible like if you could select arbitrary blocks for the revert, but that's the tradeoff for simplifying the implementation.

**Comment by rmi7** [comment]
This would "in a way" break the _promise_ of the blockchain only moving **forward**, not by undoing entire blocks, but by undoing state changes included in the last `X` blocks of a given smart contract `Y`? Still feels like going back in time, no no 💣 

For example: I wouldn't trust ERC20 tokens that have this feature in some `onlyOwner` accessible methods..they could just revert the ERC20 token balances, while still retaining the ETH balance fo the contract.

**Comment by GNSPS** [comment]
I think you’re kind of missing the point.
The capability to change storage contents  from a deployed smart contract have always been there.
If what you’re worried is that some contract developer does revert storage in the first place then you can already do that today.

Lack of _trustlessness_ in the development phase shouldn’t be an argument against this proposal.

**Comment by flygoing** [comment]
@ivica7 SCLONE (EIP905) might be pointless and is at least dangerous. Since SCLEAR refunds gas, a contract could clone a contracts storage and just delete state from itself to save the calling tx gas. So, to bypass this issue, SCLONE would have to be at least as expensive as 20,000 * (the number of non-zero storage locations in source contract), making the opcode pointless anyway since it isn't really saving gas. 

STORREVERT would only work if it was snapshot based (because non-snapshot based would mean all nodes are archive nodes) **and** would have the same issue (reverting to checkpoint with extra non-zero storage slots and then deleting storage slots to save gas) unless you charged for the checkpoint and revert based on the same 20,000 * (the number of non-zero storage locations in source snapshot), at which point it is also pointless because it is, again, not saving anyone gas.

The only way SCLONE or STORREVERT would work to save gas is if we switched from just SSET/SRESET/SCLEAR charging of state to also include rent collection based storage.

**Comment by ivica7** [comment]
> The only way SCLONE or STORREVERT would work to save gas is if we switched from just SSET/SRESET/SCLEAR charging of state to also include rent collection based storage.
That's an interesting point. Have there been proposals for this (rent collection based storage)?

**Comment by flygoing** [comment]
There have been a couple EIPs, but I don't think there have been any that have gotten real transaction. It adds a lot of complexity to contract/dapp developers since it means contracts would have to keep Ether in their balance that slowly gets used or they would lose their state, which means users either have to fund this themselves or trust that the developers keep it funded.

**Comment by fulldecent** [comment]
This EIP lacks a very strong and specific use case. That makes it impossible to evaluate the merits of the things we are discussing.

Simply on the basis that this makes my job much harder when auditing a contract, I think the potential gain is not worth it.

**Comment by SilentCicero** [comment]
The primary use-case is for upgradable contract systems, namely, proxy contracts. Aragon, Colony, Harbour and others working on upgradable governance systems will and already do desire a mechanism to either wipe contracts clear of storage or bring them back to a specific state along the upgrade process of a contract. This EIP is the start of a discussion toward that aim of clean upgradable contracts. I believe that this kind of mechanism should exist, at least in the storage clearing form.
