### ISSUE TITLE
EIP-197, generator P2 is not a point on Y^2 = X^3 + 3  over F_p^2

### ISSUE THREAD

**Issue by tjade273** [ethereum/EIPs#914]
The second group in the pairing check is a twist of the first curve with equation `Y^2 = X^3 + 3/(i+9)`.

**Comment by cdetrio** [comment]
Is this related to https://github.com/ethereum/EIPs/pull/913?

**Comment by tjade273** [comment]
Yep, that is exactly the issue. Thanks
