### ISSUE TITLE
Pros and cons of making the Foundation more transparent (Discussion)

### ISSUE THREAD

**Issue by balazskonya** [ethereum/EIPs#921]
Following up [this](https://github.com/ethereum/research/issues/81) issue, which was a follow-up to [that](https://ethresear.ch/t/meta-innovation/1272) question.

**Comment by nicksavers** [comment]
I propose to stick to proposals in this repository.

**Comment by balazskonya** [comment]
> Process EIPs are like Standards Track EIPs but apply to areas other than the Ethereum protocol itself.

> Examples of appropriate public forums to gauge interest around your EIP include the Ethereum subreddit, the Issues section of this repository, and one of the Ethereum Gitter chat rooms. In particular, the Issues section of this repository is an excellent place to discuss your proposal with the community and start creating more formalized language around your EIP.

I guess this falls into the category of a discussion starter on a potential Meta (Process) EIP, but I'm happy to move it if you can suggest a more appropriate place.

**Comment by flygoing** [comment]
@balazskonya Perhaps a better venue would be the [Ethereum Magicians](https://ethereum-magicians.org/) site that was recently setup.

**Comment by Arachnid** [comment]
The foundation doesn't run the EIP process, and isn't governed by it; there's not much point writing an EIP about this.

**Comment by balazskonya** [comment]
@flygoing I'm aware of the FEM, but as I understand they're focusing on technical questions.
@Arachnid The Foundation indirectly supports the EIP process. IMO improving the operations of it would improve Ethereum too.

**Comment by Arachnid** [comment]
@balazskonya It does, but the EIP process is not the appropriate place to suggest changes to the foundation - EIPs are for changes to *Ethereum*, not to the *Ethereum Foundation*.

**Comment by balazskonya** [comment]
Yes, I know. The only reason I created the issue here is that I couldn't find a better place for it, as I wrote it to the linked ethresear.ch topic.
> I opened an issue in, for lack of a better place, the EIPs repo to start a discussion on it.

Where would you raise an issue like this?
