### ISSUE TITLE
Outdated proposals in the Ethereum wiki

### ISSUE THREAD

**Issue by jamesray1** [ethereum/EIPs#924]
https://github.com/ethereum/wiki/wiki/Outdated:-Poll-for-token-proposal-EIP-20
https://github.com/ethereum/wiki/wiki/Outdated:-Proposal:-Reversion-Notification
https://github.com/ethereum/wiki/wiki/Outdated:-Proposal:-Reversion-Notification

**Comment by nicksavers** [comment]
Shouldn't this be an issue on the other repository https://github.com/ethereum/wiki/ ?

**Comment by jamesray1** [comment]
I think I posted these here because they should probably be moved from the wiki to this EIPs repo, so that all EIPs are in the same place.

**Comment by axic** [comment]
The links seems to be dead. @jamesray1 please reopen if the data you link to can be found somewhere.
