### ISSUE TITLE
Signature idea for use with account abstraction, proof_of_public_key = keccak256(nextPublicKey)

### ISSUE THREAD

**Issue by resilience-me** [ethereum/EIPs#935]
Uses one-time keys and a proof of the next public-private key pair included in each transaction,

`proof_of_public_key = keccak256(nextPublicKey)`

I call the scheme Teikhos, from the Greek for "wall" or "fortification", as it hides the asymmetric cryptography behind a "wall", a one-way hash function.

**Comment by aunyks** [comment]
I'm not sure that I understand the goal of this proposal.

**Comment by resilience-me** [comment]
To increase cryptographic hardness.

**Comment by aunyks** [comment]
Still not following. Is this a standard proposal for contracts? What's the context?

**Comment by resilience-me** [comment]
A signature proposal for use with account abstraction (read up on it, a few posts here and there, probably some on GitHub, could use [Google](https://www.google.com/search?q=signature+abstraction+ethereum))

**Comment by aunyks** [comment]
Please follow the [EIP template](https://github.com/ethereum/EIPs/blob/984cf5de90bbf5fbe7e49be227b0c2f9567e661e/eip-X.md) so that I, and others, can better understand your proposal.

**Comment by resilience-me** [comment]
No, account abstraction makes it possible to use new signature types (feel free to falsify if wrong), and the proposal is for a new signature type, the reason to increase cryptographic hardness.

**Comment by 3esmit** [comment]
You can implement this as a smart contract, dont need to change EVM.

**Comment by 3esmit** [comment]
If anyone wants to use this "new signature type", the following contract would do it.
```solidity
pragma solidity ^0.4.17;
contract RollingKeySignature {
   bytes32 nextKeyHash;
   uint256 nonce;
   function RollingKeySignature(bytes32 firstKeyHash) public {
       nextKeyHash = firstKey;
   }
   
   function execute(bytes signature, address to, uint256 _value, bytes data, bytes32 newKeyHash) external {
      require(nextKey == keccak256(ecrecover(keccak256(address(this), nonce, to, _value, data, newKeyHash)));
      nonce++;
      nextKeyHash= newKeyHash;
      to.call.value(_value)(_data);
   }
}
```

Not sure if the hashing of key is requried, could be used regular rolling ethereum addresses, but using the hashing seems to "improve" security, however the truth is tht is just one more hashing in top of address private key bruteforce.

**Comment by resilience-me** [comment]
@3esmit account abstraction enables new signature types, already planned change to EVM
https://ethereum.stackexchange.com/questions/18977/what-is-the-ethereum-account-abstraction/19456

taking for granted that it is very difficult to brake either, would you say it is easier to break sha256 than secp256k1?

**Comment by resilience-me** [comment]
@3esmit implementation is trivial, of course.

again, would you say it is easier to break sha256 than secp256k1?
