### ISSUE TITLE
Proposal of standard contract API feature query

### ISSUE THREAD

**Issue by larspensjo** [ethereum/EIPs#94]
### Problem
- Defining an API that lasts for ever is difficult. There is a need to support changes.
- There should be no centralized dependency. Anyone should be able to propose new functionality for any API, or to define a completely new API.
- It should be possible to fulfill any subset of versions.
### Proposed solution

Define a generic base class that all standard contract APIs have to inherit. Override a query function that returns support status for features.
### Implementation proposal

Every feature is identified by a (globally scoped) feature number. To minimize the risk of accidentally using the same number, it should be randomly generated 144 bits.

```
contract VersionInformation {
    /// @param _feature A feature number
    /// @return True if the feature is supported
    function querySuppport(uint _feature) constant returns (bool supported);
}
```

A random 144 bit feature number can be created with web3 Javascript:

```
"0x"+(BigNumber.random(11)*1e11).toString(16).slice(-9) + (BigNumber.random(11)*1e11).toString(16).slice(-9)
```

**Comment by axic** [comment]
What is a feature and who decides about the allocation of feature ids?

To tackle the same issue, I'm putting the following in my contracts:
```
uint public constant version = 1; // change accordingly
```

**Comment by larspensjo** [comment]
Anyone can propose a feature. Of course, you can't force others to use it, but good proposals will be used if there is a need for it.

I am not sure how to best allocate a feature number. As I wrote in the proposal, a random 64 bit number could be used. This is maybe not a safe process, as you could claim that you got the number '1' as a random. Another way is to use a hash, but hash on what?

I am thinking a little like you allocate a new account address. You don't need a central control of what addresses are allocated.

**Comment by axic** [comment]
Because with addresses, a 160 bits hash gives a big enough space to reduce the risk of collisions (which is still there). With 64 bits that risk is much higher.

**Comment by larspensjo** [comment]
I changed the requirement to 144 bits (18 bytes). Notice that the number of bits can easily be extended if there would be a need.

I also added an example how to use Javascript BigNumber to generate a random number with enough bits.
