### ISSUE TITLE
Make jsonrpc api engine agnostic.

### ISSUE THREAD

**Issue by debris** [ethereum/EIPs#95]
cc @frozeman @obscuren 
### Goal

Make jsonrpc api engine agnostic.
### Issue.

Currently jsonrpc methods `eth_getBlockByHash` and `eth_getBlockByNumber` return block objects with field `nonce`. Oddly, the other pow specific param `mixHash` does not exist.

```
nonce: DATA, 8 Bytes - hash of the generated proof-of-work. null when its pending block.
```

PoA blocks does not have `nonce` property.
### Proposed solution

Replace `nonce` field with `seal_fields`. An array containing all engine specific fields.

```
"seal_fields": ["0x11bbe8db4e347b4e8c937c1c8370e4b5ed33adb3db69cbdb7a38e1e50b1b82fa", "0x0000000000000042"]
```

**Comment by frozeman** [comment]
Makes sense. Any opinion @vbuterin
