### ISSUE TITLE
Possible to add telemetry to mining rewards?

### ISSUE THREAD

**Issue by mjmeans** [ethereum/EIPs#970]
With the unknown nature of ASIC risk looming I'm wondering if there is a way to add telemetry to mining rewards so that secondary research of the collected telemetry could quantify specific ASIC behavior. I.e. nothing that directly combats ASIC, but something that can detect and locate ASIC farms and particulars of ASIC behavior. If this were possible, then a future targeted fork could directly combat ASIC behavior.

**Comment by Arachnid** [comment]
No. There's already an optional field in which the miner could announce where they're from, but there's absolutely no way to enforce that people report it accurately.

**Comment by mjmeans** [comment]
I was more thinking about telemetry of the machine, like memory performance in various parts of the algo, bus performance, etc, to create a "fingerprint" of the system. Then perhaps a common feature of ASIC machines hardware can be identified and later targeted.

**Comment by Arachnid** [comment]
No, you can't force a miner to record and report those accurately either.
