### ISSUE TITLE
ASIC Hardfork Suggestion and Discussion

### ISSUE THREAD

**Issue by rebelcrypto** [ethereum/EIPs#980]
I did not find any open issue related to ASIC Resistant So open one to discuss with all Ether Supporter.

Monero team was very active and did their part with hardfork to v7 within a days, No more Bitmain Asic

Monero creater ' did the thing with the thing ' Nice one lolz

https://cointelegraph.com/news/monero-hard-fork-appears-successful-as-devs-shun-bitmains-asic-miners

Where are we with Ether Hardfork for Asic Resistant, Other Coin Devs can help the team to make it quick I think.

**Comment by bernardpeh** [comment]
it was a hot topic few days ago.

https://github.com/ethereum/EIPs/issues/958

I believe they are taking this seriously.
