### ISSUE TITLE
Assign the EIP based on the PR number

### ISSUE THREAD

**Issue by jamesray1** [ethereum/EIPs#988]
At the moment when you create a PR, you make it compatible to merge and wait or request for an EIP number to be assigned. But for the discussions-to field in the header, if you create a GItter issue, you have to edit it to update the EIP title with the number and the link on the EIPs website. I suggest adding the EIP number based on the PR number. But I guess it's not too much extra effort to change the EIP title after merging, while the link on the Gitter topic would need to updated from the PR to the EIP webpage anyway.

**Comment by 5chdn** [comment]
This is already the case even though it's not formalized yet. However, in some cases the EIP number is taken from the issue number that discussed the topic before creating an actual proposal (e.g., #156, #649).

If you want to formalize that, we could just add it to EIP-1, however, I am not entirely sure if we want to stick to Github forever with this process. Just my thoughts.

**Comment by jamesray1** [comment]
Yeah, I was aware that sometimes the issue number was used instead, which is OK.

**Comment by 5chdn** [comment]
Discussions-to is used by http://eips.ethereum.org/ to readers that want to discuss a proposal. Could be a link to a forum or the GitHub issue or Reddit, or anything really that allows to maintain a persistent record of the discussion.

**Comment by jamesray1** [comment]
OK sure, yeah I understand that, the guidelines could be generalized.

**Comment by axic** [comment]
The text
> the EIP editor will assign the EIP a number (generally the issue or PR number related to the EIP)
has been in EIP-1 at least since Feb 2017.

What exactly needs to be changed/improved here?
