### ISSUE TITLE
EVM Dashboard (for objective comparison of clients)

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/EIPs#99]
(originally created in the wrong place by mistake at https://github.com/ethereum/evmjit/issues/48)

With regard to @chfast's Cross-team EVM Benchmark Suite proposal (https://github.com/ethereum/evmjit/issues/47), I think that is a project which we absolutely should be doing, but that is just one part of something broader which we should be addressing, which is to provide a neutral dashboard showing all aspects of particular EVM's protocol compliance, performance and any other valuable metrics or statistics which can be automated.

I think that the onus is on us as the Ethereum Foundation to maintain and host publicly visible automated dashboard instances of such metrics and tests for all EVM implementations.

See https://html5test.com, for example, or https://arewefastyet.com/, for browsers.

Some examples:
- http://github.com/ethereum/tests
  - We have these, and I believe they are being run, generally, by the various client teams, but the results for those aren't aggregated anywhere to the best of my knowledge)
- https://github.com/ethereum/rpc-tests
  - I believe that these were abandoned at some point, but we should definitely have such tests, whether the are these ones, or a new suite.  @tinybike tells me that there is a suite they have at Augur.
- EVM benchmarking (as per https://github.com/ethereum/evmjit/issues/47), or perhaps there are other performance suites at ETHCORE, ConsenSys and elsewhere.    We should certainly have a single set of tests which we all run.    If our current suite is "wrong" then we should fix that.

**Comment by holiman** [comment]
Definitely, any client should be able to say an exact number of "how compatible are you?". 
To start with, I think the test-interface must be more clearly defined. Right now, I think the testcases (/tests/) are handled differently, some post-conditions are validated, some only in certain cases. The only spec seems to be in the implementation of the test-framework, which is different between py/go/cpp. 

So, formal specification of what type of tests (state-tests, vm-tests, block-tests etc) and stuff like which post-condition-checks are mandatory if present. Ideally, the same test-framework should be used for all clients.
